#region Declaim
//---------------------------------------------------------------------------
// Name:		KanbanPullOrderDetailInfo
// Function: 	Expose data in table KanbanPullOrderDetail from database as business object to MES system.
// Tool:		T4
// CreateDate:	2018年5月8日
// <auto-generated>
//     This code was generated by a tool. 
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------
#endregion 

#region Imported Namespace

using Infrustructure.Data;
using Infrustructure.Data.Integration;
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

#endregion

namespace DM.LES 
{   
	/// <summary>
    /// KanbanPullOrderDetailInfo对应表[TT_MPM_KANBAN_PULL_ORDER_DETAIL]
    /// </summary>	
	[Serializable] 
	[DataContract]	
    public partial class KanbanPullOrderDetailInfo : BusinessObject, ICloneable 
	{		  
		#region Constructors
		
		public KanbanPullOrderDetailInfo( 
					long aId,

					Guid aFid,

					Guid aOrderFid,

					string aOrderCode,

					int aOrderStatus,

					string aCardNo,

					string aPartNo,

					string aPartName,

					string aSupplierCode,

					string aSupplierName,

					decimal aPartQty,

					string aPackageCode,

					decimal aPackageQty,

					bool aValidFlag,

					DateTime aCreateDate,

					string aCreateUser,

					DateTime aModifyDate,

					string aModifyUser

				 
		) : this()
		{
			 
			Id = aId;
		 
			Fid = aFid;
		 
			OrderFid = aOrderFid;
		 
			OrderCode = aOrderCode;
		 
			OrderStatus = aOrderStatus;
		 
			CardNo = aCardNo;
		 
			PartNo = aPartNo;
		 
			PartName = aPartName;
		 
			SupplierCode = aSupplierCode;
		 
			SupplierName = aSupplierName;
		 
			PartQty = aPartQty;
		 
			PackageCode = aPackageCode;
		 
			PackageQty = aPackageQty;
		 
			ValidFlag = aValidFlag;
		 
			CreateDate = aCreateDate;
		 
			CreateUser = aCreateUser;
		 
			ModifyDate = aModifyDate;
		 
			ModifyUser = aModifyUser;
		}
		
		public KanbanPullOrderDetailInfo():base("TT_MPM_KANBAN_PULL_ORDER_DETAIL")
		{
			List<string> keys = new List<string>();
			 			keys.Add("ID");                 _Keys = keys.ToArray();
			
			Schema = new DataSchema();
			List<DataSchemaField> fields = new List<DataSchemaField>();
			
			 
			DataSchemaField IDField = new DataSchemaField();
			IDField.Name = "ID";
			IDField.Type = typeof(long).ToString();
			IDField.Index = 0;
			fields.Add(IDField);
			 
			DataSchemaField FIDField = new DataSchemaField();
			FIDField.Name = "FID";
			FIDField.Type = typeof(Guid).ToString();
			FIDField.Index = 1;
			fields.Add(FIDField);
			 
			DataSchemaField ORDER_FIDField = new DataSchemaField();
			ORDER_FIDField.Name = "ORDER_FID";
			ORDER_FIDField.Type = typeof(Guid).ToString();
			ORDER_FIDField.Index = 2;
			fields.Add(ORDER_FIDField);
			 
			DataSchemaField ORDER_CODEField = new DataSchemaField();
			ORDER_CODEField.Name = "ORDER_CODE";
			ORDER_CODEField.Type = typeof(string).ToString();
			ORDER_CODEField.Index = 3;
			fields.Add(ORDER_CODEField);
			 
			DataSchemaField ORDER_STATUSField = new DataSchemaField();
			ORDER_STATUSField.Name = "ORDER_STATUS";
			ORDER_STATUSField.Type = typeof(int).ToString();
			ORDER_STATUSField.Index = 4;
			fields.Add(ORDER_STATUSField);
			 
			DataSchemaField CARD_NOField = new DataSchemaField();
			CARD_NOField.Name = "CARD_NO";
			CARD_NOField.Type = typeof(string).ToString();
			CARD_NOField.Index = 5;
			fields.Add(CARD_NOField);
			 
			DataSchemaField PART_NOField = new DataSchemaField();
			PART_NOField.Name = "PART_NO";
			PART_NOField.Type = typeof(string).ToString();
			PART_NOField.Index = 6;
			fields.Add(PART_NOField);
			 
			DataSchemaField PART_NAMEField = new DataSchemaField();
			PART_NAMEField.Name = "PART_NAME";
			PART_NAMEField.Type = typeof(string).ToString();
			PART_NAMEField.Index = 7;
			fields.Add(PART_NAMEField);
			 
			DataSchemaField SUPPLIER_CODEField = new DataSchemaField();
			SUPPLIER_CODEField.Name = "SUPPLIER_CODE";
			SUPPLIER_CODEField.Type = typeof(string).ToString();
			SUPPLIER_CODEField.Index = 8;
			fields.Add(SUPPLIER_CODEField);
			 
			DataSchemaField SUPPLIER_NAMEField = new DataSchemaField();
			SUPPLIER_NAMEField.Name = "SUPPLIER_NAME";
			SUPPLIER_NAMEField.Type = typeof(string).ToString();
			SUPPLIER_NAMEField.Index = 9;
			fields.Add(SUPPLIER_NAMEField);
			 
			DataSchemaField PART_QTYField = new DataSchemaField();
			PART_QTYField.Name = "PART_QTY";
			PART_QTYField.Type = typeof(decimal).ToString();
			PART_QTYField.Index = 10;
			fields.Add(PART_QTYField);
			 
			DataSchemaField PACKAGE_CODEField = new DataSchemaField();
			PACKAGE_CODEField.Name = "PACKAGE_CODE";
			PACKAGE_CODEField.Type = typeof(string).ToString();
			PACKAGE_CODEField.Index = 11;
			fields.Add(PACKAGE_CODEField);
			 
			DataSchemaField PACKAGE_QTYField = new DataSchemaField();
			PACKAGE_QTYField.Name = "PACKAGE_QTY";
			PACKAGE_QTYField.Type = typeof(decimal).ToString();
			PACKAGE_QTYField.Index = 12;
			fields.Add(PACKAGE_QTYField);
			 
			DataSchemaField VALID_FLAGField = new DataSchemaField();
			VALID_FLAGField.Name = "VALID_FLAG";
			VALID_FLAGField.Type = typeof(bool).ToString();
			VALID_FLAGField.Index = 13;
			fields.Add(VALID_FLAGField);
			 
			DataSchemaField CREATE_DATEField = new DataSchemaField();
			CREATE_DATEField.Name = "CREATE_DATE";
			CREATE_DATEField.Type = typeof(DateTime).ToString();
			CREATE_DATEField.Index = 14;
			fields.Add(CREATE_DATEField);
			 
			DataSchemaField CREATE_USERField = new DataSchemaField();
			CREATE_USERField.Name = "CREATE_USER";
			CREATE_USERField.Type = typeof(string).ToString();
			CREATE_USERField.Index = 15;
			fields.Add(CREATE_USERField);
			 
			DataSchemaField MODIFY_DATEField = new DataSchemaField();
			MODIFY_DATEField.Name = "MODIFY_DATE";
			MODIFY_DATEField.Type = typeof(DateTime).ToString();
			MODIFY_DATEField.Index = 16;
			fields.Add(MODIFY_DATEField);
			 
			DataSchemaField MODIFY_USERField = new DataSchemaField();
			MODIFY_USERField.Name = "MODIFY_USER";
			MODIFY_USERField.Type = typeof(string).ToString();
			MODIFY_USERField.Index = 17;
			fields.Add(MODIFY_USERField);
						
			Schema.Fields = fields.ToArray();
		}
		
		#endregion

		#region Attributes

		[DataMember]
		public long Id{ get;set; }		
				
		[DataMember]
		public Guid? Fid{ get;set; }		
				
		[DataMember]
		public Guid? OrderFid{ get;set; }		
				
		[DataMember]
		public string OrderCode{ get;set; }		
				
		[DataMember]
		public int? OrderStatus{ get;set; }		
				
		[DataMember]
		public string CardNo{ get;set; }		
				
		[DataMember]
		public string PartNo{ get;set; }		
				
		[DataMember]
		public string PartName{ get;set; }		
				
		[DataMember]
		public string SupplierCode{ get;set; }		
				
		[DataMember]
		public string SupplierName{ get;set; }		
				
		[DataMember]
		public decimal? PartQty{ get;set; }		
				
		[DataMember]
		public string PackageCode{ get;set; }		
				
		[DataMember]
		public decimal? PackageQty{ get;set; }		
				
		[DataMember]
		public bool ValidFlag{ get;set; }		
				
		[DataMember]
		public DateTime CreateDate{ get;set; }		
				
		[DataMember]
		public string CreateUser{ get;set; }		
				
		[DataMember]
		public DateTime? ModifyDate{ get;set; }		
				
		[DataMember]
		public string ModifyUser{ get;set; }		
				
		#endregion

	 
		#region ICloneable Members

		object ICloneable.Clone()
		{
			KanbanPullOrderDetailInfo info = new KanbanPullOrderDetailInfo();

			info.Id = this.Id;
			info.Fid = this.Fid;
			info.OrderFid = this.OrderFid;
			info.OrderCode = this.OrderCode;
			info.OrderStatus = this.OrderStatus;
			info.CardNo = this.CardNo;
			info.PartNo = this.PartNo;
			info.PartName = this.PartName;
			info.SupplierCode = this.SupplierCode;
			info.SupplierName = this.SupplierName;
			info.PartQty = this.PartQty;
			info.PackageCode = this.PackageCode;
			info.PackageQty = this.PackageQty;
			info.ValidFlag = this.ValidFlag;
			info.CreateDate = this.CreateDate;
			info.CreateUser = this.CreateUser;
			info.ModifyDate = this.ModifyDate;
			info.ModifyUser = this.ModifyUser;
			return info;			
		}
		 
		public KanbanPullOrderDetailInfo Clone()
		{
			return ((ICloneable) this).Clone() as KanbanPullOrderDetailInfo;	
		}
		#endregion

		public override string ToString()
		{
			return base.ToString();
		} 
	}

	/// <summary>
    /// KanbanPullOrderDetailInfoCollection对应表[TT_MPM_KANBAN_PULL_ORDER_DETAIL]
    /// </summary>
	public partial class KanbanPullOrderDetailInfoCollection : BusinessObjectCollection<KanbanPullOrderDetailInfo>
	{
		public KanbanPullOrderDetailInfoCollection():base("TT_MPM_KANBAN_PULL_ORDER_DETAIL"){}	
	}
}
