#region Declaim
//---------------------------------------------------------------------------
// Name:		Mstae
// Function: 	Expose data in table TS_SYS_CODE,TS_SYS_CODE_ITEM from database as business object to system.
// Tool:		T4
// CreateDate:	2018-07-23
// <auto-generated>
//     This code was generated by a tool. 
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------
#endregion 
using System.ComponentModel;

namespace DM.LES 
{
	/// <summary>
	/// 接口标识 
	/// </summary>
	public enum MstaeConstants
    {
		[Description("创建")]		
		Create = 1 ,
		[Description("更改")]		
		Modify = 2 ,
		[Description("删除")]		
		Delete = 3 ,
	}
}
