#region Declaim
//---------------------------------------------------------------------------
// Name:		QmisAsnPullSheetInfo
// Function: 	Expose data in table QmisAsnPullSheet from database as business object to MES system.
// Tool:		T4
// CreateDate:	2018年7月24日
// <auto-generated>
//     This code was generated by a tool. 
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------
#endregion 

#region Imported Namespace

using Infrustructure.Data;
using Infrustructure.Data.Integration;
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

#endregion

namespace DM.LES 
{   
	/// <summary>
    /// QmisAsnPullSheetInfo对应表[TI_IFM_QMIS_ASN_PULL_SHEET]
    /// </summary>	
	[Serializable] 
	[DataContract]	
    public partial class QmisAsnPullSheetInfo : BusinessObject, ICloneable 
	{		  
		#region Constructors
		
		public QmisAsnPullSheetInfo( 
					long aId,

					Guid aFid,

					Guid aLogFid,

					string aPlant,

					string aAsnNo,

					string aOrderNo,

					string aPartNo,

					string aSupplierNo,

					int aTotalNo,

					string aCheckMode,

					DateTime aArrivalDate,

					bool aZsFlag,

					string aEpgrp,

					string aTargetPlace,

					string aPurchaseGroup,

					int aProcessFlag,

					DateTime aProcessTime,

					string aComments,

					bool aValidFlag,

					string aCreateUser,

					DateTime aCreateDate,

					string aModifyUser,

					DateTime aModifyDate

				 
		) : this()
		{
			 
			Id = aId;
		 
			Fid = aFid;
		 
			LogFid = aLogFid;
		 
			Plant = aPlant;
		 
			AsnNo = aAsnNo;
		 
			OrderNo = aOrderNo;
		 
			PartNo = aPartNo;
		 
			SupplierNo = aSupplierNo;
		 
			TotalNo = aTotalNo;
		 
			CheckMode = aCheckMode;
		 
			ArrivalDate = aArrivalDate;
		 
			ZsFlag = aZsFlag;
		 
			Epgrp = aEpgrp;
		 
			TargetPlace = aTargetPlace;
		 
			PurchaseGroup = aPurchaseGroup;
		 
			ProcessFlag = aProcessFlag;
		 
			ProcessTime = aProcessTime;
		 
			Comments = aComments;
		 
			ValidFlag = aValidFlag;
		 
			CreateUser = aCreateUser;
		 
			CreateDate = aCreateDate;
		 
			ModifyUser = aModifyUser;
		 
			ModifyDate = aModifyDate;
		}
		
		public QmisAsnPullSheetInfo():base("TI_IFM_QMIS_ASN_PULL_SHEET")
		{
			List<string> keys = new List<string>();
			 			keys.Add("ID");                      _Keys = keys.ToArray();
			
			Schema = new DataSchema();
			List<DataSchemaField> fields = new List<DataSchemaField>();
			
			 
			DataSchemaField IDField = new DataSchemaField();
			IDField.Name = "ID";
			IDField.Type = typeof(long).ToString();
			IDField.Index = 0;
			fields.Add(IDField);
			 
			DataSchemaField FIDField = new DataSchemaField();
			FIDField.Name = "FID";
			FIDField.Type = typeof(Guid).ToString();
			FIDField.Index = 1;
			fields.Add(FIDField);
			 
			DataSchemaField LOG_FIDField = new DataSchemaField();
			LOG_FIDField.Name = "LOG_FID";
			LOG_FIDField.Type = typeof(Guid).ToString();
			LOG_FIDField.Index = 2;
			fields.Add(LOG_FIDField);
			 
			DataSchemaField PLANTField = new DataSchemaField();
			PLANTField.Name = "PLANT";
			PLANTField.Type = typeof(string).ToString();
			PLANTField.Index = 3;
			fields.Add(PLANTField);
			 
			DataSchemaField ASN_NOField = new DataSchemaField();
			ASN_NOField.Name = "ASN_NO";
			ASN_NOField.Type = typeof(string).ToString();
			ASN_NOField.Index = 4;
			fields.Add(ASN_NOField);
			 
			DataSchemaField ORDER_NOField = new DataSchemaField();
			ORDER_NOField.Name = "ORDER_NO";
			ORDER_NOField.Type = typeof(string).ToString();
			ORDER_NOField.Index = 5;
			fields.Add(ORDER_NOField);
			 
			DataSchemaField PART_NOField = new DataSchemaField();
			PART_NOField.Name = "PART_NO";
			PART_NOField.Type = typeof(string).ToString();
			PART_NOField.Index = 6;
			fields.Add(PART_NOField);
			 
			DataSchemaField SUPPLIER_NOField = new DataSchemaField();
			SUPPLIER_NOField.Name = "SUPPLIER_NO";
			SUPPLIER_NOField.Type = typeof(string).ToString();
			SUPPLIER_NOField.Index = 7;
			fields.Add(SUPPLIER_NOField);
			 
			DataSchemaField TOTAL_NOField = new DataSchemaField();
			TOTAL_NOField.Name = "TOTAL_NO";
			TOTAL_NOField.Type = typeof(int).ToString();
			TOTAL_NOField.Index = 8;
			fields.Add(TOTAL_NOField);
			 
			DataSchemaField CHECK_MODEField = new DataSchemaField();
			CHECK_MODEField.Name = "CHECK_MODE";
			CHECK_MODEField.Type = typeof(string).ToString();
			CHECK_MODEField.Index = 9;
			fields.Add(CHECK_MODEField);
			 
			DataSchemaField ARRIVAL_DATEField = new DataSchemaField();
			ARRIVAL_DATEField.Name = "ARRIVAL_DATE";
			ARRIVAL_DATEField.Type = typeof(DateTime).ToString();
			ARRIVAL_DATEField.Index = 10;
			fields.Add(ARRIVAL_DATEField);
			 
			DataSchemaField ZS_FLAGField = new DataSchemaField();
			ZS_FLAGField.Name = "ZS_FLAG";
			ZS_FLAGField.Type = typeof(bool).ToString();
			ZS_FLAGField.Index = 11;
			fields.Add(ZS_FLAGField);
			 
			DataSchemaField EPGRPField = new DataSchemaField();
			EPGRPField.Name = "EPGRP";
			EPGRPField.Type = typeof(string).ToString();
			EPGRPField.Index = 12;
			fields.Add(EPGRPField);
			 
			DataSchemaField TARGET_PLACEField = new DataSchemaField();
			TARGET_PLACEField.Name = "TARGET_PLACE";
			TARGET_PLACEField.Type = typeof(string).ToString();
			TARGET_PLACEField.Index = 13;
			fields.Add(TARGET_PLACEField);
			 
			DataSchemaField PURCHASE_GROUPField = new DataSchemaField();
			PURCHASE_GROUPField.Name = "PURCHASE_GROUP";
			PURCHASE_GROUPField.Type = typeof(string).ToString();
			PURCHASE_GROUPField.Index = 14;
			fields.Add(PURCHASE_GROUPField);
			 
			DataSchemaField PROCESS_FLAGField = new DataSchemaField();
			PROCESS_FLAGField.Name = "PROCESS_FLAG";
			PROCESS_FLAGField.Type = typeof(int).ToString();
			PROCESS_FLAGField.Index = 15;
			fields.Add(PROCESS_FLAGField);
			 
			DataSchemaField PROCESS_TIMEField = new DataSchemaField();
			PROCESS_TIMEField.Name = "PROCESS_TIME";
			PROCESS_TIMEField.Type = typeof(DateTime).ToString();
			PROCESS_TIMEField.Index = 16;
			fields.Add(PROCESS_TIMEField);
			 
			DataSchemaField COMMENTSField = new DataSchemaField();
			COMMENTSField.Name = "COMMENTS";
			COMMENTSField.Type = typeof(string).ToString();
			COMMENTSField.Index = 17;
			fields.Add(COMMENTSField);
			 
			DataSchemaField VALID_FLAGField = new DataSchemaField();
			VALID_FLAGField.Name = "VALID_FLAG";
			VALID_FLAGField.Type = typeof(bool).ToString();
			VALID_FLAGField.Index = 18;
			fields.Add(VALID_FLAGField);
			 
			DataSchemaField CREATE_USERField = new DataSchemaField();
			CREATE_USERField.Name = "CREATE_USER";
			CREATE_USERField.Type = typeof(string).ToString();
			CREATE_USERField.Index = 19;
			fields.Add(CREATE_USERField);
			 
			DataSchemaField CREATE_DATEField = new DataSchemaField();
			CREATE_DATEField.Name = "CREATE_DATE";
			CREATE_DATEField.Type = typeof(DateTime).ToString();
			CREATE_DATEField.Index = 20;
			fields.Add(CREATE_DATEField);
			 
			DataSchemaField MODIFY_USERField = new DataSchemaField();
			MODIFY_USERField.Name = "MODIFY_USER";
			MODIFY_USERField.Type = typeof(string).ToString();
			MODIFY_USERField.Index = 21;
			fields.Add(MODIFY_USERField);
			 
			DataSchemaField MODIFY_DATEField = new DataSchemaField();
			MODIFY_DATEField.Name = "MODIFY_DATE";
			MODIFY_DATEField.Type = typeof(DateTime).ToString();
			MODIFY_DATEField.Index = 22;
			fields.Add(MODIFY_DATEField);
						
			Schema.Fields = fields.ToArray();
		}
		
		#endregion

		#region Attributes

		[DataMember]
		public long Id{ get;set; }		
				
		[DataMember]
		public Guid? Fid{ get;set; }		
				
		[DataMember]
		public Guid? LogFid{ get;set; }		
				
		[DataMember]
		public string Plant{ get;set; }		
				
		[DataMember]
		public string AsnNo{ get;set; }		
				
		[DataMember]
		public string OrderNo{ get;set; }		
				
		[DataMember]
		public string PartNo{ get;set; }		
				
		[DataMember]
		public string SupplierNo{ get;set; }		
				
		[DataMember]
		public int? TotalNo{ get;set; }		
				
		[DataMember]
		public string CheckMode{ get;set; }		
				
		[DataMember]
		public DateTime? ArrivalDate{ get;set; }		
				
		[DataMember]
		public bool? ZsFlag{ get;set; }		
				
		[DataMember]
		public string Epgrp{ get;set; }		
				
		[DataMember]
		public string TargetPlace{ get;set; }		
				
		[DataMember]
		public string PurchaseGroup{ get;set; }		
				
		[DataMember]
		public int? ProcessFlag{ get;set; }		
				
		[DataMember]
		public DateTime? ProcessTime{ get;set; }		
				
		[DataMember]
		public string Comments{ get;set; }		
				
		[DataMember]
		public bool? ValidFlag{ get;set; }		
				
		[DataMember]
		public string CreateUser{ get;set; }		
				
		[DataMember]
		public DateTime CreateDate{ get;set; }		
				
		[DataMember]
		public string ModifyUser{ get;set; }		
				
		[DataMember]
		public DateTime? ModifyDate{ get;set; }		
				
		#endregion

	 
		#region ICloneable Members

		object ICloneable.Clone()
		{
			QmisAsnPullSheetInfo info = new QmisAsnPullSheetInfo();

			info.Id = this.Id;
			info.Fid = this.Fid;
			info.LogFid = this.LogFid;
			info.Plant = this.Plant;
			info.AsnNo = this.AsnNo;
			info.OrderNo = this.OrderNo;
			info.PartNo = this.PartNo;
			info.SupplierNo = this.SupplierNo;
			info.TotalNo = this.TotalNo;
			info.CheckMode = this.CheckMode;
			info.ArrivalDate = this.ArrivalDate;
			info.ZsFlag = this.ZsFlag;
			info.Epgrp = this.Epgrp;
			info.TargetPlace = this.TargetPlace;
			info.PurchaseGroup = this.PurchaseGroup;
			info.ProcessFlag = this.ProcessFlag;
			info.ProcessTime = this.ProcessTime;
			info.Comments = this.Comments;
			info.ValidFlag = this.ValidFlag;
			info.CreateUser = this.CreateUser;
			info.CreateDate = this.CreateDate;
			info.ModifyUser = this.ModifyUser;
			info.ModifyDate = this.ModifyDate;
			return info;			
		}
		 
		public QmisAsnPullSheetInfo Clone()
		{
			return ((ICloneable) this).Clone() as QmisAsnPullSheetInfo;	
		}
		#endregion

		public override string ToString()
		{
			return base.ToString();
		} 
	}

	/// <summary>
    /// QmisAsnPullSheetInfoCollection对应表[TI_IFM_QMIS_ASN_PULL_SHEET]
    /// </summary>
	public partial class QmisAsnPullSheetInfoCollection : BusinessObjectCollection<QmisAsnPullSheetInfo>
	{
		public QmisAsnPullSheetInfoCollection():base("TI_IFM_QMIS_ASN_PULL_SHEET"){}	
	}
}
