#region Declaim
//---------------------------------------------------------------------------
// Name:		SrmVmiShippingNoteInfo
// Function: 	Expose data in table SrmVmiShippingNote from database as business object to MES system.
// Tool:		T4
// CreateDate:	2018年7月24日
// <auto-generated>
//     This code was generated by a tool. 
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------
#endregion 

#region Imported Namespace

using Infrustructure.Data;
using Infrustructure.Data.Integration;
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

#endregion

namespace DM.LES 
{   
	/// <summary>
    /// SrmVmiShippingNoteInfo对应表[TI_IFM_SRM_VMI_SHIPPING_NOTE]
    /// </summary>	
	[Serializable] 
	[DataContract]	
    public partial class SrmVmiShippingNoteInfo : BusinessObject, ICloneable 
	{		  
		#region Constructors
		
		public SrmVmiShippingNoteInfo( 
					long aId,

					Guid aFid,

					Guid aLogFid,

					string aPlant,

					string aShippingCode,

					string aSupplierCode,

					DateTime aDeliveryTime,

					string aVmiWmNo,

					int aProcessFlag,

					DateTime aProcessTime,

					bool aDeleteFlag,

					bool aValidFlag,

					DateTime aCreateDate,

					string aCreateUser,

					DateTime aModifyDate,

					string aModifyUser,

					string aComments

				 
		) : this()
		{
			 
			Id = aId;
		 
			Fid = aFid;
		 
			LogFid = aLogFid;
		 
			Plant = aPlant;
		 
			ShippingCode = aShippingCode;
		 
			SupplierCode = aSupplierCode;
		 
			DeliveryTime = aDeliveryTime;
		 
			VmiWmNo = aVmiWmNo;
		 
			ProcessFlag = aProcessFlag;
		 
			ProcessTime = aProcessTime;
		 
			DeleteFlag = aDeleteFlag;
		 
			ValidFlag = aValidFlag;
		 
			CreateDate = aCreateDate;
		 
			CreateUser = aCreateUser;
		 
			ModifyDate = aModifyDate;
		 
			ModifyUser = aModifyUser;
		 
			Comments = aComments;
		}
		
		public SrmVmiShippingNoteInfo():base("TI_IFM_SRM_VMI_SHIPPING_NOTE")
		{
			List<string> keys = new List<string>();
			 			keys.Add("ID");                _Keys = keys.ToArray();
			
			Schema = new DataSchema();
			List<DataSchemaField> fields = new List<DataSchemaField>();
			
			 
			DataSchemaField IDField = new DataSchemaField();
			IDField.Name = "ID";
			IDField.Type = typeof(long).ToString();
			IDField.Index = 0;
			fields.Add(IDField);
			 
			DataSchemaField FIDField = new DataSchemaField();
			FIDField.Name = "FID";
			FIDField.Type = typeof(Guid).ToString();
			FIDField.Index = 1;
			fields.Add(FIDField);
			 
			DataSchemaField LOG_FIDField = new DataSchemaField();
			LOG_FIDField.Name = "LOG_FID";
			LOG_FIDField.Type = typeof(Guid).ToString();
			LOG_FIDField.Index = 2;
			fields.Add(LOG_FIDField);
			 
			DataSchemaField PLANTField = new DataSchemaField();
			PLANTField.Name = "PLANT";
			PLANTField.Type = typeof(string).ToString();
			PLANTField.Index = 3;
			fields.Add(PLANTField);
			 
			DataSchemaField SHIPPING_CODEField = new DataSchemaField();
			SHIPPING_CODEField.Name = "SHIPPING_CODE";
			SHIPPING_CODEField.Type = typeof(string).ToString();
			SHIPPING_CODEField.Index = 4;
			fields.Add(SHIPPING_CODEField);
			 
			DataSchemaField SUPPLIER_CODEField = new DataSchemaField();
			SUPPLIER_CODEField.Name = "SUPPLIER_CODE";
			SUPPLIER_CODEField.Type = typeof(string).ToString();
			SUPPLIER_CODEField.Index = 5;
			fields.Add(SUPPLIER_CODEField);
			 
			DataSchemaField DELIVERY_TIMEField = new DataSchemaField();
			DELIVERY_TIMEField.Name = "DELIVERY_TIME";
			DELIVERY_TIMEField.Type = typeof(DateTime).ToString();
			DELIVERY_TIMEField.Index = 6;
			fields.Add(DELIVERY_TIMEField);
			 
			DataSchemaField VMI_WM_NOField = new DataSchemaField();
			VMI_WM_NOField.Name = "VMI_WM_NO";
			VMI_WM_NOField.Type = typeof(string).ToString();
			VMI_WM_NOField.Index = 7;
			fields.Add(VMI_WM_NOField);
			 
			DataSchemaField PROCESS_FLAGField = new DataSchemaField();
			PROCESS_FLAGField.Name = "PROCESS_FLAG";
			PROCESS_FLAGField.Type = typeof(int).ToString();
			PROCESS_FLAGField.Index = 8;
			fields.Add(PROCESS_FLAGField);
			 
			DataSchemaField PROCESS_TIMEField = new DataSchemaField();
			PROCESS_TIMEField.Name = "PROCESS_TIME";
			PROCESS_TIMEField.Type = typeof(DateTime).ToString();
			PROCESS_TIMEField.Index = 9;
			fields.Add(PROCESS_TIMEField);
			 
			DataSchemaField DELETE_FLAGField = new DataSchemaField();
			DELETE_FLAGField.Name = "DELETE_FLAG";
			DELETE_FLAGField.Type = typeof(bool).ToString();
			DELETE_FLAGField.Index = 10;
			fields.Add(DELETE_FLAGField);
			 
			DataSchemaField VALID_FLAGField = new DataSchemaField();
			VALID_FLAGField.Name = "VALID_FLAG";
			VALID_FLAGField.Type = typeof(bool).ToString();
			VALID_FLAGField.Index = 11;
			fields.Add(VALID_FLAGField);
			 
			DataSchemaField CREATE_DATEField = new DataSchemaField();
			CREATE_DATEField.Name = "CREATE_DATE";
			CREATE_DATEField.Type = typeof(DateTime).ToString();
			CREATE_DATEField.Index = 12;
			fields.Add(CREATE_DATEField);
			 
			DataSchemaField CREATE_USERField = new DataSchemaField();
			CREATE_USERField.Name = "CREATE_USER";
			CREATE_USERField.Type = typeof(string).ToString();
			CREATE_USERField.Index = 13;
			fields.Add(CREATE_USERField);
			 
			DataSchemaField MODIFY_DATEField = new DataSchemaField();
			MODIFY_DATEField.Name = "MODIFY_DATE";
			MODIFY_DATEField.Type = typeof(DateTime).ToString();
			MODIFY_DATEField.Index = 14;
			fields.Add(MODIFY_DATEField);
			 
			DataSchemaField MODIFY_USERField = new DataSchemaField();
			MODIFY_USERField.Name = "MODIFY_USER";
			MODIFY_USERField.Type = typeof(string).ToString();
			MODIFY_USERField.Index = 15;
			fields.Add(MODIFY_USERField);
			 
			DataSchemaField COMMENTSField = new DataSchemaField();
			COMMENTSField.Name = "COMMENTS";
			COMMENTSField.Type = typeof(string).ToString();
			COMMENTSField.Index = 16;
			fields.Add(COMMENTSField);
						
			Schema.Fields = fields.ToArray();
		}
		
		#endregion

		#region Attributes

		[DataMember]
		public long Id{ get;set; }		
				
		[DataMember]
		public Guid? Fid{ get;set; }		
				
		[DataMember]
		public Guid? LogFid{ get;set; }		
				
		[DataMember]
		public string Plant{ get;set; }		
				
		[DataMember]
		public string ShippingCode{ get;set; }		
				
		[DataMember]
		public string SupplierCode{ get;set; }		
				
		[DataMember]
		public DateTime? DeliveryTime{ get;set; }		
				
		[DataMember]
		public string VmiWmNo{ get;set; }		
				
		[DataMember]
		public int? ProcessFlag{ get;set; }		
				
		[DataMember]
		public DateTime? ProcessTime{ get;set; }		
				
		[DataMember]
		public bool? DeleteFlag{ get;set; }		
				
		[DataMember]
		public bool? ValidFlag{ get;set; }		
				
		[DataMember]
		public DateTime? CreateDate{ get;set; }		
				
		[DataMember]
		public string CreateUser{ get;set; }		
				
		[DataMember]
		public DateTime? ModifyDate{ get;set; }		
				
		[DataMember]
		public string ModifyUser{ get;set; }		
				
		[DataMember]
		public string Comments{ get;set; }		
				
		#endregion

	 
		#region ICloneable Members

		object ICloneable.Clone()
		{
			SrmVmiShippingNoteInfo info = new SrmVmiShippingNoteInfo();

			info.Id = this.Id;
			info.Fid = this.Fid;
			info.LogFid = this.LogFid;
			info.Plant = this.Plant;
			info.ShippingCode = this.ShippingCode;
			info.SupplierCode = this.SupplierCode;
			info.DeliveryTime = this.DeliveryTime;
			info.VmiWmNo = this.VmiWmNo;
			info.ProcessFlag = this.ProcessFlag;
			info.ProcessTime = this.ProcessTime;
			info.DeleteFlag = this.DeleteFlag;
			info.ValidFlag = this.ValidFlag;
			info.CreateDate = this.CreateDate;
			info.CreateUser = this.CreateUser;
			info.ModifyDate = this.ModifyDate;
			info.ModifyUser = this.ModifyUser;
			info.Comments = this.Comments;
			return info;			
		}
		 
		public SrmVmiShippingNoteInfo Clone()
		{
			return ((ICloneable) this).Clone() as SrmVmiShippingNoteInfo;	
		}
		#endregion

		public override string ToString()
		{
			return base.ToString();
		} 
	}

	/// <summary>
    /// SrmVmiShippingNoteInfoCollection对应表[TI_IFM_SRM_VMI_SHIPPING_NOTE]
    /// </summary>
	public partial class SrmVmiShippingNoteInfoCollection : BusinessObjectCollection<SrmVmiShippingNoteInfo>
	{
		public SrmVmiShippingNoteInfoCollection():base("TI_IFM_SRM_VMI_SHIPPING_NOTE"){}	
	}
}
