#region Declaim
//---------------------------------------------------------------------------
// Name:		
// Function: 	Expose data in table TS_SYS_CODE,TS_SYS_CODE_ITEM from database as business object to system.
// Tool:		T4
// CreateDate:	2018年5月3日
// <auto-generated>
//     This code was generated by a tool. 
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------
#endregion 
using System.ComponentModel;

namespace DM.LES 
{
	/// <summary>
	/// 供应商类型 
	/// </summary>
	public enum SupplierTypeConstants
    {
		[Description("物料供应商")]		
		MaterialSupplier = 10 ,
		[Description("储运供应商")]		
		LogisticsSupplier = 20 ,
	}
}
