
--零件封存或零件解封修改库存
CREATE PROC  [LES].[PROC_PARTS_STORAGE]
@TRAN_ID INT
AS
	DECLARE @TRAN_TYPE INT;--交易类型
	DECLARE @NUM NUMERIC(18,2);--数量
	DECLARE @PART_NO VARCHAR(30);--零件号
	DECLARE @PLANT NVARCHAR(5);--工厂
	DECLARE @WmNo NVARCHAR(10);--仓库
	DECLARE @D_DLOC NVARCHAR(20);--存储区
	
		SELECT @TRAN_TYPE=h.TRAN_TYPE,@NUM=d.NUM,@PART_NO=d.PART_NO,@PLANT=h.PLANT,@WmNo=d.WM_NO,@D_DLOC=D_DLOC
		FROM LES.TT_WMM_TRAN_HEAD h JOIN LES.TT_WMM_TRAN_DETAIL d ON
		h.TRAN_ID=d.TRAN_ID WHERE h.TRAN_ID=@TRAN_ID
		IF @TRAN_TYPE=301--零件封存
		BEGIN
			UPDATE LES.TT_WMS_STOCKS SET FROZEN_STOCKS=FROZEN_STOCKS+@NUM WHERE PART_NO=@PART_NO AND 
			PLANT=@PLANT AND WM_NO=@WmNo AND ZONE_NO=@D_DLOC
		END
		IF @TRAN_TYPE=302--零件解封
			BEGIN
				UPDATE LES.TT_WMS_STOCKS SET FROZEN_STOCKS=FROZEN_STOCKS-@NUM WHERE PART_NO=@PART_NO AND 
				PLANT=@PLANT AND WM_NO=@WmNo AND ZONE_NO=@D_DLOC
			END