
/*
IF EXISTS(SELECT 1 FROM sys.sysobjects WHERE type = 'p' AND name = 'PROC_ODS_GET_TERMAL_PBOM_DIFFERENCE')
	DROP PROCEDURE [LES].PROC_ODS_GET_TERMAL_PBOM_DIFFERENCE
GO
*/
CREATE PROCEDURE [LES].[PROC_BAS_INBOUND_PULL_COMBINE_STANDBY]
 
AS

BEGIN

truncate table LES.TE_BAS_INBOUND_PULL_LOGISTIC_SUBMIT

INSERT INTO [LES].TE_BAS_INBOUND_PULL_LOGISTIC_SUBMIT
           ([PLANT],[ASSEMBLY_LINE],[PLANT_ZONE],[WORKSHOP]
           ,[SUPPLIER_NUM],[TRANS_SUPPLIER_NUM],[MODEL],[PART_NO]
           ,[INDENTIFY_PART_NO],[AMOUNTRATIO],[EXTERIOR_COLOR],[INTERNAL_COLOR]
           ,[HAND_KEPT_RECORD],[COLOR_CONTROL_PATCH],[VWS]
           ,[RAND],[SECTION],[PART_OPTION],[PRODUCTION_NUMBER]
           ,[START_PRODUCTION_DATE],[CANCEL_NUMBER],[END_PRODUCTION_DATE]
           ,[MODEL_YEAR],[DOSAGE],[MEASURING_UNIT_NO], AMOUNT_FLAG, [DATA_DATE]
           ,[VORSERIE],[PART_CNAME],[PART_ENAME],[LOAD_FLAG]
           ,[ZP_FLAG],[REQUIREMENT_FLAG],[LOGICAL_PK],[ASSEMBLY_FLAG]
           ,[ASSEMBLY_FLAG_RECRUIT],[MARK] ,[PURCHASE_STYLE]
           ,[VALID_FLAG],[INBOUND_MODE],[INBOUND_LOGISTIC_MODE],[INBOUND_SYSTEM_MODE]
           ,[EFFECTIVE_STATUS],[START_EFFECTIVE_DATE],[INBOUND_PART_CLASS],[DOCK]
           ,[INBOUND_PACKAGE_MODEL],[INBOUND_PACKAGE],[IS_SPLIT],[TERMAL_PK]
           ,[DIFF_FLAG],[COMMENTS]
           ,[UPDATE_DATE],[UPDATE_USER],[CREATE_DATE],[CREATE_USER])
SELECT    Termal.PLANT, Termal.ASSEMBLY_LINE, Termal.PLANT_ZONE, Termal.WORKSHOP, 
		  Termal.SUPPLIER_NUM, Termal.TRANS_SUPPLIER_NUM, Termal.MODEL,Termal.PART_NO, 
          Termal.INDENTIFY_PART_NO, Termal.AMOUNTRATIO, Termal.EXTERIOR_COLOR,Termal.INTERNAL_COLOR, 
          Termal.HAND_KEPT_RECORD,Termal.COLOR_CONTROL_PATCH, Termal.VWS,
          Termal.[RAND],Termal.SECTION, Termal.PART_OPTION, Termal.PRODUCTION_NUMBER, 
          Termal.START_PRODUCTION_DATE,Termal.CANCEL_NUMBER, Termal.END_PRODUCTION_DATE, 
          Termal.MODEL_YEAR,Termal.DOSAGE,Termal.MEASURING_UNIT_NO,Termal.AMOUNT_FLAG, Termal.DATA_DATE,   
          Termal.VORSERIE, Termal.PART_CNAME,Termal.PART_ENAME, Termal.LOAD_FLAG, 
          Termal.ZP_FLAG,Termal.REQUIREMENT_FLAG,Termal.LOGICAL_PK, Termal.ASSEMBLY_FLAG,  
          Termal.ASSEMBLY_FLAG_RECRUIT, Termal.[Mark],Termal.PURCHASE_STYLE,
          Termal.VALID_FLAG, Termal.INBOUND_MODE, Termal.INBOUND_LOGISTIC_MODE, Termal.INBOUND_SYSTEM_MODE, 
          1 AS [EFFECTIVE_STATUS],Termal.START_EFFECTIVE_DATE, Termal.INBOUND_PART_CLASS,Termal.DOCK, 
          Termal.INBOUND_PACKAGE_MODEL, Termal.INBOUND_PACKAGE,Termal.IS_SPLIT,Termal.Termal_PK,   
          Termal.DIFF_FLAG, Termal.COMMENTS, 
          Termal.UPDATE_DATE, Termal.UPDATE_USER, Termal.CREATE_DATE, Termal.CREATE_USER
FROM [LES].[V_BAS_INBOUNDPULL_COMBINE] AS Termal
WHERE Termal.VALID_FLAG = 1

truncate table LES.TM_BAS_INBOUND_PULL_LOGISTIC_HIS

INSERT INTO [LES].TM_BAS_INBOUND_PULL_LOGISTIC_HIS
           ([PLANT],[ASSEMBLY_LINE],[PLANT_ZONE],[WORKSHOP]
           ,[SUPPLIER_NUM],[TRANS_SUPPLIER_NUM],[MODEL],[PART_NO]
           ,[INDENTIFY_PART_NO],[AMOUNTRATIO],[EXTERIOR_COLOR],[INTERNAL_COLOR]
           ,[HAND_KEPT_RECORD],[COLOR_CONTROL_PATCH],[VWS]
           ,[RAND],[SECTION],[PART_OPTION],[PRODUCTION_NUMBER]
           ,[START_PRODUCTION_DATE],[CANCEL_NUMBER],[END_PRODUCTION_DATE]
           ,[MODEL_YEAR],[DOSAGE],[MEASURING_UNIT_NO], AMOUNT_FLAG, [DATA_DATE]
           ,[VORSERIE],[PART_CNAME],[PART_ENAME],[LOAD_FLAG]
           ,[ZP_FLAG],[REQUIREMENT_FLAG],[LOGICAL_PK],[ASSEMBLY_FLAG]
           ,[ASSEMBLY_FLAG_RECRUIT],[MARK] ,[PURCHASE_STYLE]
           ,[VALID_FLAG],[INBOUND_MODE],[INBOUND_LOGISTIC_MODE],[INBOUND_SYSTEM_MODE]
           ,[EFFECTIVE_STATUS],[START_EFFECTIVE_DATE],[INBOUND_PART_CLASS],[DOCK]
           ,[INBOUND_PACKAGE_MODEL],[INBOUND_PACKAGE],[IS_SPLIT],[TERMAL_PK]
           ,[DIFF_FLAG],[COMMENTS]
           ,[UPDATE_DATE],[UPDATE_USER],[CREATE_DATE],[CREATE_USER])
SELECT		[PLANT],[ASSEMBLY_LINE],[PLANT_ZONE],[WORKSHOP]
           ,[SUPPLIER_NUM],[TRANS_SUPPLIER_NUM],[MODEL],[PART_NO]
           ,[INDENTIFY_PART_NO],[AMOUNTRATIO],[EXTERIOR_COLOR],[INTERNAL_COLOR]
           ,[HAND_KEPT_RECORD],[COLOR_CONTROL_PATCH],[VWS]
           ,[RAND],[SECTION],[PART_OPTION],[PRODUCTION_NUMBER]
           ,[START_PRODUCTION_DATE],[CANCEL_NUMBER],[END_PRODUCTION_DATE]
           ,[MODEL_YEAR],[DOSAGE],[MEASURING_UNIT_NO], AMOUNT_FLAG, [DATA_DATE]
           ,[VORSERIE],[PART_CNAME],[PART_ENAME],[LOAD_FLAG]
           ,[ZP_FLAG],[REQUIREMENT_FLAG],[LOGICAL_PK],[ASSEMBLY_FLAG]
           ,[ASSEMBLY_FLAG_RECRUIT],[MARK] ,[PURCHASE_STYLE]
           ,[VALID_FLAG],[INBOUND_MODE],[INBOUND_LOGISTIC_MODE],[INBOUND_SYSTEM_MODE]
           ,[EFFECTIVE_STATUS],[START_EFFECTIVE_DATE],[INBOUND_PART_CLASS],[DOCK]
           ,[INBOUND_PACKAGE_MODEL],[INBOUND_PACKAGE],[IS_SPLIT],[TERMAL_PK]
           ,[DIFF_FLAG],[COMMENTS]
           ,[UPDATE_DATE],[UPDATE_USER],[CREATE_DATE],[CREATE_USER]     
FROM      LES.TM_BAS_INBOUND_PULL_LOGISTIC_STANDARD
   
 

	
END