

CREATE PROCEDURE [LES].[PROC_WMM_CREATERETURN]
@PLAN_RUNSHEET_SN INT
AS
BEGIN
	declare @WM_NO nvarchar(10)
	declare @ZONE_NO nvarchar(32)
	select @WM_NO = WM_NO,@ZONE_NO = ZONE_NO from LES.TT_SPM_DELIVERY_RUNSHEET_DETAIL where PLAN_RUNSHEET_SN=@PLAN_RUNSHEET_SN;

	INSERT INTO [LES].[TT_WMM_RETURN]([RETURN_NO],[PLANT],[SUPPLIER_NUM],[WM_NO],[ZONE_NO],
	[SEND_TIME],[RETURN_TYPE],[TRAN_TIME],[RETURN_REASON],[CONFIRM_FLAG],[TRANS_SUPPLIER_NUM],
	[ASSEMBLY_LINE],[PLANT_ZONE],[WORKSHOP],[SUPPLIER_TYPE],[ERP_FLAG],[RUNSHEET_CODE],
	[COMMENTS],[CREATE_USER],[CREATE_DATE])
	SELECT [PLAN_RUNSHEET_NO],PLANT,SUPPLIER_NUM,@WM_NO,@ZONE_NO,
	SEND_TIME,1,null,'OUT_REASON',1,TRANS_SUPPLIER_NUM,
	ASSEMBLY_LINE,PLANT_ZONE,WORKSHOP,1,0,[PLAN_RUNSHEET_NO],
	COMMENTS,'admin',GETDATE() FROM LES.TT_SPM_DELIVERY_RUNSHEET
	WHERE PLAN_RUNSHEET_SN=@PLAN_RUNSHEET_SN
	DECLARE @identity INT;
	select @identity = SCOPE_IDENTITY()

	--子表
	INSERT INTO [LES].[TT_WMM_RETURN_DETAIL]([RETURN_ID],[PLANT],[SUPPLIER_NUM],[WM_NO],[ZONE_NO],[DLOC],
	[PART_NO],[PART_CNAME],[PART_CLS],[PACK_COUNT],[PACK_SIZE],[PACKAGE_MODEL],	
	[CREATE_USER],[CREATE_DATE])
	SELECT @identity,PLANT,SUPPLIER_NUM,WM_NO,ZONE_NO,DLOC,
	PART_NO,PART_CNAME,1,REQUIRED_INHOUSE_PACKAGE_QTY,REQUIRED_INHOUSE_PACKAGE,INHOUSE_PACKAGE_MODEL,
		'admin',GETDATE() FROM LES.TT_SPM_DELIVERY_RUNSHEET_DETAIL WHERE PLAN_RUNSHEET_SN=@PLAN_RUNSHEET_SN
	
END