


/********************************************************************/
/*                                                                  */
/*   Project Name:  Production Pull System                          */
/*   Program Name:  [PROC_BAS_INHOUSE_PULL_COMBINE_STANDBY]             */
/*   Called By:     by the Page							*/
/*   Purpose:       This is the main stored procedure for the       */
/*   author:       wangchanghong	2011-06-20   				       */
/********************************************************************/
CREATE PROCEDURE [LES].[PROC_BAS_INHOUSE_PULL_COMBINE_STANDBY_ASSEMBLYLINE]
 (
 	@PLANT nvarchar(5),
 	@ASSEMBLY_LINE  nvarchar(10)
 )
AS

BEGIN


truncate table LES.TM_BAS_INHOUSE_PULL_LOGISTIC_HIS

--select * from LES.TM_BAS_INHOUSE_PULL_LOGISTIC_HIS

INSERT INTO [LES].TM_BAS_INHOUSE_PULL_LOGISTIC_HIS
	   ([PLANT],[ASSEMBLY_LINE],[PLANT_ZONE],[WORKSHOP]
	   ,[SUPPLIER_NUM],[TRANS_SUPPLIER_NUM],[MODEL],[PART_NO]
	   ,[INDENTIFY_PART_NO],[AMOUNTRATIO],[EXTERIOR_COLOR],[INTERNAL_COLOR]
	   ,[HAND_KEPT_RECORD],[COLOR_CONTROL_PATCH],[VWS],[RAND]
	   ,[SECTION],[PART_OPTION],[PRODUCTION_NUMBER],[START_PRODUCTION_DATE]
	   ,[CANCEL_NUMBER],[END_PRODUCTION_DATE],[MODEL_YEAR],[DOSAGE]
	   ,[MEASURING_UNIT_NO],[AMOUNT_FLAG],[DATA_DATE],[VORSERIE]
	   ,[PART_CNAME],[PART_ENAME],[PART_NICKNAME],[LOAD_FLAG]
	   ,[ZP_FLAG],[REQUIREMENT_FLAG],[ASSEMBLY_FLAG],[ASSEMBLY_FLAG_RECRUIT]
	   ,[PURCHASE_STYLE],[VALID_FLAG],[WORKSHOP_SECTION]
	   ,[LOCATION],[IN_PLANT_LOGISTIC_MODE],[IN_PLANT_SYSTEM_MODE],[IN_PLANT_LOGISTIC_PART_CLASS]
	   ,[INHOUSE_MODE],[INHOUSE_SYSTEM_MODE],[EFFECTIVE_STATUS],[START_EFFECTIVE_DATE]
	   ,[INHOUSE_PART_CLASS],[DOCK],[INHOUSE_PACKAGE_MODEL]
	   ,[INHOUSE_PACKAGE]
	   --,[DIFF_FLAG]
	   ,TERMAL_PK,[COMMENTS]	   
	   ,[UPDATE_DATE],[UPDATE_USER],[CREATE_DATE],[CREATE_USER]
	   ,LOGICAL_PK,BUSINESS_PK)
SELECT [PLANT],[ASSEMBLY_LINE],[PLANT_ZONE],[WORKSHOP]
	   ,[SUPPLIER_NUM],[TRANS_SUPPLIER_NUM],[MODEL],[PART_NO]
	   ,[INDENTIFY_PART_NO],[AMOUNTRATIO],[EXTERIOR_COLOR],[INTERNAL_COLOR]
	   ,[HAND_KEPT_RECORD],[COLOR_CONTROL_PATCH],[VWS],[RAND]
	   ,[SECTION],[PART_OPTION],[PRODUCTION_NUMBER],[START_PRODUCTION_DATE]
	   ,[CANCEL_NUMBER],[END_PRODUCTION_DATE],[MODEL_YEAR],[DOSAGE]
	   ,[MEASURING_UNIT_NO],[AMOUNT_FLAG],[DATA_DATE],[VORSERIE]
	   ,[PART_CNAME],[PART_ENAME],[PART_NICKNAME],[LOAD_FLAG]
	   ,[ZP_FLAG],[REQUIREMENT_FLAG],[ASSEMBLY_FLAG],[ASSEMBLY_FLAG_RECRUIT]
	   ,[PURCHASE_STYLE],[VALID_FLAG],[WORKSHOP_SECTION]
	   ,[LOCATION],[IN_PLANT_LOGISTIC_MODE],[IN_PLANT_SYSTEM_MODE],[IN_PLANT_LOGISTIC_PART_CLASS]
	   ,[INHOUSE_MODE],[INHOUSE_SYSTEM_MODE],[EFFECTIVE_STATUS],[START_EFFECTIVE_DATE]
	   ,[INHOUSE_PART_CLASS],[DOCK],[INHOUSE_PACKAGE_MODEL]
	   ,[INHOUSE_PACKAGE]
	   --,[DIFF_FLAG]
	   ,TERMAL_PK,[COMMENTS]	   
	   ,[UPDATE_DATE],[UPDATE_USER],[CREATE_DATE],[CREATE_USER]
	   ,LOGICAL_PK,BUSINESS_PK
FROM  LES.TM_BAS_INHOUSE_PULL_LOGISTIC_STANDARD
 
truncate table [LES].TE_BAS_INHOUSE_PULL_LOGISTIC_SUBMIT

INSERT INTO [LES].TE_BAS_INHOUSE_PULL_LOGISTIC_SUBMIT
	   ([PLANT],[ASSEMBLY_LINE],[PLANT_ZONE],[WORKSHOP]
	   ,[SUPPLIER_NUM],[TRANS_SUPPLIER_NUM],[MODEL],[PART_NO]
	   ,[INDENTIFY_PART_NO],[AMOUNTRATIO],[EXTERIOR_COLOR],[INTERNAL_COLOR]
	   ,[HAND_KEPT_RECORD],[COLOR_CONTROL_PATCH],[VWS],[RAND]
	   ,[SECTION],[PART_OPTION],[PRODUCTION_NUMBER],[START_PRODUCTION_DATE]
	   ,[CANCEL_NUMBER],[END_PRODUCTION_DATE],[MODEL_YEAR],[DOSAGE]
	   ,[MEASURING_UNIT_NO],[AMOUNT_FLAG],[DATA_DATE],[VORSERIE]
	   ,[PART_CNAME],[PART_ENAME],[PART_NICKNAME],[LOAD_FLAG]
	   ,[ZP_FLAG],[REQUIREMENT_FLAG],[ASSEMBLY_FLAG],[ASSEMBLY_FLAG_RECRUIT]
	   ,[PURCHASE_STYLE],[VALID_FLAG],[WORKSHOP_SECTION]
	   ,[LOCATION],[IN_PLANT_LOGISTIC_MODE],[IN_PLANT_SYSTEM_MODE],[IN_PLANT_LOGISTIC_PART_CLASS]
	   ,[INHOUSE_MODE],[INHOUSE_SYSTEM_MODE],[EFFECTIVE_STATUS],[START_EFFECTIVE_DATE]
	   ,[INHOUSE_PART_CLASS],[DOCK],[INHOUSE_PACKAGE_MODEL]
	   ,[INHOUSE_PACKAGE]
	   --,[DIFF_FLAG]
	   ,TERMAL_PK,[COMMENTS]	   
	   ,[UPDATE_DATE],[UPDATE_USER],[CREATE_DATE],[CREATE_USER]
	   ,LOGICAL_PK,BUSINESS_PK)
SELECT Termal.PLANT,Termal.ASSEMBLY_LINE,Termal.PLANT_ZONE,Termal.WORKSHOP,
       Termal.SUPPLIER_NUM,Termal.TRANS_SUPPLIER_NUM,Termal.MODEL,Termal.PART_NO,
       Termal.INDENTIFY_PART_NO,Termal.AMOUNTRATIO,Termal.EXTERIOR_COLOR,Termal.INTERNAL_COLOR,
       Termal.HAND_KEPT_RECORD,Termal.COLOR_CONTROL_PATCH,Termal.VWS,Termal.[RAND],
       Termal.SECTION,Termal.PART_OPTION,Termal.PRODUCTION_NUMBER,Termal.START_PRODUCTION_DATE,
       Termal.CANCEL_NUMBER,Termal.END_PRODUCTION_DATE,Termal.MODEL_YEAR,Termal.DOSAGE,
       Termal.MEASURING_UNIT_NO,Termal.AMOUNT_FLAG,Termal.DATA_DATE,Termal.VORSERIE,
       Termal.PART_CNAME,Termal.PART_ENAME,Termal.PART_NICKNAME,Termal.LOAD_FLAG,
       Termal.ZP_FLAG,Termal.REQUIREMENT_FLAG,Termal.ASSEMBLY_FLAG,Termal.ASSEMBLY_FLAG_RECRUIT,
       Termal.PURCHASE_STYLE,Termal.VALID_FLAG,Termal.WORKSHOP_SECTION,
       Termal.LOCATION,Termal.IN_PLANT_LOGISTIC_MODE,Termal.IN_PLANT_SYSTEM_MODE,Termal.IN_PLANT_LOGISTIC_PART_CLASS,
       Termal.INHOUSE_MODE,Termal.INHOUSE_SYSTEM_MODE,1,Termal.START_EFFECTIVE_DATE,
       Termal.INHOUSE_PART_CLASS,Termal.DOCK,Termal.INHOUSE_PACKAGE_MODEL,
       Termal.INHOUSE_PACKAGE,
       --Termal.DIFF_FLAG,
       Termal.Termal_PK,Termal.COMMENTS,
       GETDATE(),Termal.UPDATE_USER,GETDATE(),Termal.CREATE_USER
       ,Termal.LOGICAL_PK ,Termal.BUSINESS_PK     
FROM [LES].[V_BAS_INHOUSEPULL_COMBINE] AS Termal
WHERE Termal.VALID_FLAG = 1 
--and Termal.Termal_PK = 'UThtm6NyYOKrJtFX6YLkHg=='



--插入到JIS变更表
/*
INSERT INTO [LES].[TE_BAS_INHOUSE_CHANGE_PULL]
           ([PART_NO],[LOGICAL_PK],[DIFF_FLAG],[TERMAL_PK]
           ,[COMMENTS]
           ,[CREATE_USER],[CREATE_DATE],[UPDATE_USER],[UPDATE_DATE])
SELECT Termal.PART_NO,Termal.LOGICAL_PK,0,Termal.Termal_PK,
       null,
       null,getdate(),null,null
FROM [LES].[V_BAS_INHOUSEPULL_COMBINE] AS Termal
WHERE (INHOUSE_SYSTEM_MODE = 'JIS' OR IN_PLANT_SYSTEM_MODE = 'JIS')
AND (Termal.Termal_Diff_Flag In (2,3,4)  OR  Termal.Inhouse_Diff_Flag In(1,2,3))
AND PLANT = @PLANT AND ASSEMBLY_LINE = @ASSEMBLY_LINE

*/
 

 
	
END