-- =============================================
-- Author:		zhangheng
-- Create date: 2016-4-19
-- Description:	检查零件库存是否足够出库
-- =============================================
CREATE PROC [LES].[PROC_WMM_OUTBOUNDDELIVERY_CHECK] 
	@OUTBOUNDDELIVERY_ID int
AS
BEGIN
    SELECT DISTINCT
	    A.[PART_NO]
    FROM
    (
	    SELECT
		    [ZONE_NO],
		    [PART_NO],
		    SUM([CURRENT_OUTBOUND_PACKAGE_QTY]) AS [CURRENT_OUTBOUND_PACKAGE_QTY]
	    FROM [LES].[TT_WMM_OUTBOUNDDELIVERY_DETAIL] WITH (NOLOCK)
	    WHERE [OUTBOUNDDELIVERY_ID] = @OUTBOUNDDELIVERY_ID AND [CURRENT_OUTBOUND_PACKAGE_QTY] > 0
	    GROUP BY [ZONE_NO], [PART_NO]
    ) AS A
    WHERE A.[CURRENT_OUTBOUND_PACKAGE_QTY] > (SELECT SUM(ISNULL([STOCKS_NUM], 0)) - SUM(ISNULL([FROZEN_STOCKS], 0)) FROM [LES].[TT_WMS_STOCKS] S WITH (NOLOCK) WHERE S.[PART_NO] = A.[PART_NO] AND S.[ZONE_NO] = A.[ZONE_NO])
    AND A.[ZONE_NO] NOT IN (SELECT [ZONE_NO] FROM [LES].[TM_WMM_ZONES] WITH (NOLOCK) WHERE [IS_NEGATIVE] = 1)
END