-- =============================================
-- Author:		XinPengZhang
-- Create date: 2017-11-13
-- Description:	根据SAP收货返回数据更新采购ASN单据数据
-- =============================================
CREATE PROCEDURE [LES].[PROC_INTERFACE_SAP_LES_UPDATEASN]

AS
BEGIN
	--缓存未处理的SAP下发的数据
	SELECT * INTO #TI_SPM_DELIVERY_RUNSHEET_RECEVIED_IN FROM [LES].[TI_SPM_DELIVERY_RUNSHEET_RECEVIED_IN] WITH(NOLOCK) WHERE ISNULL(PROCESS_FLAG,0) = 0

	--更新采购ASN单据明细中的实收数量及单据状态
	UPDATE B SET B.ACTUAL_INBOUND_PACKAGE_QTY = A.LGMNG,B.STATUS=3 FROM [LES].[TI_SPM_DELIVERY_RUNSHEET_RECEVIED_IN] A WITH(NOLOCK)
	JOIN [LES].[TT_SPM_RUNSHEET_PURCHASE_ASN_DETAIL] B WITH(NOLOCK) ON A.VBELN = B.TWD_RUNSHEET_NO AND A.ASN = B.ASN_NO AND A.MATNR = B.PART_NO
	WHERE ISNULL(A.PROCESS_FLAG,0) = 0

	--更新采购ASN单据中的状态为已完成
	UPDATE A SET A.STATUS = 3 FROM [LES].[TT_SPM_RUNSHEET_PURCHASE_ASN] A WITH(NOLOCK)
	WHERE 
	ID IN (
		SELECT DISTINCT B.ASN_ID FROM #TI_SPM_DELIVERY_RUNSHEET_RECEVIED_IN A WITH(NOLOCK)
		JOIN [LES].[TT_SPM_RUNSHEET_PURCHASE_ASN_DETAIL] B WITH(NOLOCK) ON A.VBELN = B.TWD_RUNSHEET_NO AND A.ASN = B.ASN_NO AND A.MATNR = B.PART_NO
	)

	--更新非共用件明细表中收货件数。收货件数=原收货件数+实收件数
	UPDATE B SET B.ACTUAL_INHOUSE_PACKAGE_QTY = B.ACTUAL_INHOUSE_PACKAGE_QTY +C.LGMNG FROM [LES].[TT_SPM_DELIVERY_RUNSHEET] A WITH(NOLOCK)
	JOIN [LES].[TT_SPM_DELIVERY_RUNSHEET_DETAIL] B WITH(NOLOCK) ON A.PLAN_RUNSHEET_SN = B.PLAN_RUNSHEET_SN
	JOIN #TI_SPM_DELIVERY_RUNSHEET_RECEVIED_IN C ON A.PLAN_RUNSHEET_NO = C.VBELN AND B.PART_CNAME = C.MATNR

	--更新对应非共用件订单的状态，工厂编号不是9110的为非共用件
	UPDATE A SET A.SHEET_STATUS=13 FROM [LES].[TT_SPM_DELIVERY_RUNSHEET] A WITH(NOLOCK)
	WHERE  
	PLAN_RUNSHEET_NO IN (SELECT DISTINCT VBELN FROM #TI_SPM_DELIVERY_RUNSHEET_RECEVIED_IN)
	AND NOT EXISTS
	(
		--非共用件明细表中可编辑数和ASN草稿件数不为0才能更新非共用件单据为已完成
		SELECT * FROM 
		(
			SELECT DISTINCT PLAN_RUNSHEET_NO FROM
			(
				SELECT A.PLAN_RUNSHEET_NO FROM [LES].[TT_SPM_DELIVERY_RUNSHEET] A WITH(NOLOCK)
				JOIN [LES].[TT_SPM_DELIVERY_RUNSHEET_DETAIL] B WITH(NOLOCK) ON A.PLAN_RUNSHEET_SN = B.PLAN_RUNSHEET_SN
				WHERE A.PLAN_RUNSHEET_NO IN (SELECT DISTINCT VBELN FROM #TI_SPM_DELIVERY_RUNSHEET_RECEVIED_IN)
				AND (ISNULL(REQUIRED_INHOUSE_PACKAGE_QTY, 0) - ISNULL(ASN_CONFIRM_QTY, 0) - ISNULL(ASN_DRAFT_QTY, 0) = 0 OR ISNULL(ASN_DRAFT_QTY,0) =0)
			)A
		)B WHERE A.PLAN_RUNSHEET_NO = B.PLAN_RUNSHEET_NO
	)
	AND NOT EXISTS 
	(
		--只有非共用件下所有ASN单据都为已完成才能更新非共用件单据为已完成	
		SELECT * FROM 
		(
			SELECT DISTINCT VBELN FROM #TI_SPM_DELIVERY_RUNSHEET_RECEVIED_IN A
			JOIN [LES].[TT_SPM_RUNSHEET_PURCHASE_ASN_DETAIL] B WITH(NOLOCK) ON A.VBELN = B.TWD_RUNSHEET_NO AND A.ASN = B.ASN_NO AND A.MATNR = B.PART_NO
			JOIN [LES].[TT_SPM_RUNSHEET_PURCHASE_ASN] C WITH(NOLOCK) ON B.ASN_ID = C.ID
			WHERE C.STATUS <> 3
		)B WHERE A.PLAN_RUNSHEET_NO = B.VBELN
	)		
	
	--将TI_SPM_DELIVERY_RUNSHEET_RECEVIED_IN状态更新为已处理
	UPDATE A SET A.PROCESS_FLAG = 1 
	FROM [LES].[TI_SPM_DELIVERY_RUNSHEET_RECEVIED_IN] A WITH(NOLOCK) 
	WHERE ISNULL(A.PROCESS_FLAG,0) = 0
	AND VBELN IN (SELECT VBELN FROM #TI_SPM_DELIVERY_RUNSHEET_RECEVIED_IN)

END