
/********************************************************************/
/*                                                                  */
/*   Project Name:  Production Pull System                          */
/*   Program Name:  PROC_BAS_INHOUSE_APPROVE_ID             */
/*   Called By:     by the Page							*/
/*   Purpose:       This is the main stored procedure for the       */
/*   author:       wangchanghong	2011-06-20   				       */
/********************************************************************/
CREATE PROCEDURE [LES].[PROC_BAS_INHOUSE_APPROVE_ID]
(
	@LogicalIds nvarchar(max) 
)
AS

BEGIN

--TYPE 0:未变化 1:未匹配 2:新增 3:修改 4：删除 5：已修改
declare @inser_sql  nvarchar(max)
declare @update_sql nvarchar(max)
declare @delete_sql nvarchar(max)
declare @update_confirm_sql nvarchar(max)

set @inser_sql = '	
INSERT INTO [LES].[TM_BAS_MAINTAIN_INHOUSE_LOGISTIC_STANDARD]
           ([PLANT],[ASSEMBLY_LINE],[PLANT_ZONE],[WORKSHOP]
           ,[SUPPLIER_NUM],[TRANS_SUPPLIER_NUM],[MODEL],[PART_NO]
           ,COLOR_DEPARTMENT,[HAND_KEPT_RECORD],[COLOR_CONTROL_PATCH],[VWS]
           ,[MODEL_YEAR],[PART_CNAME],[PART_ENAME],[PART_NICKNAME]
           ,[VALID_FLAG],[WORKSHOP_SECTION],[LOCATION],[IN_PLANT_LOGISTIC_MODE]
           ,[IN_PLANT_SYSTEM_MODE],[IN_PLANT_LOGISTIC_PART_CLASS],[INHOUSE_MODE],[INHOUSE_SYSTEM_MODE]
           ,[INHOUSE_PART_CLASS],[DOCK],[INHOUSE_PACKAGE_MODEL],[INHOUSE_PACKAGE]
           ,[START_EFFECTIVE_DATE],[PLATFORM_CHANGE_DATE],[LOGICAL_PK],[DELETE_FLAG]
           ,[DIFF_FLAG],[COMMENTS],[CREATE_USER],[CREATE_DATE]
           ,[UPDATE_USER],[UPDATE_DATE]
           )
	SELECT TE.[PLANT],TE.[ASSEMBLY_LINE],TE.[PLANT_ZONE],TE.[WORKSHOP]
		  ,TE.[SUPPLIER_NUM],TE.[TRANS_SUPPLIER_NUM],TE.[MODEL],TE.[PART_NO]
		  ,TE.COLOR_DEPARTMENT,TE.[HAND_KEPT_RECORD],TE.[COLOR_CONTROL_PATCH],TE.[VWS]
		  ,TE.[MODEL_YEAR],TE.[PART_CNAME],TE.[PART_ENAME],NULL
		  ,TE.[VALID_FLAG],TE.[WORKSHOP_SECTION],TE.LOCATION,TE.[IN_PLANT_LOGISTIC_MODE]
		  ,TE.[IN_PLANT_SYSTEM_MODE],TE.[IN_PLANT_LOGISTIC_PART_CLASS],TE.[INHOUSE_MODE],TE.[INHOUSE_SYSTEM_MODE]
		  ,TE.[INHOUSE_PART_CLASS],TE.[DOCK],TE.[INHOUSE_PACKAGE_MODEL],TE.[INHOUSE_PACKAGE]
		  ,TE.[START_EFFECTIVE_DATE],TE.[PLATFORM_CHANGE_DATE],TE.[LOGICAL_PK],0
		  ,TE.DIFF_FLAG,TE.[COMMENTS],TE.[CREATE_USER],GetDate()
		  ,TE.[UPDATE_USER],TE.[UPDATE_DATE]
       FROM    LES.TE_BAS_INHOUSE_LOGISTIC_STANDARD_DIFF AS TE
	WHERE  TE.DIFF_FLAG = 1  AND TE.CONFIRM_FLAG = 0 AND TE.LOGICAL_PK IN (' + @LogicalIds + ')'
 

EXECUTE sp_executesql @inser_sql  

set @update_sql = '	 
UPDATE [LES].[TM_BAS_MAINTAIN_INHOUSE_LOGISTIC_STANDARD]
   SET [SUPPLIER_NUM] = TE.[SUPPLIER_NUM]
   , COLOR_DEPARTMENT = TE.COLOR_DEPARTMENT
   , [COLOR_CONTROL_PATCH] = TE.[COLOR_CONTROL_PATCH]
   , [VWS] = TE.[VWS]
   , [MODEL_YEAR] = TE.[MODEL_YEAR]
   , [PART_CNAME] = TE.[PART_CNAME]
   , [PART_ENAME] = TE.[PART_ENAME]
   , [VALID_FLAG] = TE.[VALID_FLAG]
   , [IN_PLANT_LOGISTIC_MODE] = TE.[IN_PLANT_LOGISTIC_MODE]
   , [IN_PLANT_SYSTEM_MODE]= TE.[IN_PLANT_SYSTEM_MODE]
   , [IN_PLANT_LOGISTIC_PART_CLASS] = TE.[IN_PLANT_LOGISTIC_PART_CLASS]
   , [INHOUSE_MODE] = TE.[INHOUSE_MODE]
   , [INHOUSE_SYSTEM_MODE] = TE.[INHOUSE_SYSTEM_MODE]
   , [INHOUSE_PART_CLASS] = TE.[INHOUSE_PART_CLASS]
   , [DOCK] = TE.[DOCK]
   , [INHOUSE_PACKAGE_MODEL] = TE.[INHOUSE_PACKAGE_MODEL]
   , [INHOUSE_PACKAGE] = TE.[INHOUSE_PACKAGE]
   , [START_EFFECTIVE_DATE] = TE.[START_EFFECTIVE_DATE]
   , [PLATFORM_CHANGE_DATE] = TE.[PLATFORM_CHANGE_DATE]
   , [COMMENTS] = TE.[COMMENTS]            
FROM LES.TE_BAS_INHOUSE_LOGISTIC_STANDARD_DIFF  AS TE,
   LES.TM_BAS_MAINTAIN_INHOUSE_LOGISTIC_STANDARD AS TM 
WHERE TE.LOGICAL_PK = TM.LOGICAL_PK  
AND TE.[DIFF_FLAG] = 2 AND TE.CONFIRM_FLAG = 0 AND TE.LOGICAL_PK IN (' + @LogicalIds + ')'
 

EXECUTE sp_executesql @update_sql  

set @delete_sql = ' 
DELETE  [LES].[TM_BAS_MAINTAIN_INHOUSE_LOGISTIC_STANDARD] 
FROM [LES].[TM_BAS_MAINTAIN_INHOUSE_LOGISTIC_STANDARD] AS TM,
     [LES].TE_BAS_INHOUSE_LOGISTIC_STANDARD_DIFF AS TE
WHERE TM.LOGICAL_PK = TE.LOGICAL_PK  
 AND TE.[DIFF_FLAG] = 3 AND TE.CONFIRM_FLAG = 0  AND TE.LOGICAL_PK IN (' + @LogicalIds + ')'
 

EXECUTE sp_executesql @delete_sql  


--更新全部FLAG

set @update_confirm_sql = '
UPDATE [LES].TE_BAS_INHOUSE_LOGISTIC_STANDARD_DIFF 
SET CONFIRM_FLAG = 1 
WHERE LOGICAL_PK IN (' + @LogicalIds + ')'


EXECUTE sp_executesql @update_confirm_sql  
	
END