

/********************************************************************/
/*                                                                  */
/*   Project Name:  LES System                         */
/*   Program Name:  [PROC_WMM_TRAN_HEAD_CREATE_UPDATE]             */
/*   Called By:     by the Page							*/
/*   Purpose:       This is the main stored procedure for the       */
/*   author:       andy	2015-06-09     				       */
/********************************************************************/
CREATE PROCEDURE [LES].[PROC_WMM_TRAN_HEAD_CREATE_UPDATE]
 
AS

BEGIN

INSERT INTO [LES].[TT_WMM_TRAN_HEAD]
	(
	[TRAN_NO]
	,[PLANT]
	,[S_WM_NO]
	,[S_ZONE_NO]
	,[O_WM_NO]
	,[O_ZONE_NO]
	,[TRAN_TYPE]
	,[TRAN_TIME]
	,[COST_CODE]
	,[FINANCIAL_CODE]
	,[INTERNAL_CODE]
	,[TRAN_STATUS]
	,[PUBLISH_TIME]
	,[CREATE_USER]
	,[CREATE_DATE]
	,WBS_CODE
	)
	SELECT distinct
	    [TRAN_NO] 
        ,[PLANT]
        ,[S_WM_NO]
        ,[S_ZONE_NO]
        ,[O_WM_NO]
        ,[O_ZONE_NO]
		,d.DETAIL_CODE
		,[TRAN_TIME]
		,[COST_CODE]
		,[FINANCIAL_CODE]
		,[INTERNAL_CODE]
		,0
		,TE.[PUBLISH_TIME]
		,TE.[CREATE_USER]
		,TE.[CREATE_DATE]
		,TE.WBS_CODE
	FROM 
		[LES].[TE_WMM_TRAN_HEAD_TEMP] TE JOIN LES.TC_SYS_CODE_DETAIL d
		ON TE.TRAN_TYPE=d.DETAIL_VALUE AND d.CODE_NAME='wms_tran_type'
	WHERE 
		TE.VALID_FLAG = 1
		AND (SELECT COUNT(*) FROM 
				[LES].[TT_WMM_TRAN_HEAD] TH
			 WHERE 
				TE.PLANT = TH.PLANT
				AND TE.TRAN_NO = TH.TRAN_NO) < 1

UPDATE 
	[LES].[TT_WMM_TRAN_HEAD] 
SET
    [PLANT] = TB.PLANT_NO
	,[S_WM_NO] = TB.[S_WM_NO]
	,[S_ZONE_NO] = TB.[S_ZONE_NO]
	,[O_WM_NO] = TB.[O_WM_NO]
	,[O_ZONE_NO] = TB.[O_ZONE_NO]
	,[TRAN_TYPE] = TB.[TRAN_TYPE]
	,[TRAN_TIME] = TB.[TRAN_TIME]
	,[COST_CODE] = TB.[COST_CODE]
	,[FINANCIAL_CODE] = TB.[FINANCIAL_CODE]
	,[INTERNAL_CODE] = TB.[INTERNAL_CODE]
	,[PUBLISH_TIME] = TB.[PUBLISH_TIME]
	,[UPDATE_USER] = TB.CRT_USR
	,[UPDATE_DATE] = TB.CRT_DT
	,WBS_CODE = TB.wbs
FROM 
	(SELECT 
		TE.VALID_FLAG,
		TE.TRAN_NO as TRN_NO,
		TE.PLANT as PLANT_NO,
		TE.S_WM_NO,
		TE.S_ZONE_NO,
		TE.O_WM_NO,
		TE.O_ZONE_NO,
		d.DETAIL_CODE AS TRAN_TYPE,
		TE.[TRAN_TIME],
		TE.[COST_CODE],
		TE.[FINANCIAL_CODE],
		TE.[INTERNAL_CODE],
		TE.[PUBLISH_TIME],
		TE.CREATE_USER as CRT_USR,
		TE.CREATE_DATE as CRT_DT,
		TE.WBS_CODE AS wbs 
	FROM 
		[LES].[TE_WMM_TRAN_HEAD_TEMP] TE
		JOIN LES.TC_SYS_CODE_DETAIL d
		ON TE.TRAN_TYPE=d.DETAIL_VALUE AND d.CODE_NAME='wms_tran_type'
		) TB 
WHERE 
	TB.VALID_FLAG = 1
	AND (TRAN_STATUS = 0 OR TRAN_STATUS IS NULL)
	AND TB.TRN_NO = TRAN_NO

INSERT INTO [LES].[TT_WMM_TRAN_DETAIL]
	(
	[TRAN_ID]
	,[TRAN_NO]
	,[PART_NO]
	,[PART_CNAME]
	,[S_DLOC]
	,[D_DLOC]
	,[BOX_NUM]
	,[NUM]
	,[COMMENTS]
	,[CREATE_USER]
	,[CREATE_DATE]
	,[UPDATE_USER]
	,[UPDATE_DATE]
	,PACKAGE_MODEL
	,PACKAGE
	)
	SELECT 
		TT.[TRAN_ID]
	    ,TT.[TRAN_NO]
        ,TE.[PART_NO]
        ,TM.[PART_CNAME]
		,TM.[DLOC]
		,ST.[DLOC]
        ,TE.[BOX_NUM]
        ,TE.[NUM]
		,TE.[COMMENTS]
        ,TE.[CREATE_USER]
        ,TE.[CREATE_DATE]
        ,TE.[UPDATE_USER]
        ,TE.[UPDATE_DATE]
		,TM.PACKAGE_MODEL
		,TM.PACKAGE
	FROM 
		[LES].[TE_WMM_TRAN_HEAD_TEMP] TE 
		JOIN [LES].[TT_WMM_TRAN_HEAD] TT ON TE.VALID_FLAG = 1 AND (TT.TRAN_STATUS = 0 OR TT.TRAN_STATUS IS NULL) AND TE.TRAN_NO = TT.TRAN_NO 
		JOIN (SELECT t1.PART_NO, t1.PART_CNAME, t1.PLANT, t1.WM_NO, t1.ZONE_NO, t1.DLOC, t1.PACKAGE, t1.PACKAGE_MODEL FROM [LES].[TM_BAS_PARTS_STOCK] t1) TM ON TE.PART_NO = TM.PART_NO AND TE.PLANT=TM.PLANT AND TE.S_WM_NO = TM.WM_NO AND TE.S_ZONE_NO = TM.ZONE_NO
		LEFT JOIN (SELECT t1.PART_NO, t1.PART_CNAME, t1.PLANT, t1.WM_NO, t1.ZONE_NO, t1.DLOC FROM [LES].[TM_BAS_PARTS_STOCK] t1) ST ON TE.PART_NO = ST.PART_NO AND TE.PLANT=ST.PLANT AND TE.O_WM_NO = ST.WM_NO AND TE.O_ZONE_NO = ST.ZONE_NO
	WHERE 
		(SELECT Count(*) FROM [LES].[TT_WMM_TRAN_DETAIL] t where t.TRAN_ID = TT.TRAN_ID and t.PART_NO = TE.PART_NO) = 0

UPDATE 
	[LES].[TT_WMM_TRAN_DETAIL]
SET
    [BOX_NUM] = TE.[BOX_NUM]
    ,[NUM] = TE.[NUM]
    ,[COMMENTS] = TE.[COMMENTS]
    ,[UPDATE_USER] = TE.[CREATE_USER]
    ,[UPDATE_DATE] =TE.[CREATE_DATE]
FROM 
	[LES].[TE_WMM_TRAN_HEAD_TEMP] TE 
	JOIN [LES].[TT_WMM_TRAN_HEAD] TT ON TE.VALID_FLAG = 1 AND (TT.TRAN_STATUS = 0 OR TT.TRAN_STATUS IS NULL) AND TE.TRAN_NO = TT.TRAN_NO
	JOIN [LES].[TT_WMM_TRAN_DETAIL] DE ON TT.TRAN_ID = DE.TRAN_ID AND TE.PART_NO = DE.PART_NO

DELETE FROM 
	[LES].[TT_WMM_TRAN_DETAIL] 
WHERE 
	TRAN_DETAIL_ID IN (
		Select 
			T2.TRAN_DETAIL_ID 
		from
			(
				SELECT 
					TT.TRAN_ID, TE.PART_NO,TT.TRAN_NO 
				FROM
					[LES].[TT_WMM_TRAN_HEAD] TT JOIN [LES].[TE_WMM_TRAN_HEAD_TEMP] TE 
				ON 
					TE.VALID_FLAG = 1 
					AND TE.TRAN_NO = TT.TRAN_NO
					AND (TT.TRAN_STATUS = 0 OR TT.TRAN_STATUS IS NULL)
			) T1
			RIGHT JOIN
			(
				SELECT 
					TT.TRAN_ID, DE.PART_NO, DE.TRAN_DETAIL_ID, TT.TRAN_NO 
				FROM 
					[LES].[TT_WMM_TRAN_DETAIL] DE,
					[LES].[TT_WMM_TRAN_HEAD] TT,
					[LES].[TE_WMM_TRAN_HEAD_TEMP] TE 
				WHERE 
					TT.TRAN_ID = DE.TRAN_ID
					AND TE.TRAN_NO = TT.TRAN_NO
					AND (TT.TRAN_STATUS = 0 OR TT.TRAN_STATUS IS NULL)
			) T2
			ON 
				T1.TRAN_ID = T2.TRAN_ID
				AND T1.PART_NO = T2.PART_NO
		WHERE 
			T1.PART_NO IS NULL
	)

END