

CREATE PROCEDURE [LES].[PROC_JIS_GET_MEET_EMERGENCY_TRIGGERSTATUS_ORDERS]
(
	@PLANT	NVARCHAR(5),
	@ASSEMBLY_LINE	NVARCHAR(10),
	@START_RUNNING_NO	NVARCHAR(5),
	@END_RUNNING_NO		NVARCHAR(5)
)
AS

BEGIN

	IF CONVERT(INT, @START_RUNNING_NO) > CONVERT(INT, @END_RUNNING_NO)
	BEGIN
			SELECT	A.ID, 
				A.ORDER_ID,			
				A.KNR,
				A.PASS_TIME,			
				A.VEHICLE_STATUS,			
				A.DCP_NAME,
				A.VIN,
				A.RUNNING_NO,
				A.ASSEMBLY_LINE,
				A.PLANT,
				A.MODEL_NO,
				A.TRIGGER_TYPE,
				A.PROCESS_FLAG,
				A.UPDATE_DATE,
				A.CREATE_DATE,	
				B.FARBAU, B.FARBIN, B.MODEL_YEAR, B.MODEL, B.ORDER_DATE, B.PNR_STRING_COMPUTE, B.WERK, B.VORSERIE,B.ASSEMBLY_LINE,B.SPJ			
			FROM	[LES].TT_JIS_TRIGGER_STATUS A, [LES].TT_BAS_PULL_ORDERS B
			WHERE	A.ORDER_ID = B.ORDER_NO and A.CREATE_DATE>getdate()-2
			AND		A.PLANT = @PLANT 
			AND		A.ASSEMBLY_LINE = @ASSEMBLY_LINE
			AND		A.RUNNING_NO BETWEEN @START_RUNNING_NO AND '9999'
			AND		A.VEHICLE_STATUS = 'M100'
			AND		A.TRIGGER_TYPE = 1
		UNION	
			SELECT	A.ID, 
				A.ORDER_ID,			
				A.KNR,
				A.PASS_TIME,			
				A.VEHICLE_STATUS,			
				A.DCP_NAME,
				A.VIN,
				A.RUNNING_NO,
				A.ASSEMBLY_LINE,
				A.PLANT,
				A.MODEL_NO,
				A.TRIGGER_TYPE,
				A.PROCESS_FLAG,
				A.UPDATE_DATE,
				A.CREATE_DATE,	
				B.FARBAU, B.FARBIN, B.MODEL_YEAR, B.MODEL, B.ORDER_DATE, B.PNR_STRING_COMPUTE, B.WERK, B.VORSERIE,B.ASSEMBLY_LINE,B.SPJ			
			FROM	[LES].TT_JIS_TRIGGER_STATUS A, [LES].TT_BAS_PULL_ORDERS B
			WHERE	A.ORDER_ID = B.ORDER_NO and A.CREATE_DATE>getdate()-2
			AND		A.PLANT = @PLANT 
			AND		A.ASSEMBLY_LINE = @ASSEMBLY_LINE
			AND		A.RUNNING_NO BETWEEN '0001' AND @END_RUNNING_NO
			AND		A.VEHICLE_STATUS = 'M100'	
			AND		A.TRIGGER_TYPE = 1	
	
		ORDER	BY ID
	END
	ELSE
	BEGIN
		SELECT	A.ID, 
			A.ORDER_ID,			
			A.KNR,
			A.PASS_TIME,			
			A.VEHICLE_STATUS,			
			A.DCP_NAME,
			A.VIN,
			A.RUNNING_NO,
			A.ASSEMBLY_LINE,
			A.PLANT,
			A.MODEL_NO,
			A.TRIGGER_TYPE,
			A.PROCESS_FLAG,
			A.UPDATE_DATE,
			A.CREATE_DATE,	
			B.FARBAU, B.FARBIN, B.MODEL_YEAR, B.MODEL, B.ORDER_DATE, B.PNR_STRING_COMPUTE, B.WERK, B.VORSERIE,B.ASSEMBLY_LINE,B.SPJ 			
	FROM	[LES].TT_JIS_TRIGGER_STATUS A, [LES].TT_BAS_PULL_ORDERS B
	WHERE	A.ORDER_ID = B.ORDER_NO and A.CREATE_DATE>getdate()-2
	AND		A.PLANT = @PLANT 
	AND		A.ASSEMBLY_LINE = @ASSEMBLY_LINE
	AND		A.RUNNING_NO BETWEEN @START_RUNNING_NO AND @END_RUNNING_NO
	AND		A.VEHICLE_STATUS = 'M100'
	AND		A.TRIGGER_TYPE = 1
	ORDER	BY A.ID
	END
END