



/********************************************************************/
/*                                                                  */
/*   Project Name:  LES System                         */
/*   Program Name:  [PROC_TT_WMM_REPACKAGE_CREATE_UPDATE]             */
/*   Called By:     by the Page							*/
/*   Purpose:       This is the main stored procedure for the       */
/*   author:       andy	2015-06-09     				       */
/********************************************************************/
CREATE PROCEDURE [LES].[PROC_WMM_REPACKAGE_CREATE_UPDATE]
 
AS

BEGIN

INSERT INTO [LES].[TT_WMM_REPACKAGE_HEAD]
	(
	[REPACKAGE_NO]
	,[REPACKAGE_TIME]
	,[REPACKAGE_BTIME]
	,REPACKAGE_ETIME
	,REPACKAGE_PICKUP_TIME
	,REPACKAGE_PICKUP_ETIME
	,[REPACKAGE_ROUTE]
	,BOOK_KEEPER
	,[PLANT]
	,[WM_NO]
	,[ZONE_NO]
	,[COUNT_STATUS]
	,[CREATE_USER]
	,[CREATE_DATE]
	,[UPDATE_USER]
	,[UPDATE_DATE]
	)
	SELECT distinct 
		[REPACKAGE_NO]
		,[REPACKAGE_TIME]
		,CASE WHEN [REPACKAGE_BTIME]='1900-01-01 00:00:00.000' THEN NULL ELSE [REPACKAGE_BTIME] END AS REPACKAGE_BTIME
		,CASE WHEN [REPACKAGE_ETIME]='1900-01-01 00:00:00.000' THEN NULL ELSE [REPACKAGE_ETIME] END AS REPACKAGE_ETIME
		,CASE WHEN [REPACKAGE_PICKUP_TIME]='1900-01-01 00:00:00.000' THEN NULL ELSE [REPACKAGE_PICKUP_TIME] END AS REPACKAGE_PICKUP_TIME
		,CASE WHEN [REPACKAGE_PICKUP_ETIME]='1900-01-01 00:00:00.000' THEN NULL ELSE [REPACKAGE_PICKUP_ETIME] END AS REPACKAGE_PICKUP_ETIME
		,upper(REPACKAGE_ROUTE)
		,BOOK_KEEPER
		,TE.[PLANT]
		,TE.[WM_NO]
		,TE.[ZONE_NO]
		,0
        ,TE.[CREATE_USER]
        ,TE.[CREATE_DATE]
        ,TE.[UPDATE_USER]
        ,TE.[UPDATE_DATE]
	FROM 
		[LES].[TE_WMM_REPACKAGE_TEMP] TE
	WHERE 
		TE.VALID_FLAG = 1
		AND TE.REPACKAGE_NO NOT IN (SELECT [REPACKAGE_NO] FROM [LES].[TT_WMM_REPACKAGE_HEAD])

UPDATE 
	[LES].[TT_WMM_REPACKAGE_HEAD] 
SET
    [REPACKAGE_NO] = TE.[REPACKAGE_NO]
	,[REPACKAGE_TIME] = TE.[REPACKAGE_TIME]
	,[REPACKAGE_BTIME] = CASE WHEN TE.[REPACKAGE_BTIME]='1900-01-01 00:00:00.000' THEN NULL ELSE TE.[REPACKAGE_BTIME] END
	,REPACKAGE_ETIME = CASE WHEN TE.REPACKAGE_ETIME='1900-01-01 00:00:00.000' THEN NULL ELSE TE.REPACKAGE_ETIME END
	,REPACKAGE_PICKUP_TIME = CASE WHEN TE.REPACKAGE_PICKUP_TIME='1900-01-01 00:00:00.000' THEN NULL ELSE TE.REPACKAGE_PICKUP_TIME END
	,REPACKAGE_PICKUP_ETIME = CASE WHEN TE.REPACKAGE_PICKUP_ETIME='1900-01-01 00:00:00.000' THEN NULL ELSE TE.REPACKAGE_PICKUP_ETIME END 
	,REPACKAGE_ROUTE = upper(TE.REPACKAGE_ROUTE)
	,BOOK_KEEPER = TE.BOOK_KEEPER
	,[PLANT] = TE.[PLANT]
	,[WM_NO] = TE.[WM_NO]
	,[ZONE_NO] = TE.[ZONE_NO]
	,[UPDATE_USER] = TE.[CREATE_USER]
	,[UPDATE_DATE] = TE.[CREATE_DATE]
FROM 
	[LES].[TE_WMM_REPACKAGE_TEMP] TE,
	[LES].[TT_WMM_REPACKAGE_HEAD] TT
WHERE 
	TE.VALID_FLAG = 1 
	AND TE.REPACKAGE_NO = TT.REPACKAGE_NO 
	AND (TT.COUNT_STATUS = 0 OR TT.COUNT_STATUS IS NULL)

INSERT INTO [LES].[TT_WMM_REPACKAGE_DETAIL]
	(
	[REPACKAGE_ID]
	,[REPACKAGE_NO]
	,[PART_NO]
	,[ZONE_NO]
	,[ULOC]
	,[PART_CNAME]
	,[NUM]
	,INHOUSE_PACKAGE_MODEL
	,INHOUSE_PACKAGE
	,INBOUND_PACKAGE_MODEL
	,INBOUND_PACKAGE
	,[PACKAGE_MODEL]
	,PACKAGE
	,WM_NO
	,[CREATE_USER]
	,[CREATE_DATE]
	,[UPDATE_USER]
	,[UPDATE_DATE]
	,REQUIRED_QTY
	,ACTUAL_QTY
	)
	SELECT 
		TT.[REPACKAGE_ID]
		,TT.[REPACKAGE_NO]
        ,upper(TE.[PART_NO])
		,TE.ZONE_NO
		,TM.DLOC
        ,TM.[PART_CNAME]
        ,TE.[NUM]
		,tm.INHOUSE_PACKAGE_MODEL
        ,TM.INHOUSE_PACKAGE
		,tm.INBOUND_PACKAGE_MODEL
		,tm.INBOUND_PACKAGE
        ,TM.[PACKAGE_MODEL]
		,TM.PACKAGE
		,tt.WM_NO
        ,TE.[CREATE_USER]
        ,TE.[CREATE_DATE]
        ,TE.[UPDATE_USER]
        ,TE.[UPDATE_DATE]
		,TE.[NUM]*TM.PACKAGE
		,null
	FROM 
		[LES].[TE_WMM_REPACKAGE_TEMP] TE 
		JOIN [LES].[TT_WMM_REPACKAGE_HEAD] TT 
		ON TE.VALID_FLAG = 1 AND (TT.COUNT_STATUS = 0 OR TT.COUNT_STATUS IS NULL) AND TE.REPACKAGE_NO = TT.REPACKAGE_NO 
		JOIN  [LES].[TM_BAS_PARTS_STOCK] TM 
		ON TE.PART_NO = TM.PART_NO AND TE.PLANT=TM.PLANT AND TE.WM_NO = TM.WM_NO AND TE.ZONE_NO = TM.ZONE_NO
	WHERE 
		(SELECT Count(*) FROM [LES].[TT_WMM_REPACKAGE_DETAIL] t where t.REPACKAGE_ID = TT.REPACKAGE_ID and t.PART_NO = TE.PART_NO) = 0

UPDATE 
	[LES].[TT_WMM_REPACKAGE_DETAIL]
SET
    [REPACKAGE_ID] = TT.[REPACKAGE_ID]
	,[REPACKAGE_NO] = TE.[REPACKAGE_NO]
	,[PART_NO] = upper(TE.[PART_NO])
	,[ZONE_NO]= TE.ZONE_NO
	,[ULOC]= TM.DLOC
	,[NUM] = TE.[NUM]
	,[PART_CNAME] = TM.[PART_CNAME]
	,INHOUSE_PACKAGE_MODEL = TM.INHOUSE_PACKAGE_MODEL
	,INHOUSE_PACKAGE = TM.INHOUSE_PACKAGE
	,INBOUND_PACKAGE_MODEL=TM.INBOUND_PACKAGE_MODEL
	,INBOUND_PACKAGE = TM.INBOUND_PACKAGE
	,[PACKAGE_MODEL] = TM.[PACKAGE_MODEL]
	,PACKAGE = TM.PACKAGE
	,[UPDATE_USER] = TE.[CREATE_USER]
	,[UPDATE_DATE] = TE.[CREATE_DATE]
	,REQUIRED_QTY =TE.[NUM]*TM.PACKAGE
	,ACTUAL_QTY = null
FROM 
	[LES].[TE_WMM_REPACKAGE_TEMP] TE 
	JOIN [LES].[TT_WMM_REPACKAGE_HEAD] TT ON TE.VALID_FLAG = 1 AND (TT.COUNT_STATUS = 0 OR TT.COUNT_STATUS IS NULL) AND TE.REPACKAGE_NO = TT.REPACKAGE_NO
	JOIN [LES].[TT_WMM_REPACKAGE_DETAIL] DE ON TT.REPACKAGE_ID = DE.REPACKAGE_ID AND TE.PART_NO = DE.PART_NO
	JOIN  [LES].[TM_BAS_PARTS_STOCK] TM ON TE.PART_NO = TM.PART_NO AND TE.PLANT=TM.PLANT AND TE.WM_NO = TM.WM_NO AND TE.ZONE_NO = TM.ZONE_NO

DELETE FROM 
	[LES].[TT_WMM_REPACKAGE_DETAIL] 
WHERE 
	TRAN_ID IN (
		Select 
			T2.TRAN_ID 
		from
			(
				SELECT 
					TT.REPACKAGE_ID, TE.PART_NO,TT.REPACKAGE_NO 
				FROM
					[LES].[TT_WMM_REPACKAGE_HEAD] TT JOIN [LES].[TE_WMM_REPACKAGE_TEMP] TE 
				ON 
					TE.VALID_FLAG = 1 
					AND TE.REPACKAGE_NO = TT.REPACKAGE_NO
					AND (TT.COUNT_STATUS = 0 OR TT.COUNT_STATUS IS NULL)
			) T1
			RIGHT JOIN
			(
				SELECT 
					TT.REPACKAGE_ID, DE.PART_NO, DE.TRAN_ID, TT.REPACKAGE_NO 
				FROM 
					[LES].[TT_WMM_REPACKAGE_DETAIL] DE,
					[LES].[TT_WMM_REPACKAGE_HEAD] TT,
					[LES].[TE_WMM_REPACKAGE_TEMP] TE 
				WHERE 
					TT.REPACKAGE_ID = DE.REPACKAGE_ID
					AND TE.REPACKAGE_NO = TT.REPACKAGE_NO
					AND (TT.COUNT_STATUS = 0 OR TT.COUNT_STATUS IS NULL)
			) T2
			ON 
				T1.REPACKAGE_ID = T2.REPACKAGE_ID
				AND T1.PART_NO = T2.PART_NO
		WHERE 
			T1.PART_NO IS NULL
	)
END