
/********************************************************************/
/*                                                                  */
/*   Project Name:  Production Pull System                          */
/*   Program Name:  PROC_BAS_INBOUND_PULL_CREATE_UPDATE              */
/*   Called By:     by the Page							*/
/*   Purpose:       This is the main stored procedure for the       */
/*   author:       wangchanghong	2011-06-20   				       */
/********************************************************************/
CREATE PROCEDURE [LES].[PROC_BAS_INBOUND_PULL_CREATE_UPDATE]
 
AS



BEGIN

UPDATE [LES].[TM_BAS_INBOUND_PULL_LOGISTIC_STANDARD]
   SET [PLANT] = TE.[PLANT]
      ,[ASSEMBLY_LINE] = TE.[ASSEMBLY_LINE]
      ,[PLANT_ZONE] = TE.[PLANT_ZONE]
      ,[WORKSHOP] = TE.[WORKSHOP]
      ,[SUPPLIER_NUM] = TE.[SUPPLIER_NUM]
      ,[TRANS_SUPPLIER_NUM] = TE.[TRANS_SUPPLIER_NUM]
      ,[MODEL] = TE.[MODEL]
      ,[PART_NO] = TE.[PART_NO]
      ,[INDENTIFY_PART_NO] = TE.[INDENTIFY_PART_NO]
      ,[AMOUNTRATIO] = TE.[AMOUNTRATIO]
      ,[EXTERIOR_COLOR] = TE.[EXTERIOR_COLOR]
      ,[INTERNAL_COLOR] = TE.[INTERNAL_COLOR]
      ,[HAND_KEPT_RECORD] = TE.[HAND_KEPT_RECORD]
      ,[COLOR_CONTROL_PATCH] = TE.[COLOR_CONTROL_PATCH]
      ,[VWS] = TE.[VWS]
      ,[RAND] = TE.[RAND]
      ,[SECTION] = TE.[SECTION]
      ,[PART_OPTION] = TE.[PART_OPTION]
      ,[PRODUCTION_NUMBER] = TE.[PRODUCTION_NUMBER]
      ,[START_PRODUCTION_DATE] = TE.[START_PRODUCTION_DATE]
      ,[CANCEL_NUMBER] = TE.[CANCEL_NUMBER]
      ,[END_PRODUCTION_DATE] = TE.[END_PRODUCTION_DATE]
      ,[MODEL_YEAR] = TE.[MODEL_YEAR]
      ,[DOSAGE] = TE.[DOSAGE]
      ,[MEASURING_UNIT_NO] = TE.[MEASURING_UNIT_NO]
      ,[AMOUNT_FLAG] = TE.[AMOUNT_FLAG]
      ,[DATA_DATE] = TE.[DATA_DATE]
      ,[VORSERIE] = TE.[VORSERIE]
      ,[PART_CNAME] = TE.[PART_CNAME]
      ,[PART_ENAME] = TE.[PART_ENAME]
      ,[LOAD_FLAG] = TE.[LOAD_FLAG]
      ,[ZP_FLAG] = TE.[ZP_FLAG]
      ,[REQUIREMENT_FLAG] = TE.[REQUIREMENT_FLAG]
      ,[LOGICAL_PK] = TE.[LOGICAL_PK]
      ,[ASSEMBLY_FLAG] = TE.[ASSEMBLY_FLAG]
      ,[ASSEMBLY_FLAG_RECRUIT] = TE.[ASSEMBLY_FLAG_RECRUIT]
      ,[MARK] = TE.[MARK]
      ,[PURCHASE_STYLE] = TE.[PURCHASE_STYLE]
      ,[VALID_FLAG] =TE.[VALID_FLAG]
      ,[INBOUND_MODE] = TE.[INBOUND_MODE]
      ,[INBOUND_LOGISTIC_MODE] = TE.[INBOUND_LOGISTIC_MODE]
      ,[INBOUND_SYSTEM_MODE] = TE.[INBOUND_SYSTEM_MODE]
      ,[EFFECTIVE_STATUS] = TE.[EFFECTIVE_STATUS]
      ,[START_EFFECTIVE_DATE] = TE.[START_EFFECTIVE_DATE]
      ,[INBOUND_PART_CLASS] = TE.[INBOUND_PART_CLASS]
      ,[DOCK] = TE.[DOCK]
      ,[INBOUND_PACKAGE_MODEL] = TE.[INBOUND_PACKAGE_MODEL]
      ,[INBOUND_PACKAGE] = TE.[INBOUND_PACKAGE]
      ,[IS_SPLIT] = TE.[IS_SPLIT]
      ,[TERMAL_PK] = TE.[TERMAL_PK]
      ,[DIFF_FLAG] = TE.[DIFF_FLAG]
      ,[COMMENTS] = TE.[COMMENTS]
      ,[UPDATE_DATE] = TE.[UPDATE_DATE]
      ,[UPDATE_USER] = TE.[UPDATE_USER]
      ,[CREATE_DATE] = TE.[CREATE_DATE]
      ,[CREATE_USER] = TE.[CREATE_USER]
 FROM LES.TE_BAS_TMP_INBOUND_PULL_LOGISTIC_STANDARD AS TE,
     [LES].[TM_BAS_INBOUND_PULL_LOGISTIC_STANDARD] AS TM
 WHERE TE.LOGICAL_PK = TM.LOGICAL_PK
 
INSERT INTO [LES].[TM_BAS_INBOUND_PULL_LOGISTIC_STANDARD]
           ([PLANT],[ASSEMBLY_LINE],[PLANT_ZONE]
           ,[WORKSHOP],[SUPPLIER_NUM],[TRANS_SUPPLIER_NUM]
           ,[MODEL],[PART_NO],[INDENTIFY_PART_NO]
           ,[AMOUNTRATIO],[EXTERIOR_COLOR],[INTERNAL_COLOR]
           ,[HAND_KEPT_RECORD],[COLOR_CONTROL_PATCH],[VWS]
           ,[RAND],[SECTION],[PART_OPTION]
           ,[PRODUCTION_NUMBER],[START_PRODUCTION_DATE],[CANCEL_NUMBER]
           ,[END_PRODUCTION_DATE],[MODEL_YEAR],[DOSAGE]
           ,[MEASURING_UNIT_NO],[AMOUNT_FLAG],[DATA_DATE]
           ,[VORSERIE],[PART_CNAME],[PART_ENAME]
           ,[LOAD_FLAG],[ZP_FLAG],[REQUIREMENT_FLAG]
           ,[LOGICAL_PK],[ASSEMBLY_FLAG],[ASSEMBLY_FLAG_RECRUIT]
           ,[MARK],[PURCHASE_STYLE],[VALID_FLAG]
           ,[INBOUND_MODE],[INBOUND_LOGISTIC_MODE],[INBOUND_SYSTEM_MODE]
           ,[EFFECTIVE_STATUS],[START_EFFECTIVE_DATE],[INBOUND_PART_CLASS]
           ,[DOCK],[INBOUND_PACKAGE_MODEL],[INBOUND_PACKAGE]
           ,[IS_SPLIT],[TERMAL_PK],[DIFF_FLAG]
           ,[COMMENTS]
           ,[UPDATE_DATE],[UPDATE_USER]
           ,[CREATE_DATE],[CREATE_USER]
           )
SELECT
           TE.[PLANT],TE.[ASSEMBLY_LINE],TE.[PLANT_ZONE]
           ,TE.[WORKSHOP],TE.[SUPPLIER_NUM],TE.[TRANS_SUPPLIER_NUM]
           ,TE.[MODEL],TE.[PART_NO],TE.[PART_NO]
           ,TE.[AMOUNTRATIO],TE.[EXTERIOR_COLOR],TE.[INTERNAL_COLOR]
           ,TE.[HAND_KEPT_RECORD],TE.[COLOR_CONTROL_PATCH],TE.[VWS]
           ,TE.[RAND],TE.[SECTION],TE.[PART_OPTION]
           ,TE.[PRODUCTION_NUMBER],TE.[START_PRODUCTION_DATE],TE.[CANCEL_NUMBER]
           ,TE.[END_PRODUCTION_DATE],TE.[MODEL_YEAR],TE.[DOSAGE]
           ,TE.[MEASURING_UNIT_NO],TE.[AMOUNT_FLAG],TE.[DATA_DATE]
           ,TE.[VORSERIE],TE.[PART_CNAME],TE.[PART_ENAME]
           ,TE.[LOAD_FLAG],TE.[ZP_FLAG],TE.[REQUIREMENT_FLAG]
           ,TE.[LOGICAL_PK],TE.[ASSEMBLY_FLAG],TE.[ASSEMBLY_FLAG_RECRUIT]
           ,TE.[MARK],TE.[PURCHASE_STYLE],TE.[VALID_FLAG]
           ,TE.[INBOUND_MODE],TE.[INBOUND_LOGISTIC_MODE],TE.[INBOUND_SYSTEM_MODE]
           ,TE.[EFFECTIVE_STATUS],TE.[START_EFFECTIVE_DATE],TE.[INBOUND_PART_CLASS]
           ,TE.[DOCK],TE.[INBOUND_PACKAGE_MODEL],TE.[INBOUND_PACKAGE]
           ,TE.[IS_SPLIT],TE.[TERMAL_PK],TE.[DIFF_FLAG]
           ,TE.[COMMENTS]
           ,TE.[UPDATE_DATE],TE.[UPDATE_USER]
           ,TE.[CREATE_DATE],TE.[CREATE_USER]
  FROM [LES].[TE_BAS_TMP_INBOUND_PULL_LOGISTIC_STANDARD] AS TE
  LEFT JOIN LES.TM_BAS_MAINTAIN_INBOUND_LOGISTIC_STANDARD AS TM ON TE.LOGICAL_PK = TM.LOGICAL_PK 
WHERE TM.LOGICAL_PK IS NULL AND TE.VALID_FLAG = 1

--插入到TWD计数器

INSERT INTO [LES].[TT_TWD_CONSUME_COUNTER]
           ([PLANT] --*关键
           ,[ASSEMBLY_LINE] --*关键
           ,[SUPPLIER_NUM]       --*关键
           ,[MODEL] --*关键
           ,[PART_NO] --*关键
           ,[INDENTIFY_PART_NO]
           ,[AMOUNTRATIO]
           ,[INBOUND_PART_CLASS]
           ,[MEASURING_UNIT_NO]
           ,[PART_CNAME]
           ,[PART_ENAME]
           ,[DOCK] --*关键
           ,[INBOUND_PACKAGE_MODEL]
           ,[INBOUND_PACKAGE]
           ,[CURRENT_PART_COUNT]
           ,[CREATE_DATE])
       
	  SELECT distinct  A.[PLANT]
      ,A.[ASSEMBLY_LINE]
      ,A.[SUPPLIER_NUM]
      ,A.[MODEL]
      ,A.[PART_NO]
      ,A.[INDENTIFY_PART_NO]
      ,A.[AMOUNTRATIO]
      ,A.[INBOUND_PART_CLASS]
      ,A.[MEASURING_UNIT_NO]
      ,A.[PART_CNAME]
      ,A.[PART_ENAME]
      ,A.[DOCK]
      ,A.[INBOUND_PACKAGE_MODEL]
      ,A.[INBOUND_PACKAGE]
      ,0 
      ,getdate()
    FROM [LES].[TM_BAS_INBOUND_PULL_LOGISTIC_STANDARD]  A WHERE not exists (SELECT * FROM 
		   [LES].[TT_TWD_CONSUME_COUNTER] B WHERE A.[PLANT]=B.[PLANT] AND A.[ASSEMBLY_LINE]=B.[ASSEMBLY_LINE] AND A.[SUPPLIER_NUM]=B.[SUPPLIER_NUM] AND
		  A.[MODEL]=B.[MODEL] AND A.[PART_NO]=B.[PART_NO]) AND  A.[INBOUND_SYSTEM_MODE]='TWD' 


--更新计数器
/*UPDATE A SET  A.[INHOUSE_PACKAGE_MODEL]=B.[INHOUSE_PACKAGE_MODEL]
           ,A.[INHOUSE_PACKAGE]=B.[INHOUSE_PACKAGE]
    FROM [LES].[TT_TWD_CONSUME_COUNTER] A INNER JOIN 
    [LES].[TM_BAS_INHOUSE_PULL_LOGISTIC_STANDARD]  B  ON A.[PLANT]=B.[PLANT] AND A.[ASSEMBLY_LINE]=B.[ASSEMBLY_LINE] AND A.[SUPPLIER_NUM]=B.[SUPPLIER_NUM] AND
		  A.[LOCATION]=B.[LOCATION] and A.[PART_NO]=B.[PART_NO]
    INNER JOIN [LES].[TM_PCS_ROUTE_BOX_PARTS] C ON A.[PLANT]=C.[PLANT] AND A.[ASSEMBLY_LINE]=C.[ASSEMBLY_LINE]  and A.IN_PLANT_LOGISTIC_PART_CLASS=c.BOX_PARTS
    WHERE B.[IN_PLANT_SYSTEM_MODE]='PCS'  AND (A.[INHOUSE_PACKAGE]!=B.[INHOUSE_PACKAGE] OR A.[INHOUSE_PACKAGE_MODEL]!=B.[INHOUSE_PACKAGE_MODEL])
*/		  
--删除计数器数据
delete from [LES].[TT_TWD_CONSUME_COUNTER]  where not	exists (SELECT * FROM 
		   [LES].[TM_BAS_INBOUND_PULL_LOGISTIC_STANDARD] B WHERE [LES].[TT_TWD_CONSUME_COUNTER].[PLANT]=B.[PLANT] AND [LES].[TT_TWD_CONSUME_COUNTER].[ASSEMBLY_LINE]=B.[ASSEMBLY_LINE] AND [LES].[TT_TWD_CONSUME_COUNTER].[SUPPLIER_NUM]=B.[SUPPLIER_NUM] AND
		  [LES].[TT_TWD_CONSUME_COUNTER].[MODEL]=B.[MODEL] and [LES].[TT_TWD_CONSUME_COUNTER].[PART_NO]=B.[PART_NO] AND  B.[INBOUND_SYSTEM_MODE]='TWD'   )  

	
END