

CREATE PROCEDURE [LES].[PROC_WMM_RECEIVE_IMPORT]
 
AS

BEGIN

--注释  每次导入都为新的一批订单数据
--代码描述  如果存在重复订单则把之前录入数据复制到临时表中用于后边更新（初步猜测）
--INSERT INTO LES.TE_WMM_RECEIVE_TEMP
--SELECT DISTINCT
--     T.[RECEIVE_NO]
--	,T.[RECEIVE_TYPE]
--    ,T.[PLANT]
--    ,T.[WM_NO]
--    ,T.[ZONE_NO]
--    ,T.[SUPPLIER_NUM]
--	,T.[SEND_TIME]
--	,D.PART_NO
--	,T.[DELIVERY_LOCATION_NAME]
--    ,T.[DOCK]
--	,D.[REQUIRED_BOX_NUM]
--	,D.[REQUIRED_QTY]
--	,D.[ACTUAL_BOX_NUM]
--	,D.[ACTUAL_QTY]
--    ,T.[RECEIVE_REASON]
--    ,T.[COMMENTS]
--    ,T.[CREATE_DATE]
--    ,T.[CREATE_USER]
--    ,'' as [ERROR_MSG]
--    ,'1'as [VALID_FLAG]
--	,''
--	,''
--	,''
--	,''
--	,D.[Current_BOX_NUM]
--	,D.[Current_QTY]
--	,''
--	,''
--  FROM [LES].[TT_WMM_RECEIVE] M(NOLOCK)
--  left join [LES].[TT_WMM_RECEIVE_DETAIL] D(NOLOCK) ON M.RECEIVE_ID = D.RECEIVE_ID
--  LEFT JOIN LES.TE_WMM_RECEIVE_TEMP T (NOLOCK) on M.RECEIVE_NO = T.RECEIVE_NO
--  where D.PART_NO IS NOT NULL
--  and EXISTS
--  (
--		SELECT 1 FROM 
--		LES.TE_WMM_RECEIVE_TEMP T(NOLOCK) 
--		WHERE T.RECEIVE_NO = M.RECEIVE_NO
--		 AND T.[PART_NO] <>	D.PART_NO AND M.CONFIRM_FLAG = 0
--  )

--DELETE FROM  [LES].[TT_WMM_RECEIVE] WHERE CONFIRM_FLAG = 0 
--	AND RECEIVE_NO IN
--	(
--		SELECT DISTINCT RECEIVE_NO FROM	LES.TE_WMM_RECEIVE_TEMP (NOLOCK) 
--	)

INSERT INTO [LES].[TT_WMM_RECEIVE]
	(
	[RECEIVE_NO]
	,[RECEIVE_TYPE]
	,[PLANT]
	,[WM_NO]
	,[ZONE_NO]
	,[SUPPLIER_NUM]
	,[SEND_TIME]
	,[CONFIRM_FLAG]
	,[DELIVERY_LOCATION_NAME]
	,[DOCK]
	,RECEIVE_REASON
	,[COMMENTS]
	,[CREATE_USER]
	,[CREATE_DATE]
	)
	SELECT 
		[RECEIVE_NO]
        ,MAX([RECEIVE_TYPE]) [RECEIVE_TYPE]
        ,MAX([PLANT]) [PLANT]
        ,MAX([WM_NO]) [WM_NO]
        ,MAX([ZONE_NO]) [ZONE_NO]
        ,MAX([SUPPLIER_NUM]) [SUPPLIER_NUM]
        ,MAX([SEND_TIME]) [SEND_TIME]
		,0 AS [CONFIRM_FLAG]
		,MAX([DELIVERY_LOCATION_NAME]) [DELIVERY_LOCATION_NAME]
	    ,MAX([DOCK]) [DOCK]
		,MAX(RECEIVE_REASON) RECEIVE_REASON
		,MAX([COMMENTS]) [COMMENTS] 
        ,MAX([CREATE_USER]) [CREATE_USER]
        ,MAX([CREATE_DATE]) [CREATE_DATE]
	FROM [LES].[TE_WMM_RECEIVE_TEMP] GROUP BY [RECEIVE_NO]

INSERT INTO [LES].[TT_WMM_RECEIVE_DETAIL]
	(
	[RECEIVE_ID]
	,[PLANT]
	,[WM_NO]
	,[ZONE_NO]
	,[SUPPLIER_NUM]
	,DLOC
	,PACKAGE
	,[PACKAGE_MODEL]
	,BOX_PARTS
	,[PART_NO]
	,[PART_CNAME]
	,PART_ENAME
	--,PART_TYPE
	,[REQUIRED_BOX_NUM]
	,[REQUIRED_QTY]
	,[ACTUAL_BOX_NUM]
	,[ACTUAL_QTY]
	,[Current_BOX_NUM]
	,[Current_QTY]
	,[CREATE_USER]
	,[CREATE_DATE]
	)
	SELECT 
		TT.[RECEIVE_ID]
	    ,TT.[PLANT]
		,TT.[WM_NO]
		,TT.[ZONE_NO]
        ,TT.[SUPPLIER_NUM]
		,ST.DLOC
		,ST.PACKAGE
		,ST.PACKAGE_MODEL
		,ST.PART_CLS
        ,TE.[PART_NO]
        ,ST.[PART_CNAME]
		,ST.PART_ENAME
		--,ST.PART_CLS
        ,TE.[REQUIRED_BOX_NUM]
        ,TE.[REQUIRED_QTY]
		,TE.[ACTUAL_BOX_NUM]
        ,TE.[ACTUAL_QTY]
		,TE.[Current_BOX_NUM]
        ,TE.[Current_QTY]
        ,TE.[CREATE_USER]
        ,TE.[CREATE_DATE]
	FROM 
		[LES].[TE_WMM_RECEIVE_TEMP] TE (NOLOCK) 
		JOIN [LES].[TT_WMM_RECEIVE] TT (NOLOCK)  ON TE.RECEIVE_NO = TT.RECEIVE_NO
		LEFT JOIN [LES].[TM_BAS_PARTS_STOCK] (NOLOCK)  ST ON TT.ZONE_NO = ST.ZONE_NO AND TE.PART_NO = ST.PART_NO

END