


CREATE PROCEDURE [LES].[PROC_JIS_GET_RUNSHEET_REPORT]
(
	@pJISRunsheetSn	nvarchar(4000)
)
AS
DECLARE @SQLString NVARCHAR(2000)
BEGIN

	CREATE TABLE #Temp_JIS_BOX_SUMMARY  
	(
		JIS_RUNSHEET_SN	INT,
		JIS_RUNSHEET_NO	NVARCHAR(18),
		JIS_BOX_SN	INT,
		PART_NO NVARCHAR(20),
		PLANT NVARCHAR(5),
		ASSEMBLY_LINE NVARCHAR(10),
		RACK NVARCHAR(20),
		RACK_CNAME NVARCHAR(200),
		SUPPLIER_NUM NVARCHAR(12),
		SUPPLIER_NAME NVARCHAR(100),
		LOCATION NVARCHAR(20),
		DOCK NVARCHAR(10),		
		USAGE INT,
		MODEL NVARCHAR(10),
		MODEL_NO NVARCHAR(8),
		KNR NVARCHAR(8),
		RUNNING_NUMBER NVARCHAR(5),
		START_RUNNING_NO NVARCHAR(5),
		END_RUNNING_NO NVARCHAR(5),
		JIS_RUNSHEET_FLEX_TIME NVARCHAR(20),
		EXPECTED_ARRIVAL_TIME NVARCHAR(20),
		REQUEST_TIME NVARCHAR(20),
		PRINT_TIME NVARCHAR(20),
		PUBLISH_TIME NVARCHAR(20),
		CAT_PART_NO NVARCHAR(2000),
		CAT_USAGE NVARCHAR(200),
		SUM_PART_NO INT,
		LOC_PART_NO NVARCHAR(200),
		COMMENTS NVARCHAR(200),
		TOTAL_PART_NO INT,
		PAGE_SIZE INT,
		DETAIL_ROW_NUM INT,
		TOTAL_ROW_NUM INT,
		DETAIL_FONT_SIZE NVARCHAR(10),
		TOTAL_FONT_SIZE NVARCHAR(10)
	)
	CREATE INDEX IX_#Temp_JIS_BOX_SUMMARY ON #Temp_JIS_BOX_SUMMARY(JIS_RUNSHEET_SN)
	
	CREATE TABLE #Temp_JIS_RUNSHEET_SN
	(
		JIS_RUNSHEET_SN	INT
	)
	CREATE INDEX IX_#Temp_JIS_RUNSHEET_SN_1 ON #Temp_JIS_RUNSHEET_SN(JIS_RUNSHEET_SN)
	
	IF @pJISRunsheetSn IS NULL OR @pJISRunsheetSn = ''
	BEGIN
		SELECT A.JIS_RUNSHEET_NO, A.JIS_BOX_SN, A.PART_NO, A.PLANT, A.ASSEMBLY_LINE, A.RACK, A.RACK_CNAME, A.SUPPLIER_NUM, A.SUPPLIER_NAME,
			A.LOCATION,A.DOCK,A.USAGE, A.MODEL, A.MODEL_NO, A.KNR, A.RUNNING_NUMBER, A.START_RUNNING_NO, A.END_RUNNING_NO, 
			A.JIS_RUNSHEET_FLEX_TIME,A.EXPECTED_ARRIVAL_TIME,A.REQUEST_TIME,A.PRINT_TIME, A.PUBLISH_TIME, 
			A.CAT_PART_NO, A.CAT_USAGE, A.SUM_PART_NO, A.LOC_PART_NO, A.COMMENTS, A.TOTAL_PART_NO, A.PAGE_SIZE, 
			A.DETAIL_ROW_NUM, A.TOTAL_ROW_NUM, A.DETAIL_FONT_SIZE, A.TOTAL_FONT_SIZE
		FROM #Temp_JIS_BOX_SUMMARY A
		
		RETURN
	END
	
	SET @SQLString=	' INSERT INTO #Temp_JIS_RUNSHEET_SN ' + 
				' SELECT JIS_RUNSHEET_SN FROM LES.TT_JIS_RUNSHEET WHERE JIS_RUNSHEET_SN IN ' + @pJISRunsheetSn
				
	EXECUTE sp_executesql @SQLString
	
	INSERT INTO #Temp_JIS_BOX_SUMMARY	
	SELECT D.JIS_RUNSHEET_SN, C.JIS_RUNSHEET_NO, B.JIS_BOX_SN, A.PART_NO, C.PLANT, C.ASSEMBLY_LINE, C.RACK, NULL, D.SUPPLIER_NUM, NULL,
		ISNULL(D.LOCATION,'') AS LOCATION, D.DOCK,  A.USAGE, B.MODEL, B.MODEL_NO, C.CAR_NO, C.RUNNING_NUMBER, START_RUNNING_NO,END_RUNNING_NO,		  
		CONVERT(VARCHAR,JIS_RUNSHEET_FLEX_TIME,20) , CONVERT(VARCHAR,ESTIMATED_ARRIVAL_TIME,20) ,  CONVERT(VARCHAR,EXPECTED_ARRIVAL_TIME, 20),
		CONVERT(VARCHAR, GETDATE(),20), CONVERT(VARCHAR,JIS_RUNSHEET_TIME,20),
		'','',0,'', '', 0, 20, 0, 0, '10pt', '10pt'
	 FROM [LES].TT_JIS_RUNSHEET_DETAIL A
	 INNER JOIN [LES].TT_JIS_RUNSHEET_BOX B ON A.JIS_RUNSHEET_FLEX_SN = B.JIS_RUNSHEET_FLEX_SN AND A.JIS_RUNSHEET_BOX_SN = B.JIS_RUNSHEET_BOX_SN
	 INNER JOIN [LES].TT_JIS_RUNSHEET_FLEX C ON B.JIS_RUNSHEET_FLEX_SN = C.JIS_RUNSHEET_FLEX_SN 
	 INNER JOIN [LES].TT_JIS_RUNSHEET D ON C.JIS_RUNSHEET_NO = D.JIS_RUNSHEET_NO
	 INNER JOIN #Temp_JIS_RUNSHEET_SN E ON D.JIS_RUNSHEET_SN = E.JIS_RUNSHEET_SN
	 
	 UPDATE #Temp_JIS_BOX_SUMMARY 
	 SET	RACK_CNAME = B.RACK_CNAME
	 FROM	#Temp_JIS_BOX_SUMMARY A, [LES].TM_JIS_RACK B
	 WHERE	A.RACK = B.RACK
	 
	 UPDATE #Temp_JIS_BOX_SUMMARY 
	 SET	SUPPLIER_NAME = B.SUPPLIER_NAME
	 FROM	#Temp_JIS_BOX_SUMMARY A, [LES].TM_BAS_SUPPLIER B
	 WHERE	A.SUPPLIER_NUM = B.SUPPLIER_NUM
	
	
	UPDATE #Temp_JIS_BOX_SUMMARY
	SET	CAT_PART_NO = BB.PART_NO,
		CAT_USAGE = BB.USAGE
	FROM #Temp_JIS_BOX_SUMMARY A,
		(
		SELECT JIS_RUNSHEET_NO, JIS_BOX_SN, 
			PART_NO=(SELECT PART_NO + CHAR(10) FROM #Temp_JIS_BOX_SUMMARY WHERE JIS_RUNSHEET_NO = B.JIS_RUNSHEET_NO AND JIS_BOX_SN = B.JIS_BOX_SN FOR XML PATH('')),		
			USAGE=(SELECT  CONVERT(NVARCHAR,USAGE) + CHAR(10) FROM #Temp_JIS_BOX_SUMMARY WHERE JIS_RUNSHEET_NO = B.JIS_RUNSHEET_NO AND JIS_BOX_SN = B.JIS_BOX_SN FOR XML PATH(''))
		FROM #Temp_JIS_BOX_SUMMARY B
		GROUP BY JIS_RUNSHEET_NO, JIS_BOX_SN ) BB
	WHERE A.JIS_RUNSHEET_NO = BB.JIS_RUNSHEET_NO AND A.JIS_BOX_SN = BB.JIS_BOX_SN
	
	UPDATE #Temp_JIS_BOX_SUMMARY
	SET	LOC_PART_NO = BB.LOC_PART_NO,
		SUM_PART_NO = BB.SUM_PART_NO
	FROM #Temp_JIS_BOX_SUMMARY A,
		(
		SELECT JIS_RUNSHEET_NO, PART_NO, 
			LOC_PART_NO=(SELECT CONVERT(NVARCHAR,JIS_BOX_SN) + '  ' FROM #Temp_JIS_BOX_SUMMARY WHERE JIS_RUNSHEET_NO = B.JIS_RUNSHEET_NO AND PART_NO = B.PART_NO FOR XML PATH('')),
			SUM_PART_NO = SUM(USAGE)
		FROM #Temp_JIS_BOX_SUMMARY B
		GROUP BY JIS_RUNSHEET_NO, PART_NO ) BB
	WHERE A.JIS_RUNSHEET_NO = BB.JIS_RUNSHEET_NO AND A.PART_NO = BB.PART_NO
	
	UPDATE #Temp_JIS_BOX_SUMMARY
	SET	TOTAL_PART_NO = B.USAGE
	FROM #Temp_JIS_BOX_SUMMARY A,
	(
		SELECT JIS_RUNSHEET_NO, SUM(USAGE) AS USAGE
		FROM #Temp_JIS_BOX_SUMMARY
		GROUP BY JIS_RUNSHEET_NO
	) B
	WHERE A.JIS_RUNSHEET_NO = B.JIS_RUNSHEET_NO
	
	UPDATE #Temp_JIS_BOX_SUMMARY
	SET DETAIL_ROW_NUM = B.NUM
	FROM #Temp_JIS_BOX_SUMMARY A, (
	SELECT JIS_RUNSHEET_NO, COUNT(*) AS NUM
	FROM #Temp_JIS_BOX_SUMMARY
	GROUP BY JIS_RUNSHEET_NO ) B
	WHERE A.JIS_RUNSHEET_NO = B.JIS_RUNSHEET_NO
	
	UPDATE #Temp_JIS_BOX_SUMMARY
	SET TOTAL_ROW_NUM = C.NUM
	FROM #Temp_JIS_BOX_SUMMARY A, (SELECT JIS_RUNSHEET_NO, COUNT(*) AS NUM FROM (
	SELECT JIS_RUNSHEET_NO, PART_NO
	FROM #Temp_JIS_BOX_SUMMARY
	GROUP BY JIS_RUNSHEET_NO ,PART_NO) B GROUP BY B.JIS_RUNSHEET_NO) C
	WHERE A.JIS_RUNSHEET_NO = C.JIS_RUNSHEET_NO
	
	UPDATE	#Temp_JIS_BOX_SUMMARY
	SET		DETAIL_FONT_SIZE = B.FONT_SIZE
	FROM	#Temp_JIS_BOX_SUMMARY A, LES.TS_JIS_PRINT_CONFIG B
	WHERE	A.DETAIL_ROW_NUM BETWEEN B.START_ROW AND B.END_ROW
	
	UPDATE	#Temp_JIS_BOX_SUMMARY
	SET		TOTAL_FONT_SIZE = B.TOTAL_FONT_SIZE
	FROM	#Temp_JIS_BOX_SUMMARY A, LES.TS_JIS_PRINT_CONFIG B
	WHERE	A.TOTAL_ROW_NUM BETWEEN B.START_ROW AND B.END_ROW
		
	SELECT A.JIS_RUNSHEET_NO, A.JIS_BOX_SN,  A.PART_NO, A.PLANT, A.ASSEMBLY_LINE, A.RACK, A.RACK_CNAME, A.SUPPLIER_NUM, A.SUPPLIER_NAME,
		A.LOCATION,A.DOCK,A.USAGE, A.MODEL, A.MODEL_NO, A.KNR, A.RUNNING_NUMBER, A.START_RUNNING_NO, A.END_RUNNING_NO, 
		A.JIS_RUNSHEET_FLEX_TIME,A.EXPECTED_ARRIVAL_TIME,A.REQUEST_TIME,A.PRINT_TIME, A.PUBLISH_TIME, 
		SUBSTRING(A.CAT_PART_NO,1,LEN(A.CAT_PART_NO)-1) AS CAT_PART_NO, SUBSTRING(A.CAT_USAGE,1,LEN(A.CAT_USAGE)-1) AS CAT_USAGE, A.SUM_PART_NO, A.LOC_PART_NO, A.COMMENTS, A.TOTAL_PART_NO, A.PAGE_SIZE,
		A.DETAIL_ROW_NUM, A.TOTAL_ROW_NUM, DETAIL_FONT_SIZE, TOTAL_FONT_SIZE
			
	FROM #Temp_JIS_BOX_SUMMARY A
	ORDER BY A.JIS_RUNSHEET_NO, A.JIS_BOX_SN
	
 
END