
CREATE PROC [LES].[PROC_LargeScreen_Weld](@WMNo NVARCHAR(10),@WarningSecond int)
AS
BEGIN	
	SELECT RIGHT(OUTPUT_NO,7)  AS OUTPUT_NO,
			[ROUTE],[REQUEST_TIME],
			DATEDIFF(mi,GETDATE(),REQUEST_TIME) AS diff
		FROM LES.TT_WMM_OUTPUT
		WHERE CONFIRM_FLAG!=2 AND DATEDIFF(ss,GETDATE(),REQUEST_TIME)<=@WarningSecond
		and ZONE_NO in (@WMNo)
			AND CREATE_DATE>='2017-1-18'

END;


--EXEC LES.PROC_LargeScreen_Pull 2