
CREATE PROCEDURE [LES].[PROC_TWD_REPORT_GET]
(
	@TWD_RUNSHEET_SN_LIST NVARCHAR(MAX)
)

AS
BEGIN


SET NOCOUNT ON
DECLARE @TWD_RUNSHEET_SN NVARCHAR(100)
DECLARE @TWD_RUNSHEET_NO NVARCHAR(100)
DECLARE @TWD_COUNTS INT = 0 --总记录数
DECLARE @TWD_NEEDS INT = 0--需补充行数

CREATE TABLE LES.#TTT_TWD_RUNSHEET(
            [TWD_RUNSHEET_SN] nvarchar(100) null,[TWD_RUNSHEET_NO] nvarchar(100) null
           ,[PLANT] nvarchar(100) null,[ASSEMBLY_LINE] nvarchar(100) null
           ,DOCK nvarchar(100) null ,[SUPPLIER_NUM] nvarchar(100) null
           ,SUPPLIER_ADDRESS nvarchar(500) null ,CONTACT_NAME nvarchar(100) null
           ,CONTACT_TEL nvarchar(100) null ,NIGHTCONTACT_FAX nvarchar(100) null
           ,SEND_TIME datetime null ,[PART_NO] nvarchar(100) null
           ,[IDENTIFY_PART_NO] nvarchar(100) null,[PART_CNAME] nvarchar(100) null
           ,[PART_ENAME] nvarchar(100) null,[RDC_DLOC] nvarchar(100) null
           ,[INBOUND_PACKAGE] nvarchar(100) null,[PACK_COUNT] int
           ,[REQUIRED_INBOUND_PACKAGE] nvarchar(100) null,[REQUIRED_INBOUND_PACKAGE_QTY] nvarchar(100) null
           ,[ACTUAL_INBOUND_PACKAGE] nvarchar(100) null ,[ACTUAL_INBOUND_PACKAGE_QTY] nvarchar(100) null
           ,COMMENTS nvarchar(200) null)    
           
CREATE TABLE #Temp_TWD_RUNSHEET_SN
(
	TWD_RUNSHEET_SN	INT,
	TWD_RUNSHEET_NO NVARCHAR(30)
)
CREATE INDEX IX_#Temp_TWD_RUNSHEET_SN_1 ON #Temp_TWD_RUNSHEET_SN(TWD_RUNSHEET_SN)

DECLARE @SQLString NVARCHAR(MAX)

SET @SQLString=	' INSERT INTO #Temp_TWD_RUNSHEET_SN' + 
			    ' SELECT TWD_RUNSHEET_SN,TWD_RUNSHEET_NO FROM LES.TT_TWD_RUNSHEET WHERE TWD_RUNSHEET_SN IN (' + @TWD_RUNSHEET_SN_LIST + ')'
			
EXECUTE sp_executesql @SQLString


DECLARE TWD_Cursor CURSOR FOR SELECT TWD_RUNSHEET_SN,TWD_RUNSHEET_NO 
                              FROM #Temp_TWD_RUNSHEET_SN
           
OPEN TWD_Cursor 
FETCH NEXT FROM TWD_Cursor INTO @TWD_RUNSHEET_SN,@TWD_RUNSHEET_NO
WHILE @@FETCH_STATUS = 0
BEGIN
SELECT @TWD_COUNTS = COUNT(*) FROM LES.TT_TWD_RUNSHEET_DETAIL WHERE TWD_RUNSHEET_SN = @TWD_RUNSHEET_SN
IF(@TWD_COUNTS%15 <> 0)
BEGIN
	SET @TWD_NEEDS = (15 - @TWD_COUNTS%15);  --获取补充空白行数量
	 
END

INSERT INTO LES.#TTT_TWD_RUNSHEET
SELECT  R.[TWD_RUNSHEET_SN],R.[TWD_RUNSHEET_NO]
       ,R.[PLANT],R.[ASSEMBLY_LINE]
       ,R.DOCK,R.[SUPPLIER_NUM]
       ,SUPPLIER_ADDRESS,CONTACT_NAME
       ,CONTACT_TEL,NIGHTCONTACT_FAX
       ,PUBLISH_TIME,[PART_NO]
       ,[IDENTIFY_PART_NO],[PART_CNAME]
       ,[PART_ENAME],[RDC_DLOC]
       ,[INBOUND_PACKAGE],[PACK_COUNT]
       ,[REQUIRED_INBOUND_PACKAGE],[REQUIRED_INBOUND_PACKAGE_QTY]
       ,[ACTUAL_INBOUND_PACKAGE],[ACTUAL_INBOUND_PACKAGE_QTY]
       ,D.COMMENTS
FROM LES.TT_TWD_RUNSHEET AS R
LEFT JOIN LES.TM_BAS_SUPPLIER AS S ON R.SUPPLIER_NUM = S.SUPPLIER_NUM
LEFT JOIN  LES.TT_TWD_RUNSHEET_DETAIL AS D ON R.TWD_RUNSHEET_SN = D.TWD_RUNSHEET_SN  --WHERE R.TWD_RUNSHEET_SN = 7
WHERE R.TWD_RUNSHEET_SN = @TWD_RUNSHEET_SN

DECLARE @i INT = 0

WHILE(@i<@TWD_NEEDS)
BEGIN
	--补空行
	INSERT INTO LES.#TTT_TWD_RUNSHEET
	SELECT  @TWD_RUNSHEET_SN,@TWD_RUNSHEET_NO
           ,NULL,NULL
           ,NULL,NULL
           ,NULL,NULL
           ,NULL,NULL
           ,NULL,NULL
           ,NULL,NULL
           ,NULL,NULL
           ,NULL,NULL
           ,NULL,NULL
           ,NULL,NULL 
           ,NULL
   SET @i = @i + 1

END

FETCH NEXT FROM TWD_Cursor INTO  @TWD_RUNSHEET_SN,@TWD_RUNSHEET_NO
END

CLOSE TWD_Cursor
DEALLOCATE TWD_Cursor

--DROP TABLE LES.#TTT_TWD_RUNSHEET

SELECT * FROM LES.#TTT_TWD_RUNSHEET ORDER BY TWD_RUNSHEET_SN,PLANT desc

END