
-- =============================================
-- Author:		吕小望
-- Create date: 2011-10-13
-- Description:	TWD 生成条码
-- Modified Info: 
-- 添加履历号 added on  2014-09-18 by Caodaowei
-- =============================================
CREATE PROC [LES].[PROC_TWD_GENERATE_BARCODE_PACKAGEMODEL]
(
	@runsheetSN int
)
as
	SET NOCOUNT ON
	DECLARE DETAIL_CRSR CURSOR  FAST_FORWARD  FOR 
	SELECT SUPPLIER_NUM,PART_NO,IDENTIFY_PART_NO,PART_CNAME,BOX_PARTS
		,PICKUP_SEQ_NO,RDC_DLOC,MEASURING_UNIT_NO,INBOUND_PACKAGE_MODEL,REQUIRED_INBOUND_PACKAGE_QTY
		,REQUIRED_INBOUND_PACKAGE,[INBOUND_PACKAGE],[BOX_PARTS_SHEET]
	FROM LES.TT_TWD_RUNSHEET_DETAIL
	WHERE TWD_RUNSHEET_SN = @runsheetSN
		
	DECLARE @SUPPLIER_NUM NVARCHAR(12)
	DECLARE @PART_NO NVARCHAR(20)
	DECLARE @IDENTIFY_PART_NO NVARCHAR(20)
	DECLARE @PART_CNAME NVARCHAR(100)
	DECLARE @BOX_PARTS NVARCHAR(10)
	DECLARE @PICKUP_SEQ_NO INT
	DECLARE @RDC_DLOC VARCHAR(20)
	DECLARE @MEASURING_UNIT_NO NVARCHAR(1)
	DECLARE @INHOUSE_PACKAGE_MODEL NVARCHAR(30)
	DECLARE @REQUIRED_INBOUND_PACKAGE_QTY INT
	DECLARE @REQUIRED_INBOUND_PACKAGE INT
	DECLARE @BATCHNO NVARCHAR(30)
	DECLARE @INBOUND_PACKAGE INT
	DECLARE @DELIVERY_LOCATION NVARCHAR(12)
	DECLARE @ResumENO NVARCHAR(10)			--added on  2014-09-18 by Caodaowei
	DECLARE @Plant NVARCHAR(5)				--added on  2014-09-18 by Caodaowei
	DECLARE @AssemBLELINE NVARCHAR(10)		--added on  2014-09-18 by Caodaowei
	DECLARE @BOX_PARTS_SHEET NVARCHAR(10)
	DECLARE @RUNSHEET_DETAIL_ID INT
	DECLARE @BarCoDE_SUPPLIER_NUM NVARCHAR(12)
	
	SELECT @DELIVERY_LOCATION=[DELIVERY_LOCATION]
    FROM [LES].[TT_TWD_RUNSHEET] where TWD_RUNSHEET_SN = @runsheetSN

	SELECT @BATCHNO=CONVERT(VARCHAR(100), GETDATE(), 112)

	OPEN DETAIL_CRSR
	FETCH NEXT FROM DETAIL_CRSR
	INTO @SUPPLIER_NUM,@PART_NO,@IDENTIFY_PART_NO,@PART_CNAME,@BOX_PARTS,
		 @PICKUP_SEQ_NO,@RDC_DLOC,@MEASURING_UNIT_NO,@INHOUSE_PACKAGE_MODEL,@REQUIRED_INBOUND_PACKAGE_QTY,
		 @REQUIRED_INBOUND_PACKAGE,@INBOUND_PACKAGE,@BOX_PARTS_SHEET

	WHILE( @@FETCH_STATUS = 0 )
	BEGIN

		SELECT TOP 1 @plant=PLANT,@AssembleLine=ASSEMBLY_LINE FROM LES.TT_TWD_RUNSHEET WHERE TWD_RUNSHEET_SN=@runsheetSN

		IF (LEN(ISNULL(@BOX_PARTS_SHEET,''))>0)
		BEGIN
			SELECT @BARCODE_SUPPLIER_NUM=[SUPPLIER_NUM] FROM LES.TM_TWD_BOX_PARTS WHERE PLANT=@PLANT AND [BOX_PARTS]=@BOX_PARTS_SHEET
		END
		WHILE( @REQUIRED_INBOUND_PACKAGE >0)
		BEGIN
			DECLARE @BARCODENO NVARCHAR(32)
			DECLARE @CreatedOn DATETIME
			EXEC LES.[PROC_TWD_GET_NEXT_BARCODE_SEQUENCE] 'BARCODE', @barCodeNo OUTPUT
			--START ADD
			SET @CreatedOn = GETDATE()
			SET @RESUMENO=''
			
			SELECT TOP 1 @ResumeNo=RESUMENO FROM LES.TM_TWD_PART_RESUME
			WHERE PLANT=@Plant and PART_NO=@PART_NO 
				--AND START_EFFECTIVE_DATE<=@CreatedOn AND EXPIRE_DATE>=@CreatedOn AND ASSEMBLY_LINE=@AssembleLine
			--End Add  on 2014-09-18 by Caodaowei
			INSERT INTO [LES].[TT_TWD_RUNSHEET_BARCODE]
			   ([TWD_RUNSHEET_SN]
			   ,[SUPPLIER_NUM]
			   ,[PART_NO]
			   ,[BARCODE_DATA]
			   ,[IDENTIFY_PART_NO]
			   ,[PART_CNAME]
			   ,[BOX_PARTS]
			   ,[PICKUP_SEQ_NO]
			   ,[RDC_DLOC]
			   ,[MEASURING_UNIT_NO]
			   ,[INHOUSE_PACKAGE_MODEL]
			   ,[REQUIRED_INBOUND_PACKAGE_QTY]
			   ,[COMMENTS],[BARCODE_TYPE],BATTH_NO,[CREATE_DATE],[STORAGE_LOCATION])
			VALUES(@runsheetSN,isnull(@BarCode_SUPPLIER_NUM,@SUPPLIER_NUM),@PART_NO,@barCodeNo,@IDENTIFY_PART_NO,@PART_CNAME,isnull(@BOX_PARTS_SHEET,@BOX_PARTS),@PICKUP_SEQ_NO,@RDC_DLOC,@MEASURING_UNIT_NO
				,@INHOUSE_PACKAGE_MODEL,@INBOUND_PACKAGE,@ResumeNo,'TWD',@BATCHNO,@CreatedOn,@DELIVERY_LOCATION)

			SET @REQUIRED_INBOUND_PACKAGE = @REQUIRED_INBOUND_PACKAGE -1
		END

		FETCH NEXT FROM DETAIL_CRSR
		INTO @SUPPLIER_NUM,@PART_NO,@IDENTIFY_PART_NO,@PART_CNAME,@BOX_PARTS,
			 @PICKUP_SEQ_NO,@RDC_DLOC,@MEASURING_UNIT_NO,@INHOUSE_PACKAGE_MODEL,@REQUIRED_INBOUND_PACKAGE_QTY,
			 @REQUIRED_INBOUND_PACKAGE,@INBOUND_PACKAGE,@BOX_PARTS_SHEET		
	END

	CLOSE DETAIL_CRSR
	DEALLOCATE DETAIL_CRSR
	SET NOCOUNT OFF