


/********************************************************************/
/*                                                                  */
/*   Project Name:  LES System                         */
/*   Program Name:  [PROC_TT_WMM_OUTPUT_CREATE_UPDATE]             */
/*   Called By:     by the Page							*/
/*   Purpose:       This is the main stored procedure for the       */
/*   author:       andy	2015-06-09     				       */
/********************************************************************/
CREATE PROCEDURE [LES].[PROC_WMM_OUTPUT_CREATE_UPDATE]
 
AS

BEGIN

INSERT INTO [LES].[TT_WMM_OUTPUT]
	(
	[OUTPUT_NO]
	,[OUTPUT_TYPE]
	,[PLANT]
	,[WM_NO]
	,[ZONE_NO]
	,[PLANT_ZONE]
	,[SUPPLIER_NUM]
	,[SEND_TIME]
	,[CONFIRM_FLAG]
	,[COMMENTS]
	,[CREATE_USER]
	,[CREATE_DATE]
	,[UPDATE_USER]
	,[UPDATE_DATE]
	)
	SELECT distinct 
		[OUTPUT_NO]
        ,[OUTPUT_TYPE]
        ,[PLANT]
        ,[WM_NO]
        ,[ZONE_NO]
		,[PLANT_ZONE]
        ,[SUPPLIER_NUM]
        ,[SEND_TIME]
		,0
		,TE.[COMMENTS]
        ,TE.[CREATE_USER]
        ,TE.[CREATE_DATE]
        ,TE.[UPDATE_USER]
        ,TE.[UPDATE_DATE]
	FROM 
		[LES].[TE_WMM_OUTPUT_TEMP] TE
	WHERE 
		TE.VALID_FLAG = 1
		AND TE.OUTPUT_NO NOT IN (SELECT [OUTPUT_NO] FROM [LES].[TT_WMM_OUTPUT])

UPDATE 
	[LES].[TT_WMM_OUTPUT] 
SET
    [OUTPUT_NO] = TE.[OUTPUT_NO]
    ,[OUTPUT_TYPE] = TE.[OUTPUT_TYPE]
    ,[PLANT] = TE.[PLANT]
    ,[WM_NO] = TE.[WM_NO]
    ,[ZONE_NO] = TE.[ZONE_NO]
    ,[PLANT_ZONE] = TE.[PLANT_ZONE]
    ,[SUPPLIER_NUM] = TE.[SUPPLIER_NUM]
    ,[SEND_TIME] = TE.[SEND_TIME]
	,[COMMENTS]=TE.[COMMENTS]
    ,[UPDATE_USER] = TE.[CREATE_USER]
    ,[UPDATE_DATE] = TE.[CREATE_DATE]
FROM 
	[LES].[TE_WMM_OUTPUT_TEMP] TE,
	[LES].[TT_WMM_OUTPUT] TT
WHERE 
	TE.VALID_FLAG = 1 
	AND TE.OUTPUT_NO = TT.OUTPUT_NO 
	AND (TT.CONFIRM_FLAG = 0 OR TT.CONFIRM_FLAG IS NULL)

INSERT INTO [LES].[TT_WMM_OUTPUT_DETAIL]
	(
	[OUTPUT_ID]
	,[TRAN_NO]
	,[PLANT]
	,[WM_NO]
	,[ZONE_NO]
	,[DLOC]
	,[TARGET_WM]
	,[TARGET_ZONE]
	,[TARGET_DLOC]
	,[PART_NO]
	,[PART_CNAME]
	,[PACK_COUNT]
	,[REQUIRED_BOX_NUM]
	,[REQUIRED_QTY]
	,ACTUAL_BOX_NUM
	,ACTUAL_QTY
	,[SUPPLIER_NUM]
	,[PACKAGE_MODEL]
	,[PACKAGE]
	,[CREATE_USER]
	,[CREATE_DATE]
	,[UPDATE_USER]
	,[UPDATE_DATE]
	)
	SELECT 
		TT.[OUTPUT_ID]
		,TT.[OUTPUT_NO]
	    ,TT.[PLANT]
		,TT.[WM_NO]
		,TT.[ZONE_NO]
		,TM.[DLOC]
		,TM_TARGET.[WM_NO]
		,TM_TARGET.[ZONE_NO]
		,TM_TARGET.[DLOC]
        ,TE.[PART_NO]
        ,TM.[PART_CNAME]
		,TM.PACKAGE
        ,TE.[REQUIRED_BOX_NUM]
        ,TE.[REQUIRED_QTY]
		,TE.REQUIRED_BOX_NUM
		,TE.REQUIRED_QTY
        ,TE.[SUPPLIER_NUM]
        ,TM.[PACKAGE_MODEL]
		,TM.PACKAGE
        ,TE.[CREATE_USER]
        ,TE.[CREATE_DATE]
        ,TE.[UPDATE_USER]
        ,TE.[UPDATE_DATE]
	FROM 
		[LES].[TE_WMM_OUTPUT_TEMP] TE 
		JOIN [LES].[TT_WMM_OUTPUT] TT ON TE.VALID_FLAG = 1 AND (TT.CONFIRM_FLAG = 0 OR TT.CONFIRM_FLAG IS NULL) AND TE.OUTPUT_NO = TT.OUTPUT_NO 
		JOIN (SELECT t1.PART_NO, t1.PART_CNAME, t1.PACKAGE_MODEL,t1.PACKAGE,t1.[DLOC], t1.PLANT, t1.WM_NO, t1.ZONE_NO FROM [LES].[TM_BAS_PARTS_STOCK] t1) TM ON TE.PART_NO = TM.PART_NO AND TE.PLANT=TM.PLANT AND TE.WM_NO = TM.WM_NO AND TE.ZONE_NO = TM.ZONE_NO
		JOIN [LES].[TM_WMM_ZONES] Z ON Z.ZONE_NO=TE.PLANT_ZONE
		JOIN [LES].[TM_BAS_PARTS_STOCK] TM_TARGET ON TM_TARGET.PART_NO = TE.PART_NO AND TM_TARGET.PLANT=Z.PLANT AND TM_TARGET.WM_NO = Z.WM_NO AND TM_TARGET.ZONE_NO = TE.PLANT_ZONE
	WHERE 
		(SELECT Count(*) FROM [LES].[TT_WMM_OUTPUT_DETAIL] t where t.OUTPUT_ID = TT.OUTPUT_ID and t.PART_NO = TE.PART_NO) = 0

UPDATE 
	[LES].[TT_WMM_OUTPUT_DETAIL]
SET
    [OUTPUT_ID] = TT.[OUTPUT_ID]
	,[TRAN_NO] = TT.[OUTPUT_NO]
	,[PLANT] = TT.[PLANT]
	,[WM_NO] = TT.[WM_NO]
	,[ZONE_NO] = TT.[ZONE_NO]
	,[DLOC]=TM.[DLOC]
	,[TARGET_WM]=TM_TARGET.[WM_NO]
	,[TARGET_ZONE]=TM_TARGET.[ZONE_NO]
	,[TARGET_DLOC]=TM_TARGET.[DLOC]
    ,[PART_NO] = TE.[PART_NO]
    ,[PART_CNAME] = TM.[PART_CNAME]
	,[PACK_COUNT] = TM.PACKAGE
    ,[REQUIRED_BOX_NUM] = TE.[REQUIRED_BOX_NUM]
    ,[REQUIRED_QTY] = TE.[REQUIRED_QTY]
	,ACTUAL_BOX_NUM = TE.ACTUAL_BOX_NUM
	,ACTUAL_QTY = TE.ACTUAL_QTY
    ,[SUPPLIER_NUM] = TE.[SUPPLIER_NUM]
    ,[PACKAGE_MODEL] = TM.[PACKAGE_MODEL]
	,[PACKAGE]=TM.PACKAGE
    ,[UPDATE_USER] = TE.[CREATE_USER]
    ,[UPDATE_DATE] =TE.[CREATE_DATE]
FROM 
	[LES].[TE_WMM_OUTPUT_TEMP] TE 
	JOIN [LES].[TT_WMM_OUTPUT] TT ON TE.VALID_FLAG = 1 AND (TT.CONFIRM_FLAG = 0 OR TT.CONFIRM_FLAG IS NULL) AND TE.OUTPUT_NO = TT.OUTPUT_NO
	JOIN [LES].[TT_WMM_OUTPUT_DETAIL] DE ON TT.OUTPUT_ID = DE.OUTPUT_ID AND TE.PART_NO = DE.PART_NO
	JOIN (SELECT t1.PART_NO, t1.PART_CNAME, t1.PACKAGE_MODEL,t1.PACKAGE,t1.[DLOC], t1.PLANT, t1.WM_NO, t1.ZONE_NO FROM [LES].[TM_BAS_PARTS_STOCK] t1) TM ON TE.PART_NO = TM.PART_NO AND TE.PLANT=TM.PLANT AND TE.WM_NO = TM.WM_NO AND TE.ZONE_NO = TM.ZONE_NO
	JOIN [LES].[TM_WMM_ZONES] Z ON Z.ZONE_NO=TE.PLANT_ZONE
	JOIN [LES].[TM_BAS_PARTS_STOCK] TM_TARGET ON TM_TARGET.PART_NO = TE.PART_NO AND TM_TARGET.PLANT=Z.PLANT AND TM_TARGET.WM_NO = Z.WM_NO AND TM_TARGET.ZONE_NO = TE.PLANT_ZONE
	

DELETE FROM 
	[LES].[TT_WMM_OUTPUT_DETAIL] 
WHERE 
	OUTPUT_DETAIL_ID IN (
		Select 
			T2.OUTPUT_DETAIL_ID 
		from
			(
				SELECT 
					TT.OUTPUT_ID, TE.PART_NO,TT.OUTPUT_NO 
				FROM
					[LES].[TT_WMM_OUTPUT] TT JOIN [LES].[TE_WMM_OUTPUT_TEMP] TE 
				ON 
					TE.VALID_FLAG = 1 
					AND TE.OUTPUT_NO = TT.OUTPUT_NO
					AND (TT.CONFIRM_FLAG = 0 OR TT.CONFIRM_FLAG IS NULL)
			) T1
			RIGHT JOIN
			(
				SELECT 
					TT.OUTPUT_ID, DE.PART_NO, DE.OUTPUT_DETAIL_ID, TT.OUTPUT_NO 
				FROM 
					[LES].[TT_WMM_OUTPUT_DETAIL] DE,
					[LES].[TT_WMM_OUTPUT] TT,
					[LES].[TE_WMM_OUTPUT_TEMP] TE 
				WHERE 
					TT.OUTPUT_ID = DE.OUTPUT_ID
					AND TE.OUTPUT_NO = TT.OUTPUT_NO
					AND (TT.CONFIRM_FLAG = 0 OR TT.CONFIRM_FLAG IS NULL)
			) T2
			ON 
				T1.OUTPUT_ID = T2.OUTPUT_ID
				AND T1.PART_NO = T2.PART_NO
		WHERE 
			T1.PART_NO IS NULL
	)
END