CREATE PROC [LES].[PROC_LargeScreen_Punch](@WMNo NVARCHAR(10),@WarningSecond int)
AS
BEGIN	
	SELECT RIGHT(TM.OUTPUT_NO,7)  AS OUTPUT_NO,
	TM.[ROUTE],
	TM.[REQUEST_TIME],
	TM.[TRAN_TIME],
	TE.PART_NO,
	TE.PART_NO AS PART_CNAME, --LEFT(te.PART_CNAME,6) AS PART_CNAME PART_CNAME
	--TE.BOX_NUM,	--liutao 修改,大屏应该现实需求箱数
	TE.REQUIRED_BOX_NUM AS BOX_NUM,
	DATEDIFF(mi,TM.[TRAN_TIME],TM.[REQUEST_TIME]) AS DIFF 
	FROM LES.TT_WMM_OUTPUT TM
	INNER JOIN LES.TT_WMM_OUTPUT_DETAIL TE ON TE.OUTPUT_ID = TM.OUTPUT_ID
	--WHERE TM.CONFIRM_FLAG!=2 --wangyanping 要求更改为CONFIRM_FLAG=1
	WHERE TM.CONFIRM_FLAG=1 
	AND tm.ZONE_NO=@WMNo --liutao update,config文件配置为仓库存储区
	--AND DATEDIFF(mi,TM.[TRAN_TIME],TM.[REQUEST_TIME])<=@WarningSecond
	AND tm.CREATE_DATE>='2016-11-21'
	Order by TM.OUTPUT_ID
END;