

CREATE PROCEDURE [LES].[PROC_WMM_NOTIFICATION_DETAIL_IMPORT]
 
AS

BEGIN

DELETE FROM [LES].[TT_WMM_NOTIFICATION_DETAIL] 
WHERE TRAN_ID IN
(SELECT DISTINCT TRAN_ID FROM [LES].[TT_WMM_NOTIFICATION_DETAIL](NOLOCK) TD
left join LES.TT_WMM_NOTIFICATION_HEAD (NOLOCK) TM ON TM.NOTIFICATION_ID = TD.NOTIFICATIONID
left JOIN LES.TE_WMM_NOTIFICATION_DETAIL_TEMP (NOLOCK) T ON T.NOTIFICATION_NO = TM.NOTIFICATION_NO
 WHERE T.PART_NO = TD.PART_NO AND TM.CONFIRM_FLAG = 0)

INSERT INTO [LES].[TT_WMM_NOTIFICATION_DETAIL]
	(
	[NOTIFICATIONID]
	,[PLANT]
	,[WM_NO]
	,[ZONE_NO]
	,DLOC
	,[PART_NO]
	,[PART_CNAME]
	,PART_TYPE
	,[PACK_NUM]
    ,NUM
	,COMMENTS		
	,[CREATE_USER]
	,[CREATE_DATE]
	)
	SELECT 
		TT.[NOTIFICATION_ID]
	    ,TT.[PLANT]
		,TT.[WM_NO]
		,TT.[ZONE_NO]
		,ST.DLOC
        ,TE.[PART_NO]
        ,TM.[PART_CNAME]
		,TM.PART_CLS
        ,TE.[PACK_NUM]
        ,TE.NUM		
		,TE.COMMENTS
        ,TE.[CREATE_USER]
        ,TE.[CREATE_DATE]
	FROM 
		[LES].[TE_WMM_NOTIFICATION_DETAIL_TEMP] TE (NOLOCK) 
		JOIN [LES].[TT_WMM_NOTIFICATION_HEAD] TT (NOLOCK)  ON TE.NOTIFICATION_NO = TT.NOTIFICATION_NO
		JOIN [LES].[TM_BAS_MAINTAIN_PARTS] TM  (NOLOCK)  ON TE.PART_NO = TM.PART_NO
		LEFT JOIN [LES].[TM_BAS_PARTS_STOCK] (NOLOCK)  ST ON TT.PLANT = ST.PLANT AND TT.WM_NO = ST.WM_NO AND TT.ZONE_NO = ST.ZONE_NO AND TE.PART_NO = ST.PART_NO

END