CREATE PROCEDURE [LES].[PROC_WMM_CREATERECEIVE]
(
	@PLAN_RUNSHEET_SN INT
)
AS
BEGIN
	DECLARE @WM_NO NVARCHAR(10)
	DECLARE @ZONE_NO NVARCHAR(32)
	DECLARE @identity INT
	DECLARE @SUPPLIER_NUM NVARCHAR(12)

	SELECT TOP 1 @WM_NO = WM_NO, @ZONE_NO = ZONE_NO,@SUPPLIER_NUM = SUPPLIER_NUM FROM [LES].[TT_SPM_DELIVERY_RUNSHEET_DETAIL] WITH (NOLOCK) WHERE [PLAN_RUNSHEET_SN] = @PLAN_RUNSHEET_SN

	INSERT INTO [LES].[TT_WMM_RECEIVE]
	(
		[RECEIVE_NO],
		[PLANT],
		[SUPPLIER_NUM],
		[WM_NO],
		[ZONE_NO],
		[DELIVERY_LOCATION_NO],
		[DOCK],
		[SEND_TIME],
		[RECEIVE_TYPE],
		[TRAN_TIME],
		[RECEIVE_REASON],
		[CONFIRM_FLAG],
		[TRANS_SUPPLIER_NUM],
		[PLAN_NO],
		[ASN_NO],
		[RUNSHEET_NO],
		[ASSEMBLY_LINE],
		[PLANT_ZONE],
		[WORKSHOP],
		[SUPPLIER_TYPE],
		[ERP_FLAG],
		[RUNSHEET_CODE],
		[DELIVERY_LOCATION_NAME],
		[COMMENTS],
		[CREATE_USER],
		[CREATE_DATE]
	)
	SELECT
		[PLAN_RUNSHEET_NO],
		[PLANT],
		[SUPPLIER_NUM],
		@WM_NO,
		@ZONE_NO,
		[DELIVERY_LOCATION_NO],
		[DOCK],
		[SEND_TIME],
		1,
		NULL,
		'RECEIVE_REASON',
		1,
		[TRANS_SUPPLIER_NUM],
		[PLAN_NO],
		[ASN_NO],
		[PLAN_RUNSHEET_NO],
		[ASSEMBLY_LINE],
		[PLANT_ZONE],
		[WORKSHOP],
		1,
		0,
		'JHD',
		[DELIVERY_LOCATION_NAME],
		[COMMENTS],
		'admin',
		GETDATE()
	FROM [LES].[TT_SPM_DELIVERY_RUNSHEET] WITH (NOLOCK)
	WHERE [PLAN_RUNSHEET_SN] = @PLAN_RUNSHEET_SN

	SELECT @identity = SCOPE_IDENTITY()

	--子表
	INSERT INTO [LES].[TT_WMM_RECEIVE_DETAIL]
	(
		[RECEIVE_ID],
		[PLANT],
		[SUPPLIER_NUM],
		[WM_NO],
		[ZONE_NO],
		[DLOC],
		[TARGET_WM],
		[TARGET_ZONE],
		[TARGET_DLOC],
		[MEASURING_UNIT_NO],
		[PACKAGE],
		[NUM],
		[BOX_NUM],
		[PART_NO],
		[PART_CNAME],
		[PART_TYPE],
		[REQUIRED_BOX_NUM],
		[REQUIRED_QTY],
		[ACTUAL_BOX_NUM],
		[ACTUAL_QTY],
		[PACKAGE_MODEL],
		[BARCODE_DATA],
		[TRAN_NO],
		[IDENTIFY_PART_NO],
		[PART_ENAME],
		[DOCK],
		[ASSEMBLY_LINE],
		[BOX_PARTS],
		[SEQUENCE_NO],
		[PICKUP_SEQ_NO],
		[RDC_DLOC],
		[INHOUSE_PACKAGE],
		[INBOUND_PACKAGE_MODEL],
		[PACK_COUNT],
		[TWD_RUNSHEET_NO],
		[SUPPLIER_NUM_SHEET],
		[BOX_PARTS_SHEET],
		[RETURN_REPORT_FLAG],
		[ORDER_NO],
		[ITEM_NO],
		[COMMENTS],
		[CREATE_USER],
		[CREATE_DATE]
	)
	SELECT
		@identity,
		[PLANT],
		[SUPPLIER_NUM],
		[WM_NO],
		[ZONE_NO],
		[DLOC],
		[WM_NO],
		[ZONE_NO],
		[DLOC],
		[MEASURING_UNIT_NO],
		[INHOUSE_PACKAGE],
		[REQUIRED_INHOUSE_PACKAGE],
		[REQUIRED_INHOUSE_PACKAGE_QTY],
		[PART_NO],
		[PART_CNAME],
		NULL,
		[REQUIRED_INHOUSE_PACKAGE_QTY],
		[REQUIRED_INHOUSE_PACKAGE],
		NULL,
		NULL,
		[INHOUSE_PACKAGE_MODEL],
		[BARCODE_DATA],
		NULL,
		NULL, 
		[PART_ENAME],
		[DOCK],
		NULL,
		[BOX_PARTS],
		NULL,
		[PICKUP_SEQ_NO],
		[RDC_DLOC],
		[INHOUSE_PACKAGE],
		[INHOUSE_PACKAGE_MODEL],
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		[ORDER_NO],
		[ITEM_NO],
		[COMMENTS],
		'admin',
		GETDATE()
	FROM [LES].[TT_SPM_DELIVERY_RUNSHEET_DETAIL] WITH (NOLOCK)
	WHERE [PLAN_RUNSHEET_SN] = @PLAN_RUNSHEET_SN

END