--SAP接口_APO_整车订单BOM明细表
CREATE PROCEDURE LES.PROC_INTERFACE_SAP_LES_APOORDERPART
AS
BEGIN
	BEGIN TRY
		BEGIN TRANSACTION
		--根据主表删除明细
		DELETE FROM LES.TT_BAS_ORDER_PART_RESULTS WHERE
		ORDER_NO IN( SELECT ZORDNO FROM LES.TI_ODS_ORDER_BOM_IN WHERE ZORDNO IN
		(SELECT ZORDNO FROM LES.TI_ODS_ORDERS_IN))
		--新增
		INSERT INTO LES.TT_BAS_ORDER_PART_RESULTS
		(ORDER_NO,PLANT,PART_NO,VIN,MBOM_ITEMID,QUANTITY,LOCATION,MEASURING_UNIT_NO,KNR)
		SELECT ZORDNO,ZKWERK,ZCOMNO,ZVIN,ZBOMID,ZQTY,ZLOC,ZMEINS,'' FROM LES.TI_ODS_ORDER_BOM_IN
		WHERE ZORDNO IN (SELECT ZORDNO FROM LES.TI_ODS_ORDERS_IN)
		COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		--出错，则返回执行不成功，回滚事务
	ROLLBACK TRANSACTION
--记录错误信息
	INSERT INTO [LES].[TS_SYS_EXCEPTION] (time_stamp, [application], [METHOD], class,  exception_message, error_code)
	SELECT getdate(),'INTERFACE','PROC_INTERFACE_SAP_LES_APOORDERPART','Procedure',error_message(),ERROR_LINE()

	END CATCH
END