
/********************************************************************/
/*                                                                  */
/*   Project Name:  Production Pull System                          */
/*   Program Name:  PROC_BAS_GET_INBOUND_DIFFERENCE                      */
/*   Called By:     by the Page							*/
/*   Purpose:       This is the main stored procedure for the       */
/*   author:       wangchanghong	2011-06-20   				       */
/********************************************************************/
CREATE PROCEDURE [LES].[PROC_BAS_GET_INBOUND_DIFFERENCE]

AS

BEGIN

--step 1 删除临时表中所有数据
TRUNCATE TABLE [LES].TE_BAS_INBOUND_LOGISTIC_STANDARD_DIFF

--TYPE 1:新增 2:修改 3：删除 

-- 新增1
INSERT INTO [LES].[TE_BAS_INBOUND_LOGISTIC_STANDARD_DIFF]
           ([PLANT],[ASSEMBLY_LINE],[PLANT_ZONE],[WORKSHOP]
           ,[SUPPLIER_NUM],[TRANS_SUPPLIER_NUM],[MODEL],[PART_NO]
           ,[COLOR_DEPARTMENT],[HAND_KEPT_RECORD],[COLOR_CONTROL_PATCH],[VWS],HAND_KEP_VWS
           ,[MODEL_YEAR],[PART_CNAME],[PART_ENAME],[INBOUND_MODE]
           ,[INBOUND_LOGISTIC_MODE],[INBOUND_SYSTEM_MODE],[START_EFFECTIVE_DATE],[INBOUND_PART_CLASS]
           ,[DOCK],[INBOUND_PACKAGE_MODEL],[INBOUND_PACKAGE],[LOAD_FLAG]
           ,[ZP_FLAG],[REQUIREMENT_FLAG],[ASSEMBLY_FLAG],[ASSEMBLY_FLAG_RECRUIT]
           ,[MARK],[PURCHASE_STYLE],[DELETE_FLAG],[PLATFORM_CHANGE_DATE]
           ,[IS_SPLIT],[LOGICAL_PK],[DIFF_FLAG],[CONFIRM_FLAG]
           ,[COMMENTS],[UPDATE_DATE],[UPDATE_USER],[CREATE_DATE]
           ,[CREATE_USER])
SELECT TI.[PLANT],TI.[ASSEMBLY_LINE],TI.[PLANT_ZONE],TI.[WORKSHOP]
      ,TI.[SUPPLIER_NUM],TI.[TRANS_SUPPLIER_NUM],TI.[MODEL],TI.[PART_NO]
      ,TI.[COLOR_DEPARTMENT],TI.[HAND_KEPT_RECORD],TI.[COLOR_CONTROL_PATCH],TI.[VWS],TI.HAND_KEP_VWS
      ,TI.[MODEL_YEAR],TI.[PART_CNAME],TI.[PART_ENAME],TI.[INBOUND_MODE]
      ,TI.[INBOUND_LOGISTIC_MODE],TI.[INBOUND_SYSTEM_MODE],TI.[START_EFFECTIVE_DATE],TI.[INBOUND_PART_CLASS]
      ,TI.[DOCK],TI.[INBOUND_PACKAGE_MODEL],TI.[INBOUND_PACKAGE],TI.[LOAD_FLAG]
      ,TI.[ZP_FLAG],TI.[REQUIREMENT_FLAG],TI.[ASSEMBLY_FLAG],TI.[ASSEMBLY_FLAG_RECRUIT]
      ,TI.[MARK],TI.[PURCHASE_STYLE],TI.[DELETE_FLAG],TI.[PLATFORM_CHANGE_DATE]
      ,TI.[IS_SPLIT],TI.[LOGICAL_PK],1,0
      ,TI.[COMMENTS],TI.[UPDATE_DATE],TI.[UPDATE_USER],TI.[CREATE_DATE]
      ,TI.[CREATE_USER]
 FROM [LES].[TI_BAS_INBOUND_LOGISTIC_STANDARD] AS TI
LEFT JOIN  LES.TM_BAS_MAINTAIN_INBOUND_LOGISTIC_STANDARD AS TM ON TI.LOGICAL_PK = TM.LOGICAL_PK
WHERE   TM.LOGICAL_PK IS NULL

-- 修改2



INSERT INTO [LES].[TE_BAS_INBOUND_LOGISTIC_STANDARD_DIFF]
           ([PLANT],[ASSEMBLY_LINE],[PLANT_ZONE],[WORKSHOP]
           ,[SUPPLIER_NUM],[TRANS_SUPPLIER_NUM],[MODEL],[PART_NO]
           ,[COLOR_DEPARTMENT],[HAND_KEPT_RECORD],[COLOR_CONTROL_PATCH],[VWS],HAND_KEP_VWS
           ,[MODEL_YEAR],[PART_CNAME],[PART_ENAME],[INBOUND_MODE]
           ,[INBOUND_LOGISTIC_MODE],[INBOUND_SYSTEM_MODE],[START_EFFECTIVE_DATE],[INBOUND_PART_CLASS]
           ,[DOCK],[INBOUND_PACKAGE_MODEL],[INBOUND_PACKAGE],[LOAD_FLAG]
           ,[ZP_FLAG],[REQUIREMENT_FLAG],[ASSEMBLY_FLAG],[ASSEMBLY_FLAG_RECRUIT]
           ,[MARK],[PURCHASE_STYLE],[DELETE_FLAG],[PLATFORM_CHANGE_DATE]
           ,[IS_SPLIT],[LOGICAL_PK],[DIFF_FLAG],[CONFIRM_FLAG]
           ,[COMMENTS],[UPDATE_DATE],[UPDATE_USER],[CREATE_DATE]
           ,[CREATE_USER])
           
SELECT TI.[PLANT],TI.[ASSEMBLY_LINE],TI.[PLANT_ZONE],TI.[WORKSHOP]
      ,TI.[SUPPLIER_NUM],TI.[TRANS_SUPPLIER_NUM],TI.[MODEL],TI.[PART_NO]
      ,TI.[COLOR_DEPARTMENT],TI.[HAND_KEPT_RECORD],TI.[COLOR_CONTROL_PATCH],TI.[VWS],TI.HAND_KEP_VWS
      ,TI.[MODEL_YEAR],TI.[PART_CNAME],TI.[PART_ENAME],TI.[INBOUND_MODE]
      ,TI.[INBOUND_LOGISTIC_MODE],TI.[INBOUND_SYSTEM_MODE],TI.[START_EFFECTIVE_DATE],TI.[INBOUND_PART_CLASS]
      ,TI.[DOCK],TI.[INBOUND_PACKAGE_MODEL],TI.[INBOUND_PACKAGE],TI.[LOAD_FLAG]
      ,TI.[ZP_FLAG],TI.[REQUIREMENT_FLAG],TI.[ASSEMBLY_FLAG],TI.[ASSEMBLY_FLAG_RECRUIT]
      ,TI.[MARK],TI.[PURCHASE_STYLE],TI.[DELETE_FLAG],TI.[PLATFORM_CHANGE_DATE]
      ,TI.[IS_SPLIT],TI.[LOGICAL_PK],2,0
      ,TI.[COMMENTS],TI.[UPDATE_DATE],TI.[UPDATE_USER],TI.[CREATE_DATE]
      ,TI.[CREATE_USER]
 FROM [LES].[TI_BAS_INBOUND_LOGISTIC_STANDARD] AS TI
INNER JOIN  LES.TM_BAS_MAINTAIN_INBOUND_LOGISTIC_STANDARD AS TM ON TI.LOGICAL_PK = TM.LOGICAL_PK
WHERE 
     ( ISNULL(TI.[PLANT],'') <> ISNULL(TM.[PLANT],'')
      OR ISNULL(TI.[ASSEMBLY_LINE],'') <> ISNULL(TM.[ASSEMBLY_LINE],'')
      OR ISNULL(TI.[PLANT_ZONE],'') <> ISNULL(TM.[PLANT_ZONE],'')
      OR ISNULL(TI.[WORKSHOP],'') <> ISNULL(TM.[WORKSHOP],'')
      OR ISNULL(TI.[SUPPLIER_NUM],'')<> ISNULL(TM.[SUPPLIER_NUM],'')
      OR ISNULL(TI.[TRANS_SUPPLIER_NUM],'')<> ISNULL(TM.[TRANS_SUPPLIER_NUM],'')
      OR ISNULL(TI.[MODEL],'') <> ISNULL(TM.[MODEL],'')
      OR ISNULL(TI.[COLOR_DEPARTMENT],'')<> ISNULL(TM.[COLOR_DEPARTMENT],'')
      OR ISNULL(TI.[HAND_KEPT_RECORD],'')<> ISNULL(TM.[HAND_KEPT_RECORD],'')
      OR ISNULL(TI.[COLOR_CONTROL_PATCH],'') <> ISNULL(TM.[COLOR_CONTROL_PATCH],'')
      OR ISNULL(TI.[VWS],'')<> ISNULL(TM.[VWS],'')
      OR ISNULL(TI.HAND_KEP_VWS,'') <> ISNULL(TM.HAND_KEP_VWS,'')
      OR ISNULL(TI.[MODEL_YEAR],'')<>ISNULL( TM.[MODEL_YEAR],'')
      OR ISNULL(TI.[PART_CNAME],'')<>ISNULL( TM.[PART_CNAME],'')
      OR ISNULL(TI.[PART_ENAME],'')<> ISNULL(TM.[PART_ENAME],'')
      OR ISNULL(TI.[INBOUND_MODE],'')<> ISNULL(TM.[INBOUND_MODE],'')
      OR ISNULL(TI.[INBOUND_LOGISTIC_MODE],'')<> ISNULL(TM.[INBOUND_LOGISTIC_MODE],'')
      OR ISNULL(TI.[INBOUND_SYSTEM_MODE],'')<> ISNULL(TM.[INBOUND_SYSTEM_MODE],'')
      OR ISNULL(TI.[START_EFFECTIVE_DATE],'')<>ISNULL(TM.[START_EFFECTIVE_DATE],'')
      OR ISNULL(TI.[INBOUND_PART_CLASS],'')<>ISNULL(TM.[INBOUND_PART_CLASS],'')
      OR ISNULL(TI.[DOCK],'')<> ISNULL(TM.[DOCK],'')
      OR ISNULL(TI.[INBOUND_PACKAGE_MODEL],'')<> ISNULL(TM.[INBOUND_PACKAGE_MODEL],'')
      OR ISNULL(TI.[INBOUND_PACKAGE],'')<> ISNULL(TM.[INBOUND_PACKAGE],'')
      OR ISNULL(TI.[LOAD_FLAG],'')<> ISNULL(TM.[LOAD_FLAG],'')
      OR ISNULL(TI.[ZP_FLAG],'')<> ISNULL(TM.[ZP_FLAG],'')
      OR ISNULL(TI.[REQUIREMENT_FLAG],'')<> ISNULL(TM.[REQUIREMENT_FLAG],'')
      OR ISNULL(TI.[ASSEMBLY_FLAG],'')<> ISNULL(TM.[ASSEMBLY_FLAG],'')
      OR ISNULL(TI.[ASSEMBLY_FLAG_RECRUIT],'')<>ISNULL( TM.[ASSEMBLY_FLAG_RECRUIT],'')
      OR ISNULL(TI.[MARK],'')<> ISNULL(TM.[MARK],'')
      OR ISNULL(TI.[PURCHASE_STYLE],'')<> ISNULL(TM.[PURCHASE_STYLE],'')
      OR ISNULL(TI.[PLATFORM_CHANGE_DATE],'')<> ISNULL(TM.[PLATFORM_CHANGE_DATE],'')
      OR ISNULL(TI.[IS_SPLIT],'')<> ISNULL(TM.[IS_SPLIT],'')
  
   )

-- 删除 3
INSERT INTO [LES].[TE_BAS_INBOUND_LOGISTIC_STANDARD_DIFF]
           ([PLANT],[ASSEMBLY_LINE],[PLANT_ZONE],[WORKSHOP]
           ,[SUPPLIER_NUM],[TRANS_SUPPLIER_NUM],[MODEL],[PART_NO]
           ,[COLOR_DEPARTMENT],[HAND_KEPT_RECORD],[COLOR_CONTROL_PATCH],[VWS],HAND_KEP_VWS
           ,[MODEL_YEAR],[PART_CNAME],[PART_ENAME],[INBOUND_MODE]
           ,[INBOUND_LOGISTIC_MODE],[INBOUND_SYSTEM_MODE],[START_EFFECTIVE_DATE],[INBOUND_PART_CLASS]
           ,[DOCK],[INBOUND_PACKAGE_MODEL],[INBOUND_PACKAGE],[LOAD_FLAG]
           ,[ZP_FLAG],[REQUIREMENT_FLAG],[ASSEMBLY_FLAG],[ASSEMBLY_FLAG_RECRUIT]
           ,[MARK],[PURCHASE_STYLE],[DELETE_FLAG],[PLATFORM_CHANGE_DATE]
           ,[IS_SPLIT],[LOGICAL_PK],[DIFF_FLAG],[CONFIRM_FLAG]
           ,[COMMENTS],[UPDATE_DATE],[UPDATE_USER],[CREATE_DATE]
           ,[CREATE_USER])
SELECT TM.[PLANT],TM.[ASSEMBLY_LINE],TM.[PLANT_ZONE],TM.[WORKSHOP]
      ,TM.[SUPPLIER_NUM],TM.[TRANS_SUPPLIER_NUM],TM.[MODEL],TM.[PART_NO]
      ,TM.[COLOR_DEPARTMENT],TM.[HAND_KEPT_RECORD],TM.[COLOR_CONTROL_PATCH],TM.[VWS],TM.HAND_KEP_VWS
      ,TM.[MODEL_YEAR],TM.[PART_CNAME],TM.[PART_ENAME],TM.[INBOUND_MODE]
      ,TM.[INBOUND_LOGISTIC_MODE],TM.[INBOUND_SYSTEM_MODE],TM.[START_EFFECTIVE_DATE],TM.[INBOUND_PART_CLASS]
      ,TM.[DOCK],TM.[INBOUND_PACKAGE_MODEL],TM.[INBOUND_PACKAGE],TM.[LOAD_FLAG]
      ,TM.[ZP_FLAG],TM.[REQUIREMENT_FLAG],TM.[ASSEMBLY_FLAG],TM.[ASSEMBLY_FLAG_RECRUIT]
      ,TM.[MARK],TM.[PURCHASE_STYLE],TM.[DELETE_FLAG],TM.[PLATFORM_CHANGE_DATE]
      ,TM.[IS_SPLIT],TM.[LOGICAL_PK],3,0
      ,TM.[COMMENTS],TM.[UPDATE_DATE],TM.[UPDATE_USER],TM.[CREATE_DATE]
      ,TM.[CREATE_USER]
 FROM [LES].TM_BAS_MAINTAIN_INBOUND_LOGISTIC_STANDARD AS TM
LEFT JOIN  LES.[TI_BAS_INBOUND_LOGISTIC_STANDARD] AS TI ON TI.LOGICAL_PK = TM.LOGICAL_PK
WHERE TI.LOGICAL_PK IS NULL
	
END