/********************************************************************/
/*                                                                  */
/*   Project Name:  LES System                         */
/*   Program Name:  [PROC_BAS_MAINTAIN_PARTS_CREATE_UPDATE]             */
/*   Called By:     by the Page							*/
/*   Purpose:       This is the main stored procedure for the       */
/*   author:       andy	2015-06-09     				       */
/********************************************************************/
CREATE PROCEDURE [LES].[PROC_BAS_MAINTAIN_PARTS_CREATE_UPDATE]
 
AS

BEGIN

UPDATE [LES].[TM_BAS_MAINTAIN_PARTS]
 SET [PLANT] = TE.[PLANT]
           ,[ASSEMBLY_LINE] = TE.[ASSEMBLY_LINE]
           ,[PLANT_ZONE] = TE.[PLANT_ZONE]
           ,[WORKSHOP] = TE.[WORKSHOP]
           ,[SUPPLIER_NUM] = TE.[SUPPLIER_NUM]
           ,[PART_NO] = TE.[PART_NO]
           ,[PART_CNAME] = TE.[PART_CNAME]
           ,[PART_ENAME] = TE.[PART_ENAME]
           ,[PART_NICKNAME] = TE.[PART_NICKNAME]
           ,[PART_UNITS] = TE.[PART_UNITS]
           ,[PART_WEIGHT] = TE.[PART_WEIGHT]
           ,[PART_CLS] = (SELECT [DETAIL_CODE] FROM [LES].[TC_SYS_CODE_DETAIL] C WHERE C.[DETAIL_VALUE] = TE.[PART_CLS] AND [CODE_NAME] = 'part_category')
           ,[PART_STATE] = (SELECT [DETAIL_CODE] FROM [LES].[TC_SYS_CODE_DETAIL] C WHERE C.[DETAIL_VALUE] = TE.[PART_STATE] AND [CODE_NAME] = 'active_status')
           ,[PART_ENGINEER] = TE.[PART_ENGINEER]
           ,[PART_PURCHASER] = TE.[PART_PURCHASER]
           ,[DOCK] = TE.[DOCK]
           ,[INHOUSE_PACKAGE_MODEL] = TE.[INHOUSE_PACKAGE_MODEL]
           ,[INHOUSE_PACKAGE] = TE.[INHOUSE_PACKAGE]
           ,[INBOUND_PACKAGE_MODEL] = TE.[INBOUND_PACKAGE_MODEL]
           ,[INBOUND_PACKAGE] = TE.[INBOUND_PACKAGE]
           ,[PACKAGE_MODEL] = TE.[PACKAGE_MODEL]
           ,[PACKAGE] = TE.[PACKAGE]
           ,[LOGICAL_PK] = TE.[LOGICAL_PK]
           ,[MRP_TYPE] = TE.[MRP_TYPE]
           ,[MRP_CONTROL] = TE.[MRP_CONTROL]
           ,[MRP_GROUP] = TE.[MRP_GROUP]
           ,[ORDER_BATCH] = TE.[ORDER_BATCH]
           ,[ORDER_ADVANCE] = TE.[ORDER_ADVANCE]
           ,[REORDER_POINT] = TE.[REORDER_POINT]
           ,[PART_GROUP] = TE.[PART_GROUP]
           ,[PULL_PERSON] = TE.[PULL_PERSON]
           ,[INFO_PERSON] = TE.[INFO_PERSON]
           ,[TRANS_STYLE] = TE.[TRANS_STYLE]
           ,[TRANS_TRUCK] = TE.[TRANS_TRUCK]
           ,[TRUCK_SIZE] = TE.[TRUCK_SIZE]
           ,[PACKAGE_FEE] = TE.[PACKAGE_FEE]
           ,[TRANS_FEE] = TE.[TRANS_FEE]
           ,[STOCK_FEE] = TE.[STOCK_FEE]
           ,[DELETE_FLAG] = (SELECT [DETAIL_CODE] FROM [LES].[TC_SYS_CODE_DETAIL] C WHERE C.[DETAIL_VALUE] = TE.[DELETE_FLAG] AND [CODE_NAME] = 'delete_flag')
           ,[PURCHASE_STYLE] = TE.[PURCHASE_STYLE]
           ,[SUPPLY_STYLE] = TE.[SUPPLY_STYLE]
           ,[ROUTE] = TE.[ROUTE]
           ,[TRAN_TYPE] = TE.[TRAN_TYPE]
           ,[TRAN_SIZES] = TE.[TRAN_SIZES]
           ,[COMMENTS] = TE.[COMMENTS]           
           ,[UPDATE_USER] = TE.[CREATE_USER]
           ,[UPDATE_DATE] = TE.[UPDATE_DATE]
FROM LES.TE_BAS_MAINTAIN_PARTS_TEMP AS TE,
     LES.TM_BAS_MAINTAIN_PARTS AS TM
 WHERE TE.PLANT = TM.PLANT AND  TE.PART_NO = TM.PART_NO   AND TE.VALID_FLAG = 1

 

INSERT INTO [LES].[TM_BAS_MAINTAIN_PARTS]
           ([PLANT]
           ,[ASSEMBLY_LINE]
           ,[PLANT_ZONE]
           ,[WORKSHOP]
           ,[SUPPLIER_NUM]
           ,[PART_NO]
           ,[PART_CNAME]
           ,[PART_ENAME]
           ,[PART_NICKNAME]
           ,[PART_UNITS]
           ,[PART_WEIGHT]
           ,[PART_CLS]
           ,[PART_STATE]
           ,[PART_ENGINEER]
           ,[PART_PURCHASER]
           ,[DOCK]
           ,[INHOUSE_PACKAGE_MODEL]
           ,[INHOUSE_PACKAGE]
           ,[INBOUND_PACKAGE_MODEL]
           ,[INBOUND_PACKAGE]
           ,[PACKAGE_MODEL]
           ,[PACKAGE]
           ,[LOGICAL_PK]
           ,[MRP_TYPE]
           ,[MRP_CONTROL]
           ,[MRP_GROUP]
           ,[ORDER_BATCH]
           ,[ORDER_ADVANCE]
           ,[REORDER_POINT]
           ,[PART_GROUP]
           ,[PULL_PERSON]
           ,[INFO_PERSON]
           ,[TRANS_STYLE]
           ,[TRANS_TRUCK]
           ,[TRUCK_SIZE]
           ,[PACKAGE_FEE]
           ,[TRANS_FEE]
           ,[STOCK_FEE]
           ,[DELETE_FLAG]
           ,[PURCHASE_STYLE]
           ,[SUPPLY_STYLE]
           ,[ROUTE]
           ,[TRAN_TYPE]
           ,[TRAN_SIZES]
           ,[COMMENTS]
           ,[CREATE_USER]
           ,[CREATE_DATE]
           ,[UPDATE_USER]
           ,[UPDATE_DATE]
           )
      
	SELECT TE.[PLANT]
           ,[ASSEMBLY_LINE]
           ,[PLANT_ZONE]
           ,[WORKSHOP]
           ,[SUPPLIER_NUM]
           ,[PART_NO]
           ,[PART_CNAME]
           ,[PART_ENAME]
           ,[PART_NICKNAME]
           ,[PART_UNITS]
           ,[PART_WEIGHT]
           ,C1.[DETAIL_CODE]
           ,C2.[DETAIL_CODE]
           ,[PART_ENGINEER]
           ,[PART_PURCHASER]
           ,[DOCK]
           ,[INHOUSE_PACKAGE_MODEL]
           ,[INHOUSE_PACKAGE]
           ,[INBOUND_PACKAGE_MODEL]
           ,[INBOUND_PACKAGE]
           ,[PACKAGE_MODEL]
           ,[PACKAGE]
           ,[LOGICAL_PK]
           ,[MRP_TYPE]
           ,[MRP_CONTROL]
           ,[MRP_GROUP]
           ,[ORDER_BATCH]
           ,[ORDER_ADVANCE]
           ,[REORDER_POINT]
           ,[PART_GROUP]
           ,[PULL_PERSON]
           ,[INFO_PERSON]
           ,[TRANS_STYLE]
           ,[TRANS_TRUCK]
           ,[TRUCK_SIZE]
           ,[PACKAGE_FEE]
           ,[TRANS_FEE]
           ,[STOCK_FEE]
           ,C3.[DETAIL_CODE]
           ,[PURCHASE_STYLE]
           ,[SUPPLY_STYLE]
           ,[ROUTE]
           ,[TRAN_TYPE]
           ,[TRAN_SIZES]
           ,TE.[COMMENTS]
           ,TE.[CREATE_USER]
           ,TE.[CREATE_DATE]
           ,TE.[UPDATE_USER]
           ,TE.[UPDATE_DATE]
		   FROM [LES].TE_BAS_MAINTAIN_PARTS_TEMP TE 
		   LEFT JOIN [LES].[TC_SYS_CODE_DETAIL] C1 ON  C1.[DETAIL_VALUE] = TE.[PART_CLS] AND C1.[CODE_NAME] = 'part_category'
		   LEFT JOIN [LES].[TC_SYS_CODE_DETAIL] C2 ON  C2.[DETAIL_VALUE] = TE.[PART_STATE] AND C2.[CODE_NAME] = 'active_status'
		   LEFT JOIN [LES].[TC_SYS_CODE_DETAIL] C3 ON  C3.[DETAIL_VALUE] = TE.[DELETE_FLAG] AND C3.[CODE_NAME] = 'delete_flag'
		WHERE   TE.VALID_FLAG = 1 AND NOT EXISTS(SELECT * FROM [LES].[TM_BAS_MAINTAIN_PARTS] WHERE  PLANT =TE.PLANT AND 
 PART_NO = TE.PART_NO )
	
END