


CREATE PROCEDURE [LES].[PROC_WMM_RETURN_CREATE_UPDATE]
 
AS

BEGIN

INSERT INTO [LES].[TT_WMM_RETURN]
	(
	[RETURN_NO]
	,[RETURN_TYPE]
	,[PLANT]
	,[WM_NO]
	,[ZONE_NO]
	,[SUPPLIER_NUM]
	,[SEND_TIME]
	,[CONFIRM_FLAG]
	,RETURN_REASON
	,COMMENTS
	,[CREATE_USER]
	,[CREATE_DATE]
	)
	SELECT distinct 
		[RETURN_NO]
        ,D.DETAIL_CODE
        ,[PLANT]
        ,[WM_NO]
        ,[ZONE_NO]
        ,[SUPPLIER_NUM]
        ,[SEND_TIME]
		,0
		,RETURN_REASON
		,te.COMMENTS
        ,TE.[CREATE_USER]
        ,TE.[CREATE_DATE]
	FROM 
		[LES].[TE_WMM_RETURN_TEMP] (NOLOCK) TE JOIN les.TC_SYS_CODE_DETAIL d
		ON RETURN_TYPE=d.DETAIL_CODE AND d.CODE_NAME = 'wms_return_type'
	WHERE 
		TE.VALID_FLAG = 1
		AND TE.RETURN_NO NOT IN (SELECT RETURN_NO FROM [LES].[TT_WMM_RETURN])

UPDATE 
[LES].[TT_WMM_RETURN]
SET
[RETURN_TYPE]	= TE.RETURN_TYPE
,[PLANT]		= TE.PLANT
,[WM_NO]		= TE.WM_NO
,[ZONE_NO]		= TE.ZONE_NO
,[SUPPLIER_NUM]	= TE.SUPPLIER_NUM
,[SEND_TIME]	= TE.SEND_TIME
,RETURN_REASON	= TE.RETURN_REASON
,COMMENTS		= TE.COMMENTS
,UPDATE_USER	= TE.CREATE_USER
,UPDATE_DATE	= GETDATE()
FROM 
	(SELECT d.DETAIL_CODE AS RETURN_TYPE,T.PLANT,T.WM_NO,T.ZONE_NO,T.SUPPLIER_NUM,T.SEND_TIME,T.RETURN_REASON,T.COMMENTS,T.CREATE_USER,
	T.VALID_FLAG,T.RETURN_NO 
	 FROM [LES].[TE_WMM_RETURN_TEMP]T JOIN 
	les.TC_SYS_CODE_DETAIL d ON RETURN_TYPE=d.DETAIL_CODE 
	AND d.CODE_NAME = 'wms_return_type') AS
	 TE,
	[LES].[TT_WMM_RETURN](NOLOCK) TT
WHERE 
	TE.VALID_FLAG = 1 
	AND TE.[RETURN_NO] = TT.[RETURN_NO] 
	AND (TT.CONFIRM_FLAG = 0 OR TT.CONFIRM_FLAG IS NULL)

INSERT INTO [LES].[TT_WMM_RETURN_DETAIL]
	(
      [RETURN_ID]
      ,[PLANT]
      ,[SUPPLIER_NUM]
      ,[WM_NO]
      ,[ZONE_NO]
      ,[DLOC]
      ,[PART_NO]
      ,[PART_CNAME]
      ,[PART_CLS]
      ,[PART_COUNT]
      ,[PACK_COUNT]
      ,[PACK_SIZE]
      ,[PACKAGE_MODEL]
      ,[RETURN_REASON]
      ,[COMMENTS]
      ,[CREATE_USER]
      ,[CREATE_DATE]
	)
	SELECT 
		TT.RETURN_ID		
	    ,TE.[PLANT]
		,TE.[SUPPLIER_NUM]
		,TE.[WM_NO]
		,TE.[ZONE_NO]
		,ST.DLOC
        ,TE.[PART_NO]
        ,ST.[PART_CNAME]
		,TM.PART_CLS
        ,0 AS [PART_COUNT]
        ,TE.PART_COUNT AS [PACK_COUNT]
		,TE.PACK_COUNT as [PACK_SIZE]
        ,ST.[PACKAGE_MODEL]
		,TE.RETURN_REASON
		,TE.COMMENTS
        ,TE.[CREATE_USER]
        ,TE.[CREATE_DATE]
	FROM 
		[LES].[TE_WMM_RETURN_TEMP] (NOLOCK)  TE 
		JOIN [LES].[TT_WMM_RETURN](NOLOCK) TT ON TE.VALID_FLAG = 1 AND (TT.CONFIRM_FLAG = 0 OR TT.CONFIRM_FLAG IS NULL) AND TE.RETURN_NO = TT.RETURN_NO 
		JOIN [LES].[TM_BAS_MAINTAIN_PARTS](NOLOCK) TM ON TE.PART_NO = TM.PART_NO
		LEFT JOIN [LES].[TM_BAS_PARTS_STOCK](NOLOCK) ST ON TE.PLANT = ST.PLANT AND TE.WM_NO = ST.WM_NO AND TE.ZONE_NO = ST.ZONE_NO AND TE.PART_NO = ST.PART_NO
	WHERE 
		(SELECT Count(*) FROM [LES].[TT_WMM_RETURN_DETAIL](NOLOCK) t where t.RETURN_ID = TT.RETURN_ID and t.PART_NO = TE.PART_NO) = 0

UPDATE 
	[LES].[TT_WMM_RETURN_DETAIL]
SET
    RETURN_ID = TT.RETURN_ID
	,[PLANT] = TT.[PLANT]
	,[WM_NO] = TT.[WM_NO]
	,[ZONE_NO] = TT.[ZONE_NO]
    ,[PART_NO] = TE.[PART_NO]
    ,[PART_CNAME] = ST.[PART_CNAME]
	,[PART_CLS] = TM.PART_CLS
    --,[PART_COUNT] = TE.PART_COUNT
    ,[PACK_COUNT] = TE.PART_COUNT
	,[PACK_SIZE] = TE.PACK_COUNT
    ,[SUPPLIER_NUM] = TE.[SUPPLIER_NUM]
    ,[PACKAGE_MODEL] = ST.[PACKAGE_MODEL]
	,[RETURN_REASON] = TE.RETURN_REASON
    ,[COMMENTS] = TE.COMMENTS
    ,[UPDATE_USER] = TE.[CREATE_USER]
    ,[UPDATE_DATE] =GETDATE()
FROM 
	[LES].[TE_WMM_RETURN_TEMP](NOLOCK) TE 
	JOIN [LES].[TT_WMM_RETURN](NOLOCK) TT ON TE.VALID_FLAG = 1 AND (TT.CONFIRM_FLAG = 0 OR TT.CONFIRM_FLAG IS NULL) AND TE.RETURN_NO = TT.RETURN_NO
	JOIN [LES].[TT_WMM_RETURN_DETAIL](NOLOCK) DE ON TT.RETURN_ID = DE.RETURN_ID AND TE.PART_NO = DE.PART_NO
	JOIN [LES].[TM_BAS_MAINTAIN_PARTS](NOLOCK) TM ON TE.PART_NO = TM.PART_NO
	LEFT JOIN [LES].[TM_BAS_PARTS_STOCK] (NOLOCK)ST ON TT.PLANT = ST.PLANT AND TT.WM_NO = ST.WM_NO AND TT.ZONE_NO = ST.ZONE_NO AND TE.PART_NO = ST.PART_NO

END