
-- =============================================
-- Author:		houpeng
-- Create date: 2016-11-30
-- Description:	根据翻包计划，生成补货计划
-- =============================================
CREATE PROCEDURE [LES].[PROC_WMM_REFILL_REQUEST_CREATE]
	@REPACKAGE_PLAN_ID BIGINT
AS
BEGIN
	--DECLARE @REPACKAGE_PLAN_ID BIGINT = 2851
	--参数处理
	IF(@REPACKAGE_PLAN_ID IS NULL)
	BEGIN
		RETURN
	END

	DECLARE @OPERATION_ID UNIQUEIDENTIFIER = NEWID()

	INSERT INTO [LES].[TT_WMM_REFILL_REQUEST] (
		  [PLANT]
		  ,[WM_NO]
		  ,[ZONE_NO]
		  ,[PART_NO]
		  ,[PART_CNAME]
		  ,[PART_NICKNAME]
		  ,[REPACKAGE_ROUTE]
		  ,[DLOC]
		  ,[PACKAGE_MODEL]
		  ,[PACKAGE]
		  ,[REQUIRED_BOX_NUM]
		  ,[DEAL_FLAG]
		  ,[DEAL_DATE]
		  ,[ASSEMBLY_LINE]
		  ,[COMMENTS]
		  ,[CREATE_USER]
		  ,[CREATE_DATE]
		  ,[UPDATE_USER]
		  ,[UPDATE_DATE]
		  ,[OPERATION_ID]
		)
		SELECT S.PLANT,S.WM_NO,S.ZONE_NO,S.PART_NO,S.PART_CNAME,S.PART_NICKNAME,S.REPACK_ROUTE,S.DLOC,S.PACKAGE_MODEL,S.PACKAGE,[LES].[Func_LCM](M.REQUIRED_QTY,S.PACKAGE)/S.PACKAGE RE_NUM
			,0,NULL,S.ASSEMBLY_LINE,NULL,'admin',GETDATE(),NULL,NULL,@OPERATION_ID
			FROM (
				SELECT H.PLANT,D.WM_NO,D.ZONE_NO,D.PART_NO,SUM(D.REQUIRED_QTY) REQUIRED_QTY
					FROM [LES].[TT_WMM_REPACKAGE_HEAD] H
					INNER JOIN [LES].[TT_WMM_REPACKAGE_DETAIL] D
						ON H.REPACKAGE_ID=D.REPACKAGE_ID
					WHERE H.REPACKAGE_ID=@REPACKAGE_PLAN_ID
					GROUP BY H.PLANT,D.WM_NO,D.ZONE_NO,D.PART_NO
			) M
			INNER JOIN [LES].[TM_WMM_ZONES] Z
				ON Z.PLANT=M.PLANT AND Z.REPACKAGE_ZONE=M.ZONE_NO
			INNER JOIN [LES].[TM_BAS_PARTS_STOCK] S
				ON S.PLANT=Z.PLANT AND S.WM_NO=Z.WM_NO AND S.ZONE_NO=Z.ZONE_NO AND S.PART_NO=M.PART_NO
					AND ISNULL(S.DELETE_FLAG,0)=0 AND ISNULL(S.IS_REPACK,0)=1

END