


CREATE PROCEDURE [LES].[PROC_INTERFACE_LES_SAP_WMSOUTBOUNDDELIVERYOUT]
AS
BEGIN
	IF(not EXISTS(Select 1 From LES.TI_SPM_OUTBOUNDDELIVERY_RUNSHEET_OUT Where IsNull(DEAL_FLAG,0)=0))
	BEGIN
		--插入普通销售出库数据
		BEGIN TRANSACTION TA_OUTBOUNDDELIVERY
		BEGIN TRY
			--取出待处理的ID
			DECLARE @IDListOut TABLE(ID BIGINT) 
			INSERT INTO @IDListOut
				SELECT TOP 50 B.OUTBOUNDDELIVERY_ID
					FROM [LES].[TT_WMM_OUTBOUNDDELIVERY_DETAIL] A
						Inner Join [LES].[TT_WMM_OUTBOUNDDELIVERY] B ON (A.OUTBOUNDDELIVERY_NO=B.OUTBOUNDDELIVERY_NO)
						Inner Join [LES].[TI_SPM_OUTBOUNDDELIVERY_RUNSHEET_DETAIL_IN] C ON(ISNULL(C.PROCESS_FLAG,0)=1 And A.OUTBOUNDDELIVERY_NO=C.VBELN And A.PART_NO=C.MATNR And C.EBELN=A.PO_NO)
						Inner Join [LES].[TI_SPM_OUTBOUNDDELIVERY_RUNSHEET_IN] D ON(ISNULL(D.PROCESS_FLAG,0)=1 And C.VBELN=D.VBELN)
					Where IsNull(B.ERP_FLAG,0)=2
						And D.LFART IN('NLC1','NLC2','J')
			
			
			INSERT INTO [LES].[TI_SPM_OUTBOUNDDELIVERY_RUNSHEET_OUT] (
					[VBELN]
					,[LFIMG]
					,[POSNR]
					,[MATNR]
					,[WERKS]
					,[LGORT]
					,[MEINS]
					,[LFART]
					,[WADAT_IST]
					,[BUDAT]
					,[OPTIM]
					,[OPRTR]
					,[DEAL_FLAG]
					,[PROCESS_FLAG]
					,[PROCESS_TIME]
					,[COMMENTS]
					,[CREATE_DATE]
					,[CREATE_USER]
				)
				SELECT	A.[OUTBOUNDDELIVERY_NO]            --[VBELN]
						,A.[NUM]                            --[LFIMG]
						,C.[POSNR]                          --[POSNR]
						,A.[PART_NO]                        --[MATNR]                   
						,A.[PLANT]                          --[WERKS]
						,A.[ZONE_NO]                        --[LGORT]
						,A.[MEASURING_UNIT_NO]              --[MEINS]
						,D.LFART                            --[LFART]
						,CASE WHEN B.ACTUAL_OUTBOUNDDELIVERY_TIME IS NOT NULL Then Convert(varchar(8),B.ACTUAL_OUTBOUNDDELIVERY_TIME,112) --[WADAT_IST]
						Else Null End
						,CASE WHEN B.ACTUAL_OUTBOUNDDELIVERY_TIME IS NOT NULL Then Convert(varchar(8),B.ACTUAL_OUTBOUNDDELIVERY_TIME,112) --[BUDAT]
						Else Null End
						,CASE WHEN B.ACTUAL_OUTBOUNDDELIVERY_TIME IS NOT NULL Then Replace(Convert(varchar(8),B.ACTUAL_OUTBOUNDDELIVERY_TIME,108),':','') --[OPTIM]
						Else Null End
						,A.OPRTR                          --[OPRTR]
						,0                                --[DEAL_FLAG]
						,0                                --[PROCESS_FLAG]
						,GETDATE()                        --[PROCESS_TIME]
						,A.[COMMENTS]                     --[COMMENTS]
						,GETDATE()                        --[CREATE_DATE]
						,'admin'                          --[CREATE_USER]
					FROM [LES].[TT_WMM_OUTBOUNDDELIVERY_DETAIL] A
						Inner Join [LES].[TT_WMM_OUTBOUNDDELIVERY] B ON (A.OUTBOUNDDELIVERY_NO=B.OUTBOUNDDELIVERY_NO)
						Inner Join [LES].[TI_SPM_OUTBOUNDDELIVERY_RUNSHEET_DETAIL_IN] C ON(ISNULL(C.PROCESS_FLAG,0)=1 And A.OUTBOUNDDELIVERY_NO=C.VBELN And A.PART_NO=C.MATNR And C.EBELN=A.PO_NO)
						Inner Join [LES].[TI_SPM_OUTBOUNDDELIVERY_RUNSHEET_IN] D ON(ISNULL(D.PROCESS_FLAG,0)=1 And C.VBELN=D.VBELN)
					Where IsNull(B.ERP_FLAG,0)=2
						And D.LFART IN('NLC1','NLC2','J')
						AND B.OUTBOUNDDELIVERY_ID IN (SELECT ID FROM @IDListOut)
		
			UPDATE [LES].[TT_WMM_OUTBOUNDDELIVERY]
				SET ERP_FLAG=1 
					,UPDATE_DATE=GETDATE()
					,UPDATE_USER='admin'
				WHERE ISNULL(ERP_FLAG,0)=2
					AND OUTBOUNDDELIVERY_ID IN (SELECT ID FROM @IDListOut)

			COMMIT TRANSACTION TA_OUTBOUNDDELIVERY
		END TRY
		BEGIN CATCH
			--出错，则返回执行不成功，回滚事务
			ROLLBACK TRANSACTION TA_OUTBOUNDDELIVERY

			--记录错误信息
			DECLARE @ERROR_OUTBOUNDDELIVERY_ID NVARCHAR(MAX)
			SET @ERROR_OUTBOUNDDELIVERY_ID = (SELECT CAST(ID AS NVARCHAR(50))+',' FROM @IDListOut FOR XML PATH(''))

			INSERT INTO [LES].[TS_SYS_EXCEPTION] (time_stamp, [application], [METHOD], class,  exception_message, error_code)
				SELECT getdate(),'INTERFACE','PROC_INTERFACE_LES_SAP_WMSOUTBOUNDDELIVERYOUT','Procedure','TT_WMM_OUTBOUNDDELIVERY:'+ISNULL(error_message(),'')+';OUTBOUNDDELIVERY_ID:'+IsNull(@ERROR_OUTBOUNDDELIVERY_ID,''),ERROR_LINE()

			--标记错误的数据状态为9
			UPDATE [LES].[TT_WMM_OUTBOUNDDELIVERY]
				SET ERP_FLAG=9 
					,UPDATE_DATE=GETDATE()
					,UPDATE_USER='admin'
				WHERE ISNULL(ERP_FLAG,0)=2
					AND OUTBOUNDDELIVERY_ID IN (SELECT ID FROM @IDListOut)
		END CATCH

	

		--插入销售退货数据
		BEGIN TRANSACTION TA_OUTBOUNDDELIVERYRETURN
		BEGIN TRY
			--取出待处理的ID
			DECLARE @IDListReturn TABLE(ID BIGINT) 
			INSERT INTO @IDListReturn
				SELECT TOP 50 B.OUTBOUNDDELIVERYRETURN_ID
					FROM [LES].[TT_WMM_OUTBOUNDDELIVERYRETURN_DETAIL] A
						Inner Join [LES].[TT_WMM_OUTBOUNDDELIVERYRETURN] B ON (A.OUTBOUNDDELIVERYRETURN_NO=B.OUTBOUNDDELIVERYRETURN_NO)
						Inner Join [LES].[TI_SPM_OUTBOUNDDELIVERY_RUNSHEET_DETAIL_IN] C ON(ISNULL(C.PROCESS_FLAG,0)=1 And A.OUTBOUNDDELIVERYRETURN_NO=C.VBELN And A.PART_NO=C.MATNR And C.EBELN=A.PO_NO)
						Inner Join [LES].[TI_SPM_OUTBOUNDDELIVERY_RUNSHEET_IN] D ON(ISNULL(D.PROCESS_FLAG,0)=1 And C.VBELN=D.VBELN)
					Where IsNull(B.ERP_FLAG,0)=2
						And D.LFART IN('ZNR1','ZNR2','T')

			--插入销售退货数据
			INSERT INTO [LES].[TI_SPM_OUTBOUNDDELIVERY_RUNSHEET_OUT] (
					[VBELN]
					,[LFIMG]
					,[POSNR]
					,[MATNR]
					,[WERKS]
					,[LGORT]
					,[MEINS]
					,[LFART]
					,[WADAT_IST]
					,[BUDAT]
					,[OPTIM]
					,[OPRTR]
					,[DEAL_FLAG]
					,[PROCESS_FLAG]
					,[PROCESS_TIME]
					,[COMMENTS]
					,[CREATE_DATE]
					,[CREATE_USER]
				)
				SELECT	A.OUTBOUNDDELIVERYRETURN_NO            --[VBELN]
						,A.[NUM]                                --[LFIMG]
						,C.[POSNR]                              --[POSNR]
						,A.[PART_NO]                            --[MATNR]                   
						,A.[PLANT]                              --[WERKS]
						,A.[ZONE_NO]                            --[LGORT]
						,A.[MEASURING_UNIT_NO]                  --[MEINS]
						,D.LFART                                --[LFART]
						,CASE WHEN B.ACTUAL_ARRIVAL_TIME IS NOT NULL Then Convert(varchar(8),B.ACTUAL_ARRIVAL_TIME,112) --[WADAT_IST]
						Else Null End
						,CASE WHEN B.ACTUAL_ARRIVAL_TIME IS NOT NULL Then Convert(varchar(8),B.ACTUAL_ARRIVAL_TIME,112) --[BUDAT]
						Else Null End
						,CASE WHEN B.ACTUAL_ARRIVAL_TIME IS NOT NULL Then Replace(Convert(varchar(8),B.ACTUAL_ARRIVAL_TIME,108),':','') --[OPTIM]
						Else Null End
						,A.OPRTR                          --[OPRTR]
						,0                                --[DEAL_FLAG]
						,0                                --[PROCESS_FLAG]
						,GETDATE()                        --[PROCESS_TIME]
						,A.[COMMENTS]                     --[COMMENTS]
						,GETDATE()                        --[CREATE_DATE]
						,'admin'                          --[CREATE_USER]
					FROM [LES].[TT_WMM_OUTBOUNDDELIVERYRETURN_DETAIL] A
						Inner Join [LES].[TT_WMM_OUTBOUNDDELIVERYRETURN] B ON (A.OUTBOUNDDELIVERYRETURN_NO=B.OUTBOUNDDELIVERYRETURN_NO)
						Inner Join [LES].[TI_SPM_OUTBOUNDDELIVERY_RUNSHEET_DETAIL_IN] C ON(ISNULL(C.PROCESS_FLAG,0)=1 And A.OUTBOUNDDELIVERYRETURN_NO=C.VBELN And A.PART_NO=C.MATNR And C.EBELN=A.PO_NO)
						Inner Join [LES].[TI_SPM_OUTBOUNDDELIVERY_RUNSHEET_IN] D ON(ISNULL(D.PROCESS_FLAG,0)=1 And C.VBELN=D.VBELN)
					Where IsNull(B.ERP_FLAG,0)=2
						And D.LFART IN('ZNR1','ZNR2','T')
						AND B.OUTBOUNDDELIVERYRETURN_ID IN (SELECT ID FROM @IDListReturn)

			--更新退货数据状态
			UPDATE [LES].[TT_WMM_OUTBOUNDDELIVERYRETURN]
				SET ERP_FLAG=1 
					,UPDATE_DATE=GETDATE()
					,UPDATE_USER='admin'
				WHERE ISNULL(ERP_FLAG,0)=2 
					AND OUTBOUNDDELIVERYRETURN_ID IN (SELECT ID FROM @IDListReturn)
				--AND ISNULL(CONFIRM_FLAG,0)=2 

			 COMMIT TRANSACTION TA_OUTBOUNDDELIVERYRETURN
		END TRY
		BEGIN CATCH
			--出错，则返回执行不成功，回滚事务
			ROLLBACK TRANSACTION TA_OUTBOUNDDELIVERYRETURN
			--记录错误信息
			DECLARE @ERROR_OUTBOUNDDELIVERYRETURN_ID NVARCHAR(MAX)
			SET @ERROR_OUTBOUNDDELIVERYRETURN_ID = (SELECT CAST(ID AS NVARCHAR(50))+',' FROM @IDListReturn FOR XML PATH(''))

			INSERT INTO [LES].[TS_SYS_EXCEPTION] (time_stamp, [application], [METHOD], class,  exception_message, error_code)
				SELECT getdate(),'INTERFACE','PROC_INTERFACE_LES_SAP_WMSOUTBOUNDDELIVERYOUT','Procedure','TT_WMM_OUTBOUNDDELIVERYRETURN:'+ISNULL(error_message(),'')+';OUTBOUNDDELIVERY_ID:'+IsNull(@ERROR_OUTBOUNDDELIVERYRETURN_ID,''),ERROR_LINE()
			
			--更新退货数据状态
			UPDATE [LES].[TT_WMM_OUTBOUNDDELIVERYRETURN]
				SET ERP_FLAG=9 
					,UPDATE_DATE=GETDATE()
					,UPDATE_USER='admin'
				WHERE ISNULL(ERP_FLAG,0)=2 
					AND OUTBOUNDDELIVERYRETURN_ID IN (SELECT ID FROM @IDListReturn)
		END CATCH

	END
END