
CREATE PROCEDURE [LES].[PROC_JIS_UPDATE_RUNSHEET_DETAIL_ORDER_NO]
(
	@JIS_RUNSHEET_FLEX_SN	INT,
	@PLANT					NVARCHAR(5), 
	@SUPPLIER_NUM			NVARCHAR(8),
	@DEAL_TIME				DATETIME	
)
AS

BEGIN
	/*DECLARE @SAPPLANT NVARCHAR(8)
	select @SAPPLANT=[SAP_PLANT_CODE] from [LES].[TM_BAS_PLANT] where [PLANT]=@PLANT*/
	UPDATE	LES.TT_JIS_RUNSHEET_DETAIL
	SET		ORDER_NO = B.AGREEMENT_NO, ITEM_NO = B.PROJECT
	FROM	LES.TT_JIS_RUNSHEET_DETAIL A, LES.TI_BAS_SUPPLIER_SOURCE_LIST B
	WHERE	JIS_RUNSHEET_FLEX_SN = @JIS_RUNSHEET_FLEX_SN 
	AND		A.PART_NO = B.PART_NO
	AND		B.PLANT = @PLANT 
	AND		B.SUPPLIER_NUM = @SUPPLIER_NUM
	--modify by【运维】hx 2014/04/01【CMDB编号：CR-LES-20140402】start
	--修改起始有效期和结束有效期只比较日期
	AND		CONVERT(DATETIME,CONVERT(VARCHAR(10),@DEAL_TIME,23)) BETWEEN START_EFFECTIVE_DATE AND END_EFFECTIVE_DATE
	--modify by【运维】hx 2014/04/01 end
	
END