/*********************************************************************************************************/
/*   Project Name:  TWD																					 */
/*   Program Name:  [LES].[PROC_TWD_GEN_TWICEPULL_DATA]													 */
/*   Called By:     界面 and service																	 */
/*   Author:        xhj																					 */
/*   Modify:		Author: Andy  Note: TWD测试状态的零件类生成的送货单不需发给供应商、服务商 2014-08-11 */
/*   Modify:		Author: 孙述霄 Note: TWD二次拉动将消耗投递到中间表  DATE 2017-05-17                  */
/*********************************************************************************************************/
CREATE PROCEDURE [LES].[PROC_TWD_GEN_TWICEPULL_DATA]
(
	@runsheetSN int,
	@pullType nvarchar(50)
)
AS
BEGIN
	SET XACT_ABORT ON
	BEGIN TRY
		BEGIN TRANSACTION

		IF UPPER(@pullType) = 'TWD'
			BEGIN
				INSERT INTO [LES].[TE_TWD_MATERIAL_CONSUME_TEMP]
				(
					[PLANT_ZONE],
					[WORKSHOP],
					[ASSEMBLY_LINE],
					[PLANT],
					[LOCATION],
					[PART_NO],
					[INDENTIFY_PART_NO],
					[PART_CNAME],
					[PART_ENAME],
					[SUPPLIER_NUM],
					[DOCK],
					[BOX_PARTS],
					[PACK_COUNT],
					[INBOUND_PACKAGE_MODEL],
					[INBOUND_PACKAGE],
					[MEASURING_UNIT_NO],
					[RDC_DLOC],
					[CARD_NO],
					[PART_SUPPLIER_NUM],
					[PROCESS_FLAG],
					[CREATE_DATE],
					[CREATE_USER]
				)
				SELECT
					S.[PLANT_ZONE],
					S.[WORKSHOP],
					S.[ASSEMBLY_LINE],
					S.[PLANT],
					S.[LOCATION],
					S.[PART_NO],
					S.[PART_NO] AS [INDENTIFY_PART_NO],
					S.[PART_CNAME],
					S.[PART_ENAME],
					S.[SUPPLIER_NUM],
					S.[DOCK],
					S.[INHOUSE_PART_CLASS] AS [BOX_PARTS],
					A.[REQUIRED_INBOUND_PACKAGE_QTY] AS [PACK_COUNT],
					S.[INBOUND_PACKAGE_MODEL],
					S.[INBOUND_PACKAGE],
					A.[MEASURING_UNIT_NO],
					S.[DLOC] AS [RDC_DLOC],
					B.[TWD_RUNSHEET_NO] AS [CARD_NO],
					A.[SUPPLIER_NUM] AS [PART_SUPPLIER_NUM],
					0 AS [PROCESS_FLAG],
					GETDATE() AS [CREATE_DATE],
					'TWD CONSUME' AS [CREATE_USER]
				FROM [LES].[TT_TWD_RUNSHEET_DETAIL] A WITH (NOLOCK)
				INNER JOIN [LES].[TT_TWD_RUNSHEET] B WITH (NOLOCK) ON A.[TWD_RUNSHEET_SN] = B.[TWD_RUNSHEET_SN]
				INNER JOIN [LES].[TM_BAS_MAINTAIN_INHOUSE_LOGISTIC_STANDARD] D WITH (NOLOCK)
				ON D.[IS_TRIGGER_PULL] = 1 AND A.[PLANT] = D.[PLANT] AND A.[ASSEMBLY_LINE] = D.[ASSEMBLY_LINE]
				AND D.[INHOUSE_SYSTEM_MODE] = 'TWD' AND A.[PART_NO] = D.[PART_NO] AND A.[BOX_PARTS] = D.[INHOUSE_PART_CLASS] AND ISNULL(D.DELETE_FLAG,0) = 0
				INNER JOIN [LES].[TM_BAS_MAINTAIN_INHOUSE_LOGISTIC_STANDARD] S WITH (NOLOCK)
				ON S.[INHOUSE_SYSTEM_MODE] = 'TWD' AND D.[PART_NO] = S.[PART_NO] AND D.[ZONE_NO] = S.[PLANT_ZONE] AND ISNULL(S.DELETE_FLAG,0) = 0
				INNER JOIN [LES].[TM_TWD_BOX_PARTS] T WITH (NOLOCK)
				ON S.[PLANT] = T.[PLANT] AND S.[ASSEMBLY_LINE] = T.[ASSEMBLY_LINE] AND S.[INHOUSE_PART_CLASS] = T.[BOX_PARTS] AND S.[SUPPLIER_NUM] = T.[SUPPLIER_NUM]
				WHERE A.[TWD_RUNSHEET_SN] = @runsheetSN AND T.[PULL_MODE] <> 4
			END

		IF UPPER(@pullType) = 'JIS'
			BEGIN
				INSERT INTO [LES].[TE_TWD_MATERIAL_CONSUME_TEMP]
				(
					[PLANT_ZONE],
					[WORKSHOP],
					[ASSEMBLY_LINE],
					[PLANT],
					[LOCATION],
					[PART_NO],
					[INDENTIFY_PART_NO],
					[PART_CNAME],
					[PART_ENAME],
					[SUPPLIER_NUM],
					[DOCK],
					[BOX_PARTS],
					[PACK_COUNT],
					[INBOUND_PACKAGE_MODEL],
					[INBOUND_PACKAGE],
					[MEASURING_UNIT_NO],
					[RDC_DLOC],
					[CARD_NO],
					[PART_SUPPLIER_NUM],
					[PROCESS_FLAG],
					[CREATE_DATE],
					[CREATE_USER]
				)
				SELECT
					E.[PLANT_ZONE],
					E.[WORKSHOP],
					E.[ASSEMBLY_LINE],
					E.[PLANT],
					E.[LOCATION],
					E.[PART_NO],
					E.[PART_NO] AS [INDENTIFY_PART_NO],
					E.[PART_CNAME],
					E.[PART_ENAME],
					E.[SUPPLIER_NUM],
					E.[DOCK],
					E.[INHOUSE_PART_CLASS] AS [BOX_PARTS],
					D.[USAGE] AS [PACK_COUNT],
					E.[INBOUND_PACKAGE_MODEL],
					E.[INBOUND_PACKAGE],
					'' AS [MEASURING_UNIT_NO],
					E.[DLOC] AS [RDC_DLOC],
					R.[JIS_RUNSHEET_NO] AS [CARD_NO],
					F.[SUPPLIER_NUM] AS [PART_SUPPLIER_NUM],
					0 AS [PROCESS_FLAG],
					GETDATE() AS [CREATE_DATE],
					'JIS CONSUME' AS [CREATE_USER]
				FROM [LES].[TT_JIS_RUNSHEET_FLEX] F WITH (NOLOCK)
				INNER JOIN [LES].[TT_JIS_RUNSHEET] R WITH (NOLOCK) ON F.[JIS_RUNSHEET_SN] = R.[JIS_RUNSHEET_SN]		
				INNER JOIN [LES].[TT_JIS_RUNSHEET_DETAIL] D WITH (NOLOCK) ON F.[JIS_RUNSHEET_FLEX_SN] = D.[JIS_RUNSHEET_FLEX_SN]
				INNER JOIN [LES].[TM_BAS_MAINTAIN_INHOUSE_LOGISTIC_STANDARD] S WITH (NOLOCK)
				ON S.[IS_TRIGGER_PULL] = 1 AND S.[PLANT] = F.[PLANT] AND S.[ASSEMBLY_LINE] = D.[ASSEMBLY_LINE]
				AND S.[INHOUSE_SYSTEM_MODE] = 'JIS' AND S.[PART_NO] = D.[PART_NO] AND S.[INHOUSE_PART_CLASS] = F.[RACK] AND ISNULL(S.[DELETE_FLAG],0) = 0
				INNER JOIN [LES].[TM_BAS_MAINTAIN_INHOUSE_LOGISTIC_STANDARD] E WITH (NOLOCK)
				ON E.[INHOUSE_SYSTEM_MODE] = 'TWD' AND E.[PART_NO] = S.[PART_NO] AND E.[PLANT_ZONE] = S.[ZONE_NO]
				AND ISNULL(E.DELETE_FLAG,0) = 0
				INNER JOIN [LES].[TM_TWD_BOX_PARTS] T WITH (NOLOCK)
				ON E.[PLANT] = T.[PLANT] AND E.[ASSEMBLY_LINE] = T.[ASSEMBLY_LINE] AND E.[INHOUSE_PART_CLASS] = T.[BOX_PARTS] AND E.[SUPPLIER_NUM] = T.[SUPPLIER_NUM]
				WHERE F.[JIS_RUNSHEET_SN] = @runsheetSN AND T.[PULL_MODE] <> 4
			END

		IF UPPER(@pullType) = 'EPS'
			BEGIN
				INSERT INTO [LES].[TE_TWD_MATERIAL_CONSUME_TEMP]
				(
					[PLANT_ZONE],
					[WORKSHOP],
					[ASSEMBLY_LINE],
					[PLANT],
					[LOCATION],
					[PART_NO],
					[INDENTIFY_PART_NO],
					[PART_CNAME],
					[PART_ENAME],
					[SUPPLIER_NUM],
					[DOCK],
					[BOX_PARTS],
					[PACK_COUNT],
					[INBOUND_PACKAGE_MODEL],
					[INBOUND_PACKAGE],
					[MEASURING_UNIT_NO],
					[RDC_DLOC],
					[CARD_NO],
					[PART_SUPPLIER_NUM],
					[PROCESS_FLAG],
					[CREATE_DATE],
					[CREATE_USER]
				)
				SELECT
					S.[PLANT_ZONE],
					S.[WORKSHOP],
					S.[ASSEMBLY_LINE],
					S.[PLANT],
					S.[LOCATION],
					S.[PART_NO],
					S.[PART_NO] AS [INDENTIFY_PART_NO],
					S.[PART_CNAME],
					S.[PART_ENAME],
					S.[SUPPLIER_NUM],
					S.[DOCK],
					S.[INHOUSE_PART_CLASS] AS [BOX_PARTS],
					(A.[USAGE] * ISNULL(B.[INHOUSE_PACKAGE], 1)) AS [PACK_COUNT],
					S.[INBOUND_PACKAGE_MODEL],
					S.[INBOUND_PACKAGE],
					B.[PART_UNITS] AS [MEASURING_UNIT_NO],
					S.[DLOC] AS [RDC_DLOC],
					A.[RUNSHEET_NO] AS [CARD_NO],
					A.[SUPPLIER_NUM] AS [PART_SUPPLIER_NUM],
					0 AS [PROCESS_FLAG],
					GETDATE() AS [CREATE_DATE],
					'EPS CONSUME' AS [CREATE_USER]
				FROM [LES].[TT_EPS_TASK] A WITH (NOLOCK)
				INNER JOIN [LES].[TM_BAS_MAINTAIN_PARTS] B WITH (NOLOCK) ON A.[PLANT] = B.[PLANT] AND A.[PART_NO] = B.[PART_NO]
				INNER JOIN [LES].[TM_BAS_MAINTAIN_INHOUSE_LOGISTIC_STANDARD] D WITH (NOLOCK)
				ON D.[IS_TRIGGER_PULL] = 1 AND A.[PLANT] = D.[PLANT] AND A.[ASSEMBLY_LINE] = D.[ASSEMBLY_LINE] AND D.[INHOUSE_SYSTEM_MODE] = 'EPS'
				AND A.[PART_NO] = D.[PART_NO] AND A.[LOCATION] = D.[LOCATION] AND ISNULL(D.DELETE_FLAG,0) = 0
				INNER JOIN [LES].[TM_BAS_MAINTAIN_INHOUSE_LOGISTIC_STANDARD] S WITH (NOLOCK)
				ON S.[INHOUSE_SYSTEM_MODE] = 'TWD' AND D.[PART_NO] = S.[PART_NO] AND D.[ZONE_NO] = S.[PLANT_ZONE] AND ISNULL(S.DELETE_FLAG,0) = 0
				INNER JOIN [LES].[TM_TWD_BOX_PARTS] T WITH (NOLOCK)
				ON S.[PLANT] = T.[PLANT] AND S.[ASSEMBLY_LINE] = T.[ASSEMBLY_LINE] AND S.[INHOUSE_PART_CLASS] = T.[BOX_PARTS] AND S.[SUPPLIER_NUM] = T.[SUPPLIER_NUM]
				WHERE A.[TASK_SN] = @runsheetSN AND T.[PULL_MODE] <> 4
			END

		IF UPPER(@pullType) = 'PCS'
			BEGIN
				INSERT INTO [LES].[TE_TWD_MATERIAL_CONSUME_TEMP]
				(
					[PLANT_ZONE],
					[WORKSHOP],
					[ASSEMBLY_LINE],
					[PLANT],
					[LOCATION],
					[PART_NO],
					[INDENTIFY_PART_NO],
					[PART_CNAME],
					[PART_ENAME],
					[SUPPLIER_NUM],
					[DOCK],
					[BOX_PARTS],
					[PACK_COUNT],
					[INBOUND_PACKAGE_MODEL],
					[INBOUND_PACKAGE],
					[MEASURING_UNIT_NO],
					[RDC_DLOC],
					[CARD_NO],
					[PART_SUPPLIER_NUM],
					[PROCESS_FLAG],
					[CREATE_DATE],
					[CREATE_USER]
				)
				SELECT
					S.[PLANT_ZONE],
					S.[WORKSHOP],
					S.[ASSEMBLY_LINE],
					S.[PLANT],
					S.[LOCATION],
					S.[PART_NO],
					S.[PART_NO] AS [INDENTIFY_PART_NO],
					S.[PART_CNAME],
					S.[PART_ENAME],
					S.[SUPPLIER_NUM],
					S.[DOCK],
					S.[INHOUSE_PART_CLASS] AS [BOX_PARTS],
					A.[REQUIRED_INHOUSE_PACKAGE_QTY] AS [PACK_COUNT],
					S.[INBOUND_PACKAGE_MODEL],
					S.[INBOUND_PACKAGE],
					A.[MEASURING_UNIT_NO],
					S.[DLOC] AS [RDC_DLOC],
					B.[PCS_RUNSHEET_NO] AS [CARD_NO],
					A.[SUPPLIER_NUM] AS [PART_SUPPLIER_NUM],
					0 AS [PROCESS_FLAG],
					GETDATE() AS [CREATE_DATE],
					'PCS CONSUME' AS [CREATE_USER]
				FROM [LES].[TT_PCS_RUNSHEET_DETAIL] A WITH (NOLOCK)
				INNER JOIN [LES].[TT_PCS_RUNSHEET] B WITH (NOLOCK) ON A.[PCS_RUNSHEET_SN] = B.[PCS_RUNSHEET_SN]
				INNER JOIN [LES].[TM_BAS_MAINTAIN_INHOUSE_LOGISTIC_STANDARD] D WITH (NOLOCK)
				ON D.[IS_TRIGGER_PULL] = 1 AND A.[PLANT] = D.[PLANT] AND A.[ASSEMBLY_LINE] = D.[ASSEMBLY_LINE] AND D.[INHOUSE_SYSTEM_MODE] = 'PCS'
				AND A.[PART_NO] = D.[PART_NO] AND A.[BOX_PARTS] = D.[INHOUSE_PART_CLASS] AND A.[LOCATION] = D.[LOCATION] AND ISNULL(D.DELETE_FLAG,0) = 0
				INNER JOIN [LES].[TM_BAS_MAINTAIN_INHOUSE_LOGISTIC_STANDARD] S WITH (NOLOCK)
				ON S.[INHOUSE_SYSTEM_MODE] = 'TWD' AND D.[PART_NO] = S.[PART_NO] AND D.[ZONE_NO] = S.[PLANT_ZONE] AND ISNULL(S.DELETE_FLAG,0) = 0
				INNER JOIN [LES].[TM_TWD_BOX_PARTS] T WITH (NOLOCK)
				ON S.[PLANT] = T.[PLANT] AND S.[ASSEMBLY_LINE] = T.[ASSEMBLY_LINE] AND S.[INHOUSE_PART_CLASS] = T.[BOX_PARTS] AND S.[SUPPLIER_NUM] = T.[SUPPLIER_NUM]
				WHERE A.[PCS_RUNSHEET_SN] = @runsheetSN AND T.[PULL_MODE] <> 4
			END

		IF UPPER(@pullType) = 'SPS'
			BEGIN
				INSERT INTO [LES].[TE_TWD_MATERIAL_CONSUME_TEMP]
				(
					[PLANT_ZONE],
					[WORKSHOP],
					[ASSEMBLY_LINE],
					[PLANT],
					[LOCATION],
					[PART_NO],
					[INDENTIFY_PART_NO],
					[PART_CNAME],
					[PART_ENAME],
					[SUPPLIER_NUM],
					[DOCK],
					[BOX_PARTS],
					[PACK_COUNT],
					[INBOUND_PACKAGE_MODEL],
					[INBOUND_PACKAGE],
					[MEASURING_UNIT_NO],
					[RDC_DLOC],
					[CARD_NO],
					[PART_SUPPLIER_NUM],
					[PROCESS_FLAG],
					[CREATE_DATE],
					[CREATE_USER]
				)
				SELECT
					S.[PLANT_ZONE],
					S.[WORKSHOP],
					S.[ASSEMBLY_LINE],
					S.[PLANT],
					S.[LOCATION],
					S.[PART_NO],
					S.[PART_NO] AS [INDENTIFY_PART_NO],
					S.[PART_CNAME],
					S.[PART_ENAME],
					S.[SUPPLIER_NUM],
					S.[DOCK],
					S.[INHOUSE_PART_CLASS] AS [BOX_PARTS],
					A.[REQUIRED_INBOUND_PACKAGE_QTY] AS [PACK_COUNT],
					S.[INBOUND_PACKAGE_MODEL],
					S.[INBOUND_PACKAGE],
					A.[MEASURING_UNIT_NO],
					S.[DLOC] AS [RDC_DLOC],
					B.[SPS_RUNSHEET_NO] AS [CARD_NO],
					A.[SUPPLIER_NUM] AS [PART_SUPPLIER_NUM],
					0 AS [PROCESS_FLAG],
					GETDATE() AS [CREATE_DATE],
					'TWD CONSUME' AS [CREATE_USER]
				FROM [LES].[TT_SPS_RUNSHEET_DETAIL] A WITH (NOLOCK)
				INNER JOIN [LES].[TT_SPS_RUNSHEET] B WITH (NOLOCK) ON A.[SPS_RUNSHEET_SN] = B.[SPS_RUNSHEET_SN]
				INNER JOIN [LES].[TM_BAS_MAINTAIN_INHOUSE_LOGISTIC_STANDARD] D WITH (NOLOCK)
				ON D.[IS_TRIGGER_PULL] = 1 AND A.[PLANT] = D.[PLANT] AND A.[ASSEMBLY_LINE] = D.[ASSEMBLY_LINE]
				AND D.[INHOUSE_SYSTEM_MODE] = 'SPS' AND A.[PART_NO] = D.[PART_NO] AND A.[BOX_PARTS] = D.[INHOUSE_PART_CLASS] AND ISNULL(D.DELETE_FLAG,0) = 0
				INNER JOIN [LES].[TM_BAS_MAINTAIN_INHOUSE_LOGISTIC_STANDARD] S WITH (NOLOCK)
				ON S.[INHOUSE_SYSTEM_MODE] = 'TWD' AND D.[PART_NO] = S.[PART_NO] AND D.[ZONE_NO] = S.[PLANT_ZONE] AND ISNULL(S.DELETE_FLAG,0) = 0
				INNER JOIN [LES].[TM_TWD_BOX_PARTS] T WITH (NOLOCK)
				ON S.[PLANT] = T.[PLANT] AND S.[ASSEMBLY_LINE] = T.[ASSEMBLY_LINE] AND S.[INHOUSE_PART_CLASS] = T.[BOX_PARTS] AND S.[SUPPLIER_NUM] = T.[SUPPLIER_NUM]
				WHERE A.[SPS_RUNSHEET_SN] = @runsheetSN
			END

		COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		--出错，则返回执行不成功，回滚事务
		ROLLBACK TRANSACTION
		--记录错误信息
		INSERT INTO [LES].[TS_SYS_EXCEPTION] ([TIME_STAMP], [APPLICATION], [METHOD], [CLASS], [EXCEPTION_MESSAGE], [ERROR_CODE])
		SELECT GETDATE(), 'TWD', '[LES].[PROC_TWD_GEN_TWICEPULL_DATA]', 'Procedure', ERROR_MESSAGE(), ERROR_LINE()
	END CATCH
END