

CREATE Procedure [LES].[PROC_TOOL_DeleteOrderInfo]
(
   @VBELN as nvarchar(12)
)
AS 
Begin Transaction Tran_DeleteOrderInfo
Begin Try
--删除订单及相关联的表，例如删除订单号码4600000183的订单
--接收订单接口表
--Select * from [LES].[TI_SPM_DELIVERY_RUNSHEET_IN] WITH(NOLOCK) Where VBELN=@VBELN

Delete [LES].[TI_SPM_DELIVERY_RUNSHEET_IN] Where VBELN=@VBELN

--计划送货单
--Select * from LES.TT_SPM_DELIVERY_RUNSHEET WITH(NOLOCK) Where PLAN_RUNSHEET_NO=@VBELN

Delete LES.TT_SPM_DELIVERY_RUNSHEET Where PLAN_RUNSHEET_NO=@VBELN

 --计划送货单明细
--Select * from LES.TT_SPM_DELIVERY_RUNSHEET_DETAIL WITH(NOLOCK)
--Where PLAN_RUNSHEET_SN=(Select TOP 1 PLAN_RUNSHEET_SN 
--                          From LES.TT_SPM_DELIVERY_RUNSHEET 
--						 Where PLAN_RUNSHEET_NO=@VBELN)

Delete LES.TT_SPM_DELIVERY_RUNSHEET_DETAIL 
Where PLAN_RUNSHEET_SN=(Select TOP 1 PLAN_RUNSHEET_SN from LES.TT_SPM_DELIVERY_RUNSHEET Where PLAN_RUNSHEET_NO=@VBELN)

--删除BARCode
--Select * from LES.TT_SPM_DELIVERY_RUNSHEET_BARCODE WITH(NOLOCK)
--Where PLAN_ASN_RUNSHEET_NO=@VBELN

Delete LES.TT_SPM_DELIVERY_RUNSHEET_BARCODE
Where PLAN_ASN_RUNSHEET_NO=@VBELN


--收货单表
--Select * from LES.TT_WMM_RECEIVE WITH(NOLOCK)
--WHERE RECEIVE_NO=@VBELN

Delete LES.TT_WMM_RECEIVE WHERE RECEIVE_NO=@VBELN


--收货单明细表
--Select * from LES.TT_WMM_RECEIVE_DETAIL WITH(NOLOCK)
--Where RECEIVE_ID=(Select TOP 1 RECEIVE_ID From LES.TT_WMM_RECEIVE WHERE RECEIVE_NO=@VBELN)

Delete LES.TT_WMM_RECEIVE_DETAIL
Where RECEIVE_ID=(Select TOP 1 RECEIVE_ID From LES.TT_WMM_RECEIVE WHERE RECEIVE_NO=@VBELN)


--每次提交批次表LOG（张恒添加）
--Select * from LES.TT_WMM_RECEIVE_DETAIL_LOG WITH(NOLOCK)
--Where RECEIVE_NO=@VBELN

Delete LES.TT_WMM_RECEIVE_DETAIL_LOG
Where RECEIVE_NO=@VBELN


--通知SAP接口表，由每次提交批次表生成
--Select * from LES.TI_WMS_RECIVE_OUT WITH(NOLOCK)
--Where VBELN=@VBELN

Delete LES.TI_WMS_RECIVE_OUT
Where VBELN=@VBELN


--提交后进入此表，修改状态,整理库存访问此表
--Select *  from  LES.TM_WMM_TRAN_DETAILS WITH(NOLOCK)
--Where TRAN_NO=@VBELN

Delete LES.TM_WMM_TRAN_DETAILS
 Where TRAN_NO=@VBELN


--提交操作日志表
--Select * From  LES.TM_WMM_TRAN_DETAILS_LOG WITH(NOLOCK)
--Where TRAN_NO=@VBELN

Delete LES.TM_WMM_TRAN_DETAILS_LOG
 Where TRAN_NO=@VBELN


 Commit Transaction Tran_DeleteOrderInfo
 Print('执行成功！')
End Try
Begin Catch
   Rollback Transaction Tran_DeleteOrderInfo
   Print('Error Message:' + error_message())
   Print('执行失败！')
End Catch