
/********************************************************************/
/*                                                                  */
/*   Project Name:  Production Pull System                          */
/*   Program Name:  PROC_BAS_INHOUSE_INTERFACE_CREATE_UPDATE             */
/*   Called By:     by the Page							*/
/*   Purpose:       This is the main stored procedure for the       */
/*   author:       wangchanghong	2011-06-20   				       */
/********************************************************************/
CREATE PROCEDURE [LES].[PROC_BAS_INHOUSE_INTERFACE_CREATE_UPDATE]
 
AS

BEGIN

  UPDATE [LES].[TI_BAS_INHOUSE_LOGISTIC_STANDARD]
   SET  [PLANT] = TE.[PLANT]
      ,[ASSEMBLY_LINE] = TE.[ASSEMBLY_LINE]
      ,[PLANT_ZONE] = TE.[PLANT_ZONE]
      ,[WORKSHOP] = TE.[WORKSHOP]
      ,[SUPPLIER_NUM] = TE.[SUPPLIER_NUM]
      ,[TRANS_SUPPLIER_NUM] = TE.[TRANS_SUPPLIER_NUM]
      ,[MODEL] = TE.[MODEL]
      ,[PART_NO] = TE.[PART_NO]
      ,[COLOR_DEPARTMENT] =TE.[COLOR_DEPARTMENT]
      ,[HAND_KEPT_RECORD] = TE.[HAND_KEPT_RECORD]
      ,[COLOR_CONTROL_PATCH] = TE.[COLOR_CONTROL_PATCH]
      ,[VWS] = TE.[VWS]
      ,[MODEL_YEAR] = TE.[MODEL_YEAR]
      ,[PART_CNAME] = TE.[PART_CNAME]
      ,[PART_ENAME] = TE.[PART_ENAME]
      --,[PART_NICKNAME] = TE.[PART_NICKNAME]
      ,[VALID_FLAG] = TE.[VALID_FLAG]
      ,[WORKSHOP_SECTION] = TE.[WORKSHOP_SECTION]
      ,[LOCATION] = TE.[LOCATION]
      ,[IN_PLANT_LOGISTIC_MODE] = TE.[IN_PLANT_LOGISTIC_MODE]
      ,[IN_PLANT_SYSTEM_MODE] = TE.[IN_PLANT_SYSTEM_MODE]
      ,[IN_PLANT_LOGISTIC_PART_CLASS] = TE.[IN_PLANT_LOGISTIC_PART_CLASS]
      ,[INHOUSE_MODE] = TE.[INHOUSE_MODE]
      ,[INHOUSE_SYSTEM_MODE] = TE.[INHOUSE_SYSTEM_MODE]
      ,[INHOUSE_PART_CLASS] =TE.[INHOUSE_PART_CLASS]
      ,[DOCK] = TE.[DOCK]
      ,[INHOUSE_PACKAGE_MODEL] = TE.[INHOUSE_PACKAGE_MODEL]
      ,[INHOUSE_PACKAGE] = TE.[INHOUSE_PACKAGE]
      ,[START_EFFECTIVE_DATE] = TE.[START_EFFECTIVE_DATE]
      ,[PLATFORM_CHANGE_DATE] =TE.[PLATFORM_CHANGE_DATE]
      ,[LOGICAL_PK] = TE.[LOGICAL_PK]
      ,[DELETE_FLAG] = TE.[DELETE_FLAG]
      --,[DIFF_FLAG] = TE.[DIFF_FLAG]
      --,[STORAGE_LOCATION] = TE.[STORAGE_LOCATION]
      --,[SEQUENCE_NO] =TE.[SEQUENCE_NO]
      ,[EXPIRE_DATE] = TE.[EXPIRE_DATE]
      ,[IS_ACTIVE] = TE.[IS_ACTIVE]
      ,[REQUIREMENT_FLAG] = TE.[REQUIREMENT_FLAG]
      ,[ASSEMBLY_FLAG] = TE.[ASSEMBLY_FLAG]
      ,[ASSEMBLY_FLAG_RECRUIT] = TE.[ASSEMBLY_FLAG_RECRUIT]
      ,[PURCHASE_STYLE] = NULL
      ,[ZP_FLAG] = TE.[ZP_FLAG]
      ,[COMMENTS] = TE.[COMMENTS]
      ,[CREATE_USER] = TE.[CREATE_USER]
      ,[CREATE_DATE] = TE.[CREATE_DATE]
      ,[UPDATE_USER] = TE.[CREATE_USER]
      ,[UPDATE_DATE] = TE.[CREATE_DATE]
      ,[HAND_KEP_VWS] = TE.[HAND_KEP_VWS]
      ,[LOAD_FLAG] = TE.[LOAD_FLAG]
      ,[IS_SPLIT_LOCATION] = TE.[IS_SPLIT_LOCATION]

--SELECT *
 
FROM LES.TE_BAS_TEMP_INHOUSE_LOGISTIC_STANDARD AS TE,
     [LES].[TI_BAS_INHOUSE_LOGISTIC_STANDARD] AS TM
 WHERE TE.LOGICAL_PK = TM.LOGICAL_PK   

INSERT INTO [LES].[TI_BAS_INHOUSE_LOGISTIC_STANDARD]
           ([PLANT],[ASSEMBLY_LINE],[PLANT_ZONE],[WORKSHOP]
           ,[SUPPLIER_NUM],[TRANS_SUPPLIER_NUM],[MODEL],[PART_NO]
           ,[COLOR_DEPARTMENT],[HAND_KEPT_RECORD],[COLOR_CONTROL_PATCH],[VWS]
           ,[MODEL_YEAR],[PART_CNAME],[PART_ENAME]
           ,[VALID_FLAG],[WORKSHOP_SECTION],[LOCATION],[IN_PLANT_LOGISTIC_MODE]
           ,[IN_PLANT_SYSTEM_MODE],[IN_PLANT_LOGISTIC_PART_CLASS]
           ,[INHOUSE_MODE],[INHOUSE_SYSTEM_MODE],[INHOUSE_PART_CLASS],[DOCK]
           ,[INHOUSE_PACKAGE_MODEL],[INHOUSE_PACKAGE],[START_EFFECTIVE_DATE],[PLATFORM_CHANGE_DATE]
           ,[LOGICAL_PK],[DELETE_FLAG]
           ,[EXPIRE_DATE],[IS_ACTIVE],[REQUIREMENT_FLAG]
           ,[ASSEMBLY_FLAG],[ASSEMBLY_FLAG_RECRUIT],[PURCHASE_STYLE],[ZP_FLAG]
           ,[COMMENTS]
           ,[CREATE_USER],[CREATE_DATE],[UPDATE_USER],[UPDATE_DATE]
           ,[HAND_KEP_VWS],[LOAD_FLAG],[IS_SPLIT_LOCATION])
SELECT		TE.[PLANT],TE.[ASSEMBLY_LINE],TE.[PLANT_ZONE],TE.[WORKSHOP]
           ,TE.[SUPPLIER_NUM],TE.[TRANS_SUPPLIER_NUM],TE.[MODEL],TE.[PART_NO]
           ,TE.[COLOR_DEPARTMENT],TE.[HAND_KEPT_RECORD],TE.[COLOR_CONTROL_PATCH],TE.[VWS]
           ,TE.[MODEL_YEAR],TE.[PART_CNAME],TE.[PART_ENAME]
           ,TE.[VALID_FLAG],TE.[WORKSHOP_SECTION],TE.[LOCATION],TE.[IN_PLANT_LOGISTIC_MODE]
           ,TE.[IN_PLANT_SYSTEM_MODE],TE.[IN_PLANT_LOGISTIC_PART_CLASS]
           ,TE.[INHOUSE_MODE],TE.[INHOUSE_SYSTEM_MODE],TE.[INHOUSE_PART_CLASS],TE.[DOCK]
           ,TE.[INHOUSE_PACKAGE_MODEL],TE.[INHOUSE_PACKAGE],TE.[START_EFFECTIVE_DATE],TE.[PLATFORM_CHANGE_DATE]
           ,TE.[LOGICAL_PK],TE.[DELETE_FLAG]
           ,TE.[EXPIRE_DATE],TE.[IS_ACTIVE],TE.[REQUIREMENT_FLAG]
           ,TE.[ASSEMBLY_FLAG],TE.[ASSEMBLY_FLAG_RECRUIT],TE.[PURCHASE_STYLE],TE.[ZP_FLAG]
           ,TE.[COMMENTS]
           ,TE.[CREATE_USER],TE.[CREATE_DATE],TE.[CREATE_USER],TE.[CREATE_DATE]
           ,TE.[HAND_KEP_VWS],TE.[LOAD_FLAG],TE.[IS_SPLIT_LOCATION]

  FROM [LES].[TE_BAS_TEMP_INHOUSE_LOGISTIC_STANDARD] AS TE          
  LEFT JOIN  LES.[TI_BAS_INHOUSE_LOGISTIC_STANDARD] AS TM  ON  TE.LOGICAL_PK = TM.LOGICAL_PK
  WHERE   TE.VALID_FLAG = 1 AND TM.LOGICAL_PK IS NULL     
  

  
	
END