
/********************************************************************/
/*   Project Name:  TWD						                        */
/*   Program Name:  [PROC_TWD_GEN_PACKING_SHEE]                     */
/*   Called By:     界面												*/
/*    Author:        Caodaowei										*/
/********************************************************************/
CREATE PROCEDURE [LES].[PROC_TWD_GEN_PACKING_SHEET]
(
	@PLANT			NVARCHAR(30),
	@RECEIVED_DATE_START			DATETIME,
	@RECEIVED_DATE_END			DATETIME,
	@SUPPLIER_NUM			NVARCHAR(8),
	@CREATE_USER NVARCHAR(100)
)
AS
--创建临时表
CREATE TABLE #TEMP_TWD_RECEIVED_GOODS_FOR_RECORD_RECKONING(
	[INTERFACE_ID] [int] IDENTITY(1,1) NOT NULL,
	[PLANT] [nvarchar](5) NOT NULL,
	[ASN_NO] [nvarchar](50) NULL,
	[INTERFACE_STATUS] [int] NULL,
	[PART_NO] [nvarchar](20) NOT NULL,
	[PART_CNAME] [nvarchar](100) NULL,
	[PART_ENAME] [nvarchar](100) NULL,
	[SUPPLIER_NUM] [nvarchar](12) NULL,
	[INTERFACE_TYPE] [nvarchar](40) NULL,
	[MEASURING_UNIT_NO] [nvarchar](1) NULL,
	[REQUIRED_INBOUND_PACKAGE] [INT] NULL,
	[REQUIRED_INBOUND_PACKAGE_QTY] [int]  NULL,
	[WAREHOUSE_NAME] [varchar](30) NULL,
	[RECEIVE_QTY] [int] NULL,
	[WMSID] [nvarchar](max) NULL,
	[ORDER_NO] [nvarchar](10) NULL,
	[ITEM_NO] [nvarchar](10) NULL,
	[COMMENTS] [nvarchar](200) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[UPDATE_USER] [nvarchar](50) NULL,
	[CREATE_DATE] [datetime] NULL,
	[CREATE_USER] [nvarchar](50) NULL,
	[WMSID_SET] [nvarchar] (max) NULL,
	[RUNSHEET_NO_SET] [nvarchar](max) NULL,
	INBOUND_PACKAGE_MODEL  [nvarchar](50) NULL,
	[PLACE_OF_DELIVERY]  [nvarchar](100) NULL,
	[PACK_COUNT_MODEL] [INT] NULL,
	[REQUIRED_BOX_COUNT] [INT] NULL,
	[EXPECTED_ARRIVAL_TIME] [DATETIME]
	)
	
--把要生成送货单的零件导入到临时表
INSERT INTO #TEMP_TWD_RECEIVED_GOODS_FOR_RECORD_RECKONING
 SELECT 
 A.PLANT,
 NULL,
 NULL,
 A.PART_NO,
 MAX(ISNULL(A.PART_CNAME,'')),
 MAX(ISNULL(A.PART_ENAME,'')),
 A.SUPPLIER_NUM,
 NULL,
 MAX(ISNULL(A.MEASURING_UNIT_NO,'1')),
 MAX(ISNULL(A.ACTUAL_INBOUND_PACKAGE,'')),
 SUM(ISNULL(A.RECEIVE_QTY,0)) ,
 ISNULL(A.WAREHOUSE,''),
 SUM(ISNULL(A.RECEIVE_QTY,0)) ,
 MAX(ISNULL(A.WMSID,0)),
 A.ORDER_NO,
 A.ITEM_NO,
 NULL,
 NULL,
 NULL,
 GETDATE(),
 NULL,
 LES.Func_Get_TWD_WMSID(A.PLANT, A.SUPPLIER_NUM, A.ORDER_NO, A.ITEM_NO, A.WAREHOUSE, A.PART_NO, MAX(A.CREATE_DATE)),
 LES.Func_Get_TWD_RUNSHEET_NO(A.PLANT, A.SUPPLIER_NUM, A.ORDER_NO, A.ITEM_NO, A.WAREHOUSE, A.PART_NO, MAX(A.CREATE_DATE))
 ,MAX(INBOUND_PACKAGE_MODEL)
 ,MAX(B.PLACE_OF_DELIVERY)
 ,MAX(A.PACK_COUNT)
 ,COUNT(1)
 ,MAX([EXPECTED_ARRIVAL_TIME])
 FROM LES.TI_TWD_RECEIVED_GOODS_FOR_RECORD A
 JOIN LES.TM_TWD_BOX_PARTS B ON A.RECEIVED_DATE>=@RECEIVED_DATE_START AND A.RECEIVED_DATE<=@RECEIVED_DATE_END
	 AND (A.INTERFACE_STATUS IS NULL OR A.INTERFACE_STATUS=0)
	 AND A.PLANT=@PLANT
	 AND A.SUPPLIER_NUM=@SUPPLIER_NUM
	 AND A.PLANT = B.PLANT
	 AND A.SUPPLIER_NUM = B.SUPPLIER_NUM
	 AND A.BOX_PARTS = B.BOX_PARTS
 GROUP BY A.PLANT,A.SUPPLIER_NUM,A.ORDER_NO,A.ITEM_NO,A.WAREHOUSE,A.PART_NO

DECLARE @INTERFACE_ID int
DECLARE @Sequence int
DECLARE @SUPPLIER_TRANS nvarchar(100)
DECLARE @ORDER_NO nvarchar(10)
SET @INTERFACE_ID=0
DECLARE	@result int = 0
DECLARE @WAREHOUSE nvarchar(40)
DECLARE @RUNSHEET_NO_SET_Tmp NVARCHAR(2000)
DECLARE @DELIVERY_ORDER NVARCHAR(15)
DECLARE @PLACE_OF_DELIVERY NVARCHAR(200),
		@RunSheetNo	VARCHAR(10),
		@Year VARCHAR(1) = CONVERT(VARCHAR(1), DATEPART(YEAR, GETDATE()) % 10)

set xact_abort on
begin try
Begin Transaction 

--判断是否还有未结算的明细	
    SET @INTERFACE_ID=-1
	SELECT @INTERFACE_ID=INTERFACE_ID FROM #TEMP_TWD_RECEIVED_GOODS_FOR_RECORD_RECKONING WHERE COMMENTS  IS NULL
	SELECT @SUPPLIER_TRANS = PARAMETER_VALUE FROM LES.TS_SYS_CONFIG WHERE PARAMETER_NAME = 'SUPPLIER_TRANS_TWD'

--循环临时表，10个零件生成一张送货单
WHILE(@INTERFACE_ID <>-1)
BEGIN
	--TWD_RUNSHEET_NO 的规则是 S+两位工厂（78）+一位年份(4)+六位流水号（123456）
	EXEC @Sequence = [LES].[PROC_TWD_GET_NEXT_SEQUENCE] 'TWD_GEN_PACKING_RUNSHEET_NO'
	SET @RunSheetNo = 'S' + @PLANT + @Year + RIGHT('000000' + CONVERT(VARCHAR(10), @Sequence), 6)


	--print @result
	EXEC  @Sequence = [LES].[PROC_JIS_GET_NEXT_SEQUENCE] 'JIS_RECKONING_SHEET' --这里需要采用TWD的SEQUENCE]

	EXEC [LES].[PROC_TWD_GET_NEXT_RECKONING_SEQUENCE] @SUPPLIER_NUM,@DELIVERY_ORDER output
	
	--插入最大10条明细, 由于不同订单不能在一个送货单上，有的送货单会有不足10条的记录
	SELECT TOP 1 @ORDER_NO = ORDER_NO, @WAREHOUSE = ISNULL(WAREHOUSE_NAME,''), @PLACE_OF_DELIVERY = PLACE_OF_DELIVERY
	FROM #TEMP_TWD_RECEIVED_GOODS_FOR_RECORD_RECKONING
	WHERE COMMENTS  IS NULL
	ORDER BY INTERFACE_ID

	
	--插入送货单主表
	INSERT INTO LES.TT_TWD_RECKONING_SHEETS
        ( RECKONING_SN ,
          TWD_RUNSHEET_SN ,
          RECKONING_NO ,
          DELIVERY_ORDER ,
          ORDER_NO ,
          RECEIVE_LOCATION ,
          SUPPLIER_NUM ,
          SUPPLIER_TRANS ,
          WMS_SEND_STATUS ,
          TRANS_TYPE ,
          WMS_SEND_TIME ,
          UNLOAD_PLACE ,
          LOAD_PLACE ,
          PULL_TYPE ,
          PULL_DETAIL ,
          RECEIVED_DATE ,
          SUPPLY_STATUS ,
          SUPPLY_CONFIRM_DATE ,
          FIRST_CONFIRM_STATUS ,
          FIRST_CONFIRM_DATE ,
          SECOND_CONFIRM_STATUS ,
          SECOND_CONFIRM_DATE ,
          COMMENTS ,
          UPDATE_DATE ,
          UPDATE_USER ,
          CREATE_DATE ,
          CREATE_USER ,
          PACKAGE_TYPE ,
          WHAREHOUSE ,
          INVOICENO ,
          REC_STATUS ,
          EXPECTED_ARRIVAL_TIME ,
          SEND_TIME ,
          SEND_STATUS ,
          TWD_RUNSHEET_NO ,
          PLANT ,
          ACTUAL_ARRIVAL_TIME
        )
VALUES  ( @Sequence , -- RECKONING_SN - int
          0 , -- TWD_RUNSHEET_SN - int
          @PLANT + RIGHT(CONVERT(varchar(4) , getdate(), 112 ),2) +@SUPPLIER_NUM+ SUBSTRING('000000' + CONVERT(NVARCHAR, @Sequence), LEN(CONVERT(NVARCHAR, @Sequence))+1 , 6) ,
          @DELIVERY_ORDER  , 
          @ORDER_NO , -- ORDER_NO - nvarchar(30)
          NULL , -- RECEIVE_LOCATION - nvarchar(30)
          @SUPPLIER_NUM,  -- SUPPLIER_NUM - nvarchar(8)
          @SUPPLIER_TRANS , -- SUPPLIER_TRANS - nvarchar(100)
          1 , -- WMS_SEND_STATUS - int
          N'按收货时间生成送货单' , -- TRANS_TYPE - nvarchar(30)
          NULL , -- WMS_SEND_TIME - datetime
          @PLACE_OF_DELIVERY , -- UNLOAD_PLACE - nvarchar(50)
          @WAREHOUSE , -- LOAD_PLACE - nvarchar(50)
          N'3' , -- PULL_TYPE - nvarchar(10)
          NULL , -- PULL_DETAIL - nvarchar(2000)
          NULL , -- RECEIVED_DATE - datetime
          0 , -- SUPPLY_STATUS - int
          NULL , -- SUPPLY_CONFIRM_DATE - datetime
          0 , -- FIRST_CONFIRM_STATUS - int
          NULL , -- FIRST_CONFIRM_DATE - datetime
          0 , -- SECOND_CONFIRM_STATUS - int
          NULL , -- SECOND_CONFIRM_DATE - datetime
          N'' , -- COMMENTS - nvarchar(200)
          NULL , -- UPDATE_DATE - datetime
          NULL , -- UPDATE_USER - nvarchar(50)
          GETDATE() , -- CREATE_DATE - datetime
          @CREATE_USER , -- CREATE_USER - nvarchar(50)
          NULL , -- PACKAGE_TYPE - nvarchar(100)
          @WAREHOUSE , -- WHAREHOUSE - nvarchar(100)
          NULL, -- INVOICENO - nvarchar(30)
          0 , -- REC_STATUS - int
          (
			  SELECT MAX([EXPECTED_ARRIVAL_TIME])
			  FROM
			  (
				  SELECT TOP 10 [EXPECTED_ARRIVAL_TIME]
				  FROM	#TEMP_TWD_RECEIVED_GOODS_FOR_RECORD_RECKONING T
				  WHERE	T.COMMENTS  IS NULL
					  AND ISNULL(@ORDER_NO,'') = ISNULL(T.ORDER_NO,'')
					  AND ISNULL(T.WAREHOUSE_NAME,'')=@WAREHOUSE 
				  ORDER BY T.INTERFACE_ID
			  ) A
		  ) , -- EXPECTED_ARRIVAL_TIME - datetime
          NULL , -- SEND_TIME - datetime
          0 , -- SEND_STATUS - int
          @RunSheetNo , -- TWD_RUNSHEET_NO - varchar(22)
          @PLANT , -- PLANT - nvarchar(5)
          NULL  -- ACTUAL_ARRIVAL_TIME - datetime
        )

	SET @RUNSHEET_NO_SET_Tmp=''
	--更新10条明细已结算
	if @ORDER_NO is null
	begin
		INSERT	INTO LES.TT_TWD_RECKONING_SHEETS_DETAIL
			    (RECKONING_SN,PLANT,ASSEMBLY_LINE,SUPPLIER_NUM,PART_NO,ITEM_NO,
			    IDENTIFY_PART_NO,PART_CNAME,PART_ENAME,DOCK,BOX_PARTS,SEQUENCE_NO,PICKUP_SEQ_NO,
			    RDC_DLOC,INHOUSE_PACKAGE,MEASURING_UNIT_NO,INBOUND_PACKAGE_MODEL,PACK_COUNT,
			    REQUIRED_INBOUND_PACKAGE,REQUIRED_INBOUND_PACKAGE_QTY,TWD_RUNSHEET_SN,
			    ACTUAL_INBOUND_PACKAGE_QTY,ORDER_NO,TWD_RUNSHEET_NO,INBOUND_PACKAGE_NAME,COMMENTS)
		SELECT	TOP 10 @Sequence, T.PLANT, '', T.SUPPLIER_NUM, T.PART_NO, T.ITEM_NO, 
				NULL, T.PART_CNAME,T.PART_ENAME,'','',NULL,NULL,
				NULL,PACK_COUNT_MODEL,MEASURING_UNIT_NO,INBOUND_PACKAGE_MODEL,PACK_COUNT_MODEL,
				REQUIRED_BOX_COUNT,REQUIRED_INBOUND_PACKAGE_QTY,0,
				RECEIVE_QTY,ORDER_NO,@RunSheetNo,WAREHOUSE_NAME,COMMENTS
		FROM	#TEMP_TWD_RECEIVED_GOODS_FOR_RECORD_RECKONING T
		WHERE	T.COMMENTS  IS NULL
		AND		T.ORDER_NO is null
		AND     ISNULL(T.WAREHOUSE_NAME,'')=@WAREHOUSE 
		ORDER BY T.INTERFACE_ID

		SELECT  @RUNSHEET_NO_SET_Tmp=(SELECT DISTINCT PULL_SHEET_NO+','
		FROM LES.TI_TWD_RECEIVED_GOODS_FOR_RECORD T WITH(NOLOCK)
		WHERE RECEIVED_DATE>=@RECEIVED_DATE_START AND RECEIVED_DATE<=@RECEIVED_DATE_END
			 AND (INTERFACE_STATUS IS NULL OR INTERFACE_STATUS=0)
			 AND PLANT=@PLANT AND SUPPLIER_NUM=@SUPPLIER_NUM
			 AND PART_NO IN (SELECT	TOP 10 PART_NO FROM	#TEMP_TWD_RECEIVED_GOODS_FOR_RECORD_RECKONING T
								WHERE	T.COMMENTS  IS NULL
								AND		T.ORDER_NO is null
								AND     ISNULL(T.WAREHOUSE_NAME,'')=@WAREHOUSE 
								ORDER BY T.INTERFACE_ID) 
		FOR XML PATH(''))


		--把包装明细插入到包装明细表中
	INSERT INTO [LES].[TT_TWD_RUNSHEET_PACKAGE_DETAIL]
           ([TWD_RUNSHEET_SN]
           ,[RECKONING_SN]
           ,[PLANT]
           ,[ASSEMBLY_LINE]
           ,[SUPPLIER_NUM]
           ,[INBOUND_PACKAGE_MODEL]
           ,[RDC_DLOC]
           ,[INBOUND_PACKAGE]
           ,[MEASURING_UNIT_NO]
           ,[PACK_COUNT]
           ,[REQUIRED_INBOUND_PACKAGE]
           ,[REQUIRED_INBOUND_PACKAGE_QTY]
		   ,TWD_RUNSHEET_NO)
		   SELECT [TWD_RUNSHEET_SN]
			  ,A.[RECKONING_SN]
			  ,A.[PLANT]
			  ,A.[ASSEMBLY_LINE]
			  ,A.[SUPPLIER_NUM]
			  ,A.[INBOUND_PACKAGE_MODEL]
			  ,B.[INHOUSE_PACKAGE_MODEL_NAME]
			  ,A.[INHOUSE_PACKAGE]
			  ,A.[MEASURING_UNIT_NO]
			  ,A.[PACK_COUNT]
			  ,A.[REQUIRED_INBOUND_PACKAGE]
			  ,A.[REQUIRED_INBOUND_PACKAGE_QTY]
			  ,@RunSheetNo
		  FROM [LES].[TT_TWD_RECKONING_SHEETS_DETAIL] A 
		  left join [LES].[TT_TWD_PACKAGE_MODEL] B ON A.[INBOUND_PACKAGE_MODEL]=B.[INHOUSE_PACKAGE_MODEL]
		  where [RECKONING_SN]=@Sequence

	--更新送货单号 add by caodaowei on 20141105
	UPDATE  LES.TI_TWD_RECEIVED_GOODS_FOR_RECORD
	SET COMMENTS=@DELIVERY_ORDER
	WHERE RECEIVED_DATE>=@RECEIVED_DATE_START AND RECEIVED_DATE<=@RECEIVED_DATE_END
	AND (INTERFACE_STATUS IS NULL OR INTERFACE_STATUS=0)
	AND PLANT=@PLANT AND SUPPLIER_NUM=@SUPPLIER_NUM
	AND PART_NO IN (SELECT	TOP 10 PART_NO FROM	#TEMP_TWD_RECEIVED_GOODS_FOR_RECORD_RECKONING T
								WHERE	T.COMMENTS  IS NULL
								AND		T.ORDER_NO is null
								AND     ISNULL(T.WAREHOUSE_NAME,'')=@WAREHOUSE 
								ORDER BY T.INTERFACE_ID)

		UPDATE	#TEMP_TWD_RECEIVED_GOODS_FOR_RECORD_RECKONING SET COMMENTS = 'TEMP'
		WHERE INTERFACE_ID IN(SELECT TOP 10 INTERFACE_ID  FROM #TEMP_TWD_RECEIVED_GOODS_FOR_RECORD_RECKONING
		WHERE	COMMENTS  IS NULL
		AND		ORDER_NO is null
		AND     ISNULL(WAREHOUSE_NAME,'')=@WAREHOUSE 
		ORDER BY INTERFACE_ID	
	)
	end
	else
	begin
		INSERT	INTO LES.TT_TWD_RECKONING_SHEETS_DETAIL
			    (RECKONING_SN,PLANT,ASSEMBLY_LINE,SUPPLIER_NUM,PART_NO,ITEM_NO,
			    IDENTIFY_PART_NO,PART_CNAME,PART_ENAME,DOCK,BOX_PARTS,SEQUENCE_NO,PICKUP_SEQ_NO,
			    RDC_DLOC,INHOUSE_PACKAGE,MEASURING_UNIT_NO,INBOUND_PACKAGE_MODEL,PACK_COUNT,
			    REQUIRED_INBOUND_PACKAGE,REQUIRED_INBOUND_PACKAGE_QTY,TWD_RUNSHEET_SN,
			    ACTUAL_INBOUND_PACKAGE_QTY,ORDER_NO,TWD_RUNSHEET_NO,INBOUND_PACKAGE_NAME,COMMENTS)
		SELECT	TOP 10 @Sequence, T.PLANT, '', T.SUPPLIER_NUM, T.PART_NO, T.ITEM_NO, 
				NULL, T.PART_CNAME,T.PART_ENAME,'','',NULL,NULL,
				NULL,T.PACK_COUNT_MODEL,MEASURING_UNIT_NO,INBOUND_PACKAGE_MODEL,T.PACK_COUNT_MODEL,
				T.REQUIRED_BOX_COUNT,REQUIRED_INBOUND_PACKAGE_QTY,0,
				RECEIVE_QTY,ORDER_NO,@RunSheetNo,WAREHOUSE_NAME,COMMENTS
		FROM	#TEMP_TWD_RECEIVED_GOODS_FOR_RECORD_RECKONING T
		WHERE	T.COMMENTS  IS NULL
		AND		T.ORDER_NO = @ORDER_NO
		AND     ISNULL(WAREHOUSE_NAME,'')=@WAREHOUSE 
		ORDER BY T.INTERFACE_ID

		SELECT  @RUNSHEET_NO_SET_Tmp=(SELECT DISTINCT PULL_SHEET_NO+','
		FROM LES.TI_TWD_RECEIVED_GOODS_FOR_RECORD T WITH(NOLOCK)
		WHERE RECEIVED_DATE>=@RECEIVED_DATE_START AND RECEIVED_DATE<=@RECEIVED_DATE_END
			 AND (INTERFACE_STATUS IS NULL OR INTERFACE_STATUS=0)
			 AND PLANT=@PLANT AND SUPPLIER_NUM=@SUPPLIER_NUM
			 AND PART_NO IN (SELECT	TOP 10 PART_NO FROM	#TEMP_TWD_RECEIVED_GOODS_FOR_RECORD_RECKONING T
								WHERE	T.COMMENTS  IS NULL
								AND		T.ORDER_NO = @ORDER_NO
								AND     ISNULL(T.WAREHOUSE_NAME,'')=@WAREHOUSE 
								ORDER BY T.INTERFACE_ID)	 
		FOR XML PATH('')) 

		
		--把包装明细插入到包装明细表中
	INSERT INTO [LES].[TT_TWD_RUNSHEET_PACKAGE_DETAIL]
           ([TWD_RUNSHEET_SN]
           ,[RECKONING_SN]
           ,[PLANT]
           ,[ASSEMBLY_LINE]
           ,[SUPPLIER_NUM]
           ,[INBOUND_PACKAGE_MODEL]
           ,[RDC_DLOC]
           ,[INBOUND_PACKAGE]
           ,[MEASURING_UNIT_NO]
           ,[PACK_COUNT]
           ,[REQUIRED_INBOUND_PACKAGE]
           ,[REQUIRED_INBOUND_PACKAGE_QTY]
		   ,TWD_RUNSHEET_NO)
		   SELECT [TWD_RUNSHEET_SN]
			  ,A.[RECKONING_SN]
			  ,A.[PLANT]
			  ,A.[ASSEMBLY_LINE]
			  ,A.[SUPPLIER_NUM]
			  ,A.[INBOUND_PACKAGE_MODEL]
			  ,B.[INHOUSE_PACKAGE_MODEL_NAME]
			  ,A.[INHOUSE_PACKAGE]
			  ,A.[MEASURING_UNIT_NO]
			  ,A.[PACK_COUNT]
			  ,A.[REQUIRED_INBOUND_PACKAGE]
			  ,A.[REQUIRED_INBOUND_PACKAGE_QTY]
			  ,@RunSheetNo
		  FROM [LES].[TT_TWD_RECKONING_SHEETS_DETAIL] A 
		  left join [LES].[TT_TWD_PACKAGE_MODEL] B ON A.[INBOUND_PACKAGE_MODEL]=B.[INHOUSE_PACKAGE_MODEL]
		  where [RECKONING_SN]=@Sequence
		
	--更新送货单号 add by caodaowei on 20141105
	UPDATE  LES.TI_TWD_RECEIVED_GOODS_FOR_RECORD
	SET COMMENTS=@DELIVERY_ORDER
	WHERE RECEIVED_DATE>=@RECEIVED_DATE_START AND RECEIVED_DATE<=@RECEIVED_DATE_END
	AND (INTERFACE_STATUS IS NULL OR INTERFACE_STATUS=0)
	AND PLANT=@PLANT AND SUPPLIER_NUM=@SUPPLIER_NUM
	AND PART_NO IN (SELECT	TOP 10 PART_NO FROM	#TEMP_TWD_RECEIVED_GOODS_FOR_RECORD_RECKONING T
								WHERE	T.COMMENTS  IS NULL
								AND		T.ORDER_NO = @ORDER_NO
								AND     ISNULL(T.WAREHOUSE_NAME,'')=@WAREHOUSE 
								ORDER BY T.INTERFACE_ID)

		UPDATE	#TEMP_TWD_RECEIVED_GOODS_FOR_RECORD_RECKONING SET COMMENTS = 'TEMP'
		WHERE INTERFACE_ID IN(SELECT TOP 10 INTERFACE_ID  FROM #TEMP_TWD_RECEIVED_GOODS_FOR_RECORD_RECKONING
		WHERE	COMMENTS  IS NULL
		AND		ORDER_NO = @order_no
		AND     ISNULL(WAREHOUSE_NAME,'')=@WAREHOUSE 
		ORDER BY INTERFACE_ID)
	END
 
	--更新拉动单号
	UPDATE LES.TT_TWD_RECKONING_SHEETS
	SET PULL_DETAIL=@RUNSHEET_NO_SET_Tmp
	WHERE RECKONING_SN=@Sequence
	
	--判断是否还有未结算的明细	
    SET @INTERFACE_ID=-1
	SELECT @INTERFACE_ID=INTERFACE_ID FROM #TEMP_TWD_RECEIVED_GOODS_FOR_RECORD_RECKONING WHERE COMMENTS  IS NULL
	SET @result=@result+1
	
	
END

--更新收货的状态
UPDATE LES.TI_TWD_RECEIVED_GOODS_FOR_RECORD SET INTERFACE_STATUS=1
 WHERE RECEIVED_DATE>=@RECEIVED_DATE_START AND RECEIVED_DATE<=@RECEIVED_DATE_END 
 AND (INTERFACE_STATUS IS NULL OR INTERFACE_STATUS=0)
 AND SUPPLIER_NUM=@SUPPLIER_NUM
 and PLANT=@PLANT
 
commit transaction
end try

begin catch
	--出错，则返回执行不成功，回滚事务
	ROLLBACK TRANSACTION
	--记录错误信息
	INSERT INTO [LES].[TS_SYS_EXCEPTION] (TIME_STAMP, [APPLICATION], [METHOD], CLASS,  EXCEPTION_MESSAGE, ERROR_CODE)
	SELECT GETDATE(),'TWD','PROC_TWD_GEN_PACKING_SHEET','PROCEDURE',ERROR_MESSAGE(),ERROR_LINE()
end catch

--释放临时表
DROP TABLE #TEMP_TWD_RECEIVED_GOODS_FOR_RECORD_RECKONING

SELECT @result