
----------------------------------------
----提取待分解的零件
----生成JIS应急处理数据
----------------------------------------
CREATE PROCEDURE [LES].[PROC_JIS_GET_MEET_EMERGENCY_REPORT]
(
	@EMERG_RUNSHEET_NO NVARCHAR(20)
)
AS
DECLARE @Plant NVARCHAR(5)
DECLARE @AssemblyLine NVARCHAR(10)
DECLARE @SupplierNum NVARCHAR(8)
DECLARE @Rack NVARCHAR(20)
DECLARE @BackLogQuantity INT
BEGIN
	CREATE TABLE #TempJisMeetEmergency
	(
		RID	INT IDENTITY(1,1),
		EMERG_DETAIL_SN	int,
		GROUP_ID INT
	)
	
	SELECT	TOP 1 @Plant=PLANT, @AssemblyLine=ASSEMBLY_LINE, @SupplierNum=SUPPLIER_NUM, @Rack=RACK
	FROM	LES.TT_JIS_MEET_EMERGENCY
	WHERE	EMERG_RUNSHEET_NO = @EMERG_RUNSHEET_NO
	
	IF @Plant IS NULL
	BEGIN
		SELECT	B.GROUP_ID, VEHICLE_STATUS, PLANT, ASSEMBLY_LINE, JIS_RUNSHEET_FLEX_TIME, ESTIMATED_ARRIVAL_TIME , MODEL, KNR, RUNNING_NUMBER,
				PART_NO, USAGE, RACK_CNAME, VIN, MODEL_NO
		FROM	LES.TT_JIS_MEET_EMERGENCY A, #TempJisMeetEmergency B
		WHERE	A.EMERG_DETAIL_SN = B.EMERG_DETAIL_SN
		ORDER	BY B.GROUP_ID

		RETURN
	END
	
	SELECT  @BackLogQuantity = BACKLOG_QUANTITY
	FROM	LES.TM_JIS_RACK
	WHERE	PLANT=@Plant 
	AND		ASSEMBLY_LINE=@AssemblyLine 
	AND		SUPPLIER_NUM=@SupplierNum
	AND		RACK=@Rack
	
	IF @BackLogQuantity IS NULL OR @BackLogQuantity <= 0
	BEGIN
		SELECT	B.GROUP_ID, VEHICLE_STATUS, PLANT, ASSEMBLY_LINE, JIS_RUNSHEET_FLEX_TIME, ESTIMATED_ARRIVAL_TIME , MODEL, KNR, RUNNING_NUMBER,
				PART_NO, USAGE, RACK_CNAME, VIN, MODEL_NO
		FROM	LES.TT_JIS_MEET_EMERGENCY A, #TempJisMeetEmergency B
		WHERE	A.EMERG_DETAIL_SN = B.EMERG_DETAIL_SN
		ORDER	BY B.GROUP_ID

		RETURN
	END
	
	INSERT	INTO #TempJisMeetEmergency
	SELECT	EMERG_DETAIL_SN, 0
	FROM	LES.TT_JIS_MEET_EMERGENCY
	WHERE	EMERG_RUNSHEET_NO = @EMERG_RUNSHEET_NO
	ORDER	BY EMERG_DETAIL_SN
	
	UPDATE	#TempJisMeetEmergency
	SET		GROUP_ID = RID/@BackLogQuantity
	
	SELECT	B.GROUP_ID, VEHICLE_STATUS, PLANT, ASSEMBLY_LINE, JIS_RUNSHEET_FLEX_TIME, ESTIMATED_ARRIVAL_TIME , MODEL, KNR, RUNNING_NUMBER,
			PART_NO, USAGE, RACK_CNAME, VIN, MODEL_NO
	FROM	LES.TT_JIS_MEET_EMERGENCY A, #TempJisMeetEmergency B
	WHERE	A.EMERG_DETAIL_SN = B.EMERG_DETAIL_SN
	ORDER	BY B.GROUP_ID
END