



CREATE PROCEDURE [LES].[PROC_WMM_RETURN_DETAIL_CREATE_UPDATE]
 
AS

BEGIN

DELETE FROM [LES].[TT_WMM_RETURN_DETAIL] 
WHERE RETURN_DETAIL_ID IN
(SELECT DISTINCT RETURN_DETAIL_ID FROM [LES].[TT_WMM_RETURN_DETAIL](NOLOCK) TD
left join LES.TT_WMM_RETURN (NOLOCK) TM ON TM.RETURN_ID = TD.RETURN_ID
left JOIN LES.TE_WMM_RETURN_DETAIL_TEMP (NOLOCK) T ON T.RETURN_NO = TM.RETURN_NO
 WHERE T.PART_NO = TD.PART_NO)

INSERT INTO [LES].[TT_WMM_RETURN_DETAIL]
	(
      [RETURN_ID]
      ,[PLANT]
      ,[SUPPLIER_NUM]
      ,[WM_NO]
      ,[ZONE_NO]
      ,[DLOC]
      ,[PART_NO]
      ,[PART_CNAME]
      ,[PART_CLS]
      ,[PART_COUNT]
      ,[PACK_COUNT]
      ,[PACK_SIZE]
      ,[PACKAGE_MODEL]
      ,[RETURN_REASON]
      ,[COMMENTS]
      ,[CREATE_USER]
      ,[CREATE_DATE]
	)
	SELECT 
		TT.RETURN_ID		
	    ,TT.[PLANT]
		,TT.[SUPPLIER_NUM]
		,TT.[WM_NO]
		,TT.[ZONE_NO]
		,ST.DLOC
        ,TE.[PART_NO]
        ,ST.[PART_CNAME]
		,TM.PART_CLS
        ,0 AS [PART_COUNT]
        ,TE.PART_COUNT AS [PACK_COUNT]
		,TE.PACK_COUNT as [PACK_SIZE]
        ,ST.[PACKAGE_MODEL]
		,TT.RETURN_REASON
		,TE.COMMENTS
        ,TE.[CREATE_USER]
        ,TE.[CREATE_DATE]
	FROM 
		[LES].[TE_WMM_RETURN_DETAIL_TEMP] (NOLOCK)  TE 
		JOIN [LES].[TT_WMM_RETURN](NOLOCK) TT ON TE.VALID_FLAG = 1 AND (TT.CONFIRM_FLAG = 0 OR TT.CONFIRM_FLAG IS NULL) AND TE.RETURN_NO = TT.RETURN_NO 
		JOIN [LES].[TM_BAS_MAINTAIN_PARTS](NOLOCK) TM ON TE.PART_NO = TM.PART_NO
		LEFT JOIN [LES].[TM_BAS_PARTS_STOCK](NOLOCK) ST ON TT.PLANT = ST.PLANT AND TT.WM_NO = ST.WM_NO AND TT.ZONE_NO = ST.ZONE_NO AND TE.PART_NO = ST.PART_NO
	WHERE 
		(SELECT Count(*) FROM [LES].[TT_WMM_RETURN_DETAIL](NOLOCK) t where t.RETURN_ID = TT.RETURN_ID and t.PART_NO = TE.PART_NO) = 0

END