
-- =============================================
-- Author:		吕小望
-- Create date: 2011-10-11
-- Description:	生成结算
-- =============================================
CREATE PROCEDURE [LES].[PROC_TWD_NEW_RECKONING_SHEET]
(
	@DELIVERY_ORDER			NVARCHAR(30),
	@ORDER_NO				NVARCHAR(30), 
	@RECEIVE_LOCATION		NVARCHAR(30),
	@RECEIVE_DATE			DATETIME,
	@SUPPLIER_NUM			NVARCHAR(8),
	@SUPPLIER_TRANS			NVARCHAR(100), 
	@UNLOAD_PLACE			NVARCHAR(50),
	@LOAD_PLACE				NVARCHAR(50), 
	@PULL_TYPE				NVARCHAR(10),
	@PULL_DETAIL			NVARCHAR(2000),
	@CREATE_USER			NVARCHAR(50)
)
AS
DECLARE @TempJisRunsheetSn TABLE
(
	RUNSHEET_NO	nvarchar(30)	
)
DECLARE @ReckoningSn INT
DECLARE @Sequence INT
BEGIN
	
	EXEC  @Sequence = [LES].[PROC_JIS_GET_NEXT_SEQUENCE] 'JIS_RECKONING_SHEET'
	
	INSERT	INTO @TempJisRunsheetSn
	SELECT	SPLIT_VALUE FROM LES.FUN_SYS_SPLIT(@PULL_DETAIL, ',')
	
	INSERT	INTO LES.TT_JIS_RECKONING_SHEET
	(
		RECKONING_SN,
		RECKONING_NO,
		DELIVERY_ORDER,
		ORDER_NO,
		RECEIVE_LOCATION,
		RECEIVED_DATE,
		SUPPLIER_NUM,
		SUPPLIER_TRANS,
		WMS_SEND_STATUS,
		TRANS_TYPE,
		WMS_SEND_TIME,
		UNLOAD_PLACE,
		LOAD_PLACE,
		PULL_TYPE,
		PULL_DETAIL,
		SUPPLY_STATUS,
		SUPPLY_CONFIRM_DATE,
		FIRST_CONFIRM_STATUS,
		FIRST_CONFIRM_DATE,
		SECOND_CONFIRM_STATUS,
		SECOND_CONFIRM_DATE,
		COMMENTS,
		UPDATE_DATE,
		UPDATE_USER,
		CREATE_DATE,
		CREATE_USER
	)

	SELECT	
			@Sequence,
			NULL,
			@DELIVERY_ORDER, 
			A.ORDER_NO,
			@RECEIVE_LOCATION,
			@RECEIVE_DATE,
			@SUPPLIER_NUM,
			@SUPPLIER_TRANS,
			1,
			'TWD',
			GETDATE(),
			@UNLOAD_PLACE,
			@LOAD_PLACE,
			@PULL_TYPE,
			@PULL_DETAIL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			NULL,
			'Temp',
			NULL,
			NULL,			
			GETDATE(),
			@CREATE_USER
	FROM	LES.TI_TWD_RECEIVED_GOODS A, @TempJisRunsheetSn B
	WHERE	A.PULL_SHEET_NO = B.RUNSHEET_NO
	GROUP	BY A.ORDER_NO

	UPDATE	LES.TT_JIS_RECKONING_SHEET SET RECKONING_NO = CONVERT(varchar(6),   getdate(),112)+SUBSTRING(@SUPPLIER_NUM, 2, 4) + SUBSTRING('000000' + CONVERT(NVARCHAR, @Sequence), LEN(CONVERT(NVARCHAR, @Sequence))+1 , 6) , 
	@Sequence = @Sequence + 1 WHERE COMMENTS = 'Temp'
	
	UPDATE	LES.TS_JIS_SEQUENCE
	SET		CURRENT_VALUE = @Sequence
	WHERE	SEQUENCE_NAME = 'JIS_RECKONING_SHEET'
	
	INSERT	INTO LES.TT_JIS_RECKONING_DETAIL
	SELECT	E.RECKONING_SN, C.PLANT, C.ASSEMBLY_LINE, NULL, D.PART_NO, NULL, NULL, c.BOX_PARTS,
			'', C.SUPPLIER_NUM, D.PART_CNAME, '', NULL, '', NULL, NULL, A.MEASURING_UNIT_NO,
			D.PART_CNAME, C.CREATE_DATE, D.BARCODE_DATA, A.REQUIRED_INBOUND_PACKAGE_QTY, A.ACTUAL_INBOUND_PACKAGE_QTY, A.INTERFACE_ID,A.COMMENTS, A.WAREHOUSE_NAME
	FROM	LES.TI_TWD_RECEIVED_GOODS A, @TempJisRunsheetSn B, LES.TT_TWD_RUNSHEET C, LES.TT_TWD_RUNSHEET_DETAIL D, LES.TT_JIS_RECKONING_SHEET E
	WHERE	A.PULL_SHEET_NO = B.RUNSHEET_NO
	AND		A.ORDER_NO = E.ORDER_NO 
	AND		C.TWD_RUNSHEET_NO = B.RUNSHEET_NO
	AND		C.TWD_RUNSHEET_SN = D.TWD_RUNSHEET_SN
	AND		A.PART_NO = D.PART_NO
	AND		E.COMMENTS = 'Temp'
	
	UPDATE	LES.TT_JIS_RECKONING_SHEET SET COMMENTS = NULL

END