CREATE PROCEDURE [LES].[PROC_STA_MANUL_BARCODE]
@SUPPLIER_NUM nvarchar(12),		--供应商编号
@PART_NO nvarchar(20),			--零件号
@STORAGE_LOCATION varchar(20),				--存储区
@INHOUSE_PACKAGE_MODEL nvarchar(30),	--箱型
@REQUIRED_INBOUND_PACKAGE_QTY INT,		--包装数
@PLANT nvarchar(5),			--工厂
@CREATE_USER nvarchar(50),	--创建人
@BARCODE_TYPE nvarchar(10),   --标签类型
@TWD_RUNSHEET_NO nvarchar(22),	--母卷号
@BarcodeNum int,			--标签数量
@ProductLine nvarchar(30),	--生产线体
@BagNum nvarchar(30),		--捆包号
@NetWeight numeric(18,2)	--净重
AS

DECLARE @PLAN_RUNSHEET_NO nvarchar(30)
SET @PLAN_RUNSHEET_NO = '1000000000';  --订单号设置同一个值

DECLARE @SUPPLIER_NAME nvarchar(100);
SELECT @SUPPLIER_NAME = SUPPLIER_NAME FROM LES.TM_BAS_SUPPLIER WHERE SUPPLIER_NUM = @SUPPLIER_NUM 

DECLARE @PART_CNAME nvarchar(300);
DECLARE @PART_NICKNAME nvarchar(50);
SELECT @PART_CNAME = PART_CNAME,@PART_NICKNAME = PART_NICKNAME FROM LES.TM_BAS_MAINTAIN_PARTS WHERE PART_NO = @PART_NO

DECLARE @DOCK nvarchar(10);
SET @DOCK = '';  --卸货区域设置为空

DECLARE @barCodeNo nvarchar(32);

DECLARE @EXPECTED_ARRIVAL_TIME DATETIME;
SET @EXPECTED_ARRIVAL_TIME = getdate();


BEGIN
	while (@BarcodeNum > 0)		--循环创建BARCODE
	begin			
		EXEC [LES].[PROC_SPM_GET_NEXT_BARCODE_SEQUENCE] 'BARCODE', @barCodeNo OUTPUT

		INSERT INTO LES.TT_SPM_DELIVERY_RUNSHEET_BARCODE
		(PLAN_ASN_RUNSHEET_NO,SUPPLIER_NUM,PART_NO,PART_CNAME,BOX_PARTS,MEASURING_UNIT_NO,INHOUSE_PACKAGE_MODEL,REQUIRED_INBOUND_PACKAGE_QTY,PLANT,DOCK,BARCODE_DATA,REQUIRED_DATE,SUPPLIER_NAME,STORAGE_LOCATION,PART_NICKNAME,CREATE_USER,CREATE_DATE,BARCODE_TYPE,TWD_RUNSHEET_NO,[PRODUCT_LINE],[BAG_NUM],[NET_WEIGHT]) 
		VALUES (@PLAN_RUNSHEET_NO,@SUPPLIER_NUM,@PART_NO,@PART_CNAME,'DS','EA',@INHOUSE_PACKAGE_MODEL,@REQUIRED_INBOUND_PACKAGE_QTY,@PLANT,@DOCK,@barCodeNo,@EXPECTED_ARRIVAL_TIME,@SUPPLIER_NAME,@STORAGE_LOCATION,@PART_NICKNAME,@CREATE_USER,getdate(),@BARCODE_TYPE,@TWD_RUNSHEET_NO,@ProductLine,@BagNum,@NetWeight)
		
		set @BarcodeNum = @BarcodeNum -1
	end

END