



/**********************************************************************/
/*                                                                    */
/*   Project Name:  TWD                                               */
/*   Program Name:  TWD_CALCULATE_SUPPLIER_SENDTIME                   */
/*   Called By:     TWD_CALCULATE_SUPPLIER_SENDTIME                   */
/*   Purpose:       This stored procedure calculate supplier sendtime */
/*   Author:        shenjinkui                                        */
/**********************************************************************/

CREATE PROCEDURE [LES].[PROC_TWD_SAVETO_RECEIVED_GOODS_FOR_RECORD]
AS
BEGIN
	DECLARE @Min INT,
			@Max INT

	SELECT @Min = LAST_MAX_IDENTITY_ID
	FROM [LES].[TS_SYS_IDENTITY_SEGMENT]
	WHERE NAME='TI_TWD_RECEIVED_GOODS_INTERFACE_ID'
		AND LAST_MAX_IDENTITY_ID > LAST_MIN_IDENTITY_ID	--防止最大处理的Id被不小心人为的改小了，导致重复的（无法完全保障被手动修改导致的风险）
	IF @Min IS NULL
	BEGIN
		PRINT '手动配置最大ID数据错误，不再继续执行。'
		RETURN;
	END

	SET @Max = ISNULL((SELECT MAX(INTERFACE_ID) FROM [LES].[TI_TWD_RECEIVED_GOODS]),0)

	BEGIN TRAN
		INSERT INTO [LES].[TI_TWD_RECEIVED_GOODS_FOR_RECORD]
		([PLANT] ,[ASSEMBLY_LINE] ,[PULL_SHEET_NO] ,[PULL_DETAIL_ID] ,[ASN_NO] ,[REQUEST_TIME] ,[INTERFACE_STATUS] ,[PROCESS_TIME] ,[PART_NO] ,[PART_CNAME] ,
		[PART_ENAME] ,[SUPPLIER_NUM] ,[SUPPLIER_NAME] ,[SUPPLIER_TYPE] ,[INTERFACE_TYPE] ,[PACK_COUNT] ,
		[INHOUSE_PACKAGE_MODEL] ,[INHOUSE_PACKAGE] ,[MEASURING_UNIT_NO] ,[WAREHOUSE] ,[RECEIVED_DATE] ,
		[REQUIRED_INBOUND_PACKAGE] ,[REQUIRED_INBOUND_PACKAGE_QTY] ,[ACTUAL_INBOUND_PACKAGE] ,[ACTUAL_INBOUND_PACKAGE_QTY] ,
		[WAREHOUSE_NAME] ,[RECEIVE_QTY] ,[WMSID] ,[ORDER_NO] ,[ITEM_NO] ,[RECKONING_NO] ,
		[COMMENTS] ,[UPDATE_DATE] ,[UPDATE_USER] ,[CREATE_DATE] ,[CREATE_USER] ,[RUNSHEET_SN] ,
		[BOX_PARTS] ,[EXPECTED_ARRIVAL_TIME] ,[INBOUND_PACKAGE_MODEL])
		SELECT GB.[PLANT] ,R.[ASSEMBLY_LINE] ,GB.[PULL_SHEET_NO] ,GB.[PULL_DETAIL_ID] ,GB.[ASN_NO] ,
		GB.[REQUEST_TIME] ,GB.[INTERFACE_STATUS] ,GB.[PROCESS_TIME] ,GB.[PART_NO] ,GB.[PART_CNAME] ,
		GB.[PART_ENAME] ,GB.[SUPPLIER_NUM] ,GB.[SUPPLIER_NAME] ,GB.[SUPPLIER_TYPE] ,GB.[INTERFACE_TYPE] ,
		D.INBOUND_PACKAGE ,
		GB.[INHOUSE_PACKAGE_MODEL] ,GB.[INHOUSE_PACKAGE] ,GB.[MEASURING_UNIT_NO] ,GB.[WAREHOUSE] ,
		GB.[RECEIVED_DATE] ,GB.[REQUIRED_INBOUND_PACKAGE] ,GB.[REQUIRED_INBOUND_PACKAGE_QTY] ,
		GB.[ACTUAL_INBOUND_PACKAGE] ,GB.[ACTUAL_INBOUND_PACKAGE_QTY] ,GB.[WAREHOUSE_NAME] ,GB.[RECEIVE_QTY] ,
		GB.[WMSID] ,GB.[ORDER_NO] ,
		GB.[ITEM_NO] ,GB.[RECKONING_NO] ,GB.[COMMENTS] ,GB.[UPDATE_DATE] ,GB.[UPDATE_USER] ,GB.[CREATE_DATE] ,
		GB.[CREATE_USER] ,GB.[RUNSHEET_SN] ,R.[BOX_PARTS] ,R.[EXPECTED_ARRIVAL_TIME] ,D.INBOUND_PACKAGE_MODEL AS [INBOUND_PACKAGE_MODEL]
		FROM [LES].[TI_TWD_RECEIVED_GOODS] GB 
		JOIN [LES].[TT_TWD_RUNSHEET] R ON GB.INTERFACE_ID > @Min
			AND GB.INTERFACE_ID <= @Max
			AND GB.PULL_SHEET_NO = R.TWD_RUNSHEET_NO
			AND R.GENERATE_TYPE = 1
		JOIN [LES].[TT_TWD_RUNSHEET_DETAIL] D ON R.TWD_RUNSHEET_SN = D.TWD_RUNSHEET_SN
		AND D.PART_NO = GB.PART_NO
	

		UPDATE [LES].[TS_SYS_IDENTITY_SEGMENT] SET LAST_MAX_IDENTITY_ID = @Max, LAST_MIN_IDENTITY_ID=@Min, LAST_DATETIME = GETDATE() WHERE NAME='TI_TWD_RECEIVED_GOODS_INTERFACE_ID'
	COMMIT TRAN
END