/********************************************************************/
/*                                                                  */
/*   Project Name:  LES System                         */
/*   Program Name:  [PROC_BAS_WAREHOUSE_LOCATION_CREATE_UPDATE]             */
/*   Called By:     by the Page							*/
/*   Purpose:       This is the main stored procedure for the       */
/*   author:       andy	2015-06-09     				       */
/********************************************************************/
CREATE PROCEDURE [LES].[PROC_BAS_WAREHOUSE_LOCATION_CREATE_UPDATE]
 
AS

BEGIN

INSERT INTO [LES].[TM_BAS_WAREHOUSE_LOCATION]
	(
	[PLANT]
	,[WM_NO]
	,[ZONE_NO]
	,[DLOC]
	,[STORAGE_LOCATION_NAME]
	,[LOCATION_TYPE]
	,[SEQUENCE_NO]
	,[COUNT_PARTITION]
	,[COMMENTS]
	,[CREATE_USER]
	,[CREATE_DATE]
	,[UPDATE_USER]
	,[UPDATE_DATE]
	,[LANE_NO]
	,[SHELVES_NO]
	,[LAYER_NO]
	,[GRID_NO]
	,[PART_CLASSIFY_AREA_NO]
	)
	SELECT 
		[PLANT]
		,[WM_NO]
		,[ZONE_NO]
		,[DLOC]
		,[STORAGE_LOCATION_NAME]
		,[LOCATION_TYPE]
		,[SEQUENCE_NO]
		,[COUNT_PARTITION]
		,[COMMENTS]
		,[CREATE_USER]
		,[CREATE_DATE]
		,[UPDATE_USER]
		,[UPDATE_DATE]
		,[LANE_NO]
		,[SHELVES_NO]
		,[LAYER_NO]
		,[GRID_NO]
		,[PART_CLASSIFY_AREA_NO] 
	FROM (
		SELECT distinct 
			TE.[PLANT]
			,TE.[WM_NO]
			,TE.[ZONE_NO]
			,TE.[DLOC]
			,TE.[STORAGE_LOCATION_NAME]
			,TE.[LOCATION_TYPE]
			,TE.[SEQUENCE_NO]
			,TE.[COUNT_PARTITION]
			,TE.[COMMENTS]
			,TE.[CREATE_USER]
			,TE.[CREATE_DATE]
			,TE.[UPDATE_USER]
			,TE.[UPDATE_DATE]
			, WL.DLOC FLG
			,ISNULL(TE.[LANE_NO],0) [LANE_NO]
			,ISNULL(TE.[SHELVES_NO],0) [SHELVES_NO]
			,ISNULL(TE.[LAYER_NO],0) [LAYER_NO]
			,ISNULL(TE.[GRID_NO],0) [GRID_NO]
			,TE.[PART_CLASSIFY_AREA_NO]
		FROM 
			[LES].[TE_BAS_WAREHOUSE_LOCATION_TEMP] TE LEFT JOIN [LES].[TM_BAS_WAREHOUSE_LOCATION] WL ON 
			TE.VALID_FLAG = 1 
			AND TE.PLANT = WL.PLANT 
			AND TE.WM_NO = WL.WM_NO 
			AND TE.ZONE_NO = WL.ZONE_NO 
			AND TE.DLOC = WL.DLOC) DT
	WHERE DT.FLG IS NULL

UPDATE 
	[LES].[TM_BAS_WAREHOUSE_LOCATION] 
SET
    [PLANT] = DT.[PLANT]
	,[WM_NO] = DT.[WM_NO]
	,[ZONE_NO] = DT.[ZONE_NO]
	,[DLOC] = DT.[DLOC]
	,[STORAGE_LOCATION_NAME] = DT.[STORAGE_LOCATION_NAME]
	,[LOCATION_TYPE] = DT.[LOCATION_TYPE]
	,[SEQUENCE_NO] = DT.[SEQUENCE_NO]
	,[COUNT_PARTITION] = DT.[COUNT_PARTITION]
	,[COMMENTS] = DT.[COMMENTS]
	,[UPDATE_USER] = DT.CREATE_USER
	,[UPDATE_DATE] = DT.CREATE_DATE
	,[LANE_NO] = ISNULL(DT.[LANE_NO],0)
	,[SHELVES_NO] = ISNULL(DT.[SHELVES_NO],0)
	,[LAYER_NO] = ISNULL(DT.[LAYER_NO],0)
	,[GRID_NO] = ISNULL(DT.[GRID_NO],0)
	,[PART_CLASSIFY_AREA_NO] = DT.[PART_CLASSIFY_AREA_NO]
FROM 
	[LES].[TE_BAS_WAREHOUSE_LOCATION_TEMP] DT
WHERE 
	DT.VALID_FLAG = 1 
	AND DT.PLANT = [LES].[TM_BAS_WAREHOUSE_LOCATION].PLANT
	AND DT.WM_NO = [LES].[TM_BAS_WAREHOUSE_LOCATION].WM_NO
	AND DT.ZONE_NO = [LES].[TM_BAS_WAREHOUSE_LOCATION].ZONE_NO
	AND DT.DLOC = [LES].[TM_BAS_WAREHOUSE_LOCATION].DLOC


END