



/*
IF EXISTS(SELECT 1 FROM sys.sysobjects WHERE type = 'p' AND name = 'PROC_ODS_GET_TERMAL_PBOM_DIFFERENCE')
	DROP PROCEDURE [LES].PROC_ODS_GET_TERMAL_PBOM_DIFFERENCE
GO
*/
CREATE PROCEDURE [LES].[PROC_BAS_INHOUSE_PULL_COMBINE_BY_ASSEMBLYLINE]
(
 	@PLANT nvarchar(5),
 	@ASSEMBLY_LINE  nvarchar(10)
)
AS

Declare @rowcount int
BEGIN

select @rowcount=isnull(count(*),0) from  LES.TE_BAS_INHOUSE_PULL_LOGISTIC_SUBMIT 
WHERE PLANT = @PLANT AND ASSEMBLY_LINE = @ASSEMBLY_LINE
if(@rowcount<0)
return

BEGIN TRY
	
	UPDATE [LES].[TS_SYS_COMBINE_CONTROL] set [ISPASS]=1,[LAST_UPDATE_DATE]=getdate() where [SEQID]=1
	waitfor delay '00:00:20'
END TRY
BEGIN CATCH
      INSERT  INTO [LES].[TS_SYS_EXCEPTION] (time_stamp,[application],[METHOD],class,exception_message,error_code)
                SELECT  GETDATE(),'INHOUSECOMBINE','PROC_BAS_INHOUSE_PULL_COMBINE','Procedure',ERROR_MESSAGE(),ERROR_LINE()
    RETURN -1
END CATCH   

BEGIN TRY

BEGIN TRAN

delete from [LES].TM_BAS_INHOUSE_PULL_LOGISTIC_STANDARD 
where PLANT = @PLANT AND ASSEMBLY_LINE = @ASSEMBLY_LINE


INSERT INTO [LES].TM_BAS_INHOUSE_PULL_LOGISTIC_STANDARD
	   ([PLANT],[ASSEMBLY_LINE],[PLANT_ZONE],[WORKSHOP]
	   ,[SUPPLIER_NUM],[TRANS_SUPPLIER_NUM],[MODEL],[PART_NO]
	   ,[INDENTIFY_PART_NO],[AMOUNTRATIO],[EXTERIOR_COLOR],[INTERNAL_COLOR]
	   ,[HAND_KEPT_RECORD],[COLOR_CONTROL_PATCH],[VWS],[RAND]
	   ,[SECTION],[PART_OPTION],[PRODUCTION_NUMBER],[START_PRODUCTION_DATE]
	   ,[CANCEL_NUMBER],[END_PRODUCTION_DATE],[MODEL_YEAR],[DOSAGE]
	   ,[MEASURING_UNIT_NO],[AMOUNT_FLAG],[DATA_DATE],[VORSERIE]
	   ,[PART_CNAME],[PART_ENAME],[PART_NICKNAME],[LOAD_FLAG]
	   ,[ZP_FLAG],[REQUIREMENT_FLAG],[ASSEMBLY_FLAG],[ASSEMBLY_FLAG_RECRUIT]
	   ,[PURCHASE_STYLE],[VALID_FLAG],[WORKSHOP_SECTION]
	   ,[LOCATION],[IN_PLANT_LOGISTIC_MODE],[IN_PLANT_SYSTEM_MODE],[IN_PLANT_LOGISTIC_PART_CLASS]
	   ,[INHOUSE_MODE],[INHOUSE_SYSTEM_MODE],[EFFECTIVE_STATUS],[START_EFFECTIVE_DATE]
	   ,[INHOUSE_PART_CLASS],[DOCK],[INHOUSE_PACKAGE_MODEL]
	   ,[INHOUSE_PACKAGE]
	   --,[DIFF_FLAG]
	   ,TERMAL_PK,[COMMENTS]	   
	   ,[UPDATE_DATE],[UPDATE_USER],[CREATE_DATE],[CREATE_USER]
	   ,LOGICAL_PK,BUSINESS_PK)
SELECT [PLANT],[ASSEMBLY_LINE],[PLANT_ZONE],[WORKSHOP]
	   ,[SUPPLIER_NUM],[TRANS_SUPPLIER_NUM],[MODEL],[PART_NO]
	   ,[INDENTIFY_PART_NO],[AMOUNTRATIO],[EXTERIOR_COLOR],[INTERNAL_COLOR]
	   ,[HAND_KEPT_RECORD],[COLOR_CONTROL_PATCH],[VWS],[RAND]
	   ,[SECTION],[PART_OPTION],[PRODUCTION_NUMBER],[START_PRODUCTION_DATE]
	   ,[CANCEL_NUMBER],[END_PRODUCTION_DATE],[MODEL_YEAR],[DOSAGE]
	   ,[MEASURING_UNIT_NO],[AMOUNT_FLAG],[DATA_DATE],[VORSERIE]
	   ,[PART_CNAME],[PART_ENAME],[PART_NICKNAME],[LOAD_FLAG]
	   ,[ZP_FLAG],[REQUIREMENT_FLAG],[ASSEMBLY_FLAG],[ASSEMBLY_FLAG_RECRUIT]
	   ,[PURCHASE_STYLE],[VALID_FLAG],[WORKSHOP_SECTION]
	   ,[LOCATION],[IN_PLANT_LOGISTIC_MODE],[IN_PLANT_SYSTEM_MODE],[IN_PLANT_LOGISTIC_PART_CLASS]
	   ,[INHOUSE_MODE],[INHOUSE_SYSTEM_MODE],[EFFECTIVE_STATUS],[START_EFFECTIVE_DATE]
	   ,[INHOUSE_PART_CLASS],[DOCK],[INHOUSE_PACKAGE_MODEL]
	   ,[INHOUSE_PACKAGE]
	   --,[DIFF_FLAG]
	   ,TERMAL_PK,[COMMENTS]	   
	   ,[UPDATE_DATE],[UPDATE_USER],[CREATE_DATE],[CREATE_USER]
	   ,LOGICAL_PK,BUSINESS_PK
FROM  LES.TE_BAS_INHOUSE_PULL_LOGISTIC_SUBMIT
WHERE PLANT = @PLANT AND ASSEMBLY_LINE = @ASSEMBLY_LINE
--插入到PCS计数器

INSERT INTO [LES].[TT_PCS_COUNTER]
           ([PLANT]           --*关键
           ,[ASSEMBLY_LINE]       --*关键
            ,[SUPPLIER_NUM]       --*关键
           ,[PART_NO]         --*关键
           ,[INDENTIFY_PART_NO]
           ,[AMOUNTRATIO]          
           ,[MEASURING_UNIT_NO]
           ,[PART_CNAME]
           ,[PART_ENAME]
           ,[LOCATION]            --*关键
           ,[IN_PLANT_LOGISTIC_PART_CLASS] --*关键
           ,[INHOUSE_PACKAGE_MODEL]
           ,[INHOUSE_PACKAGE]
           ,[CURRENT_PART_COUNT]
           ,[CREATE_DATE])         
           SELECT  
	   A.[PLANT]
      ,A.[ASSEMBLY_LINE]
      ,C.[SUPPLIER_NUM]
      ,A.[PART_NO]
      ,A.[INDENTIFY_PART_NO]
      ,min(A.[AMOUNTRATIO])
      ,min(A.[MEASURING_UNIT_NO])
      ,Min(A.[PART_CNAME])
      ,Min(A.[PART_ENAME])

      ,A.[LOCATION]
      ,A.[IN_PLANT_LOGISTIC_PART_CLASS]

      ,MIN(A.[INHOUSE_PACKAGE_MODEL])
      ,MIN(A.[INHOUSE_PACKAGE])
      ,MIN(A.[INHOUSE_PACKAGE])
      ,GETDATE()
    FROM [LES].[TM_BAS_INHOUSE_PULL_LOGISTIC_STANDARD]  A 
    INNER JOIN [LES].[TM_PCS_ROUTE_BOX_PARTS] C ON A.[PLANT]=C.[PLANT] AND A.[ASSEMBLY_LINE]=C.[ASSEMBLY_LINE]  and A.IN_PLANT_LOGISTIC_PART_CLASS=c.BOX_PARTS
    WHERE not exists (SELECT * FROM 
		   [LES].[TT_PCS_COUNTER] B WHERE A.[PLANT]=B.[PLANT] AND A.[ASSEMBLY_LINE]=B.[ASSEMBLY_LINE] AND C.[SUPPLIER_NUM]=B.[SUPPLIER_NUM] AND
		  A.[LOCATION]=B.[LOCATION] and A.[PART_NO]=B.[PART_NO] AND A.[IN_PLANT_LOGISTIC_PART_CLASS]=B.[IN_PLANT_LOGISTIC_PART_CLASS] ) AND  A.[IN_PLANT_SYSTEM_MODE]='PCS' 
	GROUP BY 
    A.[PLANT]
      ,A.[ASSEMBLY_LINE]
      ,C.[SUPPLIER_NUM]
      --,A.[MODEL]
      ,A.[PART_NO]
      ,A.[INDENTIFY_PART_NO]
      ,A.[LOCATION]
      ,A.[IN_PLANT_LOGISTIC_PART_CLASS]

	 
--更新计数器
--更新计数器--包装更改
UPDATE A SET  A.[INHOUSE_PACKAGE]=INHOUSE_PULL_GROUP.[INHOUSE_PACKAGE], A.[CURRENT_PART_COUNT]=INHOUSE_PULL_GROUP.[INHOUSE_PACKAGE]
    FROM [LES].[TT_PCS_COUNTER] A INNER JOIN 
    (SELECT [PLANT],[ASSEMBLY_LINE],[LOCATION],[PART_NO],[IN_PLANT_LOGISTIC_PART_CLASS],MIN([INHOUSE_PACKAGE_MODEL])AS [INHOUSE_PACKAGE_MODEL],MIN([INHOUSE_PACKAGE]) AS [INHOUSE_PACKAGE] FROM [LES].[TM_BAS_INHOUSE_PULL_LOGISTIC_STANDARD] WHERE [IN_PLANT_SYSTEM_MODE]='PCS'
    GROUP BY   [PLANT],[ASSEMBLY_LINE],[LOCATION],[PART_NO],[IN_PLANT_LOGISTIC_PART_CLASS]) AS INHOUSE_PULL_GROUP
    ON A.[PLANT]=INHOUSE_PULL_GROUP.[PLANT] AND A.[ASSEMBLY_LINE]=INHOUSE_PULL_GROUP.[ASSEMBLY_LINE] AND 
		  A.[LOCATION]=INHOUSE_PULL_GROUP.[LOCATION] and A.[PART_NO]=INHOUSE_PULL_GROUP.[PART_NO] AND A.[IN_PLANT_LOGISTIC_PART_CLASS]=INHOUSE_PULL_GROUP.[IN_PLANT_LOGISTIC_PART_CLASS]
    WHERE (A.[INHOUSE_PACKAGE]!=INHOUSE_PULL_GROUP.[INHOUSE_PACKAGE])
	--更新计数器----包装型号更改	
	UPDATE A SET  A.[INHOUSE_PACKAGE_MODEL]=INHOUSE_PULL_GROUP.[INHOUSE_PACKAGE_MODEL]
    FROM [LES].[TT_PCS_COUNTER] A INNER JOIN 
    (SELECT [PLANT],[ASSEMBLY_LINE],[LOCATION],[PART_NO],[IN_PLANT_LOGISTIC_PART_CLASS],MIN([INHOUSE_PACKAGE_MODEL])AS [INHOUSE_PACKAGE_MODEL],MIN([INHOUSE_PACKAGE]) AS [INHOUSE_PACKAGE] FROM [LES].[TM_BAS_INHOUSE_PULL_LOGISTIC_STANDARD] WHERE [IN_PLANT_SYSTEM_MODE]='PCS'
    GROUP BY   [PLANT],[ASSEMBLY_LINE],[LOCATION],[PART_NO],[IN_PLANT_LOGISTIC_PART_CLASS]) AS INHOUSE_PULL_GROUP
    ON A.[PLANT]=INHOUSE_PULL_GROUP.[PLANT] AND A.[ASSEMBLY_LINE]=INHOUSE_PULL_GROUP.[ASSEMBLY_LINE] AND 
		  A.[LOCATION]=INHOUSE_PULL_GROUP.[LOCATION] and A.[PART_NO]=INHOUSE_PULL_GROUP.[PART_NO] AND A.[IN_PLANT_LOGISTIC_PART_CLASS]=INHOUSE_PULL_GROUP.[IN_PLANT_LOGISTIC_PART_CLASS]
    WHERE (A.[INHOUSE_PACKAGE_MODEL]!=INHOUSE_PULL_GROUP.[INHOUSE_PACKAGE_MODEL])
		    
--删除计数器数据
delete from [LES].[TT_PCS_COUNTER]  where not	exists (SELECT * FROM 
		   [LES].[TM_BAS_INHOUSE_PULL_LOGISTIC_STANDARD] B WHERE [LES].[TT_PCS_COUNTER].[PLANT]=B.[PLANT] AND [LES].[TT_PCS_COUNTER].[ASSEMBLY_LINE]=B.[ASSEMBLY_LINE] AND 
		  [LES].[TT_PCS_COUNTER].[LOCATION]=B.[LOCATION] and [LES].[TT_PCS_COUNTER].[PART_NO]=B.[PART_NO] AND [LES].[TT_PCS_COUNTER].[IN_PLANT_LOGISTIC_PART_CLASS]=B.[IN_PLANT_LOGISTIC_PART_CLASS] AND  B.[IN_PLANT_SYSTEM_MODE]='PCS'  )  

--删除计数器数据,由于供应商变更导致的无法删除的数据
delete from [LES].[TT_PCS_COUNTER]  where not	exists (SELECT * FROM 
		   [LES].[TM_PCS_ROUTE_BOX_PARTS]  B WHERE [LES].[TT_PCS_COUNTER].[PLANT]=B.[PLANT] AND [LES].[TT_PCS_COUNTER].[ASSEMBLY_LINE]=B.[ASSEMBLY_LINE] AND 
		    [LES].[TT_PCS_COUNTER].[IN_PLANT_LOGISTIC_PART_CLASS]=B.[BOX_PARTS] and  [LES].[TT_PCS_COUNTER].[SUPPLIER_NUM]=B.[SUPPLIER_NUM]) 
--插入到JIS变更表
--INSERT INTO [LES].[TE_BAS_INHOUSE_CHANGE_PULL]
--           ([PART_NO],[LOGICAL_PK],[DIFF_FLAG],[TERMAL_PK]
--           ,[COMMENTS]
--           ,[CREATE_USER],[CREATE_DATE],[UPDATE_USER],[UPDATE_DATE])
--SELECT Termal.PART_NO,Termal.LOGICAL_PK,0,Termal.Termal_PK,
--       null,
--       null,getdate(),null,null
--FROM [LES].[V_BAS_INHOUSEPULL_COMBINE] AS Termal
--WHERE (INHOUSE_SYSTEM_MODE = 'JIS' OR IN_PLANT_SYSTEM_MODE = 'JIS')
--AND (Termal.Termal_Diff_Flag In (2,3,4)  OR  Termal.Inhouse_Diff_Flag In(1,2,3))
 

--更新Inhouse拉动数据
/*
DELETE  [LES].[TM_BAS_INHOUSE_PULL_LOGISTIC_STANDARD]   
FROM [LES].[V_BAS_INHOUSEPULL_COMBINE] AS Termal,
     LES.TM_BAS_INHOUSE_PULL_LOGISTIC_STANDARD AS TM    
WHERE   Termal.Termal_PK = TM.TERMAL_PK --AND Termal.VALID_FLAG = 1 
        AND (Termal.Termal_Diff_Flag = 4 OR Termal.Inhouse_Diff_Flag = 3)
       
--更新状态Termal/PBOM合并表、更新状态Inhouse物流标准表

UPDATE  [LES].TM_ODS_TERMAL_PBOM_COMBINE_RESULT
SET     DIFF_FLAG = 0
FROM [LES].TM_ODS_TERMAL_PBOM_COMBINE_RESULT AS Termal
WHERE Termal.DIFF_FLAG <> 0

UPDATE  [LES].TM_BAS_MAINTAIN_INHOUSE_LOGISTIC_STANDARD
SET     DIFF_FLAG = 0
FROM [LES].TM_BAS_MAINTAIN_INHOUSE_LOGISTIC_STANDARD AS TM
WHERE TM.DIFF_FLAG <> 0
*/
 UPDATE [LES].[TS_SYS_COMBINE_CONTROL] set [ISPASS]=0 where [SEQID]=1
COMMIT TRAN
RETURN  0 --成功

END TRY
BEGIN CATCH

    ROLLBACK TRAN
    UPDATE [LES].[TS_SYS_COMBINE_CONTROL] set [ISPASS]=0 where [SEQID]=1
     INSERT  INTO [LES].[TS_SYS_EXCEPTION] (time_stamp,[application],[METHOD],class,exception_message,error_code)
                SELECT  GETDATE(),'INHOUSECOMBINE','PROC_BAS_INHOUSE_PULL_COMBINE','Procedure',ERROR_MESSAGE(),ERROR_LINE()
    RETURN -1
END CATCH   

	
END