-- =============================================
-- Author:		Andy Liu
-- Create date: Aug 05,2016
-- Description:	<Description, ,>
-- =============================================
CREATE FUNCTION [LES].[FN_GET_TWD_SENDTIME]
(
	 @PLANT VARCHAR(10),
	 @WORKSHOP VARCHAR(10),
     @WINDOWDATE DATETIME,
     @ONLINE_TIME INT
)
RETURNS DATETIME
AS
BEGIN
	DECLARE @RTIME DATETIME
	SET @RTIME = DATEADD(MI, -@ONLINE_TIME, @WINDOWDATE)
	IF NOT EXISTS
	(
		SELECT * FROM LES.[TM_BAS_WORK_SCHEDULE] WITH (NOLOCK)
		WHERE [PLANT] = @PLANT AND [ASSEMBLY_LINE] = @WORKSHOP
        AND [BEGIN_TIME] <= @WINDOWDATE AND [END_TIME] >= @WINDOWDATE
     )
		BEGIN
				RETURN @RTIME
		END
   

	DECLARE @MI_COUNT INT
	DECLARE @START_TIME DATETIME

	SELECT @MI_COUNT = DATEDIFF(MI,[BEGIN_TIME],@WINDOWDATE),@START_TIME = [BEGIN_TIME] 
	FROM [LES].[TM_BAS_WORK_SCHEDULE] WITH (NOLOCK)
	WHERE [PLANT] = @PLANT AND [ASSEMBLY_LINE] = @WORKSHOP --AND WORK_SCHEDULE_TYPE=1 
	AND [BEGIN_TIME] <= @WINDOWDATE AND [END_TIME] >= @WINDOWDATE

	WHILE(@ONLINE_TIME-@MI_COUNT>0)
		BEGIN
			SET @ONLINE_TIME = @ONLINE_TIME - @MI_COUNT
			IF EXISTS
			(
				SELECT TOP 1 *  
				FROM LES.[TM_BAS_WORK_SCHEDULE] WITH (NOLOCK)
				WHERE [PLANT] = @PLANT AND [ASSEMBLY_LINE] = @WORKSHOP --AND WORK_SCHEDULE_TYPE=1 
				AND [END_TIME] <= @START_TIME
			)
				BEGIN
					SELECT @WINDOWDATE=MAX([END_TIME])
					FROM LES.[TM_BAS_WORK_SCHEDULE] WITH (NOLOCK)
					WHERE PLANT=@PLANT AND ASSEMBLY_LINE=@WORKSHOP --AND WORK_SCHEDULE_TYPE=1 
					   AND [END_TIME]<=@START_TIME

					SELECT @MI_COUNT = DATEDIFF(MI, MIN([BEGIN_TIME]), @WINDOWDATE), @START_TIME = MIN([BEGIN_TIME])
					FROM LES.[TM_BAS_WORK_SCHEDULE] WITH (NOLOCK)
					WHERE [PLANT] = @PLANT AND [ASSEMBLY_LINE] = @WORKSHOP --AND WORK_SCHEDULE_TYPE=1 
					AND [BEGIN_TIME] <= @WINDOWDATE AND [END_TIME] >= @WINDOWDATE
				END
			ELSE
				BEGIN
					SET @WINDOWDATE = NULL
					BREAK
				END
		END
	    
	IF(@WINDOWDATE IS NOT NULL)
		SET @WINDOWDATE = DATEADD(MI, -@ONLINE_TIME, @WINDOWDATE)

	IF (@WINDOWDATE IS NULL)
		SET @WINDOWDATE = @RTIME
	
	RETURN @WINDOWDATE
END