
/**********************************************************************************
* Purpose		: Get TWD RUNSHEET_NO SET BY CONDITION  
* Author		: Yinxuefeng
* CreateDate	: 2013-01-21
***********************************************************************************/

CREATE FUNCTION [LES].[Func_Get_TWD_RUNSHEET_NO](
	@PLANT			NVARCHAR(5), 
	@SUPPLIER_NUM	NVARCHAR(12), 
	@ORDER_NO		NVARCHAR(10), 
	@ITEM_NO		NVARCHAR(10), 
	@WAREHOUSE		NVARCHAR(50), 
	@PART_NO		NVARCHAR(20), 
	@CREATE_DATE	DATETIME
)  
RETURNS   NVARCHAR(2000)   
AS   
BEGIN   

	DECLARE		@RUNSHEET_NO_SET   NVARCHAR(MAX)  
	SET			@RUNSHEET_NO_SET = ''   
	
	SELECT @RUNSHEET_NO_SET=LTRIM(RTRIM(STUFF((SELECT DISTINCT ','+ISNULL(PULL_SHEET_NO,'*') FROM [LES].[TI_TWD_RECEIVED_GOODS] A
    WHERE A.[PLANT] = @PLANT
	AND	A.[SUPPLIER_NUM] = @SUPPLIER_NUM
	AND	ISNULL(A.[ORDER_NO], '') = ISNULL(@ORDER_NO, '')
	AND	ISNULL(A.[ITEM_NO], '') = ISNULL(@ITEM_NO,'')
	AND	ISNULL(A.[WAREHOUSE],'') = ISNULL(@WAREHOUSE, '')
	AND	A.[PART_NO] = @PART_NO
	AND	A.[CREATE_DATE] <= @CREATE_DATE
	AND	A.[INTERFACE_TYPE] = 'TWD'
	AND	A.[INTERFACE_STATUS] IS NULL
    FOR XML PATH('')),1,1,'')))
    
    
	IF(LEN(@RUNSHEET_NO_SET)>2000)
		RETURN SUBSTRING(@RUNSHEET_NO_SET,1,2000)
	RETURN @RUNSHEET_NO_SET
END