#region Declaim
//---------------------------------------------------------------------------
// Name:		InterfaceConfigDAL
// Function: 	Expose data in table TS_SYS_INTERFACE_CONFIG from database as business object to MES system.
// Tool:		T4
// CreateDate:	2020年3月9日
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------
#endregion

#region Imported Namespace

using DM.SYS;
using Infrustructure.Data;
using Infrustructure.Utilities;
using Microsoft.Practices.EnterpriseLibrary.Data;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
          
#endregion

namespace DAL.SYS 
{     
	//// <summary>
    /// InterfaceConfigDAL对应表[TS_SYS_INTERFACE_CONFIG]
    /// </summary>
    public partial class InterfaceConfigDAL : BusinessObjectProvider<InterfaceConfigInfo>
	{
		#region Sql Statements
		private const string TS_SYS_INTERFACE_CONFIG_SELECT_BY_ID =
			@"SELECT INTERFACE_CODE,
				METHROD_NAME,
				SYS_METHROD_NAME,
				CALL_URL,
				USER_NAME,
				PASS_WORD,
				SYS_NAME,
				PARAM1,
				PARAM2,
				PARAM3,
				CREATE_USER,
				MODIFY_DATE,
				ID,
				CREATE_DATE,
				FID,
				MODIFY_USER,
				VALID_FLAG				  
				FROM [dbo].[TS_SYS_INTERFACE_CONFIG] WITH(NOLOCK) WHERE [VALID_FLAG] = 1 AND ID =@ID;";
			
		private const string TS_SYS_INTERFACE_CONFIG_SELECT = 
			@"SELECT INTERFACE_CODE,
				METHROD_NAME,
				SYS_METHROD_NAME,
				CALL_URL,
				USER_NAME,
				PASS_WORD,
				SYS_NAME,
				PARAM1,
				PARAM2,
				PARAM3,
				CREATE_USER,
				MODIFY_DATE,
				ID,
				CREATE_DATE,
				FID,
				MODIFY_USER,
				VALID_FLAG				 
				FROM [dbo].[TS_SYS_INTERFACE_CONFIG] WITH (NOLOCK) WHERE [VALID_FLAG] = 1 {0};";
		
		private const string TS_SYS_INTERFACE_CONFIG_SELECT_COUNTS = 
			@"SELECT count(*) FROM [dbo].[TS_SYS_INTERFACE_CONFIG]  WITH(NOLOCK) WHERE [VALID_FLAG] = 1 {0};";

		private const string TS_SYS_INTERFACE_CONFIG_INSERT =
			@"INSERT INTO [dbo].[TS_SYS_INTERFACE_CONFIG] (
				INTERFACE_CODE,
				METHROD_NAME,
				SYS_METHROD_NAME,
				CALL_URL,
				USER_NAME,
				PASS_WORD,
				SYS_NAME,
				PARAM1,
				PARAM2,
				PARAM3,
				CREATE_USER,
				MODIFY_DATE,
				CREATE_DATE,
				FID,
				MODIFY_USER,
				VALID_FLAG				 
			) VALUES (
				@INTERFACE_CODE,
				@METHROD_NAME,
				@SYS_METHROD_NAME,
				@CALL_URL,
				@USER_NAME,
				@PASS_WORD,
				@SYS_NAME,
				@PARAM1,
				@PARAM2,
				@PARAM3,
				@CREATE_USER,
				@MODIFY_DATE,
				@CREATE_DATE,
				@FID,
				@MODIFY_USER,
				@VALID_FLAG				 
			);SELECT @@IDENTITY;";
		private const string TS_SYS_INTERFACE_CONFIG_UPDATE =
			@"UPDATE [dbo].[TS_SYS_INTERFACE_CONFIG] WITH(ROWLOCK) 
				SET INTERFACE_CODE=@INTERFACE_CODE,
				METHROD_NAME=@METHROD_NAME,
				SYS_METHROD_NAME=@SYS_METHROD_NAME,
				CALL_URL=@CALL_URL,
				USER_NAME=@USER_NAME,
				PASS_WORD=@PASS_WORD,
				SYS_NAME=@SYS_NAME,
				PARAM1=@PARAM1,
				PARAM2=@PARAM2,
				PARAM3=@PARAM3,
				CREATE_USER=@CREATE_USER,
				MODIFY_DATE=@MODIFY_DATE,
				CREATE_DATE=@CREATE_DATE,
				FID=@FID,
				MODIFY_USER=@MODIFY_USER,
				VALID_FLAG=@VALID_FLAG				 
				WHERE [VALID_FLAG] = 1 AND ID =@ID;";

		private const string TS_SYS_INTERFACE_CONFIG_DELETE =
			@"DELETE FROM [dbo].[TS_SYS_INTERFACE_CONFIG] WITH(ROWLOCK)  
				WHERE [VALID_FLAG] = 1 AND ID =@ID;";
		#endregion
		 
		#region Access Methods
		 
		/// <summary>
		/// Get InterfaceConfigInfo
		/// </summary>
		/// <param name="ID">InterfaceConfigInfo Primary key </param>
		/// <returns></returns> 
		public InterfaceConfigInfo GetInfo(long aId)
		{	
			Database db = DatabaseFactory.CreateDatabase();
			DbCommand dbCommand = db.GetSqlStringCommand(TS_SYS_INTERFACE_CONFIG_SELECT_BY_ID);
			db.AddInParameter(dbCommand, "@ID", DbType.Int64, aId);
			using (IDataReader dr = db.ExecuteReader(dbCommand))
			{
				if (dr.Read())
					return CreateInterfaceConfigInfo(dr);
			}
			return null;
		}
		/// <summary>
		/// Get data collection
		/// </summary>
		/// <param name="textWhere">Conditon</param>
		/// <param name="orderText">Sort</param>
		/// <returns>InterfaceConfigInfo Collection </returns>
		public List<InterfaceConfigInfo> GetList(string textWhere,string orderText)
		{
			string query = string.Empty;
			if (string.IsNullOrEmpty(textWhere))
				query = string.Empty;
			else
			{				
				if (textWhere.Trim().StartsWith("and", StringComparison.OrdinalIgnoreCase))
					query = textWhere;
				else
					query = " and " + textWhere;
			}
			if (!string.IsNullOrEmpty(orderText))
				query += " order by " + orderText;
			
			return GetList(string.Format(TS_SYS_INTERFACE_CONFIG_SELECT, query));
		}		
		/// <summary>
		/// Get data collection
		/// </summary>
		/// <param name="sql">SQL Statement</param>
		/// <returns>InterfaceConfigInfo Collection </returns>
		public List<InterfaceConfigInfo> GetList(string sql)
		{
			Database db = DatabaseFactory.CreateDatabase();
			DbCommand dbCommand = db.GetSqlStringCommand(sql);
			List<InterfaceConfigInfo> list = new List<InterfaceConfigInfo>();
			using (IDataReader dr = db.ExecuteReader(dbCommand))
			{
				while (dr.Read())
				{
					list.Add(CreateInterfaceConfigInfo(dr));
				}
			}
			return list;
		}		
		/// <summary>
        /// 分页查询
        /// </summary>        
        /// <param name="textWhere">查询条件</param>
        /// <param name="orderText">排序字段</param>
        /// <param name="startRowIndex">当前页第一行行号</param>                    
        /// <param name="maximumRows">每页记录数</param>        
        /// <returns></returns>
		public List<InterfaceConfigInfo> GetListByPage(string textWhere, string textOrder, int pageIndex, int pageRow)
		{
		    if (pageIndex <= 0) pageIndex = 1;
            if (pageRow <= 0) pageRow = 10;
			string whereText = string.Empty;
            if (!string.IsNullOrEmpty(textWhere))
            {
                if (textWhere.Trim().StartsWith("and", StringComparison.OrdinalIgnoreCase))
                    whereText += " where [VALID_FLAG] = 1 " + textWhere;
                else
                    whereText += " where " + textWhere + " and [VALID_FLAG] = 1";
            }
			else
                whereText += " where [VALID_FLAG] = 1 ";
            if (string.IsNullOrEmpty(textOrder))
                textOrder += "[ID] desc";
            string sql = "select top " + pageRow + " * from "
                + "(select row_number() over(order by " + textOrder + ") as rownumber"
                + ",* from [dbo].[TS_SYS_INTERFACE_CONFIG]  WITH(NOLOCK) " + whereText + ") T "
                + "where rownumber > " + (pageIndex - 1) * pageRow + " ";
            Database db = DatabaseFactory.CreateDatabase();
            DbCommand dbCommand = db.GetSqlStringCommand(sql);
            List<InterfaceConfigInfo> list = new List<InterfaceConfigInfo>();
            using (IDataReader dr = db.ExecuteReader(dbCommand))
            {
                while (dr.Read())
                {
                    list.Add(CreateInterfaceConfigInfo(dr));
                }
            }
            return list;
		}
		/// <summary>
        /// 分页查询
        /// </summary>        
        /// <param name="textWhere">查询条件</param>
        /// <param name="orderText">排序字段</param>            
        /// <returns></returns>
        public int GetCounts(string textWhere)
        {			
			if (string.IsNullOrEmpty(textWhere))
				textWhere = string.Empty;
			else
			{				
				if (!textWhere.Trim().StartsWith("and", StringComparison.OrdinalIgnoreCase))
					textWhere = " and " + textWhere;						
			}
			Database db = DatabaseFactory.CreateDatabase();
            DbCommand cmd = db.GetSqlStringCommand(string.Format(TS_SYS_INTERFACE_CONFIG_SELECT_COUNTS, textWhere));
			return Convert.ToInt32(db.ExecuteScalar(cmd));            
        }
		/// <summary>
		/// Add
		/// </summary>
		/// <param name="info"> info</param>
		public long Add(InterfaceConfigInfo info)
		{ 
			Database db = DatabaseFactory.CreateDatabase();	
			DbCommand dbCommand = db.GetSqlStringCommand(TS_SYS_INTERFACE_CONFIG_INSERT);			
			db.AddInParameter(dbCommand, "@INTERFACE_CODE", DbType.String, info.InterfaceCode);
			db.AddInParameter(dbCommand, "@METHROD_NAME", DbType.String, info.MethrodName);
			db.AddInParameter(dbCommand, "@SYS_METHROD_NAME", DbType.String, info.SysMethrodName);
			db.AddInParameter(dbCommand, "@CALL_URL", DbType.String, info.CallUrl);
			db.AddInParameter(dbCommand, "@USER_NAME", DbType.String, info.UserName);
			db.AddInParameter(dbCommand, "@PASS_WORD", DbType.String, info.PassWord);
			db.AddInParameter(dbCommand, "@SYS_NAME", DbType.String, info.SysName);
			db.AddInParameter(dbCommand, "@PARAM1", DbType.String, info.Param1);
			db.AddInParameter(dbCommand, "@PARAM2", DbType.String, info.Param2);
			db.AddInParameter(dbCommand, "@PARAM3", DbType.String, info.Param3);
			db.AddInParameter(dbCommand, "@CREATE_USER", DbType.String, info.CreateUser);
			db.AddInParameter(dbCommand, "@MODIFY_DATE", DbType.DateTime, info.ModifyDate);
			db.AddInParameter(dbCommand, "@CREATE_DATE", DbType.DateTime, info.CreateDate);
			db.AddInParameter(dbCommand, "@FID", DbType.Guid, info.Fid);
			db.AddInParameter(dbCommand, "@MODIFY_USER", DbType.String, info.ModifyUser);
			db.AddInParameter(dbCommand, "@VALID_FLAG", DbType.Boolean, info.ValidFlag);
			return long.Parse("0" + db.ExecuteScalar(dbCommand));		
		}		
		/// <summary>
		/// GetInsertSql
		/// </summary>
		/// <param name="info"> info</param>
		public static string GetInsertSql(InterfaceConfigInfo info)
		{
			return  
			@"insert into [dbo].[TS_SYS_INTERFACE_CONFIG] (
				INTERFACE_CODE,
				METHROD_NAME,
				SYS_METHROD_NAME,
				CALL_URL,
				USER_NAME,
				PASS_WORD,
				SYS_NAME,
				PARAM1,
				PARAM2,
				PARAM3,
				CREATE_USER,
				MODIFY_DATE,
				CREATE_DATE,
				FID,
				MODIFY_USER,
				VALID_FLAG				 
			) values ("+
				(string.IsNullOrEmpty(info.InterfaceCode) ? "NULL" : "N'" + info.InterfaceCode + "'") + ","+
				(string.IsNullOrEmpty(info.MethrodName) ? "NULL" : "N'" + info.MethrodName + "'") + ","+
				(string.IsNullOrEmpty(info.SysMethrodName) ? "NULL" : "N'" + info.SysMethrodName + "'") + ","+
				(string.IsNullOrEmpty(info.CallUrl) ? "NULL" : "N'" + info.CallUrl + "'") + ","+
				(string.IsNullOrEmpty(info.UserName) ? "NULL" : "N'" + info.UserName + "'") + ","+
				(string.IsNullOrEmpty(info.PassWord) ? "NULL" : "N'" + info.PassWord + "'") + ","+
				(string.IsNullOrEmpty(info.SysName) ? "NULL" : "N'" + info.SysName + "'") + ","+
				(string.IsNullOrEmpty(info.Param1) ? "NULL" : "N'" + info.Param1 + "'") + ","+
				(string.IsNullOrEmpty(info.Param2) ? "NULL" : "N'" + info.Param2 + "'") + ","+
				(string.IsNullOrEmpty(info.Param3) ? "NULL" : "N'" + info.Param3 + "'") + ","+
				"N'" + info.CreateUser + "'" + ","+		
				"NULL" + ","+			
				"GETDATE()" + ","+			
				(info.Fid == null ? "NEWID()" : "N'" + info.Fid.GetValueOrDefault() + "'") + ","+
				"NULL" + ","+			
				"1" + ");";		
				}
		/// <summary>
		/// Update
		/// </summary>
		/// <param name="info">info</param>
		public int Update(InterfaceConfigInfo info)
		{
			Database db = DatabaseFactory.CreateDatabase();
			DbCommand dbCommand = db.GetSqlStringCommand(TS_SYS_INTERFACE_CONFIG_UPDATE);				
			db.AddInParameter(dbCommand, "@INTERFACE_CODE", DbType.String, info.InterfaceCode);
			db.AddInParameter(dbCommand, "@METHROD_NAME", DbType.String, info.MethrodName);
			db.AddInParameter(dbCommand, "@SYS_METHROD_NAME", DbType.String, info.SysMethrodName);
			db.AddInParameter(dbCommand, "@CALL_URL", DbType.String, info.CallUrl);
			db.AddInParameter(dbCommand, "@USER_NAME", DbType.String, info.UserName);
			db.AddInParameter(dbCommand, "@PASS_WORD", DbType.String, info.PassWord);
			db.AddInParameter(dbCommand, "@SYS_NAME", DbType.String, info.SysName);
			db.AddInParameter(dbCommand, "@PARAM1", DbType.String, info.Param1);
			db.AddInParameter(dbCommand, "@PARAM2", DbType.String, info.Param2);
			db.AddInParameter(dbCommand, "@PARAM3", DbType.String, info.Param3);
			db.AddInParameter(dbCommand, "@CREATE_USER", DbType.String, info.CreateUser);
			db.AddInParameter(dbCommand, "@MODIFY_DATE", DbType.DateTime, info.ModifyDate);
			db.AddInParameter(dbCommand, "@ID", DbType.Int64, info.Id);
			db.AddInParameter(dbCommand, "@CREATE_DATE", DbType.DateTime, info.CreateDate);
			db.AddInParameter(dbCommand, "@FID", DbType.Guid, info.Fid);
			db.AddInParameter(dbCommand, "@MODIFY_USER", DbType.String, info.ModifyUser);
			db.AddInParameter(dbCommand, "@VALID_FLAG", DbType.Boolean, info.ValidFlag);
			return int.Parse("0" + db.ExecuteNonQuery(dbCommand));
		}		
		/// <summary>
		/// Delete
		/// </summary>
		/// <param name="ID">InterfaceConfigInfo Primary key </param>
		/// <returns></returns>
		public int Delete(long aId)
		{
			Database db = DatabaseFactory.CreateDatabase();
			DbCommand dbCommand = db.GetSqlStringCommand(TS_SYS_INTERFACE_CONFIG_DELETE);
		    db.AddInParameter(dbCommand, "@ID", DbType.Int64, aId);
			return int.Parse("0" + db.ExecuteNonQuery(dbCommand));
		}/// <summary>
		/// LogciDelete
		/// </summary>
		/// <param name="ID">InterfaceConfigInfo Primary key </param>
		/// <returns></returns>
		public int LogicDelete(long aId, string loginUser)
		{
		    string sql = "update [dbo].[TS_SYS_INTERFACE_CONFIG] WITH(ROWLOCK) "
                + "set [VALID_FLAG] = @VALID_FLAG ,[MODIFY_USER] = @MODIFY_USER ,[MODIFY_DATE] = GETDATE() "
                + "WHERE [VALID_FLAG] = 1 AND ID =@ID;";
			Database db = DatabaseFactory.CreateDatabase();
			DbCommand dbCommand = db.GetSqlStringCommand(sql);
             			db.AddInParameter(dbCommand, "@ID", DbType.Int64, aId);
    db.AddInParameter(dbCommand, "@VALID_FLAG", DbType.Boolean, false);
			db.AddInParameter(dbCommand, "@MODIFY_USER", DbType.AnsiString, loginUser);
			return int.Parse("0" + db.ExecuteNonQuery(dbCommand));
		}
		/// <summary>
		/// UpdateInfo
		/// </summary>
		/// <param name="ID">InterfaceConfigInfo Primary key </param>
		/// <returns></returns>
		public int UpdateInfo(string fields ,long aId)
		{
		    string sql = "update [dbo].[TS_SYS_INTERFACE_CONFIG] WITH(ROWLOCK) "
                + "set " + fields
                + "WHERE [VALID_FLAG] = 1 AND ID =@ID;";
			Database db = DatabaseFactory.CreateDatabase();
			DbCommand dbCommand = db.GetSqlStringCommand(sql);
			db.AddInParameter(dbCommand, "@ID", DbType.Int64, aId);
			return int.Parse("0" + db.ExecuteNonQuery(dbCommand));
		}		
		#endregion
		  
		#region Helpers   
	  
		private static InterfaceConfigInfo CreateInterfaceConfigInfo(IDataReader rdr)
		{
			InterfaceConfigInfo info = new InterfaceConfigInfo();
			info.InterfaceCode = DBConvert.GetString(rdr, rdr.GetOrdinal("INTERFACE_CODE"));			
			info.MethrodName = DBConvert.GetString(rdr, rdr.GetOrdinal("METHROD_NAME"));			
			info.SysMethrodName = DBConvert.GetString(rdr, rdr.GetOrdinal("SYS_METHROD_NAME"));			
			info.CallUrl = DBConvert.GetString(rdr, rdr.GetOrdinal("CALL_URL"));			
			info.UserName = DBConvert.GetString(rdr, rdr.GetOrdinal("USER_NAME"));			
			info.PassWord = DBConvert.GetString(rdr, rdr.GetOrdinal("PASS_WORD"));			
			info.SysName = DBConvert.GetString(rdr, rdr.GetOrdinal("SYS_NAME"));			
			info.Param1 = DBConvert.GetString(rdr, rdr.GetOrdinal("PARAM1"));			
			info.Param2 = DBConvert.GetString(rdr, rdr.GetOrdinal("PARAM2"));			
			info.Param3 = DBConvert.GetString(rdr, rdr.GetOrdinal("PARAM3"));			
			info.CreateUser = DBConvert.GetString(rdr, rdr.GetOrdinal("CREATE_USER"));			
			info.ModifyDate = DBConvert.GetDateTimeNullable(rdr, rdr.GetOrdinal("MODIFY_DATE"));			
			info.Id = DBConvert.GetInt64(rdr, rdr.GetOrdinal("ID"));			
			info.CreateDate = DBConvert.GetDateTimeNullable(rdr, rdr.GetOrdinal("CREATE_DATE"));			
			info.Fid = DBConvert.GetGuidNullable(rdr, rdr.GetOrdinal("FID"));			
			info.ModifyUser = DBConvert.GetString(rdr, rdr.GetOrdinal("MODIFY_USER"));			
			info.ValidFlag = DBConvert.GetBoolNullable(rdr, rdr.GetOrdinal("VALID_FLAG"));			
			return info;
		}
		
		#endregion
	}
}
