#region Declaim
//---------------------------------------------------------------------------
// Name:		MenuDAL
// Function: 	Expose data in table TS_SYS_MENU from database as business object to MES system.
// Tool:		T4
// CreateDate:	2020年3月9日
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------
#endregion

#region Imported Namespace

using DM.SYS;
using Infrustructure.Data;
using Infrustructure.Utilities;
using Microsoft.Practices.EnterpriseLibrary.Data;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
          
#endregion

namespace DAL.SYS 
{     
	//// <summary>
    /// MenuDAL对应表[TS_SYS_MENU]
    /// </summary>
    public partial class MenuDAL : BusinessObjectProvider<MenuInfo>
	{
		#region Sql Statements
		private const string TS_SYS_MENU_SELECT_BY_ID =
			@"SELECT MENU_NAME,
				DISPLAY_ORDER,
				IMAGE_URL,
				LINK_URL,
				COMMENTS,
				MENU_TYPE,
				NEED_AUTH,
				MENU_NAME_CN,
				FAVORITE_PIC,
				EDIT_FORM_WIDTH,
				EDIT_FORM_HEIGHT,
				VALID_FLAG,
				CREATE_DATE,
				ID,
				PARENT_MENU_FID,
				MODIFY_USER,
				FID,
				CREATE_USER,
				MODIFY_DATE				  
				FROM [dbo].[TS_SYS_MENU] WITH(NOLOCK) WHERE [VALID_FLAG] = 1 AND ID =@ID;";
			
		private const string TS_SYS_MENU_SELECT = 
			@"SELECT MENU_NAME,
				DISPLAY_ORDER,
				IMAGE_URL,
				LINK_URL,
				COMMENTS,
				MENU_TYPE,
				NEED_AUTH,
				MENU_NAME_CN,
				FAVORITE_PIC,
				EDIT_FORM_WIDTH,
				EDIT_FORM_HEIGHT,
				VALID_FLAG,
				CREATE_DATE,
				ID,
				PARENT_MENU_FID,
				MODIFY_USER,
				FID,
				CREATE_USER,
				MODIFY_DATE				 
				FROM [dbo].[TS_SYS_MENU] WITH (NOLOCK) WHERE [VALID_FLAG] = 1 {0};";
		
		private const string TS_SYS_MENU_SELECT_COUNTS = 
			@"SELECT count(*) FROM [dbo].[TS_SYS_MENU]  WITH(NOLOCK) WHERE [VALID_FLAG] = 1 {0};";

		private const string TS_SYS_MENU_INSERT =
			@"INSERT INTO [dbo].[TS_SYS_MENU] (
				MENU_NAME,
				DISPLAY_ORDER,
				IMAGE_URL,
				LINK_URL,
				COMMENTS,
				MENU_TYPE,
				NEED_AUTH,
				MENU_NAME_CN,
				FAVORITE_PIC,
				EDIT_FORM_WIDTH,
				EDIT_FORM_HEIGHT,
				VALID_FLAG,
				CREATE_DATE,
				PARENT_MENU_FID,
				MODIFY_USER,
				FID,
				CREATE_USER,
				MODIFY_DATE				 
			) VALUES (
				@MENU_NAME,
				@DISPLAY_ORDER,
				@IMAGE_URL,
				@LINK_URL,
				@COMMENTS,
				@MENU_TYPE,
				@NEED_AUTH,
				@MENU_NAME_CN,
				@FAVORITE_PIC,
				@EDIT_FORM_WIDTH,
				@EDIT_FORM_HEIGHT,
				@VALID_FLAG,
				@CREATE_DATE,
				@PARENT_MENU_FID,
				@MODIFY_USER,
				@FID,
				@CREATE_USER,
				@MODIFY_DATE				 
			);SELECT @@IDENTITY;";
		private const string TS_SYS_MENU_UPDATE =
			@"UPDATE [dbo].[TS_SYS_MENU] WITH(ROWLOCK) 
				SET MENU_NAME=@MENU_NAME,
				DISPLAY_ORDER=@DISPLAY_ORDER,
				IMAGE_URL=@IMAGE_URL,
				LINK_URL=@LINK_URL,
				COMMENTS=@COMMENTS,
				MENU_TYPE=@MENU_TYPE,
				NEED_AUTH=@NEED_AUTH,
				MENU_NAME_CN=@MENU_NAME_CN,
				FAVORITE_PIC=@FAVORITE_PIC,
				EDIT_FORM_WIDTH=@EDIT_FORM_WIDTH,
				EDIT_FORM_HEIGHT=@EDIT_FORM_HEIGHT,
				VALID_FLAG=@VALID_FLAG,
				CREATE_DATE=@CREATE_DATE,
				PARENT_MENU_FID=@PARENT_MENU_FID,
				MODIFY_USER=@MODIFY_USER,
				FID=@FID,
				CREATE_USER=@CREATE_USER,
				MODIFY_DATE=@MODIFY_DATE				 
				WHERE [VALID_FLAG] = 1 AND ID =@ID;";

		private const string TS_SYS_MENU_DELETE =
			@"DELETE FROM [dbo].[TS_SYS_MENU] WITH(ROWLOCK)  
				WHERE [VALID_FLAG] = 1 AND ID =@ID;";
		#endregion
		 
		#region Access Methods
		 
		/// <summary>
		/// Get MenuInfo
		/// </summary>
		/// <param name="ID">MenuInfo Primary key </param>
		/// <returns></returns> 
		public MenuInfo GetInfo(long aId)
		{	
			Database db = DatabaseFactory.CreateDatabase();
			DbCommand dbCommand = db.GetSqlStringCommand(TS_SYS_MENU_SELECT_BY_ID);
			db.AddInParameter(dbCommand, "@ID", DbType.Int64, aId);
			using (IDataReader dr = db.ExecuteReader(dbCommand))
			{
				if (dr.Read())
					return CreateMenuInfo(dr);
			}
			return null;
		}
		/// <summary>
		/// Get data collection
		/// </summary>
		/// <param name="textWhere">Conditon</param>
		/// <param name="orderText">Sort</param>
		/// <returns>MenuInfo Collection </returns>
		public List<MenuInfo> GetList(string textWhere,string orderText)
		{
			string query = string.Empty;
			if (string.IsNullOrEmpty(textWhere))
				query = string.Empty;
			else
			{				
				if (textWhere.Trim().StartsWith("and", StringComparison.OrdinalIgnoreCase))
					query = textWhere;
				else
					query = " and " + textWhere;
			}
			if (!string.IsNullOrEmpty(orderText))
				query += " order by " + orderText;
			
			return GetList(string.Format(TS_SYS_MENU_SELECT, query));
		}		
		/// <summary>
		/// Get data collection
		/// </summary>
		/// <param name="sql">SQL Statement</param>
		/// <returns>MenuInfo Collection </returns>
		public List<MenuInfo> GetList(string sql)
		{
			Database db = DatabaseFactory.CreateDatabase();
			DbCommand dbCommand = db.GetSqlStringCommand(sql);
			List<MenuInfo> list = new List<MenuInfo>();
			using (IDataReader dr = db.ExecuteReader(dbCommand))
			{
				while (dr.Read())
				{
					list.Add(CreateMenuInfo(dr));
				}
			}
			return list;
		}		
		/// <summary>
        /// 分页查询
        /// </summary>        
        /// <param name="textWhere">查询条件</param>
        /// <param name="orderText">排序字段</param>
        /// <param name="startRowIndex">当前页第一行行号</param>                    
        /// <param name="maximumRows">每页记录数</param>        
        /// <returns></returns>
		public List<MenuInfo> GetListByPage(string textWhere, string textOrder, int pageIndex, int pageRow)
		{
		    if (pageIndex <= 0) pageIndex = 1;
            if (pageRow <= 0) pageRow = 10;
			string whereText = string.Empty;
            if (!string.IsNullOrEmpty(textWhere))
            {
                if (textWhere.Trim().StartsWith("and", StringComparison.OrdinalIgnoreCase))
                    whereText += " where [VALID_FLAG] = 1 " + textWhere;
                else
                    whereText += " where " + textWhere + " and [VALID_FLAG] = 1";
            }
			else
                whereText += " where [VALID_FLAG] = 1 ";
            if (string.IsNullOrEmpty(textOrder))
                textOrder += "[ID] desc";
            string sql = "select top " + pageRow + " * from "
                + "(select row_number() over(order by " + textOrder + ") as rownumber"
                + ",* from [dbo].[TS_SYS_MENU]  WITH(NOLOCK) " + whereText + ") T "
                + "where rownumber > " + (pageIndex - 1) * pageRow + " ";
            Database db = DatabaseFactory.CreateDatabase();
            DbCommand dbCommand = db.GetSqlStringCommand(sql);
            List<MenuInfo> list = new List<MenuInfo>();
            using (IDataReader dr = db.ExecuteReader(dbCommand))
            {
                while (dr.Read())
                {
                    list.Add(CreateMenuInfo(dr));
                }
            }
            return list;
		}
		/// <summary>
        /// 分页查询
        /// </summary>        
        /// <param name="textWhere">查询条件</param>
        /// <param name="orderText">排序字段</param>            
        /// <returns></returns>
        public int GetCounts(string textWhere)
        {			
			if (string.IsNullOrEmpty(textWhere))
				textWhere = string.Empty;
			else
			{				
				if (!textWhere.Trim().StartsWith("and", StringComparison.OrdinalIgnoreCase))
					textWhere = " and " + textWhere;						
			}
			Database db = DatabaseFactory.CreateDatabase();
            DbCommand cmd = db.GetSqlStringCommand(string.Format(TS_SYS_MENU_SELECT_COUNTS, textWhere));
			return Convert.ToInt32(db.ExecuteScalar(cmd));            
        }
		/// <summary>
		/// Add
		/// </summary>
		/// <param name="info"> info</param>
		public long Add(MenuInfo info)
		{ 
			Database db = DatabaseFactory.CreateDatabase();	
			DbCommand dbCommand = db.GetSqlStringCommand(TS_SYS_MENU_INSERT);			
			db.AddInParameter(dbCommand, "@MENU_NAME", DbType.String, info.MenuName);
			db.AddInParameter(dbCommand, "@DISPLAY_ORDER", DbType.Int32, info.DisplayOrder);
			db.AddInParameter(dbCommand, "@IMAGE_URL", DbType.String, info.ImageUrl);
			db.AddInParameter(dbCommand, "@LINK_URL", DbType.String, info.LinkUrl);
			db.AddInParameter(dbCommand, "@COMMENTS", DbType.String, info.Comments);
			db.AddInParameter(dbCommand, "@MENU_TYPE", DbType.Int32, info.MenuType);
			db.AddInParameter(dbCommand, "@NEED_AUTH", DbType.Boolean, info.NeedAuth);
			db.AddInParameter(dbCommand, "@MENU_NAME_CN", DbType.String, info.MenuNameCn);
			db.AddInParameter(dbCommand, "@FAVORITE_PIC", DbType.String, info.FavoritePic);
			db.AddInParameter(dbCommand, "@EDIT_FORM_WIDTH", DbType.Int32, info.EditFormWidth);
			db.AddInParameter(dbCommand, "@EDIT_FORM_HEIGHT", DbType.Int32, info.EditFormHeight);
			db.AddInParameter(dbCommand, "@VALID_FLAG", DbType.Boolean, info.ValidFlag);
			db.AddInParameter(dbCommand, "@CREATE_DATE", DbType.DateTime, info.CreateDate);
			db.AddInParameter(dbCommand, "@PARENT_MENU_FID", DbType.Guid, info.ParentMenuFid);
			db.AddInParameter(dbCommand, "@MODIFY_USER", DbType.String, info.ModifyUser);
			db.AddInParameter(dbCommand, "@FID", DbType.Guid, info.Fid);
			db.AddInParameter(dbCommand, "@CREATE_USER", DbType.String, info.CreateUser);
			db.AddInParameter(dbCommand, "@MODIFY_DATE", DbType.DateTime, info.ModifyDate);
			return long.Parse("0" + db.ExecuteScalar(dbCommand));		
		}		
		/// <summary>
		/// GetInsertSql
		/// </summary>
		/// <param name="info"> info</param>
		public static string GetInsertSql(MenuInfo info)
		{
			return  
			@"insert into [dbo].[TS_SYS_MENU] (
				MENU_NAME,
				DISPLAY_ORDER,
				IMAGE_URL,
				LINK_URL,
				COMMENTS,
				MENU_TYPE,
				NEED_AUTH,
				MENU_NAME_CN,
				FAVORITE_PIC,
				EDIT_FORM_WIDTH,
				EDIT_FORM_HEIGHT,
				VALID_FLAG,
				CREATE_DATE,
				PARENT_MENU_FID,
				MODIFY_USER,
				FID,
				CREATE_USER,
				MODIFY_DATE				 
			) values ("+
				(string.IsNullOrEmpty(info.MenuName) ? "NULL" : "N'" + info.MenuName + "'") + ","+
				(info.DisplayOrder == null ? "NULL" : "" + info.DisplayOrder.GetValueOrDefault() + "") + ","+
				(string.IsNullOrEmpty(info.ImageUrl) ? "NULL" : "N'" + info.ImageUrl + "'") + ","+
				(string.IsNullOrEmpty(info.LinkUrl) ? "NULL" : "N'" + info.LinkUrl + "'") + ","+
				(string.IsNullOrEmpty(info.Comments) ? "NULL" : "N'" + info.Comments + "'") + ","+
				(info.MenuType == null ? "NULL" : "" + info.MenuType.GetValueOrDefault() + "") + ","+
				(info.NeedAuth == null ? "NULL" : "" + (info.NeedAuth.GetValueOrDefault() ? "1" : "0") + "") + ","+
				(string.IsNullOrEmpty(info.MenuNameCn) ? "NULL" : "N'" + info.MenuNameCn + "'") + ","+
				(string.IsNullOrEmpty(info.FavoritePic) ? "NULL" : "N'" + info.FavoritePic + "'") + ","+
				(info.EditFormWidth == null ? "NULL" : "" + info.EditFormWidth.GetValueOrDefault() + "") + ","+
				(info.EditFormHeight == null ? "NULL" : "" + info.EditFormHeight.GetValueOrDefault() + "") + ","+
				"1" + ","+		
				"GETDATE()" + ","+			
				(info.ParentMenuFid == null ? "NULL" : "N'" + info.ParentMenuFid.GetValueOrDefault() + "'") + ","+
				"NULL" + ","+			
				(info.Fid == null ? "NEWID()" : "N'" + info.Fid.GetValueOrDefault() + "'") + ","+
				"N'" + info.CreateUser + "'" + ","+		
				"NULL" + ");";			
				}
		/// <summary>
		/// Update
		/// </summary>
		/// <param name="info">info</param>
		public int Update(MenuInfo info)
		{
			Database db = DatabaseFactory.CreateDatabase();
			DbCommand dbCommand = db.GetSqlStringCommand(TS_SYS_MENU_UPDATE);				
			db.AddInParameter(dbCommand, "@MENU_NAME", DbType.String, info.MenuName);
			db.AddInParameter(dbCommand, "@DISPLAY_ORDER", DbType.Int32, info.DisplayOrder);
			db.AddInParameter(dbCommand, "@IMAGE_URL", DbType.String, info.ImageUrl);
			db.AddInParameter(dbCommand, "@LINK_URL", DbType.String, info.LinkUrl);
			db.AddInParameter(dbCommand, "@COMMENTS", DbType.String, info.Comments);
			db.AddInParameter(dbCommand, "@MENU_TYPE", DbType.Int32, info.MenuType);
			db.AddInParameter(dbCommand, "@NEED_AUTH", DbType.Boolean, info.NeedAuth);
			db.AddInParameter(dbCommand, "@MENU_NAME_CN", DbType.String, info.MenuNameCn);
			db.AddInParameter(dbCommand, "@FAVORITE_PIC", DbType.String, info.FavoritePic);
			db.AddInParameter(dbCommand, "@EDIT_FORM_WIDTH", DbType.Int32, info.EditFormWidth);
			db.AddInParameter(dbCommand, "@EDIT_FORM_HEIGHT", DbType.Int32, info.EditFormHeight);
			db.AddInParameter(dbCommand, "@VALID_FLAG", DbType.Boolean, info.ValidFlag);
			db.AddInParameter(dbCommand, "@CREATE_DATE", DbType.DateTime, info.CreateDate);
			db.AddInParameter(dbCommand, "@ID", DbType.Int64, info.Id);
			db.AddInParameter(dbCommand, "@PARENT_MENU_FID", DbType.Guid, info.ParentMenuFid);
			db.AddInParameter(dbCommand, "@MODIFY_USER", DbType.String, info.ModifyUser);
			db.AddInParameter(dbCommand, "@FID", DbType.Guid, info.Fid);
			db.AddInParameter(dbCommand, "@CREATE_USER", DbType.String, info.CreateUser);
			db.AddInParameter(dbCommand, "@MODIFY_DATE", DbType.DateTime, info.ModifyDate);
			return int.Parse("0" + db.ExecuteNonQuery(dbCommand));
		}		
		/// <summary>
		/// Delete
		/// </summary>
		/// <param name="ID">MenuInfo Primary key </param>
		/// <returns></returns>
		public int Delete(long aId)
		{
			Database db = DatabaseFactory.CreateDatabase();
			DbCommand dbCommand = db.GetSqlStringCommand(TS_SYS_MENU_DELETE);
		    db.AddInParameter(dbCommand, "@ID", DbType.Int64, aId);
			return int.Parse("0" + db.ExecuteNonQuery(dbCommand));
		}/// <summary>
		/// LogciDelete
		/// </summary>
		/// <param name="ID">MenuInfo Primary key </param>
		/// <returns></returns>
		public int LogicDelete(long aId, string loginUser)
		{
		    string sql = "update [dbo].[TS_SYS_MENU] WITH(ROWLOCK) "
                + "set [VALID_FLAG] = @VALID_FLAG ,[MODIFY_USER] = @MODIFY_USER ,[MODIFY_DATE] = GETDATE() "
                + "WHERE [VALID_FLAG] = 1 AND ID =@ID;";
			Database db = DatabaseFactory.CreateDatabase();
			DbCommand dbCommand = db.GetSqlStringCommand(sql);
              			db.AddInParameter(dbCommand, "@ID", DbType.Int64, aId);
     db.AddInParameter(dbCommand, "@VALID_FLAG", DbType.Boolean, false);
			db.AddInParameter(dbCommand, "@MODIFY_USER", DbType.AnsiString, loginUser);
			return int.Parse("0" + db.ExecuteNonQuery(dbCommand));
		}
		/// <summary>
		/// UpdateInfo
		/// </summary>
		/// <param name="ID">MenuInfo Primary key </param>
		/// <returns></returns>
		public int UpdateInfo(string fields ,long aId)
		{
		    string sql = "update [dbo].[TS_SYS_MENU] WITH(ROWLOCK) "
                + "set " + fields
                + "WHERE [VALID_FLAG] = 1 AND ID =@ID;";
			Database db = DatabaseFactory.CreateDatabase();
			DbCommand dbCommand = db.GetSqlStringCommand(sql);
			db.AddInParameter(dbCommand, "@ID", DbType.Int64, aId);
			return int.Parse("0" + db.ExecuteNonQuery(dbCommand));
		}		
		#endregion
		  
		#region Helpers   
	  
		private static MenuInfo CreateMenuInfo(IDataReader rdr)
		{
			MenuInfo info = new MenuInfo();
			info.MenuName = DBConvert.GetString(rdr, rdr.GetOrdinal("MENU_NAME"));			
			info.DisplayOrder = DBConvert.GetInt32Nullable(rdr, rdr.GetOrdinal("DISPLAY_ORDER"));			
			info.ImageUrl = DBConvert.GetString(rdr, rdr.GetOrdinal("IMAGE_URL"));			
			info.LinkUrl = DBConvert.GetString(rdr, rdr.GetOrdinal("LINK_URL"));			
			info.Comments = DBConvert.GetString(rdr, rdr.GetOrdinal("COMMENTS"));			
			info.MenuType = DBConvert.GetInt32Nullable(rdr, rdr.GetOrdinal("MENU_TYPE"));			
			info.NeedAuth = DBConvert.GetBoolNullable(rdr, rdr.GetOrdinal("NEED_AUTH"));			
			info.MenuNameCn = DBConvert.GetString(rdr, rdr.GetOrdinal("MENU_NAME_CN"));			
			info.FavoritePic = DBConvert.GetString(rdr, rdr.GetOrdinal("FAVORITE_PIC"));			
			info.EditFormWidth = DBConvert.GetInt32Nullable(rdr, rdr.GetOrdinal("EDIT_FORM_WIDTH"));			
			info.EditFormHeight = DBConvert.GetInt32Nullable(rdr, rdr.GetOrdinal("EDIT_FORM_HEIGHT"));			
			info.ValidFlag = DBConvert.GetBoolNullable(rdr, rdr.GetOrdinal("VALID_FLAG"));			
			info.CreateDate = DBConvert.GetDateTimeNullable(rdr, rdr.GetOrdinal("CREATE_DATE"));			
			info.Id = DBConvert.GetInt64(rdr, rdr.GetOrdinal("ID"));			
			info.ParentMenuFid = DBConvert.GetGuidNullable(rdr, rdr.GetOrdinal("PARENT_MENU_FID"));			
			info.ModifyUser = DBConvert.GetString(rdr, rdr.GetOrdinal("MODIFY_USER"));			
			info.Fid = DBConvert.GetGuidNullable(rdr, rdr.GetOrdinal("FID"));			
			info.CreateUser = DBConvert.GetString(rdr, rdr.GetOrdinal("CREATE_USER"));			
			info.ModifyDate = DBConvert.GetDateTimeNullable(rdr, rdr.GetOrdinal("MODIFY_DATE"));			
			return info;
		}
		
		#endregion
	}
}
