#region Declaim
//---------------------------------------------------------------------------
// Name:		BomRepleaceConditionVehicleDAL
// Function: 	Expose data in table TT_BPM_BOM_REPLEACE_CONDITION_VEHICLE from database as business object to MES system.
// Tool:		T4
// CreateDate:	2018年7月17日
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------
#endregion

#region Imported Namespace

using DM.LES;
using Infrustructure.Data;
using Infrustructure.Utilities;
using Microsoft.Practices.EnterpriseLibrary.Data;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
          
#endregion

namespace DAL.LES 
{     
	//// <summary>
    /// BomRepleaceConditionVehicleDAL对应表[TT_BPM_BOM_REPLEACE_CONDITION_VEHICLE]
    /// </summary>
    public partial class BomRepleaceConditionVehicleDAL : BusinessObjectProvider<BomRepleaceConditionVehicleInfo>
	{
		#region Sql Statements
		private const string TT_BPM_BOM_REPLEACE_CONDITION_VEHICLE_SELECT_BY_ID =
			@"SELECT ID,
				FID,
				CONDITION_FID,
				CONDITION_CODE,
				PART_NO,
				MODEL_YEAR,
				FARBAU,
				PNR_STRING,
				ZCOLORI,
				REPLEACED_VEHICLE_QTY,
				STATUS,
				COMMENTS,
				VALID_FLAG,
				CREATE_DATE,
				CREATE_USER,
				MODIFY_DATE,
				MODIFY_USER				  
				FROM [LES].[TT_BPM_BOM_REPLEACE_CONDITION_VEHICLE] WITH(NOLOCK) WHERE [VALID_FLAG] = 1  AND ID =@ID;";
			
		private const string TT_BPM_BOM_REPLEACE_CONDITION_VEHICLE_SELECT = 
			@"SELECT ID,
				FID,
				CONDITION_FID,
				CONDITION_CODE,
				PART_NO,
				MODEL_YEAR,
				FARBAU,
				PNR_STRING,
				ZCOLORI,
				REPLEACED_VEHICLE_QTY,
				STATUS,
				COMMENTS,
				VALID_FLAG,
				CREATE_DATE,
				CREATE_USER,
				MODIFY_DATE,
				MODIFY_USER				 
				FROM [LES].[TT_BPM_BOM_REPLEACE_CONDITION_VEHICLE] WITH (NOLOCK) WHERE [VALID_FLAG] = 1 {0};";
		
		private const string TT_BPM_BOM_REPLEACE_CONDITION_VEHICLE_SELECT_COUNTS = 
			@"SELECT count(*) FROM [LES].[TT_BPM_BOM_REPLEACE_CONDITION_VEHICLE]  WITH(NOLOCK) WHERE [VALID_FLAG] = 1 {0};";

		private const string TT_BPM_BOM_REPLEACE_CONDITION_VEHICLE_INSERT =
			@"INSERT INTO [LES].[TT_BPM_BOM_REPLEACE_CONDITION_VEHICLE] (
				FID,
				CONDITION_FID,
				CONDITION_CODE,
				PART_NO,
				MODEL_YEAR,
				FARBAU,
				PNR_STRING,
				ZCOLORI,
				REPLEACED_VEHICLE_QTY,
				STATUS,
				COMMENTS,
				VALID_FLAG,
				CREATE_DATE,
				CREATE_USER,
				MODIFY_DATE,
				MODIFY_USER				 
			) VALUES (
				@FID,
				@CONDITION_FID,
				@CONDITION_CODE,
				@PART_NO,
				@MODEL_YEAR,
				@FARBAU,
				@PNR_STRING,
				@ZCOLORI,
				@REPLEACED_VEHICLE_QTY,
				@STATUS,
				@COMMENTS,
				@VALID_FLAG,
				GETDATE(),
				@CREATE_USER,
				@MODIFY_DATE,
				@MODIFY_USER				 
			);SELECT @@IDENTITY;";
		private const string TT_BPM_BOM_REPLEACE_CONDITION_VEHICLE_UPDATE =
			@"UPDATE [LES].[TT_BPM_BOM_REPLEACE_CONDITION_VEHICLE] WITH(ROWLOCK) 
				SET FID=@FID,
				CONDITION_FID=@CONDITION_FID,
				CONDITION_CODE=@CONDITION_CODE,
				PART_NO=@PART_NO,
				MODEL_YEAR=@MODEL_YEAR,
				FARBAU=@FARBAU,
				PNR_STRING=@PNR_STRING,
				ZCOLORI=@ZCOLORI,
				REPLEACED_VEHICLE_QTY=@REPLEACED_VEHICLE_QTY,
				STATUS=@STATUS,
				COMMENTS=@COMMENTS,
				VALID_FLAG=@VALID_FLAG,
				CREATE_DATE=@CREATE_DATE,
				CREATE_USER=@CREATE_USER,
				MODIFY_DATE=@MODIFY_DATE,
				MODIFY_USER=@MODIFY_USER				 
				WHERE [VALID_FLAG] = 1  AND ID =@ID;";

		private const string TT_BPM_BOM_REPLEACE_CONDITION_VEHICLE_DELETE =
			@"DELETE FROM [LES].[TT_BPM_BOM_REPLEACE_CONDITION_VEHICLE] WITH(ROWLOCK)  
				WHERE [VALID_FLAG] = 1  AND ID =@ID;";
		#endregion
		 
		#region Access Methods
		 
		/// <summary>
		/// Get BomRepleaceConditionVehicleInfo
		/// </summary>
		/// <param name="ID">BomRepleaceConditionVehicleInfo Primary key </param>
		/// <returns></returns> 
		public BomRepleaceConditionVehicleInfo GetInfo(long aId)
		{	
			Database db = DatabaseFactory.CreateDatabase();
			DbCommand dbCommand = db.GetSqlStringCommand(TT_BPM_BOM_REPLEACE_CONDITION_VEHICLE_SELECT_BY_ID);
			db.AddInParameter(dbCommand, "@ID", DbType.Int64, aId);
			using (IDataReader dr = db.ExecuteReader(dbCommand))
			{
				if (dr.Read())
					return CreateBomRepleaceConditionVehicleInfo(dr);
			}
			return null;
		}
		/// <summary>
		/// Get data collection
		/// </summary>
		/// <param name="textWhere">Conditon</param>
		/// <param name="orderText">Sort</param>
		/// <returns>BomRepleaceConditionVehicleInfo Collection </returns>
		public List<BomRepleaceConditionVehicleInfo> GetList(string textWhere,string orderText)
		{
			string query = string.Empty;
			if (string.IsNullOrEmpty(textWhere))
				query = string.Empty;
			else
			{				
				if (textWhere.Trim().StartsWith("and", StringComparison.OrdinalIgnoreCase))
					query = textWhere;
				else
					query = " and " + textWhere;				
			}
			if (!string.IsNullOrEmpty(orderText))
				query += " order by " + orderText;
			
			return GetList(string.Format(TT_BPM_BOM_REPLEACE_CONDITION_VEHICLE_SELECT, query));
		}		
		/// <summary>
		/// Get data collection
		/// </summary>
		/// <param name="sql">SQL Statement</param>
		/// <returns>BomRepleaceConditionVehicleInfo Collection </returns>
		public List<BomRepleaceConditionVehicleInfo> GetList(string sql)
		{
			Database db = DatabaseFactory.CreateDatabase();
			DbCommand dbCommand = db.GetSqlStringCommand(sql);
			List<BomRepleaceConditionVehicleInfo> list = new List<BomRepleaceConditionVehicleInfo>();
			using (IDataReader dr = db.ExecuteReader(dbCommand))
			{
				while (dr.Read())
				{
					list.Add(CreateBomRepleaceConditionVehicleInfo(dr));
				}
			}
			return list;
		}		
		/// <summary>
        /// 分页查询
        /// </summary>        
        /// <param name="textWhere">查询条件</param>
        /// <param name="orderText">排序字段</param>
        /// <param name="startRowIndex">当前页第一行行号</param>                    
        /// <param name="maximumRows">每页记录数</param>        
        /// <returns></returns>
		public List<BomRepleaceConditionVehicleInfo> GetListByPage(string textWhere, string textOrder, int pageIndex, int pageRow)
		{
		    if (pageIndex <= 0) pageIndex = 1;
            if (pageRow <= 0) pageRow = 10;
			string whereText = string.Empty;
            if (!string.IsNullOrEmpty(textWhere))
            {
                if (textWhere.Trim().StartsWith("and", StringComparison.OrdinalIgnoreCase))
                    whereText += " where [VALID_FLAG] = 1 " + textWhere;
                else
                    whereText += " where " + textWhere + " and [VALID_FLAG] = 1";
            }
			else
                whereText += " where [VALID_FLAG] = 1 ";
            if (string.IsNullOrEmpty(textOrder))
                textOrder += "[ID] desc";
            string sql = "select top " + pageRow + " * from "
                + "(select row_number() over(order by " + textOrder + ") as rownumber"
                + ",* from [LES].[TT_BPM_BOM_REPLEACE_CONDITION_VEHICLE]  WITH(NOLOCK) " + whereText + ") T "
                + "where rownumber > " + (pageIndex - 1) * pageRow + " ";
            Database db = DatabaseFactory.CreateDatabase();
            DbCommand dbCommand = db.GetSqlStringCommand(sql);
            List<BomRepleaceConditionVehicleInfo> list = new List<BomRepleaceConditionVehicleInfo>();
            using (IDataReader dr = db.ExecuteReader(dbCommand))
            {
                while (dr.Read())
                {
                    list.Add(CreateBomRepleaceConditionVehicleInfo(dr));
                }
            }
            return list;
		}
		/// <summary>
        /// 分页查询
        /// </summary>        
        /// <param name="textWhere">查询条件</param>
        /// <param name="orderText">排序字段</param>            
        /// <returns></returns>
        public int GetCounts(string textWhere)
        {			
			if (string.IsNullOrEmpty(textWhere))
				textWhere = string.Empty;
			else
			{				
				if (!textWhere.Trim().StartsWith("and", StringComparison.OrdinalIgnoreCase))
					textWhere = " and " + textWhere;						
			}
			Database db = DatabaseFactory.CreateDatabase();
            DbCommand cmd = db.GetSqlStringCommand(string.Format(TT_BPM_BOM_REPLEACE_CONDITION_VEHICLE_SELECT_COUNTS, textWhere));
			return Convert.ToInt32(db.ExecuteScalar(cmd));            
        }
		/// <summary>
		/// Add
		/// </summary>
		/// <param name="info"> info</param>
		public long Add(BomRepleaceConditionVehicleInfo info)
		{ 
			Database db = DatabaseFactory.CreateDatabase();	
			DbCommand dbCommand = db.GetSqlStringCommand(TT_BPM_BOM_REPLEACE_CONDITION_VEHICLE_INSERT);			
			db.AddInParameter(dbCommand, "@FID", DbType.Guid, info.Fid);
			db.AddInParameter(dbCommand, "@CONDITION_FID", DbType.Guid, info.ConditionFid);
			db.AddInParameter(dbCommand, "@CONDITION_CODE", DbType.String, info.ConditionCode);
			db.AddInParameter(dbCommand, "@PART_NO", DbType.String, info.PartNo);
			db.AddInParameter(dbCommand, "@MODEL_YEAR", DbType.String, info.ModelYear);
			db.AddInParameter(dbCommand, "@FARBAU", DbType.String, info.Farbau);
			db.AddInParameter(dbCommand, "@PNR_STRING", DbType.String, info.PnrString);
			db.AddInParameter(dbCommand, "@ZCOLORI", DbType.String, info.Zcolori);
			db.AddInParameter(dbCommand, "@REPLEACED_VEHICLE_QTY", DbType.Int32, info.RepleacedVehicleQty);
			db.AddInParameter(dbCommand, "@STATUS", DbType.Int32, info.Status);
			db.AddInParameter(dbCommand, "@COMMENTS", DbType.String, info.Comments);
			db.AddInParameter(dbCommand, "@VALID_FLAG", DbType.Boolean, info.ValidFlag);
			db.AddInParameter(dbCommand, "@CREATE_DATE", DbType.DateTime, info.CreateDate);
			db.AddInParameter(dbCommand, "@CREATE_USER", DbType.String, info.CreateUser);
			db.AddInParameter(dbCommand, "@MODIFY_DATE", DbType.DateTime, info.ModifyDate);
			db.AddInParameter(dbCommand, "@MODIFY_USER", DbType.String, info.ModifyUser);
			return long.Parse("0" + db.ExecuteScalar(dbCommand));		
		}
		/// <summary>
		/// GetInsertSql
		/// </summary>
		/// <param name="info"> info</param>
		public static string GetInsertSql(BomRepleaceConditionVehicleInfo info)
		{
			return  
			@"insert into [LES].[TT_BPM_BOM_REPLEACE_CONDITION_VEHICLE] (
				FID,
				CONDITION_FID,
				CONDITION_CODE,
				PART_NO,
				MODEL_YEAR,
				FARBAU,
				PNR_STRING,
				ZCOLORI,
				REPLEACED_VEHICLE_QTY,
				STATUS,
				COMMENTS,
				VALID_FLAG,
				CREATE_DATE,
				CREATE_USER,
				MODIFY_DATE,
				MODIFY_USER				 
			) values ("+
				(info.Fid == null ? "NEWID()" : "N'" + info.Fid.GetValueOrDefault() + "'") + ","+
				(info.ConditionFid == null ? "NULL" : "N'" + info.ConditionFid.GetValueOrDefault() + "'") + ","+
				(string.IsNullOrEmpty(info.ConditionCode) ? "NULL" : "N'" + info.ConditionCode + "'") + ","+
				(string.IsNullOrEmpty(info.PartNo) ? "NULL" : "N'" + info.PartNo + "'") + ","+
				(string.IsNullOrEmpty(info.ModelYear) ? "NULL" : "N'" + info.ModelYear + "'") + ","+
				(string.IsNullOrEmpty(info.Farbau) ? "NULL" : "N'" + info.Farbau + "'") + ","+
				(string.IsNullOrEmpty(info.PnrString) ? "NULL" : "N'" + info.PnrString + "'") + ","+
				(string.IsNullOrEmpty(info.Zcolori) ? "NULL" : "N'" + info.Zcolori + "'") + ","+
				(info.RepleacedVehicleQty == null ? "NULL" : "" + info.RepleacedVehicleQty.GetValueOrDefault() + "") + ","+
				(info.Status == null ? "NULL" : "" + info.Status.GetValueOrDefault() + "") + ","+
				(string.IsNullOrEmpty(info.Comments) ? "NULL" : "N'" + info.Comments + "'") + ","+
				"1" + ","+		
				"GETDATE()" + ","+			
				"N'" + info.CreateUser + "'" + ","+		
				"NULL" + ","+			
				"NULL" + ");";			
				}
		/// <summary>
		/// Update
		/// </summary>
		/// <param name="info">info</param>
		public int Update(BomRepleaceConditionVehicleInfo info)
		{
			Database db = DatabaseFactory.CreateDatabase();
			DbCommand dbCommand = db.GetSqlStringCommand(TT_BPM_BOM_REPLEACE_CONDITION_VEHICLE_UPDATE);				
			db.AddInParameter(dbCommand, "@ID", DbType.Int64, info.Id);
			db.AddInParameter(dbCommand, "@FID", DbType.Guid, info.Fid);
			db.AddInParameter(dbCommand, "@CONDITION_FID", DbType.Guid, info.ConditionFid);
			db.AddInParameter(dbCommand, "@CONDITION_CODE", DbType.String, info.ConditionCode);
			db.AddInParameter(dbCommand, "@PART_NO", DbType.String, info.PartNo);
			db.AddInParameter(dbCommand, "@MODEL_YEAR", DbType.String, info.ModelYear);
			db.AddInParameter(dbCommand, "@FARBAU", DbType.String, info.Farbau);
			db.AddInParameter(dbCommand, "@PNR_STRING", DbType.String, info.PnrString);
			db.AddInParameter(dbCommand, "@ZCOLORI", DbType.String, info.Zcolori);
			db.AddInParameter(dbCommand, "@REPLEACED_VEHICLE_QTY", DbType.Int32, info.RepleacedVehicleQty);
			db.AddInParameter(dbCommand, "@STATUS", DbType.Int32, info.Status);
			db.AddInParameter(dbCommand, "@COMMENTS", DbType.String, info.Comments);
			db.AddInParameter(dbCommand, "@VALID_FLAG", DbType.Boolean, info.ValidFlag);
			db.AddInParameter(dbCommand, "@CREATE_DATE", DbType.DateTime, info.CreateDate);
			db.AddInParameter(dbCommand, "@CREATE_USER", DbType.String, info.CreateUser);
			db.AddInParameter(dbCommand, "@MODIFY_DATE", DbType.DateTime, info.ModifyDate);
			db.AddInParameter(dbCommand, "@MODIFY_USER", DbType.String, info.ModifyUser);
			return int.Parse("0" + db.ExecuteNonQuery(dbCommand));
		}		
		/// <summary>
		/// Delete
		/// </summary>
		/// <param name="ID">BomRepleaceConditionVehicleInfo Primary key </param>
		/// <returns></returns>
		public int Delete(long aId)
		{
			Database db = DatabaseFactory.CreateDatabase();
			DbCommand dbCommand = db.GetSqlStringCommand(TT_BPM_BOM_REPLEACE_CONDITION_VEHICLE_DELETE);
		    db.AddInParameter(dbCommand, "@ID", DbType.Int64, aId);
			return int.Parse("0" + db.ExecuteNonQuery(dbCommand));
		}/// <summary>
		/// LogciDelete
		/// </summary>
		/// <param name="ID">BomRepleaceConditionVehicleInfo Primary key </param>
		/// <returns></returns>
		public int LogicDelete(long aId, string loginUser)
		{
		    string sql = "update [LES].[TT_BPM_BOM_REPLEACE_CONDITION_VEHICLE] WITH(ROWLOCK) "
                + "set [VALID_FLAG] = @VALID_FLAG ,[MODIFY_USER] = @MODIFY_USER ,[MODIFY_DATE] = GETDATE() "
                + "WHERE [VALID_FLAG] = 1  AND ID =@ID;";
			Database db = DatabaseFactory.CreateDatabase();
			DbCommand dbCommand = db.GetSqlStringCommand(sql);
 			db.AddInParameter(dbCommand, "@ID", DbType.Int64, aId);
                db.AddInParameter(dbCommand, "@VALID_FLAG", DbType.Boolean, false);
			db.AddInParameter(dbCommand, "@MODIFY_USER", DbType.AnsiString, loginUser);
			return int.Parse("0" + db.ExecuteNonQuery(dbCommand));
		}
		/// <summary>
		/// UpdateInfo
		/// </summary>
		/// <param name="ID">BomRepleaceConditionVehicleInfo Primary key </param>
		/// <returns></returns>
		public int UpdateInfo(string fields ,long aId)
		{
		    string sql = "update [LES].[TT_BPM_BOM_REPLEACE_CONDITION_VEHICLE] WITH(ROWLOCK) "
                + "set " + fields
                + "WHERE [VALID_FLAG] = 1  AND ID =@ID;";
			Database db = DatabaseFactory.CreateDatabase();
			DbCommand dbCommand = db.GetSqlStringCommand(sql);
			db.AddInParameter(dbCommand, "@ID", DbType.Int64, aId);
			return int.Parse("0" + db.ExecuteNonQuery(dbCommand));
		}		
		#endregion
		  
		#region Helpers   
	  
		private static BomRepleaceConditionVehicleInfo CreateBomRepleaceConditionVehicleInfo(IDataReader rdr)
		{
			BomRepleaceConditionVehicleInfo info = new BomRepleaceConditionVehicleInfo();
			info.Id = DBConvert.GetInt64(rdr, rdr.GetOrdinal("ID"));			
			info.Fid = DBConvert.GetGuidNullable(rdr, rdr.GetOrdinal("FID"));			
			info.ConditionFid = DBConvert.GetGuidNullable(rdr, rdr.GetOrdinal("CONDITION_FID"));			
			info.ConditionCode = DBConvert.GetString(rdr, rdr.GetOrdinal("CONDITION_CODE"));			
			info.PartNo = DBConvert.GetString(rdr, rdr.GetOrdinal("PART_NO"));			
			info.ModelYear = DBConvert.GetString(rdr, rdr.GetOrdinal("MODEL_YEAR"));			
			info.Farbau = DBConvert.GetString(rdr, rdr.GetOrdinal("FARBAU"));			
			info.PnrString = DBConvert.GetString(rdr, rdr.GetOrdinal("PNR_STRING"));			
			info.Zcolori = DBConvert.GetString(rdr, rdr.GetOrdinal("ZCOLORI"));			
			info.RepleacedVehicleQty = DBConvert.GetInt32Nullable(rdr, rdr.GetOrdinal("REPLEACED_VEHICLE_QTY"));			
			info.Status = DBConvert.GetInt32Nullable(rdr, rdr.GetOrdinal("STATUS"));			
			info.Comments = DBConvert.GetString(rdr, rdr.GetOrdinal("COMMENTS"));			
			info.ValidFlag = DBConvert.GetBool(rdr, rdr.GetOrdinal("VALID_FLAG"));			
			info.CreateDate = DBConvert.GetDateTime(rdr, rdr.GetOrdinal("CREATE_DATE"));			
			info.CreateUser = DBConvert.GetString(rdr, rdr.GetOrdinal("CREATE_USER"));			
			info.ModifyDate = DBConvert.GetDateTimeNullable(rdr, rdr.GetOrdinal("MODIFY_DATE"));			
			info.ModifyUser = DBConvert.GetString(rdr, rdr.GetOrdinal("MODIFY_USER"));			
			return info;
		}
		
		#endregion
	}
}
