#region Declaim
//---------------------------------------------------------------------------
// Name:		PullOrdersDAL
// Function: 	Expose data in table TT_BAS_PULL_ORDERS from database as business object to MES system.
// Tool:		T4
// CreateDate:	2018年4月11日
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------
#endregion

#region Imported Namespace

using DM.LES;
using Infrustructure.Data;
using Infrustructure.Utilities;
using Microsoft.Practices.EnterpriseLibrary.Data;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;

#endregion

namespace DAL.LES
{
    public partial class PullOrdersDAL
    {
        /// <summary>
        /// 根据订单号获取订单日期
        /// </summary>
        /// <param name="ZordNo"></param>
        /// <returns></returns>
        public DateTime GetDate(string ZordNo)
        {
            string sql = string.Format(@"select [ORDER_DATE] from LES.TT_BAS_PULL_ORDERS where [VALID_FLAG] = 1 and [ORDER_NO] = N'{0}'", ZordNo);
            Database db = DatabaseFactory.CreateDatabase();
            DbCommand dbCommand = db.GetSqlStringCommand(sql);
            return Convert.ToDateTime(dbCommand.ExecuteScalar());
        }
        /// <summary>
        /// 根据订单号获取信息
        /// </summary>
        /// <param name="orderNo"></param>
        /// <returns></returns>
        public PullOrdersInfo GetInfoByOrderNo(string orderNo)
        {
            string sql = "select top 1 * from [LES].[TT_BAS_PULL_ORDERS] where [VALID_FLAG] = 1 and [ORDER_NO] = @ORDER_NO;";
            Database db = DatabaseFactory.CreateDatabase();
            DbCommand cmd = db.GetSqlStringCommand(sql);
            db.AddInParameter(cmd, "@ORDER_NO", DbType.AnsiString, orderNo);
            using (IDataReader dr = db.ExecuteReader(cmd))
            {
                if (dr.Read())
                    return CreatePullOrdersInfo(dr);
            }
            return null;
        }
    }
}
