#region Declaim
//---------------------------------------------------------------------------
// Name:		RepackageScheduleDAL
// Function: 	Expose data in table TT_WMM_REPACKAGE_SCHEDULE from database as business object to MES system.
// Tool:		T4
// CreateDate:	2017年12月21日
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------
#endregion

#region Imported Namespace

using DM.LES;
using Infrustructure.Data;
using Infrustructure.Utilities;
using Microsoft.Practices.EnterpriseLibrary.Data;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
          
#endregion

namespace DAL.LES 
{     
	//// <summary>
    /// RepackageScheduleDAL对应表[TT_WMM_REPACKAGE_SCHEDULE]
    /// </summary>
    public partial class RepackageScheduleDAL : BusinessObjectProvider<RepackageScheduleInfo>
	{
		#region Sql Statements
		private const string TT_WMM_REPACKAGE_SCHEDULE_SELECT_BY_ID =
			@"SELECT SCHEDULE_IDENTITY,
				PLANT,
				ASSEMBLY_LINE,
				WORKSHOP,
				PLANT_ZONE,
				ROUTES,
				WINDOWS_TIME,
				IS_ACTIVE,
				LAST_RUN,
				COMMENTS,
				CREATE_USER,
				CREATE_DATE,
				UPDATE_USER,
				UPDATE_DATE				  
				FROM [LES].[TT_WMM_REPACKAGE_SCHEDULE] WITH(NOLOCK) WHERE 1=1  AND SCHEDULE_IDENTITY =@SCHEDULE_IDENTITY;";
			
		private const string TT_WMM_REPACKAGE_SCHEDULE_SELECT = 
			@"SELECT SCHEDULE_IDENTITY,
				PLANT,
				ASSEMBLY_LINE,
				WORKSHOP,
				PLANT_ZONE,
				ROUTES,
				WINDOWS_TIME,
				IS_ACTIVE,
				LAST_RUN,
				COMMENTS,
				CREATE_USER,
				CREATE_DATE,
				UPDATE_USER,
				UPDATE_DATE				 
				FROM [LES].[TT_WMM_REPACKAGE_SCHEDULE] WITH (NOLOCK) WHERE 1=1 {0};";
		
		private const string TT_WMM_REPACKAGE_SCHEDULE_SELECT_COUNTS = 
			@"SELECT count(*) FROM [LES].[TT_WMM_REPACKAGE_SCHEDULE]  WITH(NOLOCK) WHERE 1=1 {0};";

		private const string TT_WMM_REPACKAGE_SCHEDULE_INSERT =
			@"INSERT INTO [LES].[TT_WMM_REPACKAGE_SCHEDULE] (
				PLANT,
				ASSEMBLY_LINE,
				WORKSHOP,
				PLANT_ZONE,
				ROUTES,
				WINDOWS_TIME,
				IS_ACTIVE,
				LAST_RUN,
				COMMENTS,
				CREATE_USER,
				CREATE_DATE,
				UPDATE_USER,
				UPDATE_DATE				 
			) VALUES (
				@PLANT,
				@ASSEMBLY_LINE,
				@WORKSHOP,
				@PLANT_ZONE,
				@ROUTES,
				@WINDOWS_TIME,
				@IS_ACTIVE,
				@LAST_RUN,
				@COMMENTS,
				@CREATE_USER,
				@CREATE_DATE,
				@UPDATE_USER,
				@UPDATE_DATE				 
			);SELECT @@IDENTITY;";
		private const string TT_WMM_REPACKAGE_SCHEDULE_UPDATE =
			@"UPDATE [LES].[TT_WMM_REPACKAGE_SCHEDULE] WITH(ROWLOCK) 
				SET PLANT=@PLANT,
				ASSEMBLY_LINE=@ASSEMBLY_LINE,
				WORKSHOP=@WORKSHOP,
				PLANT_ZONE=@PLANT_ZONE,
				ROUTES=@ROUTES,
				WINDOWS_TIME=@WINDOWS_TIME,
				IS_ACTIVE=@IS_ACTIVE,
				LAST_RUN=@LAST_RUN,
				COMMENTS=@COMMENTS,
				CREATE_USER=@CREATE_USER,
				CREATE_DATE=@CREATE_DATE,
				UPDATE_USER=@UPDATE_USER,
				UPDATE_DATE=@UPDATE_DATE				 
				WHERE 1=1  AND SCHEDULE_IDENTITY =@SCHEDULE_IDENTITY;";

		private const string TT_WMM_REPACKAGE_SCHEDULE_DELETE =
			@"DELETE FROM [LES].[TT_WMM_REPACKAGE_SCHEDULE] WITH(ROWLOCK)  
				WHERE 1=1  AND SCHEDULE_IDENTITY =@SCHEDULE_IDENTITY;";
		#endregion
		 
		#region Access Methods
		 
		/// <summary>
		/// Get RepackageScheduleInfo
		/// </summary>
		/// <param name="SCHEDULE_IDENTITY">RepackageScheduleInfo Primary key </param>
		/// <returns></returns> 
		public RepackageScheduleInfo GetInfo(int aScheduleIdentity)
		{	
			Database db = DatabaseFactory.CreateDatabase();
			DbCommand dbCommand = db.GetSqlStringCommand(TT_WMM_REPACKAGE_SCHEDULE_SELECT_BY_ID);
			db.AddInParameter(dbCommand, "@SCHEDULE_IDENTITY", DbType.Int32, aScheduleIdentity);
			using (IDataReader dr = db.ExecuteReader(dbCommand))
			{
				if (dr.Read())
					return CreateRepackageScheduleInfo(dr);
			}
			return null;
		}
		/// <summary>
		/// Get data collection
		/// </summary>
		/// <param name="textWhere">Conditon</param>
		/// <param name="orderText">Sort</param>
		/// <returns>RepackageScheduleInfo Collection </returns>
		public List<RepackageScheduleInfo> GetList(string textWhere,string orderText)
		{
			string query = string.Empty;
			if (string.IsNullOrEmpty(textWhere))
				query = string.Empty;
			else
			{				
				if (textWhere.Trim().StartsWith("and", StringComparison.OrdinalIgnoreCase))
					query = textWhere;
				else
					query = " and " + textWhere;				
			}
			if (!string.IsNullOrEmpty(orderText))
				query += " order by " + orderText;
			
			return GetList(string.Format(TT_WMM_REPACKAGE_SCHEDULE_SELECT, query));
		}		
		/// <summary>
		/// Get data collection
		/// </summary>
		/// <param name="sql">SQL Statement</param>
		/// <returns>RepackageScheduleInfo Collection </returns>
		public List<RepackageScheduleInfo> GetList(string sql)
		{
			Database db = DatabaseFactory.CreateDatabase();
			DbCommand dbCommand = db.GetSqlStringCommand(sql);
			List<RepackageScheduleInfo> list = new List<RepackageScheduleInfo>();
			using (IDataReader dr = db.ExecuteReader(dbCommand))
			{
				while (dr.Read())
				{
					list.Add(CreateRepackageScheduleInfo(dr));
				}
			}
			return list;
		}		
		/// <summary>
        /// 分页查询
        /// </summary>        
        /// <param name="textWhere">查询条件</param>
        /// <param name="orderText">排序字段</param>
        /// <param name="startRowIndex">当前页第一行行号</param>                    
        /// <param name="maximumRows">每页记录数</param>        
        /// <returns></returns>
		public List<RepackageScheduleInfo> GetListByPage(string textWhere, string textOrder, int pageIndex, int pageRow)
		{
		    if (pageIndex <= 0) pageIndex = 1;
            if (pageRow <= 0) pageRow = 10;
			string whereText = string.Empty;
            if (!string.IsNullOrEmpty(textWhere))
            {
                if (textWhere.Trim().StartsWith("and", StringComparison.OrdinalIgnoreCase))
                    whereText += " where 1=1 " + textWhere;
                else
                    whereText += " where " + textWhere + " and 1=1";
            }
			else
                whereText += " where 1=1 ";
            if (string.IsNullOrEmpty(textOrder))
                textOrder += "[SCHEDULE_IDENTITY] desc";
            string sql = "select top " + pageRow + " * from "
                + "(select row_number() over(order by " + textOrder + ") as rownumber"
                + ",* from [LES].[TT_WMM_REPACKAGE_SCHEDULE]  WITH(NOLOCK) " + whereText + ") T "
                + "where rownumber > " + (pageIndex - 1) * pageRow + " ";
            Database db = DatabaseFactory.CreateDatabase();
            DbCommand dbCommand = db.GetSqlStringCommand(sql);
            List<RepackageScheduleInfo> list = new List<RepackageScheduleInfo>();
            using (IDataReader dr = db.ExecuteReader(dbCommand))
            {
                while (dr.Read())
                {
                    list.Add(CreateRepackageScheduleInfo(dr));
                }
            }
            return list;
		}
		/// <summary>
        /// 分页查询
        /// </summary>        
        /// <param name="textWhere">查询条件</param>
        /// <param name="orderText">排序字段</param>            
        /// <returns></returns>
        public int GetCounts(string textWhere)
        {			
			if (string.IsNullOrEmpty(textWhere))
				textWhere = string.Empty;
			else
			{				
				if (!textWhere.Trim().StartsWith("and", StringComparison.OrdinalIgnoreCase))
					textWhere = " and " + textWhere;						
			}
			Database db = DatabaseFactory.CreateDatabase();
            DbCommand cmd = db.GetSqlStringCommand(string.Format(TT_WMM_REPACKAGE_SCHEDULE_SELECT_COUNTS, textWhere));
			return Convert.ToInt32(db.ExecuteScalar(cmd));            
        }
		/// <summary>
		/// Add
		/// </summary>
		/// <param name="info"> info</param>
		public int Add(RepackageScheduleInfo info)
		{ 
			Database db = DatabaseFactory.CreateDatabase();	
			DbCommand dbCommand = db.GetSqlStringCommand(TT_WMM_REPACKAGE_SCHEDULE_INSERT);			
			db.AddInParameter(dbCommand, "@PLANT", DbType.String, info.Plant);
			db.AddInParameter(dbCommand, "@ASSEMBLY_LINE", DbType.String, info.AssemblyLine);
			db.AddInParameter(dbCommand, "@WORKSHOP", DbType.String, info.Workshop);
			db.AddInParameter(dbCommand, "@PLANT_ZONE", DbType.String, info.PlantZone);
			db.AddInParameter(dbCommand, "@ROUTES", DbType.String, info.Routes);
			db.AddInParameter(dbCommand, "@WINDOWS_TIME", DbType.String, info.WindowsTime);
			db.AddInParameter(dbCommand, "@IS_ACTIVE", DbType.Int32, info.IsActive);
			db.AddInParameter(dbCommand, "@LAST_RUN", DbType.DateTime, info.LastRun);
			db.AddInParameter(dbCommand, "@COMMENTS", DbType.String, info.Comments);
			db.AddInParameter(dbCommand, "@CREATE_USER", DbType.String, info.CreateUser);
			db.AddInParameter(dbCommand, "@CREATE_DATE", DbType.DateTime, info.CreateDate);
			db.AddInParameter(dbCommand, "@UPDATE_USER", DbType.String, info.UpdateUser);
			db.AddInParameter(dbCommand, "@UPDATE_DATE", DbType.DateTime, info.UpdateDate);
			return int.Parse("0" + db.ExecuteScalar(dbCommand));		
		}		
		/// <summary>
		/// Update
		/// </summary>
		/// <param name="info">info</param>
		public int Update(RepackageScheduleInfo info)
		{
			Database db = DatabaseFactory.CreateDatabase();
			DbCommand dbCommand = db.GetSqlStringCommand(TT_WMM_REPACKAGE_SCHEDULE_UPDATE);				
			db.AddInParameter(dbCommand, "@SCHEDULE_IDENTITY", DbType.Int32, info.ScheduleIdentity);
			db.AddInParameter(dbCommand, "@PLANT", DbType.String, info.Plant);
			db.AddInParameter(dbCommand, "@ASSEMBLY_LINE", DbType.String, info.AssemblyLine);
			db.AddInParameter(dbCommand, "@WORKSHOP", DbType.String, info.Workshop);
			db.AddInParameter(dbCommand, "@PLANT_ZONE", DbType.String, info.PlantZone);
			db.AddInParameter(dbCommand, "@ROUTES", DbType.String, info.Routes);
			db.AddInParameter(dbCommand, "@WINDOWS_TIME", DbType.String, info.WindowsTime);
			db.AddInParameter(dbCommand, "@IS_ACTIVE", DbType.Int32, info.IsActive);
			db.AddInParameter(dbCommand, "@LAST_RUN", DbType.DateTime, info.LastRun);
			db.AddInParameter(dbCommand, "@COMMENTS", DbType.String, info.Comments);
			db.AddInParameter(dbCommand, "@CREATE_USER", DbType.String, info.CreateUser);
			db.AddInParameter(dbCommand, "@CREATE_DATE", DbType.DateTime, info.CreateDate);
			db.AddInParameter(dbCommand, "@UPDATE_USER", DbType.String, info.UpdateUser);
			db.AddInParameter(dbCommand, "@UPDATE_DATE", DbType.DateTime, info.UpdateDate);
			return int.Parse("0" + db.ExecuteNonQuery(dbCommand));
		}		
		/// <summary>
		/// Delete
		/// </summary>
		/// <param name="SCHEDULE_IDENTITY">RepackageScheduleInfo Primary key </param>
		/// <returns></returns>
		public int Delete(int aScheduleIdentity)
		{
			Database db = DatabaseFactory.CreateDatabase();
			DbCommand dbCommand = db.GetSqlStringCommand(TT_WMM_REPACKAGE_SCHEDULE_DELETE);
		    db.AddInParameter(dbCommand, "@SCHEDULE_IDENTITY", DbType.Int32, aScheduleIdentity);
			return int.Parse("0" + db.ExecuteNonQuery(dbCommand));
		}
		/// <summary>
		/// UpdateInfo
		/// </summary>
		/// <param name="SCHEDULE_IDENTITY">RepackageScheduleInfo Primary key </param>
		/// <returns></returns>
		public int UpdateInfo(string fields ,int aScheduleIdentity)
		{
		    string sql = "update [LES].[TT_WMM_REPACKAGE_SCHEDULE] WITH(ROWLOCK) "
                + "set " + fields
                + "WHERE 1=1  AND SCHEDULE_IDENTITY =@SCHEDULE_IDENTITY;";
			Database db = DatabaseFactory.CreateDatabase();
			DbCommand dbCommand = db.GetSqlStringCommand(sql);
			db.AddInParameter(dbCommand, "@SCHEDULE_IDENTITY", DbType.Int32, aScheduleIdentity);
			return int.Parse("0" + db.ExecuteNonQuery(dbCommand));
		}		
		#endregion
		  
		#region Helpers   
	  
		private static RepackageScheduleInfo CreateRepackageScheduleInfo(IDataReader rdr)
		{
			RepackageScheduleInfo info = new RepackageScheduleInfo();
			info.ScheduleIdentity = DBConvert.GetInt32(rdr, rdr.GetOrdinal("SCHEDULE_IDENTITY"));			
			info.Plant = DBConvert.GetString(rdr, rdr.GetOrdinal("PLANT"));			
			info.AssemblyLine = DBConvert.GetString(rdr, rdr.GetOrdinal("ASSEMBLY_LINE"));			
			info.Workshop = DBConvert.GetString(rdr, rdr.GetOrdinal("WORKSHOP"));			
			info.PlantZone = DBConvert.GetString(rdr, rdr.GetOrdinal("PLANT_ZONE"));			
			info.Routes = DBConvert.GetString(rdr, rdr.GetOrdinal("ROUTES"));			
			info.WindowsTime = DBConvert.GetString(rdr, rdr.GetOrdinal("WINDOWS_TIME"));			
			info.IsActive = DBConvert.GetInt32Nullable(rdr, rdr.GetOrdinal("IS_ACTIVE"));			
			info.LastRun = DBConvert.GetDateTimeNullable(rdr, rdr.GetOrdinal("LAST_RUN"));			
			info.Comments = DBConvert.GetString(rdr, rdr.GetOrdinal("COMMENTS"));			
			info.CreateUser = DBConvert.GetString(rdr, rdr.GetOrdinal("CREATE_USER"));			
			info.CreateDate = DBConvert.GetDateTime(rdr, rdr.GetOrdinal("CREATE_DATE"));			
			info.UpdateUser = DBConvert.GetString(rdr, rdr.GetOrdinal("UPDATE_USER"));			
			info.UpdateDate = DBConvert.GetDateTimeNullable(rdr, rdr.GetOrdinal("UPDATE_DATE"));			
			return info;
		}
		
		#endregion
	}
}
