#region Declaim
//---------------------------------------------------------------------------
// Name:		SupplierPartQuotaDAL
// Function: 	Expose data in table TT_SPM_SUPPLIER_PART_QUOTA from database as business object to MES system.
// Tool:		T4
// CreateDate:	2020年10月22日
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------
#endregion

#region Imported Namespace

using DM.LES;
using Infrustructure.Data;
using Infrustructure.Utilities;
using Microsoft.Practices.EnterpriseLibrary.Data;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
          
#endregion

namespace DAL.LES 
{     
	//// <summary>
    /// SupplierPartQuotaDAL对应表[TT_SPM_SUPPLIER_PART_QUOTA]
    /// </summary>
    public partial class SupplierPartQuotaDAL : BusinessObjectProvider<SupplierPartQuotaInfo>
	{
		#region Sql Statements
		private const string TT_SPM_SUPPLIER_PART_QUOTA_SELECT_BY_ID =
			@"SELECT ID,
				PLANT,
				PLANT_NAME,
				PART_NO,
				PART_CNAME,
				WORKSHOP,
				WORKSHOP_NAME,
				SUPPLIER_NUM,
				SUPPLIER_NAME,
				START_EFFECTIVE_DATE,
				END_EFFECTIVE_DATE,
				QUOTE,
				PROJECT,
				AGREEMENT_NO,
				COMMENTS,
				MODIFY_DATE,
				MODIFY_USER,
				CREATE_DATE,
				CREATE_USER,
				LOEKZ,
				PROCESS_FLAG,
				FID,
				VALID_FLAG				  
				FROM [LES].[TT_SPM_SUPPLIER_PART_QUOTA] WITH(NOLOCK) WHERE [VALID_FLAG] = 1  AND ID =@ID;";
			
		private const string TT_SPM_SUPPLIER_PART_QUOTA_SELECT = 
			@"SELECT ID,
				PLANT,
				PLANT_NAME,
				PART_NO,
				PART_CNAME,
				WORKSHOP,
				WORKSHOP_NAME,
				SUPPLIER_NUM,
				SUPPLIER_NAME,
				START_EFFECTIVE_DATE,
				END_EFFECTIVE_DATE,
				QUOTE,
				PROJECT,
				AGREEMENT_NO,
				COMMENTS,
				MODIFY_DATE,
				MODIFY_USER,
				CREATE_DATE,
				CREATE_USER,
				LOEKZ,
				PROCESS_FLAG,
				FID,
				VALID_FLAG				 
				FROM [LES].[TT_SPM_SUPPLIER_PART_QUOTA] WITH (NOLOCK) WHERE [VALID_FLAG] = 1 {0};";
		
		private const string TT_SPM_SUPPLIER_PART_QUOTA_SELECT_COUNTS = 
			@"SELECT count(*) FROM [LES].[TT_SPM_SUPPLIER_PART_QUOTA]  WITH(NOLOCK) WHERE [VALID_FLAG] = 1 {0};";

		private const string TT_SPM_SUPPLIER_PART_QUOTA_INSERT =
			@"INSERT INTO [LES].[TT_SPM_SUPPLIER_PART_QUOTA] (
				PLANT,
				PLANT_NAME,
				PART_NO,
				PART_CNAME,
				WORKSHOP,
				WORKSHOP_NAME,
				SUPPLIER_NUM,
				SUPPLIER_NAME,
				START_EFFECTIVE_DATE,
				END_EFFECTIVE_DATE,
				QUOTE,
				PROJECT,
				AGREEMENT_NO,
				COMMENTS,
				MODIFY_DATE,
				MODIFY_USER,
				CREATE_DATE,
				CREATE_USER,
				LOEKZ,
				PROCESS_FLAG,
				FID,
				VALID_FLAG				 
			) VALUES (
				@PLANT,
				@PLANT_NAME,
				@PART_NO,
				@PART_CNAME,
				@WORKSHOP,
				@WORKSHOP_NAME,
				@SUPPLIER_NUM,
				@SUPPLIER_NAME,
				@START_EFFECTIVE_DATE,
				@END_EFFECTIVE_DATE,
				@QUOTE,
				@PROJECT,
				@AGREEMENT_NO,
				@COMMENTS,
				@MODIFY_DATE,
				@MODIFY_USER,
				GETDATE(),
				@CREATE_USER,
				@LOEKZ,
				@PROCESS_FLAG,
				@FID,
				@VALID_FLAG				 
			);SELECT @@IDENTITY;";
		private const string TT_SPM_SUPPLIER_PART_QUOTA_UPDATE =
			@"UPDATE [LES].[TT_SPM_SUPPLIER_PART_QUOTA] WITH(ROWLOCK) 
				SET PLANT=@PLANT,
				PLANT_NAME=@PLANT_NAME,
				PART_NO=@PART_NO,
				PART_CNAME=@PART_CNAME,
				WORKSHOP=@WORKSHOP,
				WORKSHOP_NAME=@WORKSHOP_NAME,
				SUPPLIER_NUM=@SUPPLIER_NUM,
				SUPPLIER_NAME=@SUPPLIER_NAME,
				START_EFFECTIVE_DATE=@START_EFFECTIVE_DATE,
				END_EFFECTIVE_DATE=@END_EFFECTIVE_DATE,
				QUOTE=@QUOTE,
				PROJECT=@PROJECT,
				AGREEMENT_NO=@AGREEMENT_NO,
				COMMENTS=@COMMENTS,
				MODIFY_DATE=@MODIFY_DATE,
				MODIFY_USER=@MODIFY_USER,
				CREATE_DATE=@CREATE_DATE,
				CREATE_USER=@CREATE_USER,
				LOEKZ=@LOEKZ,
				PROCESS_FLAG=@PROCESS_FLAG,
				FID=@FID,
				VALID_FLAG=@VALID_FLAG				 
				WHERE [VALID_FLAG] = 1  AND ID =@ID;";

		private const string TT_SPM_SUPPLIER_PART_QUOTA_DELETE =
			@"DELETE FROM [LES].[TT_SPM_SUPPLIER_PART_QUOTA] WITH(ROWLOCK)  
				WHERE [VALID_FLAG] = 1  AND ID =@ID;";
		#endregion
		 
		#region Access Methods
		 
		/// <summary>
		/// Get SupplierPartQuotaInfo
		/// </summary>
		/// <param name="ID">SupplierPartQuotaInfo Primary key </param>
		/// <returns></returns> 
		public SupplierPartQuotaInfo GetInfo(long aId)
		{	
			Database db = DatabaseFactory.CreateDatabase();
			DbCommand dbCommand = db.GetSqlStringCommand(TT_SPM_SUPPLIER_PART_QUOTA_SELECT_BY_ID);
			db.AddInParameter(dbCommand, "@ID", DbType.Int64, aId);
			using (IDataReader dr = db.ExecuteReader(dbCommand))
			{
				if (dr.Read())
					return CreateSupplierPartQuotaInfo(dr);
			}
			return null;
		}
		/// <summary>
		/// Get data collection
		/// </summary>
		/// <param name="textWhere">Conditon</param>
		/// <param name="orderText">Sort</param>
		/// <returns>SupplierPartQuotaInfo Collection </returns>
		public List<SupplierPartQuotaInfo> GetList(string textWhere,string orderText)
		{
			string query = string.Empty;
			if (string.IsNullOrEmpty(textWhere))
				query = string.Empty;
			else
			{				
				if (textWhere.Trim().StartsWith("and", StringComparison.OrdinalIgnoreCase))
					query = textWhere;
				else
					query = " and " + textWhere;				
			}
			if (!string.IsNullOrEmpty(orderText))
				query += " order by " + orderText;
			
			return GetList(string.Format(TT_SPM_SUPPLIER_PART_QUOTA_SELECT, query));
		}		
		/// <summary>
		/// Get data collection
		/// </summary>
		/// <param name="sql">SQL Statement</param>
		/// <returns>SupplierPartQuotaInfo Collection </returns>
		public List<SupplierPartQuotaInfo> GetList(string sql)
		{
			Database db = DatabaseFactory.CreateDatabase();
			DbCommand dbCommand = db.GetSqlStringCommand(sql);
			List<SupplierPartQuotaInfo> list = new List<SupplierPartQuotaInfo>();
			using (IDataReader dr = db.ExecuteReader(dbCommand))
			{
				while (dr.Read())
				{
					list.Add(CreateSupplierPartQuotaInfo(dr));
				}
			}
			return list;
		}		
		/// <summary>
        /// 分页查询
        /// </summary>        
        /// <param name="textWhere">查询条件</param>
        /// <param name="orderText">排序字段</param>
        /// <param name="startRowIndex">当前页第一行行号</param>                    
        /// <param name="maximumRows">每页记录数</param>        
        /// <returns></returns>
		public List<SupplierPartQuotaInfo> GetListByPage(string textWhere, string textOrder, int pageIndex, int pageRow)
		{
		    if (pageIndex <= 0) pageIndex = 1;
            if (pageRow <= 0) pageRow = 10;
			string whereText = string.Empty;
            if (!string.IsNullOrEmpty(textWhere))
            {
                if (textWhere.Trim().StartsWith("and", StringComparison.OrdinalIgnoreCase))
                    whereText += " where [VALID_FLAG] = 1 " + textWhere;
                else
                    whereText += " where " + textWhere + " and [VALID_FLAG] = 1";
            }
			else
                whereText += " where [VALID_FLAG] = 1 ";
            if (string.IsNullOrEmpty(textOrder))
                textOrder += "[ID] desc";
            string sql = "select top " + pageRow + " * from "
                + "(select row_number() over(order by " + textOrder + ") as rownumber"
                + ",* from [LES].[TT_SPM_SUPPLIER_PART_QUOTA]  WITH(NOLOCK) " + whereText + ") T "
                + "where rownumber > " + (pageIndex - 1) * pageRow + " ";
            Database db = DatabaseFactory.CreateDatabase();
            DbCommand dbCommand = db.GetSqlStringCommand(sql);
            List<SupplierPartQuotaInfo> list = new List<SupplierPartQuotaInfo>();
            using (IDataReader dr = db.ExecuteReader(dbCommand))
            {
                while (dr.Read())
                {
                    list.Add(CreateSupplierPartQuotaInfo(dr));
                }
            }
            return list;
		}
		/// <summary>
        /// 分页查询
        /// </summary>        
        /// <param name="textWhere">查询条件</param>
        /// <param name="orderText">排序字段</param>            
        /// <returns></returns>
        public int GetCounts(string textWhere)
        {			
			if (string.IsNullOrEmpty(textWhere))
				textWhere = string.Empty;
			else
			{				
				if (!textWhere.Trim().StartsWith("and", StringComparison.OrdinalIgnoreCase))
					textWhere = " and " + textWhere;						
			}
			Database db = DatabaseFactory.CreateDatabase();
            DbCommand cmd = db.GetSqlStringCommand(string.Format(TT_SPM_SUPPLIER_PART_QUOTA_SELECT_COUNTS, textWhere));
			return Convert.ToInt32(db.ExecuteScalar(cmd));            
        }
		/// <summary>
		/// Add
		/// </summary>
		/// <param name="info"> info</param>
		public long Add(SupplierPartQuotaInfo info)
		{ 
			Database db = DatabaseFactory.CreateDatabase();	
			DbCommand dbCommand = db.GetSqlStringCommand(TT_SPM_SUPPLIER_PART_QUOTA_INSERT);			
			db.AddInParameter(dbCommand, "@PLANT", DbType.String, info.Plant);
			db.AddInParameter(dbCommand, "@PLANT_NAME", DbType.AnsiString, info.PlantName);
			db.AddInParameter(dbCommand, "@PART_NO", DbType.String, info.PartNo);
			db.AddInParameter(dbCommand, "@PART_CNAME", DbType.String, info.PartCname);
			db.AddInParameter(dbCommand, "@WORKSHOP", DbType.String, info.Workshop);
			db.AddInParameter(dbCommand, "@WORKSHOP_NAME", DbType.String, info.WorkshopName);
			db.AddInParameter(dbCommand, "@SUPPLIER_NUM", DbType.String, info.SupplierNum);
			db.AddInParameter(dbCommand, "@SUPPLIER_NAME", DbType.String, info.SupplierName);
			db.AddInParameter(dbCommand, "@START_EFFECTIVE_DATE", DbType.DateTime, info.StartEffectiveDate);
			db.AddInParameter(dbCommand, "@END_EFFECTIVE_DATE", DbType.DateTime, info.EndEffectiveDate);
			db.AddInParameter(dbCommand, "@QUOTE", DbType.Decimal, info.Quote);
			db.AddInParameter(dbCommand, "@PROJECT", DbType.String, info.Project);
			db.AddInParameter(dbCommand, "@AGREEMENT_NO", DbType.String, info.AgreementNo);
			db.AddInParameter(dbCommand, "@COMMENTS", DbType.String, info.Comments);
			db.AddInParameter(dbCommand, "@MODIFY_DATE", DbType.DateTime, info.ModifyDate);
			db.AddInParameter(dbCommand, "@MODIFY_USER", DbType.String, info.ModifyUser);
			db.AddInParameter(dbCommand, "@CREATE_DATE", DbType.DateTime, info.CreateDate);
			db.AddInParameter(dbCommand, "@CREATE_USER", DbType.String, info.CreateUser);
			db.AddInParameter(dbCommand, "@LOEKZ", DbType.String, info.Loekz);
			db.AddInParameter(dbCommand, "@PROCESS_FLAG", DbType.Int32, info.ProcessFlag);
			db.AddInParameter(dbCommand, "@FID", DbType.Guid, info.Fid);
			db.AddInParameter(dbCommand, "@VALID_FLAG", DbType.Boolean, info.ValidFlag);
			return long.Parse("0" + db.ExecuteScalar(dbCommand));		
		}
		/// <summary>
		/// GetInsertSql
		/// </summary>
		/// <param name="info"> info</param>
		public static string GetInsertSql(SupplierPartQuotaInfo info)
		{
			return  
			@"insert into [LES].[TT_SPM_SUPPLIER_PART_QUOTA] (
				PLANT,
				PLANT_NAME,
				PART_NO,
				PART_CNAME,
				WORKSHOP,
				WORKSHOP_NAME,
				SUPPLIER_NUM,
				SUPPLIER_NAME,
				START_EFFECTIVE_DATE,
				END_EFFECTIVE_DATE,
				QUOTE,
				PROJECT,
				AGREEMENT_NO,
				COMMENTS,
				MODIFY_DATE,
				MODIFY_USER,
				CREATE_DATE,
				CREATE_USER,
				LOEKZ,
				PROCESS_FLAG,
				FID,
				VALID_FLAG				 
			) values ("+
				(string.IsNullOrEmpty(info.Plant) ? "NULL" : "N'" + info.Plant + "'") + ","+
				(string.IsNullOrEmpty(info.PlantName) ? "NULL" : "N'" + info.PlantName + "'") + ","+
				(string.IsNullOrEmpty(info.PartNo) ? "NULL" : "N'" + info.PartNo + "'") + ","+
				(string.IsNullOrEmpty(info.PartCname) ? "NULL" : "N'" + info.PartCname + "'") + ","+
				(string.IsNullOrEmpty(info.Workshop) ? "NULL" : "N'" + info.Workshop + "'") + ","+
				(string.IsNullOrEmpty(info.WorkshopName) ? "NULL" : "N'" + info.WorkshopName + "'") + ","+
				(string.IsNullOrEmpty(info.SupplierNum) ? "NULL" : "N'" + info.SupplierNum + "'") + ","+
				(string.IsNullOrEmpty(info.SupplierName) ? "NULL" : "N'" + info.SupplierName + "'") + ","+
				(info.StartEffectiveDate == null ? "NULL" : "N'" + info.StartEffectiveDate.GetValueOrDefault() + "'") + ","+
				(info.EndEffectiveDate == null ? "NULL" : "N'" + info.EndEffectiveDate.GetValueOrDefault() + "'") + ","+
				(info.Quote == null ? "NULL" : "" + info.Quote.GetValueOrDefault() + "") + ","+
				(string.IsNullOrEmpty(info.Project) ? "NULL" : "N'" + info.Project + "'") + ","+
				(string.IsNullOrEmpty(info.AgreementNo) ? "NULL" : "N'" + info.AgreementNo + "'") + ","+
				(string.IsNullOrEmpty(info.Comments) ? "NULL" : "N'" + info.Comments + "'") + ","+
				"NULL" + ","+			
				"NULL" + ","+			
				"GETDATE()" + ","+			
				"N'" + info.CreateUser + "'" + ","+		
				(string.IsNullOrEmpty(info.Loekz) ? "NULL" : "N'" + info.Loekz + "'") + ","+
				(info.ProcessFlag == null ? "NULL" : "" + info.ProcessFlag.GetValueOrDefault() + "") + ","+
				(info.Fid == null ? "NEWID()" : "N'" + info.Fid.GetValueOrDefault() + "'") + ","+
				"1" + ");";		
				}
		/// <summary>
		/// Update
		/// </summary>
		/// <param name="info">info</param>
		public int Update(SupplierPartQuotaInfo info)
		{
			Database db = DatabaseFactory.CreateDatabase();
			DbCommand dbCommand = db.GetSqlStringCommand(TT_SPM_SUPPLIER_PART_QUOTA_UPDATE);				
			db.AddInParameter(dbCommand, "@ID", DbType.Int64, info.Id);
			db.AddInParameter(dbCommand, "@PLANT", DbType.String, info.Plant);
			db.AddInParameter(dbCommand, "@PLANT_NAME", DbType.AnsiString, info.PlantName);
			db.AddInParameter(dbCommand, "@PART_NO", DbType.String, info.PartNo);
			db.AddInParameter(dbCommand, "@PART_CNAME", DbType.String, info.PartCname);
			db.AddInParameter(dbCommand, "@WORKSHOP", DbType.String, info.Workshop);
			db.AddInParameter(dbCommand, "@WORKSHOP_NAME", DbType.String, info.WorkshopName);
			db.AddInParameter(dbCommand, "@SUPPLIER_NUM", DbType.String, info.SupplierNum);
			db.AddInParameter(dbCommand, "@SUPPLIER_NAME", DbType.String, info.SupplierName);
			db.AddInParameter(dbCommand, "@START_EFFECTIVE_DATE", DbType.DateTime, info.StartEffectiveDate);
			db.AddInParameter(dbCommand, "@END_EFFECTIVE_DATE", DbType.DateTime, info.EndEffectiveDate);
			db.AddInParameter(dbCommand, "@QUOTE", DbType.Decimal, info.Quote);
			db.AddInParameter(dbCommand, "@PROJECT", DbType.String, info.Project);
			db.AddInParameter(dbCommand, "@AGREEMENT_NO", DbType.String, info.AgreementNo);
			db.AddInParameter(dbCommand, "@COMMENTS", DbType.String, info.Comments);
			db.AddInParameter(dbCommand, "@MODIFY_DATE", DbType.DateTime, info.ModifyDate);
			db.AddInParameter(dbCommand, "@MODIFY_USER", DbType.String, info.ModifyUser);
			db.AddInParameter(dbCommand, "@CREATE_DATE", DbType.DateTime, info.CreateDate);
			db.AddInParameter(dbCommand, "@CREATE_USER", DbType.String, info.CreateUser);
			db.AddInParameter(dbCommand, "@LOEKZ", DbType.String, info.Loekz);
			db.AddInParameter(dbCommand, "@PROCESS_FLAG", DbType.Int32, info.ProcessFlag);
			db.AddInParameter(dbCommand, "@FID", DbType.Guid, info.Fid);
			db.AddInParameter(dbCommand, "@VALID_FLAG", DbType.Boolean, info.ValidFlag);
			return int.Parse("0" + db.ExecuteNonQuery(dbCommand));
		}		
		/// <summary>
		/// Delete
		/// </summary>
		/// <param name="ID">SupplierPartQuotaInfo Primary key </param>
		/// <returns></returns>
		public int Delete(long aId)
		{
			Database db = DatabaseFactory.CreateDatabase();
			DbCommand dbCommand = db.GetSqlStringCommand(TT_SPM_SUPPLIER_PART_QUOTA_DELETE);
		    db.AddInParameter(dbCommand, "@ID", DbType.Int64, aId);
			return int.Parse("0" + db.ExecuteNonQuery(dbCommand));
		}/// <summary>
		/// LogciDelete
		/// </summary>
		/// <param name="ID">SupplierPartQuotaInfo Primary key </param>
		/// <returns></returns>
		public int LogicDelete(long aId, string loginUser)
		{
		    string sql = "update [LES].[TT_SPM_SUPPLIER_PART_QUOTA] WITH(ROWLOCK) "
                + "set [VALID_FLAG] = @VALID_FLAG ,[MODIFY_USER] = @MODIFY_USER ,[MODIFY_DATE] = GETDATE() "
                + "WHERE [VALID_FLAG] = 1  AND ID =@ID;";
			Database db = DatabaseFactory.CreateDatabase();
			DbCommand dbCommand = db.GetSqlStringCommand(sql);
 			db.AddInParameter(dbCommand, "@ID", DbType.Int64, aId);
                      db.AddInParameter(dbCommand, "@VALID_FLAG", DbType.Boolean, false);
			db.AddInParameter(dbCommand, "@MODIFY_USER", DbType.AnsiString, loginUser);
			return int.Parse("0" + db.ExecuteNonQuery(dbCommand));
		}
		/// <summary>
		/// UpdateInfo
		/// </summary>
		/// <param name="ID">SupplierPartQuotaInfo Primary key </param>
		/// <returns></returns>
		public int UpdateInfo(string fields ,long aId)
		{
		    string sql = "update [LES].[TT_SPM_SUPPLIER_PART_QUOTA] WITH(ROWLOCK) "
                + "set " + fields
                + "WHERE [VALID_FLAG] = 1  AND ID =@ID;";
			Database db = DatabaseFactory.CreateDatabase();
			DbCommand dbCommand = db.GetSqlStringCommand(sql);
			db.AddInParameter(dbCommand, "@ID", DbType.Int64, aId);
			return int.Parse("0" + db.ExecuteNonQuery(dbCommand));
		}		
		#endregion
		  
		#region Helpers   
	  
		private static SupplierPartQuotaInfo CreateSupplierPartQuotaInfo(IDataReader rdr)
		{
			SupplierPartQuotaInfo info = new SupplierPartQuotaInfo();
			info.Id = DBConvert.GetInt64(rdr, rdr.GetOrdinal("ID"));			
			info.Plant = DBConvert.GetString(rdr, rdr.GetOrdinal("PLANT"));			
			info.PlantName = DBConvert.GetString(rdr, rdr.GetOrdinal("PLANT_NAME"));			
			info.PartNo = DBConvert.GetString(rdr, rdr.GetOrdinal("PART_NO"));			
			info.PartCname = DBConvert.GetString(rdr, rdr.GetOrdinal("PART_CNAME"));			
			info.Workshop = DBConvert.GetString(rdr, rdr.GetOrdinal("WORKSHOP"));			
			info.WorkshopName = DBConvert.GetString(rdr, rdr.GetOrdinal("WORKSHOP_NAME"));			
			info.SupplierNum = DBConvert.GetString(rdr, rdr.GetOrdinal("SUPPLIER_NUM"));			
			info.SupplierName = DBConvert.GetString(rdr, rdr.GetOrdinal("SUPPLIER_NAME"));			
			info.StartEffectiveDate = DBConvert.GetDateTimeNullable(rdr, rdr.GetOrdinal("START_EFFECTIVE_DATE"));			
			info.EndEffectiveDate = DBConvert.GetDateTimeNullable(rdr, rdr.GetOrdinal("END_EFFECTIVE_DATE"));			
			info.Quote = DBConvert.GetDecimalNullable(rdr, rdr.GetOrdinal("QUOTE"));			
			info.Project = DBConvert.GetString(rdr, rdr.GetOrdinal("PROJECT"));			
			info.AgreementNo = DBConvert.GetString(rdr, rdr.GetOrdinal("AGREEMENT_NO"));			
			info.Comments = DBConvert.GetString(rdr, rdr.GetOrdinal("COMMENTS"));			
			info.ModifyDate = DBConvert.GetDateTimeNullable(rdr, rdr.GetOrdinal("MODIFY_DATE"));			
			info.ModifyUser = DBConvert.GetString(rdr, rdr.GetOrdinal("MODIFY_USER"));			
			info.CreateDate = DBConvert.GetDateTime(rdr, rdr.GetOrdinal("CREATE_DATE"));			
			info.CreateUser = DBConvert.GetString(rdr, rdr.GetOrdinal("CREATE_USER"));			
			info.Loekz = DBConvert.GetString(rdr, rdr.GetOrdinal("LOEKZ"));			
			info.ProcessFlag = DBConvert.GetInt32Nullable(rdr, rdr.GetOrdinal("PROCESS_FLAG"));			
			info.Fid = DBConvert.GetGuidNullable(rdr, rdr.GetOrdinal("FID"));			
			info.ValidFlag = DBConvert.GetBoolNullable(rdr, rdr.GetOrdinal("VALID_FLAG"));			
			return info;
		}
		
		#endregion
	}
}
