//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrustructure.Utilities.Exception
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionRecs
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionRecs()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YF.MES.CC.Utility.Exception.ExceptionRecs", typeof(ExceptionRecs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 系统出现异常.
        /// </summary>
        internal static string E_00001
        {
            get
            {
                return ResourceManager.GetString("E_00001", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 公共级异常.
        /// </summary>
        internal static string E_00201
        {
            get
            {
                return ResourceManager.GetString("E_00201", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 参数不能为空.
        /// </summary>
        internal static string E_00202
        {
            get
            {
                return ResourceManager.GetString("E_00202", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 用户输入的应用参数名已经存在.
        /// </summary>
        internal static string E_00203
        {
            get
            {
                return ResourceManager.GetString("E_00203", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 用户未登录.
        /// </summary>
        internal static string E_00204
        {
            get
            {
                return ResourceManager.GetString("E_00204", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 编辑页面QueryString参数错误.
        /// </summary>
        internal static string E_00205
        {
            get
            {
                return ResourceManager.GetString("E_00205", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 用户输入的参数名已经存在.
        /// </summary>
        internal static string E_00206
        {
            get
            {
                return ResourceManager.GetString("E_00206", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 无法根据主键找到记录.
        /// </summary>
        internal static string E_00207
        {
            get
            {
                return ResourceManager.GetString("E_00207", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 没有数据可供导出，请先查询到数据后再进行导出.
        /// </summary>
        internal static string E_00208
        {
            get
            {
                return ResourceManager.GetString("E_00208", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 导出的数据量太大，请联系IT管理员从其他途径获取当前数据.
        /// </summary>
        internal static string E_00209
        {
            get
            {
                return ResourceManager.GetString("E_00209", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 系统管理异常.
        /// </summary>
        internal static string E_00501
        {
            get
            {
                return ResourceManager.GetString("E_00501", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 外部接口管理子系统异常.
        /// </summary>
        internal static string E_01001
        {
            get
            {
                return ResourceManager.GetString("E_01001", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 区域管理异常.
        /// </summary>
        internal static string E_02001
        {
            get
            {
                return ResourceManager.GetString("E_02001", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 加载工厂列表失败.
        /// </summary>
        internal static string E_02002
        {
            get
            {
                return ResourceManager.GetString("E_02002", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 加载车间列表失败.
        /// </summary>
        internal static string E_02003
        {
            get
            {
                return ResourceManager.GetString("E_02003", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 加载路径列表失败.
        /// </summary>
        internal static string E_02004
        {
            get
            {
                return ResourceManager.GetString("E_02004", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 加载位置列表失败.
        /// </summary>
        internal static string E_02005
        {
            get
            {
                return ResourceManager.GetString("E_02005", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 加载区域列表失败.
        /// </summary>
        internal static string E_02006
        {
            get
            {
                return ResourceManager.GetString("E_02006", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 加载DOCK列表失败.
        /// </summary>
        internal static string E_02007
        {
            get
            {
                return ResourceManager.GetString("E_02007", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 工厂已经存在.
        /// </summary>
        internal static string E_02008
        {
            get
            {
                return ResourceManager.GetString("E_02008", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 车间已经存在.
        /// </summary>
        internal static string E_02009
        {
            get
            {
                return ResourceManager.GetString("E_02009", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DOCK已经存在.
        /// </summary>
        internal static string E_02010
        {
            get
            {
                return ResourceManager.GetString("E_02010", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 位置已经存在.
        /// </summary>
        internal static string E_02011
        {
            get
            {
                return ResourceManager.GetString("E_02011", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 路径已经存在.
        /// </summary>
        internal static string E_02012
        {
            get
            {
                return ResourceManager.GetString("E_02012", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 区域已经存在.
        /// </summary>
        internal static string E_02013
        {
            get
            {
                return ResourceManager.GetString("E_02013", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 导入的文件格式不正确，请严格按照导出的预定格式填写.
        /// </summary>
        internal static string E_02014
        {
            get
            {
                return ResourceManager.GetString("E_02014", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 该车间还存在用户和供应商与之关联，请先删除相关的供应商和用户关联.
        /// </summary>
        internal static string E_02017
        {
            get
            {
                return ResourceManager.GetString("E_02017", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 该工厂还存在车间与之关联，请先删除相关的车间关联.
        /// </summary>
        internal static string E_02018
        {
            get
            {
                return ResourceManager.GetString("E_02018", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DD管理异常.
        /// </summary>
        internal static string E_02050
        {
            get
            {
                return ResourceManager.GetString("E_02050", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 非按灯卡，不能扫描.
        /// </summary>
        internal static string E_02051
        {
            get
            {
                return ResourceManager.GetString("E_02051", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 物料单数据错误，缺少零件记录.
        /// </summary>
        internal static string E_02052
        {
            get
            {
                return ResourceManager.GetString("E_02052", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 没有卡组号，不能扫描.
        /// </summary>
        internal static string E_02054
        {
            get
            {
                return ResourceManager.GetString("E_02054", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 非看板卡号，不能扫描.
        /// </summary>
        internal static string E_02055
        {
            get
            {
                return ResourceManager.GetString("E_02055", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EPS管理异常.
        /// </summary>
        internal static string E_02150
        {
            get
            {
                return ResourceManager.GetString("E_02150", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 无法根据拉动关系主键找到记录.
        /// </summary>
        internal static string E_02151
        {
            get
            {
                return ResourceManager.GetString("E_02151", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 无法找到按钮记录.
        /// </summary>
        internal static string E_02152
        {
            get
            {
                return ResourceManager.GetString("E_02152", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 无法取消任务,在任务已取消、空箱返回和任务已完成状态下不能取消.
        /// </summary>
        internal static string E_02153
        {
            get
            {
                return ResourceManager.GetString("E_02153", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 终端编号已经存在.
        /// </summary>
        internal static string E_02154
        {
            get
            {
                return ResourceManager.GetString("E_02154", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 按钮已经存在.
        /// </summary>
        internal static string E_02155
        {
            get
            {
                return ResourceManager.GetString("E_02155", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 无法找到按钮.
        /// </summary>
        internal static string E_02156
        {
            get
            {
                return ResourceManager.GetString("E_02156", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 无法找到终端.
        /// </summary>
        internal static string E_02157
        {
            get
            {
                return ResourceManager.GetString("E_02157", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 待删除的拉动关系对应的零件卡已经建立了与卡片的关联关系，请先删除按钮与卡片的关联关系.
        /// </summary>
        internal static string E_02158
        {
            get
            {
                return ResourceManager.GetString("E_02158", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to JIT管理异常.
        /// </summary>
        internal static string E_02200
        {
            get
            {
                return ResourceManager.GetString("E_02200", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 加载料架列表失败.
        /// </summary>
        internal static string E_02201
        {
            get
            {
                return ResourceManager.GetString("E_02201", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 加载成对料架列表失败.
        /// </summary>
        internal static string E_02202
        {
            get
            {
                return ResourceManager.GetString("E_02202", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 料架已经存在.
        /// </summary>
        internal static string E_02203
        {
            get
            {
                return ResourceManager.GetString("E_02203", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 成对料架已经存在.
        /// </summary>
        internal static string E_02204
        {
            get
            {
                return ResourceManager.GetString("E_02204", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 无法找到JIT4位零件.
        /// </summary>
        internal static string E_02205
        {
            get
            {
                return ResourceManager.GetString("E_02205", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to JIT零件4位对8位对应关系已经存在.
        /// </summary>
        internal static string E_02206
        {
            get
            {
                return ResourceManager.GetString("E_02206", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 无法找到Runsheet特殊说明.
        /// </summary>
        internal static string E_02207
        {
            get
            {
                return ResourceManager.GetString("E_02207", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Runsheet特殊说明已经存在.
        /// </summary>
        internal static string E_02208
        {
            get
            {
                return ResourceManager.GetString("E_02208", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 导入的料架数据格式不正确，建议先导出然后再导入.
        /// </summary>
        internal static string E_02209
        {
            get
            {
                return ResourceManager.GetString("E_02209", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 在编辑FLEX零件号对应关系时输入的零件号码格式不正确，零件号码的后四位应该与FLEX零件号一致.
        /// </summary>
        internal static string E_02210
        {
            get
            {
                return ResourceManager.GetString("E_02210", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 零件管理异常.
        /// </summary>
        internal static string E_02250
        {
            get
            {
                return ResourceManager.GetString("E_02250", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 卡号位数不正确!请输入4位卡号!.
        /// </summary>
        internal static string E_02251
        {
            get
            {
                return ResourceManager.GetString("E_02251", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 卡号位数不正确!请输入8位卡号!.
        /// </summary>
        internal static string E_02252
        {
            get
            {
                return ResourceManager.GetString("E_02252", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 零件卡信息不存在！.
        /// </summary>
        internal static string E_02253
        {
            get
            {
                return ResourceManager.GetString("E_02253", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 零件信息不存在！.
        /// </summary>
        internal static string E_02254
        {
            get
            {
                return ResourceManager.GetString("E_02254", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 该卡未启用！.
        /// </summary>
        internal static string E_02255
        {
            get
            {
                return ResourceManager.GetString("E_02255", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  需要两级拉动的零件在RC车间无对应的卡号!.
        /// </summary>
        internal static string E_02256
        {
            get
            {
                return ResourceManager.GetString("E_02256", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  零件库存信息不存在!.
        /// </summary>
        internal static string E_02257
        {
            get
            {
                return ResourceManager.GetString("E_02257", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  零件与零件卡的关联关系不存在!.
        /// </summary>
        internal static string E_02258
        {
            get
            {
                return ResourceManager.GetString("E_02258", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  零件盘点记录不存在!.
        /// </summary>
        internal static string E_02259
        {
            get
            {
                return ResourceManager.GetString("E_02259", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  零件盘点记录已经存在!.
        /// </summary>
        internal static string E_02260
        {
            get
            {
                return ResourceManager.GetString("E_02260", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 库存信息中的路径、零件号、库位与零件卡里的对应字段匹配不上.
        /// </summary>
        internal static string E_02261
        {
            get
            {
                return ResourceManager.GetString("E_02261", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PPS管理异常.
        /// </summary>
        internal static string E_02300
        {
            get
            {
                return ResourceManager.GetString("E_02300", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 打印机管理异常.
        /// </summary>
        internal static string E_02400
        {
            get
            {
                return ResourceManager.GetString("E_02400", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 报表管理异常.
        /// </summary>
        internal static string E_02500
        {
            get
            {
                return ResourceManager.GetString("E_02500", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 供应商管理异常.
        /// </summary>
        internal static string E_02600
        {
            get
            {
                return ResourceManager.GetString("E_02600", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  加载供应商列表失败.
        /// </summary>
        internal static string E_02601
        {
            get
            {
                return ResourceManager.GetString("E_02601", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  供应商已经存在.
        /// </summary>
        internal static string E_02602
        {
            get
            {
                return ResourceManager.GetString("E_02602", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  供应商工厂车间关系已经存在.
        /// </summary>
        internal static string E_02603
        {
            get
            {
                return ResourceManager.GetString("E_02603", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 供应商窗口时间已经存在.
        /// </summary>
        internal static string E_02604
        {
            get
            {
                return ResourceManager.GetString("E_02604", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 系统管理异常.
        /// </summary>
        internal static string E_02650
        {
            get
            {
                return ResourceManager.GetString("E_02650", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  用户输入的代码值和代码名称已经存在.
        /// </summary>
        internal static string E_02651
        {
            get
            {
                return ResourceManager.GetString("E_02651", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  用户输入的代码名称已经存在.
        /// </summary>
        internal static string E_02652
        {
            get
            {
                return ResourceManager.GetString("E_02652", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  用户输入的系统表示符已经存在.
        /// </summary>
        internal static string E_02653
        {
            get
            {
                return ResourceManager.GetString("E_02653", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 监控管理异常.
        /// </summary>
        internal static string E_02750
        {
            get
            {
                return ResourceManager.GetString("E_02750", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 接口查询异常.
        /// </summary>
        internal static string E_02850
        {
            get
            {
                return ResourceManager.GetString("E_02850", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 备用异常.
        /// </summary>
        internal static string E_02900
        {
            get
            {
                return ResourceManager.GetString("E_02900", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 无法根据Activity找到纪录.
        /// </summary>
        internal static string E_02901
        {
            get
            {
                return ResourceManager.GetString("E_02901", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Activity编号已经存在.
        /// </summary>
        internal static string E_02902
        {
            get
            {
                return ResourceManager.GetString("E_02902", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 物流执行引擎子系统异常.
        /// </summary>
        internal static string E_03001
        {
            get
            {
                return ResourceManager.GetString("E_03001", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EPS无线终端客户端应用子系统.
        /// </summary>
        internal static string E_04001
        {
            get
            {
                return ResourceManager.GetString("E_04001", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EPS任务发布子系统.
        /// </summary>
        internal static string E_05001
        {
            get
            {
                return ResourceManager.GetString("E_05001", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  无线按钮表中，没有指定按钮编号的配置信息.
        /// </summary>
        internal static string E_05002
        {
            get
            {
                return ResourceManager.GetString("E_05002", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RDC供应商客户端应用子系统.
        /// </summary>
        internal static string E_06001
        {
            get
            {
                return ResourceManager.GetString("E_06001", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 外部供应商客户端应用子系统.
        /// </summary>
        internal static string E_07001
        {
            get
            {
                return ResourceManager.GetString("E_07001", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to JIT/DD发布子系统错误.
        /// </summary>
        internal static string E_08001
        {
            get
            {
                return ResourceManager.GetString("E_08001", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 运营监控管理子系统.
        /// </summary>
        internal static string E_09001
        {
            get
            {
                return ResourceManager.GetString("E_09001", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 基础服务子系统.
        /// </summary>
        internal static string E_10001
        {
            get
            {
                return ResourceManager.GetString("E_10001", resourceCulture);
            }
        }
    }
}
