CREATE TABLE [LES].[RUNSHEET_TEMP] (
    [WM_NO]         NVARCHAR (10) NULL,
    [ZONE_NO]       NVARCHAR (20) NULL,
    [DLOC]          NVARCHAR (20) NULL,
    [PACKAGE_MODEL] NVARCHAR (30) NULL,
    [vbeln]         NVARCHAR (12) NULL,
    [MATNR]         NVARCHAR (18) NULL
);

