CREATE TABLE [LES].[TI_BAS_PART_LACATION_IN_20160919] (
    [SEQ_ID]       BIGINT         IDENTITY (1, 1) NOT NULL,
    [ZDOCNUM]      NVARCHAR (16)  NULL,
    [ZKWERK]       NVARCHAR (4)   NULL,
    [ZIDNKD]       NVARCHAR (18)  NULL,
    [ZWS]          NVARCHAR (2)   NULL,
    [ZLINE]        NVARCHAR (8)   NULL,
    [ZLOC]         NVARCHAR (8)   NULL,
    [ZVRKME]       NVARCHAR (10)  NULL,
    [DEAL_FLAG]    INT            NULL,
    [PROCESS_FLAG] INT            NULL,
    [PROCESS_TIME] DATETIME       NULL,
    [LOGICAL_PK]   NVARCHAR (50)  NULL,
    [BUSINESS_PK]  NVARCHAR (50)  NULL,
    [COMMENTS]     NVARCHAR (200) NULL,
    [UPDATE_DATE]  DATETIME       NULL,
    [UPDATE_USER]  NVARCHAR (50)  NULL,
    [CREATE_DATE]  DATETIME       NOT NULL,
    [CREATE_USER]  NVARCHAR (50)  NOT NULL
);

