CREATE TABLE [LES].[TI_SPM_UNPAY_IN_ARC] (
    [SEQ_ID]         BIGINT          IDENTITY (1, 1) NOT NULL,
    [MJAHR]          NVARCHAR (4)    NULL,
    [ZEILE]          NVARCHAR (4)    NULL,
    [BUDAT1]         DATETIME        NULL,
    [DEAL_FLAG]      INT             NULL,
    [INVOICE_NO]     NVARCHAR (50)   NULL,
    [INVOICE_AMOUNT] NUMERIC (18, 3) NULL,
    [VBELN]          NVARCHAR (10)   NULL,
    [POSNR]          NVARCHAR (18)   NULL,
    [MATNR]          NVARCHAR (18)   NULL,
    [LGMNG]          NUMERIC (18, 3) NULL,
    [MEINS]          NVARCHAR (8)    NULL,
    [LIFNR]          NVARCHAR (10)   NULL,
    [BUDAT]          NVARCHAR (10)   NULL,
    [LFUHR]          NVARCHAR (10)   NULL,
    [WERKS]          NVARCHAR (4)    NULL,
    [LGORT]          NVARCHAR (18)   NULL,
    [LFART]          NVARCHAR (4)    NULL,
    [MBLNR]          NVARCHAR (10)   NULL,
    [ZYSQJC]         NVARCHAR (20)   NULL,
    [BSTRF]          NUMERIC (18, 3) NULL,
    [MAKTX_ZH]       NVARCHAR (40)   NULL,
    [AMOUNT]         DECIMAL (18, 3) NULL,
    [PROCESS_FLAG]   INT             NULL,
    [PROCESS_TIME]   DATETIME        NULL,
    [COMMENTS]       NVARCHAR (200)  NULL,
    [UPDATE_DATE]    DATETIME        NULL,
    [UPDATE_USER]    NVARCHAR (50)   NULL,
    [CREATE_DATE]    DATETIME        NOT NULL,
    [CREATE_USER]    NVARCHAR (50)   NOT NULL,
    [EMLIF]          NVARCHAR (10)   NULL,
    [MWSKZ]          NVARCHAR (2)    NULL,
    [WAERS]          NVARCHAR (5)    NULL,
    [SCHPR]          NVARCHAR (1)    NULL
);

