CREATE TABLE [LES].[TT_TWD_RUNSHEET_DETAIL] (
    [RUNSHEET_DETAIL_ID]           INT            IDENTITY (1, 1) NOT NULL,
    [TWD_RUNSHEET_SN]              INT            NOT NULL,
    [PLANT]                        NVARCHAR (5)   NOT NULL,
    [ASSEMBLY_LINE]                NVARCHAR (10)  NOT NULL,
    [SUPPLIER_NUM]                 NVARCHAR (12)  NOT NULL,
    [PART_NO]                      NVARCHAR (20)  NOT NULL,
    [IDENTIFY_PART_NO]             NVARCHAR (20)  NULL,
    [PART_CNAME]                   NVARCHAR (300) NULL,
    [PART_ENAME]                   NVARCHAR (300) NULL,
    [DOCK]                         NVARCHAR (10)  NOT NULL,
    [BOX_PARTS]                    NVARCHAR (10)  NOT NULL,
    [SEQUENCE_NO]                  INT            NULL,
    [PICKUP_SEQ_NO]                INT            NULL,
    [RDC_DLOC]                     VARCHAR (20)   NULL,
    [INBOUND_PACKAGE]              INT            NOT NULL,
    [MEASURING_UNIT_NO]            VARCHAR (8)    NULL,
    [INBOUND_PACKAGE_MODEL]        NVARCHAR (30)  NULL,
    [PACK_COUNT]                   INT            NOT NULL,
    [REQUIRED_INBOUND_PACKAGE]     INT            NOT NULL,
    [REQUIRED_INBOUND_PACKAGE_QTY] INT            NOT NULL,
    [ACTUAL_INBOUND_PACKAGE]       INT            NULL,
    [ACTUAL_INBOUND_PACKAGE_QTY]   INT            NULL,
    [BARCODE_DATA]                 NVARCHAR (50)  NULL,
    [ORDER_NO]                     NVARCHAR (50)  NULL,
    [ITEM_NO]                      NVARCHAR (50)  NULL,
    [COMMENTS]                     NVARCHAR (200) NULL,
    [RECKONING_SN]                 INT            NULL,
    [SUPPLIER_NUM_SHEET]           NVARCHAR (12)  NULL,
    [BOX_PARTS_SHEET]              NVARCHAR (10)  NULL,
    [MANUAL_LOCATION]              NVARCHAR (20)  NULL,
    [PRINT_TIMES]                  INT            NULL,
    [PRINT_STATE]                  INT            NULL,
    [PRINT_SUPPLEMENT]             INT            NULL,
    [ASN_DRAFT_QTY]                INT            NULL,
    [ASN_CONFIRM_QTY]              INT            NULL
);

