CREATE TABLE [dbo].[TM_BAS_COMPANY] (
    [ID]          BIGINT           IDENTITY (1, 1) NOT NULL,
    [FID]         UNIQUEIDENTIFIER NULL,
    [OID]         UNIQUEIDENTIFIER NULL,
    [C_CODE]      NVARCHAR (50)    NULL,
    [C_NAME]      NVARCHAR (50)    NULL,
    [COM_ID]      NVARCHAR (50)    NULL,
    [DEPT_ID]     NVARCHAR (50)    NULL,
    [PROVINCE]    NVARCHAR (50)    NULL,
    [CITY]        NVARCHAR (50)    NULL,
    [C_ADDRESS]   NVARCHAR (50)    NULL,
    [ZIP_CODE]    NVARCHAR (50)    NULL,
    [CREATE_DATE] DATETIME         NULL,
    [CREATE_USER] NVARCHAR (50)    NULL,
    [MODIFY_DATE] DATETIME         NULL,
    [MODIFY_USER] NVARCHAR (50)    NULL,
    [VALID_FLAG]  BIT              NULL,
    CONSTRAINT [PK_TM_BAS_COMPANY] PRIMARY KEY CLUSTERED ([ID] ASC)
);

