CREATE TABLE [LES].[TM_BAS_PLANT_ZONE] (
    [PLANT]               NVARCHAR (5)   NOT NULL,
    [PLANT_ZONE]          NVARCHAR (5)   NOT NULL,
    [PLANT_ZONE_NAME]     NVARCHAR (100) NOT NULL,
    [PLANT_ZONE_NICKNAME] NVARCHAR (20)  NULL,
    [ADDRESS]             NVARCHAR (200) NULL,
    [CREATE_USER]         NVARCHAR (50)  NOT NULL,
    [CREATE_DATE]         DATETIME       NOT NULL,
    [UPDATE_USER]         NVARCHAR (50)  NULL,
    [UPDATE_DATE]         DATETIME       NULL,
    CONSTRAINT [IDX_PK_PLANT_ZONE_PLANT_PLANT_ZONE] PRIMARY KEY CLUSTERED ([PLANT] ASC, [PLANT_ZONE] ASC)
);

