CREATE TABLE [LES].[TM_BAS_WORKSHOP] (
    [PLANT]               NVARCHAR (5)   NOT NULL,
    [WORKSHOP]            NVARCHAR (4)   NOT NULL,
    [WORKSHOP_NAME]       NVARCHAR (100) NOT NULL,
    [TIME_REFERENCE_TYPE] INT            NULL,
    [WORK_SCHEDULE_TYPE]  INT            NULL,
    [WORKSHOP_TYPE]       INT            NULL,
    [CREATE_USER]         NVARCHAR (50)  NOT NULL,
    [CREATE_DATE]         DATETIME       NOT NULL,
    [UPDATE_USER]         NVARCHAR (50)  NULL,
    [UPDATE_DATE]         DATETIME       NULL,
    CONSTRAINT [IDX_PK_WORKSHOP_PLANT_WORKSHOP] PRIMARY KEY CLUSTERED ([PLANT] ASC, [WORKSHOP] ASC)
);

