CREATE VIEW [LES].[V_TM_RPM_PACKAGE_STOCKS_VIEW]
AS 
SELECT t_stocks.*,t_appliance.PACKAGE_CNAME,t_appliance.PACKAGE_ENAME,t_detail1.DETAIL_VALUE AS PACKAGE_TYPE_Name,t_appliance.PACKAGE_TYPE
	FROM LES.TM_RPM_PACKAGE_STOCKS t_stocks 
	INNER JOIN LES.TM_RPM_PACKAGE_APPLIANCE t_appliance
ON t_appliance.PACKAGE_NO = t_stocks.PACKAGE_NO 
	LEFT JOIN LES.TC_SYS_CODE_DETAIL t_detail1
ON t_detail1.DETAIL_CODE = t_appliance.PACKAGE_TYPE
	 AND t_detail1.CODE_NAME='pack_PACKAGE_TYPE'