-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE PROC_TMP_INSERT_OUTPUT
	-- Add the parameters for the stored procedure here
	@RunsheetSn INT,
	@OutPutId	bigint
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    DECLARE @PLANT_ZONE NVARCHAR(10)
	declare @TARGET_WM NVARCHAR(20)
	declare @TARGET_ZONE  NVARCHAR(20)

	DECLARE @JIS_RUNSHEET_NO NVARCHAR(100);	--将拉动单取出
		
	DECLARE @SUPPLIER_NUM NVARCHAR(20);		--拉动供应商

	SELECT @JIS_RUNSHEET_NO=JIS_RUNSHEET_NO,@SUPPLIER_NUM = SUPPLIER_NUM, @PLANT_ZONE=PLANT_ZONE FROM LES.TT_JIS_RUNSHEET WHERE JIS_RUNSHEET_SN=@RunsheetSn;
	select top 1 @TARGET_WM =WM_NO from [LES].[TM_WMM_ZONES] C where C.ZONE_NO = @PLANT_ZONE
	select top 1 @TARGET_ZONE = ZONE_NO from [LES].[TM_WMM_ZONES] C where C.ZONE_NO = @PLANT_ZONE

	-------插入数据到出库明细表--------
	INSERT INTO [LES].[TT_WMM_OUTPUT_DETAIL] ( 
		OUTPUT_ID,--出库主表ID
		PLANT,--工厂
		SUPPLIER_NUM,--供应商
		WM_NO,--仓库编码
		ZONE_NO,--存储区编码
		DLOC,---库位
		TRAN_NO,--交易编码
		TARGET_WM,--目的仓库
		TARGET_ZONE,--目的存储区
		TARGET_DLOC,--目的库位
		PART_NO,--零件号
		PART_CNAME,--零件中文名
		PACK_COUNT,--包装数
		REQUIRED_BOX_NUM,--需求箱数
		REQUIRED_QTY,--需求数量
		ACTUAL_BOX_NUM,--实际箱数
		ACTUAL_QTY,--实际数量
		PACKAGE_MODEL,--包装型号
		BARCODE_DATA,--条码
		MEASURING_UNIT_NO,--单位
		PACKAGE,--单位
		NUM,--数量
		BOX_NUM,--箱数
		IDENTIFY_PART_NO,--标识零件号
		PART_ENAME,--零件德文名
		DOCK,--工厂模型DOCK
		ASSEMBLY_LINE,--流水线
		BOX_PARTS,--零件类
		SEQUENCE_NO,--排序号
		PICKUP_SEQ_NO,--捡料顺序号
		RDC_DLOC,--供应商库位
		INHOUSE_PACKAGE,--上线包装数量
		INBOUND_PACKAGE_MODEL,--上线包装型号
		SUPPLIER_NUM_SHEET,--基础数据组单_供应商
		BOX_PARTS_SHEET,--零件类组单
		ORDER_NO,--订单号
		ITEM_NO,
		TWD_RUNSHEET_NO,--拉动单号
		COMMENTS,--备注
		CREATE_DATE,
		CREATE_USER		 
	)
	Select * from 
	(
		SELECT 
		@OutPutId AS OUTPUT_ID,
		D.PLANT AS PLANT,
		F.SUPPLIER_NUM,
		(select top 1 WM_NO from [LES].[TM_WMM_ZONES] B where B.PLANT = F.PLANT AND B.ZONE_NO = F.SUPPLIER_NUM ) AS WM_NO,
		F.SUPPLIER_NUM AS ZONE_NO,
		(select top 1 DLOC from les.TM_BAS_PARTS_STOCK P where p.part_no = D.PART_NO 
			and p.PLANT = F.PLANT AND p.ZONE_NO = F.SUPPLIER_NUM) AS	DLOC,
		@RunsheetSn AS TRAN_NO,
		@TARGET_WM AS TARGET_WM,
		@TARGET_ZONE AS TARGET_ZONE,
		(select top 1 DLOC from les.TM_BAS_PARTS_STOCK TARGET_P where TARGET_P.part_no = D.PART_NO 
			and TARGET_P.PLANT = F.PLANT AND TARGET_P.ZONE_NO = @PLANT_ZONE) AS	TARGET_DLOC,
		D.PART_NO,
		D.PART_CNAME,
		E.INBOUND_PACKAGE AS	PACK_COUNT,
		1 AS REQUIRED_BOX_NUM,--需求箱数
		D.USAGE AS	REQUIRED_QTY,--需求数量
		1  AS	ACTUAL_BOX_NUM,--实际箱数
		D.USAGE AS ACTUAL_QTY,--实际数量
		E.INBOUND_PACKAGE_MODEL AS PACKAGE_MODEL,--包装型号
		NULL AS	BARCODE_DATA,
		(select top 1 part_units from les.TM_BAS_MAINTAIN_PARTS s where s.plant=d.PLANT and s.part_no=d.part_no) AS	MEASURING_UNIT_NO,--单位
		E.INBOUND_PACKAGE AS	PACKAGE,
		NULL AS	NUM,
		NULL AS	BOX_NUM,
		D.PART_NO AS	IDENTIFY_PART_NO,
		E.PART_ENAME AS	PART_ENAME,
		E.DOCK,
		D.ASSEMBLY_LINE AS	ASSEMBLY_LINE,
		BOX_PARTS,
		NULL AS	SEQUENCE_NO,
		NULL AS	PICKUP_SEQ_NO,
		NULL AS	RDC_DLOC,
		E.INBOUND_PACKAGE	AS	INHOUSE_PACKAGE,
		E.INBOUND_PACKAGE_MODEL AS	INBOUND_PACKAGE_MODEL,
		NULL AS	SUPPLIER_NUM_SHEET,
		NULL AS	BOX_PARTS_SHEET,
		NULL AS	ORDER_NO,
		NULL AS	ITEM_NO,
		@JIS_RUNSHEET_NO AS	TWD_RUNSHEET_NO,
		D.COMMENTS AS COMMENTS,
		GETDATE() AS	CREATE_DATE,
		'admin' AS	CREATE_USER				
		FROM LES.TT_JIS_RUNSHEET_FLEX F
		INNER JOIN  LES.TT_JIS_RUNSHEET_DETAIL D ON F.JIS_RUNSHEET_FLEX_SN=D.JIS_RUNSHEET_FLEX_SN
		INNER JOIN LES.TM_JIS_RACK R ON F.RACK=R.RACK and R.ASSEMBLY_LINE=F.ASSEMBLY_LINE
		INNER JOIN [LES].[TM_BAS_MAINTAIN_INHOUSE_LOGISTIC_STANDARD] E ON E.LOCATION=R.LOCATION AND E.PLANT = F.PLANT AND E.PART_NO = D.PART_NO AND E.INHOUSE_PART_CLASS = F.RACK 
		WHERE F.JIS_RUNSHEET_SN=@RunsheetSn and E.INHOUSE_SYSTEM_MODE = 'JIS' 
	) as Temp
	where  Temp.WM_NO is not null

END