CREATE VIEW LES.TT_WMM_ONBOARDTASK_SELECT_lIST
AS
SELECT
    A.*,
    ORDER_NO = (SELECT TOP 1 ORDER_NO FROM[LES].[TT_SPM_TRAY_LOG] B WITH(NOLOCK) WHERE A.REAL_TRAY_BARCODE = B.TRAY_NO ORDER BY ID DESC)
    FROM[LES].[TT_WMM_ONBOARD_TASK] A WITH(NOLOCK)
    WHERE A.REAL_TRAY_BARCODE IS NOT NULL AND LEN(A.REAL_TRAY_BARCODE) > 0
    UNION
    SELECT
    A.*,
    ORDER_NO = (SELECT TOP 1 ORDER_NO FROM[LES].[TT_SPM_TRAY_LOG] B WITH(NOLOCK) WHERE A.RECOMMEND_TRAY_BARCODE = B.TRAY_NO ORDER BY ID DESC)
    FROM[LES].[TT_WMM_ONBOARD_TASK]
        A WITH(NOLOCK)
    WHERE A.REAL_TRAY_BARCODE IS NULL OR A.REAL_TRAY_BARCODE = ''