
CREATE VIEW [LES].[V_BAS_LOCATION_COORDINATE]
AS
	SELECT	A.*, B.FOOTPRINT 
	FROM	LES.TM_BAS_LOCATION_COORDINATE A
	INNER	JOIN LES.TM_BAS_LOCATION B
	ON		A.PLANT = B.PLANT AND A.ASSEMBLY_LINE = B.ASSEMBLY_LINE AND A.LOCATION = B.LOCATION