


/*添加外库库存查询视图*/
CREATE VIEW [LES].[V_BAS_VMI_SUPPLIER_ASN_FLAG]
AS
	SELECT   
	SEQ_ID, PLANT, WM_NO, ZONE_NO,ZONE_NAME, SUPPLIER_NUM, SUPPLIER_NAME, COMMENTS, CREATE_USER, CREATE_DATE, 
	UPDATE_USER, UPDATE_DATE, ASN_FLAG,VMI_FLAG
	FROM 
	(
		SELECT   
		VS.SEQ_ID, VS.PLANT, VS.WM_NO, VS.ZONE_NO,WZ.ZONE_NAME, VS.SUPPLIER_NUM, VS.SUPPLIER_NAME, VS.COMMENTS, 
		VS.CREATE_USER, VS.CREATE_DATE, VS.UPDATE_USER, VS.UPDATE_DATE, ISNULL(VS.ASN_FLAG, 0) AS ASN_FLAG,ISNULL(VS.VMI_FLAG,0) AS VMI_FLAG
		FROM LES.TM_BAS_VMI_SUPPLIER AS VS WITH(NOLOCK) 
		INNER JOIN [LES].[TM_WMM_ZONES] AS WZ WITH(NOLOCK) ON VS.ZONE_NO=WZ.ZONE_NO
	) AS T