
/********************************************************************/
/*   Project Name:  BAS                                               */
/*   Program Name:  [V_BAS_INBOUND_PULL_LOGISTIC_STANDARD_GROUP_BY_SUPPLYER]*/
/*   Called By:     入库拉动单物流标准                                  */
/*    Author:       yingxuefeng                                      */
/********************************************************************/
CREATE view [LES].[V_BAS_INBOUND_PULL_LOGISTIC_STANDARD_GROUP_BY_SUPPLYER]
AS

SELECT 
	   MAX(INBOUND_IDENTITY) AS INBOUND_IDENTITY
	  ,[PLANT]
      ,[ASSEMBLY_LINE]
      ,[PLANT_ZONE]
      ,[WORKSHOP]
      ,[MODEL]
      ,[PART_NO]
      ,[INDENTIFY_PART_NO]
      ,[AMOUNTRATIO]
      ,[EXTERIOR_COLOR]
      ,[INTERNAL_COLOR]
      ,[HAND_KEPT_RECORD]
      ,[COLOR_CONTROL_PATCH]
      ,[VWS]
      ,[RAND]
      ,[SECTION]
      ,[PART_OPTION]
      ,[PRODUCTION_NUMBER]
      ,[START_PRODUCTION_DATE]
      ,[CANCEL_NUMBER]
      ,[END_PRODUCTION_DATE]
      ,[MODEL_YEAR]
      ,[DOSAGE]
      ,[MEASURING_UNIT_NO]
      ,[DATA_DATE]
      ,[VORSERIE]
      ,[PART_CNAME]
      ,[PART_ENAME]
      ,[LOAD_FLAG]
      ,[ZP_FLAG]
      ,[REQUIREMENT_FLAG]
      ,[LOGICAL_PK]
      ,[ASSEMBLY_FLAG]
      ,[ASSEMBLY_FLAG_RECRUIT]
      ,[MARK]
      ,[PURCHASE_STYLE]
      ,[VALID_FLAG]
      ,[INBOUND_MODE]
      ,[INBOUND_LOGISTIC_MODE]
      ,[INBOUND_SYSTEM_MODE]
      ,[EFFECTIVE_STATUS]
      ,[START_EFFECTIVE_DATE]
      ,[INBOUND_PART_CLASS]
      ,[INBOUND_PACKAGE_MODEL]
      ,[INBOUND_PACKAGE]
      ,[IS_SPLIT]
  FROM [LES].[TM_BAS_INBOUND_PULL_LOGISTIC_STANDARD]
  GROUP BY 
  [PLANT]
      ,[ASSEMBLY_LINE]
      ,[PLANT_ZONE]
      ,[WORKSHOP]
      ,[MODEL]
      ,[PART_NO]
      ,[INDENTIFY_PART_NO]
      ,[AMOUNTRATIO]
      ,[EXTERIOR_COLOR]
      ,[INTERNAL_COLOR]
      ,[HAND_KEPT_RECORD]
      ,[COLOR_CONTROL_PATCH]
      ,[VWS]
      ,[RAND]
      ,[SECTION]
      ,[PART_OPTION]
      ,[PRODUCTION_NUMBER]
      ,[START_PRODUCTION_DATE]
      ,[CANCEL_NUMBER]
      ,[END_PRODUCTION_DATE]
      ,[MODEL_YEAR]
      ,[DOSAGE]
      ,[MEASURING_UNIT_NO]
      ,[DATA_DATE]
      ,[VORSERIE]
      ,[PART_CNAME]
      ,[PART_ENAME]
      ,[LOAD_FLAG]
      ,[ZP_FLAG]
      ,[REQUIREMENT_FLAG]
      ,[LOGICAL_PK]
      ,[ASSEMBLY_FLAG]
      ,[ASSEMBLY_FLAG_RECRUIT]
      ,[MARK]
      ,[PURCHASE_STYLE]
      ,[VALID_FLAG]
      ,[INBOUND_MODE]
      ,[INBOUND_LOGISTIC_MODE]
      ,[INBOUND_SYSTEM_MODE]
      ,[EFFECTIVE_STATUS]
      ,[START_EFFECTIVE_DATE]
      ,[INBOUND_PART_CLASS]
      ,[INBOUND_PACKAGE_MODEL]
      ,[INBOUND_PACKAGE]
      ,[IS_SPLIT]