

CREATE VIEW [LES].[V_GET_EDIWEB_INHOUSE_AND_INBOUND]
AS
(
SELECT DISTINCT ISNULL(P.SAP_PLANT_CODE,'***') AS SAP_PLANT,ISNULL(R.PLANT,'***') AS PLANT,ISNULL(R.SUPPLIER_NUM,'***') AS SUPPLIER_NUM,ISNULL(S.PART_NO,'***') AS PART_NO FROM LES.TM_BAS_MAINTAIN_INHOUSE_LOGISTIC_STANDARD S
INNER JOIN LES.TM_JIS_RACK R ON S.PLANT = R.PLANT
AND S.ASSEMBLY_LINE = R.ASSEMBLY_LINE
AND (S.INHOUSE_PART_CLASS=R.RACK OR s.IN_PLANT_SYSTEM_MODE=R.RACK)
LEFT JOIN LES.TM_BAS_PLANT P ON R.PLANT = P.PLANT
WHERE 1=1
AND (S.INHOUSE_SYSTEM_MODE='JIS' OR s.IN_PLANT_SYSTEM_MODE='JIS')
AND R.RACK_STATE=2--活动的
AND R.CACULATE_TERM!=5--非手工结算

UNION

SELECT DISTINCT ISNULL(P.SAP_PLANT_CODE,'***') AS SAP_PLANT,ISNULL(R.PLANT,'***') AS PLANT,ISNULL(R.SUPPLIER_NUM,'***') AS SUPPLIER_NUM,ISNULL(S.PART_NO,'***') AS PART_NO FROM LES.TM_BAS_MAINTAIN_INBOUND_LOGISTIC_STANDARD S
INNER JOIN LES.TM_TWD_BOX_PARTS R ON S.PLANT = R.PLANT
AND S.ASSEMBLY_LINE = R.ASSEMBLY_LINE
AND S.INBOUND_PART_CLASS=R.BOX_PARTS
LEFT JOIN LES.TM_BAS_PLANT P ON R.PLANT = P.PLANT
WHERE 1=1
AND S.INBOUND_SYSTEM_MODE='TWD'
AND R.BOX_PARTS_STATE=1--活动的

--ORDER BY SAP_PLANT,r.SUPPLIER_NUM,s.PART_NO
)