




CREATE VIEW [LES].[V_SPM_ASN_RUNSHEET_PURCHASE_VM]
AS
SELECT   ID, ASN_NO, PLANT, ASSEMBLY_LINE, WORKSHOP, PLANT_ZONE, RUNSHEET_TYPE, SUPPLIER_NUM, 
                SUPPLIER_SN, DOCK, DELIVERY_LOCATION, BOX_PARTS, PART_TYPE, PROMISE_DELIVERY_TIME, STATUS, 
                CREATE_DATE, CREATE_USER, MODIFY_DATE, MODIFY_USER, VALID_FLAG, PRINT_TIMES, LAST_PRINT_TIME, 
                CARRIER_DRIVER, CARRIER_TRUCK_LICENCE_PLATE_NO, REAL_ARRIVAL_TIME, REAL_INTO_PLANT_TIME, 
                REAL_UNLOAD_START_TIME, REAL_UNLOAD_END_TIME, REAL_LEAVE_TIME, IS_URGENT, CARRIER_PHONE,
                    (SELECT   SUPPLIER_NAME
                     FROM      LES.TM_BAS_SUPPLIER AS d WITH(NOLOCK)
                     WHERE   (SUPPLIER_NUM = ttsra.SUPPLIER_NUM)) AS SUPPLIER_NAME, PRINT_STATE, RECEIVE_TYPE
FROM      LES.[TT_SPM_RUNSHEET_PURCHASE_ASN] AS ttsra with(nolock)