CREATE VIEW [LES].[V_SPM_CAR_MODEL]
AS
SELECT
	A.[TWD_RUNSHEET_NO],
	A.[PLANT],
	A.[ASSEMBLY_LINE],
	A.[SUPPLIER_NUM],
	A.[BOX_PARTS],
	A.[PUBLISH_TIME],
	A.[EXPECTED_ARRIVAL_TIME],
	A.[SUGGEST_DELIVERY_TIME],
	A.[FARBAU],
	A.[FARBIN],
	A.[MODEL_YEAR],
	A.[MODEL],
	A.[ZCOLORI],
	A.[ZCOLORI_D],
	A.[MODEL_NUM] * ISNULL(C.[SET_NUM], 1) AS [MODEL_NUM],
	A.[GENERATE_NUM] * ISNULL(C.[SET_NUM], 1) AS [GENERATE_NUM],
	B.[RUNSHEET_TYPE]
FROM
(
	SELECT
		[TWD_RUNSHEET_NO],
		[PLANT],
		[ASSEMBLY_LINE],
		[SUPPLIER_NUM],
		[BOX_PARTS],
		MAX([PUBLISH_TIME]) AS [PUBLISH_TIME],
		MAX([EXPECTED_ARRIVAL_TIME]) AS [EXPECTED_ARRIVAL_TIME],
		MAX([SUGGEST_DELIVERY_TIME]) AS [SUGGEST_DELIVERY_TIME],
		[FARBAU],
		MAX([FARBIN]) AS [FARBIN],
		[MODEL_YEAR],
		MAX([MODEL]) AS [MODEL],
		[ZCOLORI],
		MAX([ZCOLORI_D]) AS [ZCOLORI_D],
		COUNT(1) AS [MODEL_NUM],
		COUNT(1) AS [GENERATE_NUM]
	FROM
	(
		SELECT DISTINCT
			[TWD_RUNSHEET_NO],
			[PLANT],
			[ASSEMBLY_LINE],
			[SUPPLIER_NUM],
			[BOX_PARTS],
			[DMSNO],
			[PUBLISH_TIME],
			[EXPECTED_ARRIVAL_TIME],
			[SUGGEST_DELIVERY_TIME],
			[FARBAU],
			[FARBIN],
			[MODEL_YEAR],
			[MODEL],
			[ZCOLORI],
			[ZCOLORI_D]
		FROM [LES].[TL_TWD_MATERIAL_TRAY_LOG] WITH (NOLOCK)
		WHERE [IS_ASN] = 1 AND [PROCESS_FLAG] = 1 AND [IS_GENERATE] = 0
	) AS A
	GROUP BY [TWD_RUNSHEET_NO], [PLANT], [ASSEMBLY_LINE], [SUPPLIER_NUM], [BOX_PARTS], [FARBAU], [MODEL_YEAR], [ZCOLORI]
) AS A
INNER JOIN [LES].[TT_TWD_RUNSHEET] B WITH (NOLOCK) ON A.[TWD_RUNSHEET_NO] = B.[TWD_RUNSHEET_NO] AND (B.[SHEET_STATUS] IS NULL OR B.[SHEET_STATUS] = 0)
LEFT JOIN [LES].[TT_SPS_MANUAL_PULL] C WITH (NOLOCK) ON A.[TWD_RUNSHEET_NO] = C.[TWD_RUNSHEET_NO]