CREATE VIEW [LES].[V_TR_BAS_PART_DYNAMIC_STOCK_VM]
AS 
SELECT
	A.[ID],
	A.[PART_NO],
	C.[PART_CNAME],
	A.[DLOC],
	B.[STORAGE_LOCATION_NAME],
	A.[PLANT],
	D.[PLANT_NAME],
	A.[WM_NO],
	E.[WAREHOUSE_NAME],
	A.[ZONE_NO],
	F.[ZONE_NAME],
	A.[VALID_FLAG],
	C.[PART_CLASSIFY_AREA_NO] 
FROM [LES].[TR_BAS_PART_DYNAMIC_STOCK] A WITH (NOLOCK)
LEFT JOIN [LES].[TM_BAS_WAREHOUSE_LOCATION] B WITH (NOLOCK) ON A.[PLANT] = B.[PLANT] AND A.[WM_NO] = B.[WM_NO] AND A.[ZONE_NO] = B.[ZONE_NO] AND A.[DLOC] = B.[DLOC]
LEFT JOIN [LES].[TM_BAS_PARTS_STOCK] C WITH (NOLOCK) ON A.[PART_NO] = C.[PART_NO] AND A.[PLANT] = C.[PLANT] AND A.[WM_NO] = C.[WM_NO] AND A.[ZONE_NO] = C.[ZONE_NO]
LEFT JOIN [LES].[TM_BAS_PLANT] D WITH (NOLOCK) ON A.[PLANT] = D.[PLANT]
LEFT JOIN [LES].[TM_BAS_WAREHOUSE] E WITH (NOLOCK) ON A.[PLANT] = E.[PLANT] AND A.[WM_NO] = E.[WAREHOUSE]
LEFT JOIN [LES].[TM_WMM_ZONES] F WITH (NOLOCK) ON A.[PLANT] = F.[PLANT] AND A.[WM_NO] = F.[WM_NO] AND A.[ZONE_NO] = F.[ZONE_NO]
WHERE A.[VALID_FLAG] = 1