CREATE VIEW [LES].[V_TWD_RUNSHEET_DETAIL_VM]
AS 
SELECT
	A.[TWD_RUNSHEET_NO],
	A.[TWD_RUNSHEET_SN],
	B.[RUNSHEET_DETAIL_ID],
	A.[PLANT],
	A.[SUPPLIER_NUM],
	C.[SUPPLIER_NAME],
	A.[CREATE_DATE],
	B.[BARCODE_DATA],
	A.[SHEET_STATUS],
	A.[DELIVERY_LOCATION] AS [ZONE_NAME],
	A.[PLANT_ZONE],
	A.[DOCK],
	B.[PART_NO],
	B.[PART_CNAME],
	B.[INBOUND_PACKAGE_MODEL],
	B.[INBOUND_PACKAGE],
	B.[REQUIRED_INBOUND_PACKAGE],
	B.[REQUIRED_INBOUND_PACKAGE_QTY],
	B.[ASN_DRAFT_QTY],
	B.[ASN_CONFIRM_QTY],
	B.[ACTUAL_INBOUND_PACKAGE_QTY],
	B.[COMMENTS],
	A.[RUNSHEET_TYPE],
	(ISNULL(B.[REQUIRED_INBOUND_PACKAGE_QTY], 0) - ISNULL(B.[ASN_CONFIRM_QTY], 0) - ISNULL(B.[ASN_DRAFT_QTY], 0)) AS [ASN_EDIT_QTY],
	C.[ASN_FLAG],
	A.[IS_ASN],
	A.[IS_TRAY],
	a.[TIME_AND],
	A.BOX_PARTS
FROM [LES].[TT_TWD_RUNSHEET] A WITH (NOLOCK)
LEFT JOIN [LES].[TT_TWD_RUNSHEET_DETAIL] B WITH (NOLOCK) ON A.[TWD_RUNSHEET_SN] = B.[TWD_RUNSHEET_SN]
LEFT JOIN [LES].[TM_BAS_SUPPLIER] C WITH (NOLOCK) ON C.[SUPPLIER_NUM] = A.[SUPPLIER_NUM]