CREATE VIEW [LES].[V_WMM_PART_STOCKS_VIEW]
AS
SELECT
	P.[STOCK_IDENTITY],
    P.[PLANT],
    P.[WM_NO],
    P.[ZONE_NO],
	P.[DLOC],
    P.[PART_NO],
    P.[PART_CNAME],
    P.[PART_NICKNAME],
	ISNULL(S.[STOCKS], 0) AS [STOCKS],
    ISNULL(S.[STOCKS_NUM], 0) AS STOCKS_NUM,
	ISNULL(S.[FRAGMENT_NUM], 0) AS [FRAGMENT_NUM],
	ISNULL(S.[AVAILBLE_STOCKS], 0) AS [AVAILBLE_STOCKS],
    ISNULL(S.[FROZEN_STOCKS], 0) AS FROZEN_STOCKS,
    S.[PART_CLS],
    ISNULL(S.[PACKAGE], 1) AS PACKAGE,
    S.[PACKAGE_MODEL],
    ISNULL(P.[SUPPLIER_NUM], '') AS [SUPPLIER_NUM],
    P.[VALUE_SORT],
    P.[PARTS_ATTRIBUTE],
    L.[COUNT_PARTITION]
FROM [LES].[TM_BAS_PARTS_STOCK] AS P WITH (NOLOCK)
LEFT JOIN
(
	SELECT
		[PLANT],
		[WM_NO],
		[ZONE_NO],
		[PART_NO],
        MAX(ISNULL([PACKAGE], 1)) AS [PACKAGE],
        MAX([PACKAGE_MODEL]) AS [PACKAGE_MODEL],
		SUM(ISNULL([STOCKS_NUM], 0)) AS [STOCKS_NUM],
        SUM(ISNULL([FROZEN_STOCKS], 0)) AS [FROZEN_STOCKS],
		CAST((CAST(SUM(ISNULL([STOCKS_NUM], 0)) AS INT) / MAX(ISNULL([PACKAGE], 1))) AS DECIMAL) AS [STOCKS],
		CAST((CAST(SUM(ISNULL([STOCKS_NUM], 0) - ISNULL([FROZEN_STOCKS], 0)) AS INT) % MAX(ISNULL([PACKAGE], 1))) AS DECIMAL) AS [FRAGMENT_NUM],
		CAST((CAST(SUM(ISNULL([STOCKS_NUM], 0) - ISNULL([FROZEN_STOCKS], 0)) AS INT) / MAX(ISNULL([PACKAGE], 1))) AS DECIMAL) AS [AVAILBLE_STOCKS],
        MAX([PART_CLS]) AS [PART_CLS]
	FROM [LES].[TT_WMS_STOCKS] WITH (NOLOCK)
	WHERE [DELETE_FLAG] = 0 OR [DELETE_FLAG] IS NULL
	GROUP BY [PLANT], [WM_NO], [ZONE_NO], [PART_NO]
) AS S
ON P.[PLANT] = S.[PLANT] AND P.[WM_NO] = S.[WM_NO] AND P.[ZONE_NO] = S.[ZONE_NO] AND P.[PART_NO] = S.[PART_NO]
LEFT JOIN [LES].[TM_BAS_WAREHOUSE_LOCATION] L WITH (NOLOCK)
ON L.[PLANT] = P.[PLANT] AND L.[WM_NO] = P.[WM_NO] AND L.[ZONE_NO] = P.[ZONE_NO] AND L.[DLOC] = P.[DLOC]
WHERE P.[DELETE_FLAG] = 0