CREATE TABLE [dbo].[TI_ODS_ORDERS_IN_TEST] (
    [SEQ_ID]       BIGINT          IDENTITY (1, 1) NOT NULL,
    [ZORDNO]       NVARCHAR (10)   NULL,
    [ZKWERK]       NVARCHAR (4)    NULL,
    [ZMATNR]       NVARCHAR (18)   NULL,
    [ZIDNKD]       NVARCHAR (18)   NULL,
    [ZCOLOR]       NVARCHAR (30)   NULL,
    [ZCOLOR_D]     NVARCHAR (30)   NULL,
    [ZMODEL]       NVARCHAR (30)   NULL,
    [ZMODEL_D]     NVARCHAR (30)   NULL,
    [ZPACK]        NVARCHAR (30)   NULL,
    [ZPACK_D]      NVARCHAR (30)   NULL,
    [ZVIN]         NVARCHAR (17)   NULL,
    [ZQTY]         NUMERIC (18, 2) NULL,
    [ZDATE]        DATETIME        NULL,
    [ZDISPO]       NVARCHAR (3)    NULL,
    [ZST]          NVARCHAR (1)    NULL,
    [ZMEMO]        NVARCHAR (80)   NULL,
    [ZMEINS]       NVARCHAR (8)    NULL,
    [DEAL_FLAG]    INT             NULL,
    [PROCESS_FLAG] INT             NULL,
    [PROCESS_TIME] DATETIME        NULL,
    [COMMENTS]     NVARCHAR (200)  NULL,
    [UPDATE_DATE]  DATETIME        NULL,
    [UPDATE_USER]  NVARCHAR (50)   NULL,
    [CREATE_DATE]  DATETIME        NOT NULL,
    [CREATE_USER]  NVARCHAR (50)   NOT NULL
);

